### ISSUE TITLE
Rancher Desktop

### ISSUE THREAD

**Issue by eladius1129** [markshust/docker-magento#1019]
**Description**
I tried to run every steps mentioned in the documentation, but looks like is not compatible with rancher desktop

Have you guys tested this project on Rancher Desktop ?

<img width="1722" alt="image" src="https://github.com/markshust/docker-magento/assets/38100308/08dce588-918a-4ec3-8652-282781cd7bc7">

**Comment by markshust** [comment]
@eladius1129 I'm really not sure, as I don't use Rancher.

This ticket lacks specific details, test cases, etc. so I'm closing it out. Please open a new ticket if you have a very specific testing scenario, and perhaps someone can help you out. Thanks!

**Comment by eladius1129** [comment]
Thanks, I could resolved the issue, I had to do some changes in my compose.yml
