### ISSUE TITLE
Stuck on curl command

### ISSUE THREAD

**Issue by haerrizr** [markshust/docker-magento#1022]
**Description**
curl going to time out

**Steps To Reproduce**
1. on entering "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p3 community" it waits and times out

**Expected Result**
containers should be created

**Actual Result**
Times out and nothing happens

**Comment by prjktcode** [comment]
> **Description** curl going to time out
> 
> **Steps To Reproduce**
> 
> 1. on entering "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p3 community" it waits and times out
> 
> **Expected Result** containers should be created
> 
> **Actual Result** Times out and nothing happens

Did you manage to fix this?

**Comment by markshust** [comment]
I'm unable to replicate this, so I'm closing it out. But do you have a corporate firewall or vpn installed that could perhaps be timing out this request? Or an ISP that is blocking a connection to github?
