### ISSUE TITLE
bin/docker-compose: line 28: docker-compose: command not found

### ISSUE THREAD

**Issue by markosege** [markshust/docker-magento#1023]
**Description**
`bin/start` or any other `bin` command not working

**Steps To Reproduce**
1. When I run the `bin/start` command, I get the below error
`bin/docker-compose: line 28: docker-compose: command not found`

**Expected Result**
containers should be created

**Actual Result**
`bin/docker-compose: line 28: docker-compose: command not found`

**Comment by EvgeniyZverev** [comment]
Ensure that the Docker Compose is installed:

docker-compose --version

**Comment by markshust** [comment]
Yes, this appears to be because Docker Desktop (mac/win) or Docker Compose (linux) is not installed. Once you install that prerequisite, it should work 👍
