### ISSUE TITLE
Cannot access admin

### ISSUE THREAD

**Issue by thaingocthienlong** [markshust/docker-magento#1024]
**Description**
Cannot access admin pannel

**Steps To Reproduce**
1. Install magento docker on wsl2 ubuntu
2. Open magento.test/admin
3. Login john.smith password123

**Expected Result**
Admin pannel show up

**Actual Result**
![image](https://github.com/markshust/docker-magento/assets/118582064/b6dcc79a-a6e7-4bdd-aa40-bd649441e57a)

**Comment by ipatalas** [comment]
You can run the following commands to disable MFA:
```
bin/magento module:disable Magento_AdminAdobeImsTwoFactorAuth Magento_TwoFactorAuth
bin/magento setup:upgrade
```

**Comment by markshust** [comment]
Ok, you are able to access the admin, but it's asking for a 2FA setup. So this isn't at all an issue with this setup, as this is a standard thing that happens for all Magento installs, irregardless of if you use docker-magento, local install, etc.

@ipatalas I don't recommend disabling 2FA that way. It opens up security holes in prod, and if you're running Adobe Commerce Cloud, they could reject your builds as it doesn't abide by their security standards.

A better way is to install [my Disable 2FA module](https://github.com/markshust/magento2-module-disabletwofactorauth). This module disables 2FA for you automatically, but only in development mode. This allows you to retain 2FA on staging/prod, and should still align with Adobe Cloud's security requirements.

**Comment by ipatalas** [comment]
> @ipatalas I don't recommend disabling 2FA that way. It opens up security holes in prod, and if you're running Adobe Commerce Cloud, they could reject your builds as it doesn't abide by their security standards.

You're right. I only needed that workaround for local development so that was irrelevant. I wouldn't recommend disabling that for Prod environment as well but you mention yourself that this repo is not meant to be used for production so I didn't add any disclaimer here.
