### ISSUE TITLE
404 link on repo

### ISSUE THREAD

**Issue by hans2103** [markshust/docker-magento#1027]
**Description**

when clicking on the link in the top right corner of this repo it leads to a 404 page
https://m.academy/courses/setup-magento-2-development-environment-docker

![Scherm­afbeelding 2023-12-20 om 14 30 35](https://github.com/markshust/docker-magento/assets/639822/85325c2c-00d2-410d-b69e-f52b87e60c61)

**Steps To Reproduce**
1. Go to https://github.com/markshust/docker-magento/
2. Click on link mentioned just below _About_

**Expected Result**

Expecting to see the page explaining me how to set up a Magento 2 development environment with Docker

**Actual Result**

I get a 404 page

**Suggested solution**

Replace the current link in the About section with the link below
https://m.academy/courses/set-up-magento-2-development-environment-docker/

The difference is `setup` vs `set-up`

**Comment by markshust** [comment]
Thanks a lot, should be all fixed now! I just removed some 301 redirects last week, which probably caused some old, non-updated links to go dead.
