### ISSUE TITLE
"chmod: cannot access 'bin/magento': No such file or directory" on Mac M2

### ISSUE THREAD

**Issue by kwindo** [markshust/docker-magento#1028]
**System (Not sure which is relevant, feel free to ask more):**

- MacBook Pro (Apple M2 Pro)
- OS: Ventura "13.6.2"
- Magento version: 2.4.6-p3
- Docker: 4.26.1

The Mac was brand new when I first tried Docker-Magento. I've been experimentng with other ways of installing Magento locally (using MAMP) which made me install HomeBrew, PHP and Composer globally. However this did not seem to affect the issue.

**Description:**

I am trying to install Magento using Docker-magento on a Mac M2, following the procedure exactly as described. I am unsure if the Mac processor type is relevant but I mentioned it because I was able to install Magento this way on my previous Intel Mac.

**Step to reproduce:**

On a Mac M2 follow the procedure as decried

1.  - enter "mkdir -p ~/Sites/magento"
2.  - cd to the project directory "cd $_"
3.  - Run: "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p3 community"

**Expected results:**

I fairly new to Magento and I'm trying to learn but I've been trying to install it locally for a while so I did expect issues ;-). However, I was hoping to get further than this ;-)

**Actual results:**

After running "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p3 community" this is returned in Terminal:

```
Initialized empty Git repository in /Users/[username]/Sites/magento/.git/
WARNING: daemon is not using the default seccomp profile
[+] Running 13/13
 ✔ Network magento_default          Created                                0.0s 
 ✔ Volume "magento_dbdata"          Created                                0.0s 
 ✔ Volume "magento_rabbitmqdata"    Cre...                                 0.0s 
 ✔ Volume "magento_ssldata"         Created                                0.0s 
 ✔ Volume "magento_sockdata"        Created                                0.0s 
 ✔ Volume "magento_appdata"         Created                                0.0s 
 ✔ Container magento-mailcatcher-1  S...                                   0.0s 
 ✔ Container magento-rabbitmq-1     Heal...                                0.0s 
 ✔ Container magento-opensearch-1   He...                                  0.0s 
 ✔ Container magento-redis-1        Healthy                                0.0s 
 ✔ Container magento-db-1           Healthy                                0.0s 
 ✔ Container magento-phpfpm-1       Starte...                              0.0s 
 ✔ Container magento-app-1          Started                                0.0s 
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.6-p3" project at "./"
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

In AuthHelper.php line 205:
                                                                               
  The 'https://repo.magento.com/packages.json' URL required authentication (H  
  TTP 401).                                                                    
  You must be using the interactive console to authenticate                    
                                                                               

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]

[+] Stopping 7/7
 ✔ Container magento-app-1          Stopped                                0.2s 
 ✔ Container magento-mailcatcher-1  S...                                   0.1s 
 ✔ Container magento-phpfpm-1       Stoppe...                              0.1s 
 ✔ Container magento-opensearch-1   St...                                 10.2s 
 ✔ Container magento-db-1           Stopped                                0.3s 
 ✔ Container magento-rabbitmq-1     Stop...                                6.2s 
 ✔ Container magento-redis-1        Stopped                                0.2s 
WARNING: daemon is not using the default seccomp profile
[+] Running 7/7
 ✔ Container magento-db-1           Healthy                                0.0s 
 ✔ Container magento-redis-1        Healthy                                0.0s 
 ✔ Container magento-opensearch-1   He...                                  0.0s 
 ✔ Container magento-mailcatcher-1  S...                                   0.0s 
 ✔ Container magento-rabbitmq-1     Heal...                                0.0s 
 ✔ Container magento-phpfpm-1       Starte...                              0.0s 
 ✔ Container magento-app-1          Started                                0.0s 
chmod: cannot access 'bin/magento': No such file or directory
```
I would like to mention I didn't find some issues here that were related. Which I am still trying to use to solve this.

For example: I tried this work around:
https://github.com/markshust/docker-magento/issues/731#issuecomment-1185415231

This is exactly what I did:

1. Run the install as discribedafter cd'ing to the project directory I created : "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p3 community"
2. Check if the Docker name with: "docker container ls"
3. Use the correct Docker name in the following command: "docker exec -it magento-phpfpm-1 bash". In my case "magento-phpfpm-1" was correct. This returning line looks something like this "app@fbfa655d5dbb:~/html$"
4. Create a directory "temp": "mkdir temp"
5. Go into the new "temp" directory": "cd temp"

Then I ran "composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.6-p3 ." And got this returned:

 ```
Creating a "magento/project-community-edition=2.4.6-p3" project at "./"
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

In AuthHelper.php line 216:
                                                                                          
  Invalid credentials (HTTP 401) for 'https://repo.magento.com/packages.json', aborting.  
                                                                                          

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]
```
Meaning, I ran into a totally different issue so I exited with "exit" to go back to the original project directory. :-(

**Comment by EvgeniyZverev** [comment]
Hello, @kwindo 
I think the problem is with auth.json
Enter the following data into your auth.json file to  log in. Please use the Public Key and the Private Key

1 **To create authentication keys:**

1.1 Login to the [Commerce Marketplace](https://commercemarketplace.adobe.com/). If you don’t have an account, click Register.

1.2 Click your account name in the top right of the page and select My Profile.

1.3 Click Access Keys in the Marketplace tab.

![image](https://github.com/markshust/docker-magento/assets/43544955/c3744cbc-e7a6-4463-bfa5-813b3255a6b8)

1.4 Click Create a New Access Key. Enter a specific name for the keys (for example, the name of the developer receiving the keys) and click OK.

1.5 New public and private keys are now associated with your account that you can click to copy. Save this information or keep the page open when working on your project. Use the Public key as your username and the Private key as your 
password.

**2.  Now that you have the public and private keys, create the file auth.json using this command:**

 nano ~/.composer/auth.json 
(the file is in ~/.composer/auth.json and in Magento root )

and paste this:
````json
{
    "http-basic": {
        "repo.magento.com": {
            "username":"your public key",
            "password":"your private key"
        }
    }
}
````
And try again to install Magento

**Comment by kwindo** [comment]
Thanks a lot for your reply @EvgeniyZverev 

I just checked auth.json and these values are allready in there.

Now, after posting this issue I continued searching for a way to install Magento locally and stumbeled on Warden (https://warden.dev/). Warden allowd me to install Magento without significant issues. I am pretty sure installing Magento with Warden added these values to auth.json. I needed to add these keys during the install process.

I am pretty new to Docker and Magento and - at the moment - I need to learn as much as I can in very little time. However I have spend almost a week trying out different approaches to install the CMS locally. I was so happy, yesterday, that it finally worked. Warden now allows me to install multiple instances of Magento feairly quickly. 

Also, at this point, I fear, this script somewhat overshoots it's purpous as a simple way to install Magento locally. At least for someone with a similmar system then mine. Warden made it surprisingly simple. So, I am going to stick with that.

With no disrespect or lack of gratitude to the creator of this script but I am hesitant to try out the install again, fearing it might break my now working system.

**Comment by EvgeniyZverev** [comment]
Hi, @kwindo  

I'm glad to hear that you were able to install Magento using Warden successfully. 

I also used to install Magento using Warden, but I found that using a one-liner script to install Magento was the most convenient way for me. This method usually installs Magento within 3 minutes without breaking the system.

However, if you receive an error notice during the installation process, you might want to consider configuring it manually. I would be happy to assist you with this if needed.

Wishing you all the best in your journey to learn Magento 2!

**Comment by markshust** [comment]
@kwindo thanks a lot for the candid feedback. I like hearing criticism as it helps make stuff better. I don't think I'll be planning out any major changes to anything, as I've been consistently working with this setup for 5+ years with no issues. But perhaps it's because I have intricate knowledge of the setup. If I hear this more, I'll look into it.

@EvgeniyZverev thanks so much for your help with this ticket!

**Comment by tamdt5** [comment]
> Hello, [@kwindo](https://github.com/kwindo) I think the problem is with auth.json Enter the following data into your auth.json file to log in. Please use the Public Key and the Private Key
> 
> 1 **To create authentication keys:**
> 
> 1.1 Login to the [Commerce Marketplace](https://commercemarketplace.adobe.com/). If you don’t have an account, click Register.
> 
> 1.2 Click your account name in the top right of the page and select My Profile.
> 
> 1.3 Click Access Keys in the Marketplace tab.
> 
> ![image](https://github.com/markshust/docker-magento/assets/43544955/c3744cbc-e7a6-4463-bfa5-813b3255a6b8)
> 
> 1.4 Click Create a New Access Key. Enter a specific name for the keys (for example, the name of the developer receiving the keys) and click OK.
> 
> 1.5 New public and private keys are now associated with your account that you can click to copy. Save this information or keep the page open when working on your project. Use the Public key as your username and the Private key as your password.
> 
> **2. Now that you have the public and private keys, create the file auth.json using this command:**
> 
> nano ~/.composer/auth.json (the file is in ~/.composer/auth.json and in Magento root )
> 
> and paste this:
> 
> {
>     "http-basic": {
>         "repo.magento.com": {
>             "username":"your public key",
>             "password":"your private key"
>         }
>     }
> }
> And try again to install Magento

Thanks, this work for me
