### ISSUE TITLE
RabbitMQ Management Access

### ISSUE THREAD

**Issue by pcis-mub** [markshust/docker-magento#1029]
**Description**
RabbitMQ Management is accessible at http://magento.test:15672/ but any access combination is not working

**Steps To Reproduce**
1. Navigate to http://magento.test:15672/
2. Try any of the following combinations
admin/admin
guest/guest
admin/changeme

**Expected Result**
Default access combination should work

**Actual Result**
Default access combination is not working

**Comment by EvgeniyZverev** [comment]
Hi, @pcis-mub 

It seems like there might be a misunderstanding or a misconfiguration in the RabbitMQ access. The RabbitMQ Management interface is configured with the RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS according to the env/rabbitmq.env file.

I can advise the user to try accessing http://magento.test:15672/ with the following credentials:

Username: magento
Password: magento

Feel free to let me know if you have further questions or need more assistance!

**Comment by EvgeniyZverev** [comment]
Hi, @pcis-mub 

It seems like there might be a misunderstanding or a misconfiguration in the RabbitMQ access. The RabbitMQ Management interface is configured with the RABBITMQ_DEFAULT_USER and RABBITMQ_DEFAULT_PASS according to the env/rabbitmq.env file.

I can advise you to try accessing http://magento.test:15672/ with the following credentials:

Username: magento
Password: magento

Feel free to let me know if you have further questions or need more assistance!

**Comment by markshust** [comment]
Thanks @EvgeniyZverev for the response!

Yes, the settings for this come from the env vars. Perhaps this needs to be documented better, but if anyone else needs this the `magento:magento` user:pass work for RabbitMQ.
