### ISSUE TITLE
No executive permissions on few bin scripts

### ISSUE THREAD

**Issue by Linek** [markshust/docker-magento#1037]
**Description**
Once repository is cloned, few scripts in /composer/bin has no execution rights:

<img width="702" alt="image" src="https://github.com/markshust/docker-magento/assets/136248/5fd845f7-9e64-447e-b896-e76ee7fe21c5">

**Steps To Reproduce**
-

**Expected Result**
All the scripts in compose/bin should be executable

**Actual Result**
`zsh: permission denied: ./phpcs`

**Comment by EvgeniyZverev** [comment]
bin/deploy the same

**Comment by markshust** [comment]
Merged, this should now be resolved 👍
