### ISSUE TITLE
Redis connection fails

### ISSUE THREAD

**Issue by RicoSolutions** [markshust/docker-magento#1053]
Hi there,
Steps to reproduce
Execute the following command described on this github page:
**_bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis --cache-backend-redis-db=0_**

**Outcome**:
The following error occurs:
_Connection to Redis standalone tcp://redis:6379 failed after 2 failures.Last Error : (0) php_network_getaddresses: getaddrinfo for redis failed: nodename nor servname provided, or not known_

I tried this on a macbook pro m2 and an Ubuntu 23.10.

**Comment by NetStorm84** [comment]
I assume you are in the wrong directory, probably "src" back out one level with "cd ../" and try the command again.

**Comment by markshust** [comment]
Yup I'm almost sure it's the directory location is the issue. I'll close this out, but if you are still having issues please let me know and I can reopen it.

**Comment by psahni** [comment]
👍
