### ISSUE TITLE
Xdebug not being enabled

### ISSUE THREAD

**Issue by Sorg3** [markshust/docker-magento#1057]
**Description**
When i run "bin/xdebug  enable" i receive:

sed: cannot rename /usr/local/etc/php/sedzKBYxZ: Device or resource busy

Containers get restarted and i get two warnings, together with success result:

WARNING: Plugin "/Users/myuser/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/myuser/.docker/cli-plugins/docker-scan: no such file or directory
WARNING: daemon is not using the default seccomp profile
Xdebug debug mode has been enabled.

I tried to fix own and perm but:

![image](https://github.com/markshust/docker-magento/assets/104192245/93169d09-3953-4c1a-9e36-8acfeeaf64fc)

**Steps To Reproduce**
1. 

**Expected Result**

Xdebug enabled

**Actual Result**

But if i do bin/xdebug status:
Xdebug debug mode is disabled.

**Comment by marcelo011982** [comment]
Did you try to run 
bin/fixperms 
And after that enable xdebug?

**Comment by markshust** [comment]
It appears the ownerships of your local host files and directory are incorrect. They should all be owned by your local mac username. I'd run `chown -R myuser my-magento-dir` (obv replacing `myuser` with your local username, and `my-magento-dir` with your local magento project directory name), and it should correct your issue. I just executed `bin/xdebug enable` on a fresh install and I was unable to replicate any issue -- all worked as expected.
