### ISSUE TITLE
Could not find package magento/project-enterprise-edition with version 2.4.6-p3.

### ISSUE THREAD

**Issue by MikeAplazo** [markshust/docker-magento#1059]
**Description**
When I try manual setup and execute bin/download 2.4.6-p3 enterprise, I get the error message: 
```
In CreateProjectCommand.php line 424:                                                                               
  Could not find package magento/project-enterprise-edition with version 2.4.  
  6-p3.
```

**Steps To Reproduce**
1. Exec
 `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash`
 Response
 `Initialized empty Git repository in /var/www/magentoEnterprise/.git/`
2. Exec
`bin/download 2.4.6-p3 enterprise`
Response
`[+] Running 13/13
 ⠿ Network magentoenterprise_default          Created                                                                             0.1s
 ⠿ Volume "magentoenterprise_dbdata"          Created                                                                             0.0s
 ⠿ Volume "magentoenterprise_rabbitmqdata"    Created                                                                             0.0s
 ⠿ Volume "magentoenterprise_ssldata"         Created                                                                             0.0s
 ⠿ Volume "magentoenterprise_sockdata"        Created                                                                             0.0s
 ⠿ Volume "magentoenterprise_appdata"         Created                                                                             0.0s
 ⠿ Container magentoenterprise-rabbitmq-1     Healthy                                                                             8.2s
 ⠿ Container magentoenterprise-redis-1        Healthy                                                                             6.7s
 ⠿ Container magentoenterprise-mailcatcher-1  Started                                                                             1.1s
 ⠿ Container magentoenterprise-opensearch-1   Healthy                                                                            16.7s
 ⠿ Container magentoenterprise-db-1           Healthy                                                                             6.2s
 ⠿ Container magentoenterprise-phpfpm-1       Started                                                                            16.9s
 ⠿ Container magentoenterprise-app-1          Started                                                                            17.2s
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-enterprise-edition=2.4.6-p3" project at "./"

In CreateProjectCommand.php line 424:
                                                                               
  Could not find package magento/project-enterprise-edition with version 2.4.  
  6-p3.                                                                        
                                                                               

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]
`
 

**Expected Result**
Not get the error `Could not find package magento/project-enterprise-edition with version 2.4.6-p3. `

**Actual Result**
I get the error `Could not find package magento/project-enterprise-edition with version 2.4.6-p3. `

**Comment by markshust** [comment]
This command only works for `enterprise` if your Compose auth creds have been approved to download Adobe Commerce (you'd need to get access from an Adobe partner or a client running Commerce to be able to download it).

**Comment by mrahman3177** [comment]
@MikeAplazo , if you have the creds, you can run this command to update composer auth.json file before bin/download 2.4.6-p3 enterprise. Make sure to replace USERNAME and PASSWORD with valid entry

`bin/composer config --global http-basic.repo.magento.com USERNAME PASSWORD`

**Comment by MikeAplazo** [comment]
@mrahman3177 thank you, I solved it with the manual setup but I had to change the auth.json manually.
