### ISSUE TITLE
When xdebug is enabled bin/magento commands won't work

### ISSUE THREAD

**Issue by tomasperezponisio** [markshust/docker-magento#1064]
**Description**
If xdebug is enabled, bin/magento commands won't work, and let's say if i run bin/magento cache:clean PhpStorm starts to debug out of nothing.

Also I get this message in console:
`Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(`

It was working perfectly and suddenly this started to happen, any ideas?

If I disable it everything works ok.

**Comment by tomasperezponisio** [comment]
I forgot to say that i'm on Ubuntu 20.04.6 LTS x86_64, and using phpStorm 2023.3.4, and latest version of Docker Desktop 4.27.2

**Comment by markshust** [comment]
It sounds like the PhpStorm Xdebug settings are set up to trigger "upon entry" or something like that. Please see https://courses.m.academy/courses/487758/lectures/9064478 for videos on how to set up Xdebug so it only triggers on breakpoints and when the IDE_KEY variable is set.
