### ISSUE TITLE
Error response from daemon:  page not found during executing `bin/docker-stats` script

### ISSUE THREAD

**Issue by YevhenZvieriev** [markshust/docker-magento#1075]
### Description

I noticed, that after this [commit](https://github.com/markshust/docker-magento/pull/1017/commits/b7418753bebbe7aeaf70b35bffc025480733b435) I got the error  `Error response from daemon:  page not found` during executing `bin/docker-stats`

I got this issue only once, and now, I cannot replicate this, and the script works for me.

Could anyone please confirm the issue? Then I'll fix this.

**Comment by markshust** [comment]
I'm able to replicate:

```
~/Sites/magento246-p4 bin/docker-compose ps -q                                                   
2e3807f2d1fd1d7c67385c419bdc59f8779b1bf9bc56b8684454b05bcacab68a
d1a5fd3ddb014725f075a45929635b99903462828cc952c4e9fed76ffdb51b6a
0d09d6a88158916fae8a642bf41a35e2a488ff1c15b9f8556f731e6675d91a25
e545f37be0f8811fafe0a434ebc24fff3f433a0cbe3501b9d98e211493e4bc6c
58c4b726208bdc258581c0e8ee79b95ae8c7a57d457c07fcd26664672b13eb14
043f381b91a16fd010fd59bcca2eaa879d22b17e1ec5aff8f580b9ec18dda77c
daf2dc472b1e74da43bad8ed88987385a921a0c652819386db1413623563cc5d
657b5a73f70e2db8b1eb6aa3b761f08a20e6e2b5d3e60337b2066a0cab4c6b82
~/Sites/magento246-p4 bin/docker-stats                                                        
Error response from daemon: page not found
~/Sites/magento246-p4 docker stats "2e3807f2d1fd1d7c67385c419bdc59f8779b1bf9bc56b8684454b05bcacab68a
d1a5fd3ddb014725f075a45929635b99903462828cc952c4e9fed76ffdb51b6a
0d09d6a88158916fae8a642bf41a35e2a488ff1c15b9f8556f731e6675d91a25
e545f37be0f8811fafe0a434ebc24fff3f433a0cbe3501b9d98e211493e4bc6c
58c4b726208bdc258581c0e8ee79b95ae8c7a57d457c07fcd26664672b13eb14
043f381b91a16fd010fd59bcca2eaa879d22b17e1ec5aff8f580b9ec18dda77c
daf2dc472b1e74da43bad8ed88987385a921a0c652819386db1413623563cc5d
657b5a73f70e2db8b1eb6aa3b761f08a20e6e2b5d3e60337b2066a0cab4c6b82"
Error response from daemon: page not found
```

**Comment by markshust** [comment]
Note that if I replace:

```docker stats "$container_ids"```

With:

```docker stats $container_ids```

Everything works as expected, but it fails shellcheck (my correction of this script by shellcheck analysis almost assuredly caused this issue).

**Comment by markshust** [comment]
All fixed!

**Comment by YevhenZvieriev** [comment]
Good job, Mark!

But I want you to pay attention to the fact that we should change the documentation description to `make` command in `Makefile` and `Readme`.

You wrote, that `bin/docker-stats` displays the status for CPU, memory usage, and memory limit, but after the last commit, it starts displaying more information about docker-containers, such as : 

CONTAINER ID   NAME                       CPU %     MEM USAGE / LIMIT    MEM %     NET I/O       BLOCK I/O         PIDS

Feel free to check this screenshot:
![Screenshot from 2024-03-06 17-53-27](https://github.com/markshust/docker-magento/assets/43544955/5685d7c8-e605-4d9a-b214-82afacc8f2a6)

Or we can revert this script to the [commit](https://github.com/markshust/docker-magento/pull/1017/commits/2dfb8a740f5b9d32ebc1c54219b1ef82ef124fd8) when the script works following, displays just 

Name CPU %  Memory Usage  Memory Limit 

![image](https://github.com/markshust/docker-magento/assets/43544955/e539227a-9795-416b-ad6a-f67256dc672d)

What do you think about this, @markshust ?

**Comment by YevhenZvieriev** [comment]
@markshust Which result do you prefer? If you like when the script gives more information about docker-containers I will not change the script, but if you prefer more shortly output, I'll change the script.

**Comment by markshust** [comment]
Let's go ahead and switch it to the simplified output, as I'm not sure Net & Block I/O and PIDs are needed at all.
