### ISSUE TITLE
Controling 80 and 443 ports on linux

### ISSUE THREAD

**Issue by vhdmoradi** [markshust/docker-magento#1077]
So, I have a question regarding ports, not sure if I need to open a new issue.
I am on linux and the ports 80 and 443 are already in use most of the time, and I do not understand quite well, but sometimes services like gnome shell are using these ports. So, my first problem occurs when I try to just kill the processes using these ports (which I am not 100% sure is the best way); usually when I close some unimportant service using these ports (like telegram or so), it makes the port available. But when gnome shell is using it, killing the service is not right.
My main question is, is there a way to config the docker-magento to use other ports rather than 80 and 443? maybe in the docker-compose file? I tried in the compose file, changing here:
```
app:
    image: markoshust/magento-nginx:1.18-8
    ports:
      - "81:8000"
      - "444:8443"
```
But after getting the containers up, magento.test does not open the website.
![Screenshot from 2024-02-27 14-30-40](https://github.com/markshust/docker-magento/assets/86122932/8f98b9be-261f-4eab-acf5-149a00f40a82)
If not, how can I open these ports without killing services like gnome-shell?

**Comment by markshust** [comment]
Have you updated the base_url setting in Magento's database? (`core_config_data`)

**Comment by vhdmoradi** [comment]
No I have not tried it, but I will definitely let you know if it works or gives any errors.

**Comment by markshust** [comment]
I believe that is the required path, as I don't think there is any other way to do this other than to set up a proxy that sits in front of Nginx (like Traefik), so I'm going to close this one out as it's a non-issue.
