### ISSUE TITLE
Detecting changes from config.php / env.php

### ISSUE THREAD

**Issue by mihai-RW** [markshust/docker-magento#1079]
Greetings everyone,

I am having some difficulties when it comes to changing configurations from app/etc/config.php or env.php
Whenever i do, magento correctly picks up the changes although when i run the app:config:import, the error message doesn't go away and most of the times i end up restarting the container.

Sorry for the newbness when it comes to docker and volumes, is there anything i am missing when it comes to cached / delegated volumes ? What exactly should i do to make this work.

Also just for reference, what would be an ideal composer.dev.yaml in order to have these files configured properly between host and container, i often find myself having to change config.php or env.php or composer.json etc, so would help me get rid of the restart each time i do a change to these. 

Cheers for the help!

**Comment by YevhenZvieriev** [comment]
Hi, @mihai-RW 

Are you changing the configuration from files `config.php` or `env.php` inside the docker container or locally?


It sounds like you're encountering issues related to Docker volumes and file synchronization between your host and container.

**Comment by mihai-RW** [comment]
heya @YevhenZvieriev , i am changing it locally, and also have the volume mounted as ./src/app/etc/config:/var/www/html/app/etc/config.php specifically not to trigger the copytocontainer manually

**Comment by YevhenZvieriev** [comment]
You can mount a full `etc` folder instead `config.php` and `env.php` files, but the easiest way is to use `bin/cli vi app/etc/env.php` and `bin/cli vi app/etc/config.php` to open these files within the docker container.

**Comment by mihai-RW** [comment]
Heya @YevhenZvieriev thanks for the feedback. I am terribly embarrassed, i narrowed it down to opcache and the validate timestamps property, i accidentally left it to 0 and files would automatically get cached.... 
Will close this one as it works properly now ... Thank you again
