### ISSUE TITLE
Download Magento fail in Windows since it doesn't allows to enter the composer authentication

### ISSUE THREAD

**Issue by cuongtran-6618** [markshust/docker-magento#1081]
**Description**

**Steps To Reproduce**
1. Operation: Windows 11, Docker desktop v4.27.2 with wsl 2
2. Following automatical setup
```
# Create your project directory then go into it:
mkdir -p ~/Sites/magento
cd $_

# Run this automated one-liner from the directory you want to install your project.
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p4 community
```

![image](https://github.com/markshust/docker-magento/assets/5196596/aa152521-b8ba-476e-9f5c-dbfd8b46204c)

**Expected Result**
- it allowed to enter username and password in order to download and complete setup

**Actual Result**
- There is no way to enter the username and password. Typing, copy paste doesn't do anything.
- Ctrl + C, then it is able to typing again

**Comment by joaogvedes** [comment]
Hello Cuong Tran,
I am having the same problem... When the composer authentication shows up, I can't type or paste nothing on the username and the installation gets stuck.

**Did you manage to get solution for this ?** If so, please let me know.
Thank you.
