### ISSUE TITLE
cannot access 'bin/magento': No such file or directory

### ISSUE THREAD

**Issue by ajahongir** [markshust/docker-magento#1086]
**Description**
while installing magento having [issue](https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty) 
installing on 3 machines(also digitailocian droplet) and having same issue. is there any way to fix this? 

**Steps To Reproduce**
1. `cannot access 'bin/magento': No such file or directory` and giving [instruction](https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty) it does not helps. tries on 3 different machines same issue. is there any way to fix it?`

**Expected Result**

_

> root@ubuntu-s-fra1-01:~/Sites/magento# bin/download 2.4.6-p4 community
> [+] Running 7/7
>  ✔ Container magento-mailcatcher-1  Started                                                                                                                                                           1.1s 
>  ✔ Container magento-redis-1        Healthy                                                                                                                                                           6.0s 
>  ✔ Container magento-db-1           Healthy                                                                                                                                                           6.5s 
>  ✔ Container magento-opensearch-1   Healthy                                                                                                                                                          32.5s 
>  ✔ Container magento-rabbitmq-1     Healthy                                                                                                                                                           8.5s 
>  ✔ Container magento-phpfpm-1       Started                                                                                                                                                          32.8s 
>  ✔ Container magento-app-1          Started                                                                                                                                                          33.1s 
> 
> Composer authentication required (repo.magento.com public and private keys):
>     Username: Username
>     Password: Password
> 
> Composer auth has been set up.
> Fixing filesystem ownerships...
> Filesystem ownerships fixed.
> Creating a "magento/project-community-edition=2.4.6-p4" project at "./"
> Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
> 
> In AuthHelper.php line 205:
>                                                                                
>   The 'https://repo.magento.com/packages.json' URL required authentication (H  
>   TTP 401).                                                                    
>   You must be using the interactive console to authenticate                    
>                                                                                
> 
> create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]
> 
> Please check the installation guide at https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty for troubleshooting.

_

**Actual Result**

**Comment by YevhenZvieriev** [comment]
Hi, @ajahongir 

I see you made a mistake.

You entered incorrect Magento authentication keys.

I see, that in this step:

`Composer authentication required (repo.magento.com public and private keys): `

You entered follow:


`Username: Username`
`Password: Password`

It's a **mistake**!

If you don't already have Magento authentication keys - you should create them.

Feel free to look at my answer, [this](https://github.com/markshust/docker-magento/issues/1028#issuecomment-1868334008) will resolve your issue.

If you have any questions, I will help you with pleasure.
