### ISSUE TITLE
Hi, there is a bug in your website.

### ISSUE THREAD

**Issue by leon-zhang-awx** [markshust/docker-magento#1100]
**Description**
When i login in your website, it redirects infinite.

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**

**Comment by leon-zhang-awx** [comment]
Even if I login in another browser, still has problem. They all login via google login.

**Comment by markshust** [comment]
Hi @leon-zhang-awx,

Since this doesn't have to do with the docker-magento repo, I'm going to close this one out. However, I've noticed that Google Login sometimes causes this. Can you try clearing out your cookies and/or logging in and out of Google, and try again?

Cheers,
M
