### ISSUE TITLE
Copytocontainer not working properly in Windows WSL

### ISSUE THREAD

**Issue by bigbadbaz** [markshust/docker-magento#1103]
**Description**
My first attempt at setting up a local Magento development environment on my Windows 11 PC with WSL and Ubuntu. Following the manual setup for existing projects, I have got as far as running bin/copytocontainer --all and the Magento code in folder src clearly isn't copying as it should. 

The containers all appear to be running ok.
NAME                    IMAGE                                 COMMAND                  SERVICE       CREATED        STATUS                  PORTS
magento-app-1           markoshust/magento-nginx:1.18-8       "/docker-entrypoint.…"   app           22 hours ago   Up 22 hours (healthy)   80/tcp, 0.0.0.0:80->8000/tcp, 0.0.0.0:443->8443/tcp
magento-db-1            mariadb:10.6                          "docker-entrypoint.s…"   db            22 hours ago   Up 22 hours (healthy)   0.0.0.0:3306->3306/tcp
magento-mailcatcher-1   sj26/mailcatcher                      "mailcatcher --foreg…"   mailcatcher   22 hours ago   Up 22 hours (healthy)   1025/tcp, 0.0.0.0:1080->1080/tcp
magento-opensearch-1    markoshust/magento-opensearch:2.5-1   "./opensearch-docker…"   opensearch    22 hours ago   Up 22 hours (healthy)   0.0.0.0:9200->9200/tcp, 9600/tcp, 0.0.0.0:9300->9300/tcp, 9650/tcp
magento-phpfpm-1        markoshust/magento-php:8.2-fpm-2      "docker-php-entrypoi…"   phpfpm        22 hours ago   Up 22 hours             9000/tcp
magento-rabbitmq-1      markoshust/magento-rabbitmq:3.11-1    "docker-entrypoint.s…"   rabbitmq      22 hours ago   Up 22 hours (healthy)   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp
magento-redis-1         redis:7.0-alpine                      "docker-entrypoint.s…"   redis         22 hours ago   Up 22 hours (healthy)   0.0.0.0:6379->6379/tcp

**Steps To Reproduce**
1. From ~/Sites/magento run bin/copytocontainer --all

**Expected Result**
Completed copying all files from host to container
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Fixing filesystem permissions...
Filesystem permissions fixed.

**Actual Result**
Successfully copied 110MB to 7f84b4f1c7347ccf228fef7ab29c7b44b7c298e8ba4d911024bf357c138caa65:/var/www/html/
Error response from daemon: cannot overwrite non-directory "/var/www/html/bin" with directory "/var/www/html"
Completed copying all files from host to container
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Fixing filesystem permissions...
find: 'var': No such file or directory
find: 'vendor': No such file or directory
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory
chmod: cannot access 'bin/magento': No such file or directory
Filesystem permissions fixed.

**Comment by bigbadbaz** [comment]
Sorry I didn't spot the discussion Documentation for WSL2 - will put a link and continue in there.

**Comment by bhushanmeetanshi** [comment]
how to install magento247 using docker in windows 10
