### ISSUE TITLE
Xdebug 3.3.1 and Blackfire PHP extension incompatibility

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#1118]
There is currently an outstanding bug with Xdebug 3.3.1, which causes a 502 Gateway Error when it runs alongside the Blackfire PHP extension (see https://bugs.xdebug.org/view.php?id=2230).

Because of this, the PHP 8.1 and 8.2 images have been reverted to Xdebug 3.2.2. Since this version is incompatible with PHP 8.3, the Blackfire extension has been disabled by default in the PHP 8.3 image. This was patched and released in docker-magento 46.1.0.

If you wish to use Blackfire with PHP 8.3, please first disable Xdebug by running `bin/xdebug disable`, and then enable Blackfire with `bin/blackfire enable` until this issue is resolved.

Once the Xdebug but is resolved, we can upgrade Xdebug in all PHP images to that version, rebuild and retag the Docker images, and resolve this ticket.

**Comment by YevhenZvieriev** [comment]
I think you should temporarily duplicate this in the README until it is resolved.

**Comment by markshust** [comment]
Xdebug 3.3.2 was released yesterday. I tested it out, and it appears to fix this issue. I'll have a new build out shortly, so the `markoshust/magento-php:8.3-fpm-1` image and docker-magento `46.1.1` release should resolve this issue!

**Comment by markshust** [comment]
This bug is now resolved. Awaiting the PHP image to be built before merging in https://github.com/markshust/docker-magento/pull/1123
