### ISSUE TITLE
Unable to bind listening socket (php-fpm)

### ISSUE THREAD

**Issue by ashpd** [markshust/docker-magento#112]
Running Docker on Linux.

bash-4.2# cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="7.5"
ID="ol"
VERSION_ID="7.5"
PRETTY_NAME="Oracle Linux Server 7.5"

Error - 
phpfpm_1_516574473f7e | [14-Dec-2018 10:30:24] ERROR: unable to bind listening socket for address '/sock/docker.sock': Address already in use (98)
phpfpm_1_516574473f7e | [14-Dec-2018 10:30:24] ERROR: unable to bind listening socket for address '/sock/docker.sock': Address already in use (98)
phpfpm_1_516574473f7e | [14-Dec-2018 10:30:24] ERROR: FPM initialization failed
phpfpm_1_516574473f7e | [14-Dec-2018 10:30:24] ERROR: FPM initialization failed
docker-magento-master_phpfpm_1_516574473f7e exited with code 78

**Comment by markoshust** [comment]
is this still an issue? a lot of updates have been made to this setup since this post.

**Comment by markshust** [comment]
closing as i'm unable to replicate
