### ISSUE TITLE
Start magento docker containers automatically whenever the host node get started

### ISSUE THREAD

**Issue by MohammadrezaNasrabadi** [markshust/docker-magento#1124]
**Description**

It seems after the Magento cluster is installed with the docker-compose file if the host server gets rebooted or started at another time, the Magento containers won't be started automatically. I think it's better to add a `restart-policy` option on the compose file.

**Steps To Reproduce**
1. Just set up Magento based on the provided documentation and reboot the server. You can see that Magento containers aren't started automatically.

**Expected Result**

**Actual Result**

**Comment by markshust** [comment]
This setup is meant for development, and I don't think we want to auto-start containers on boot. I think it's simple enough to run `bin/start` after a reboot. We also want to make sure resources aren't unnecessarily utilized on system starts.
