### ISSUE TITLE
Abort docker-compose install on non-empty directory

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#1126]
If you try to install docker-magento on a non-empty directory, the following lines occur:

```
mv: rename compose/bin to ./bin: Directory not empty
mv: rename compose/env to ./env: Directory not empty
mv: rename compose/template to ./template: Directory not empty
mv: rename compose/.vscode to ./.vscode: Directory not empty
Initialized empty Git repository in /Users/markshust/Sites/m247/.git/
```

...then, installation continues, and fails. Let's simply detect if the `bin` directory exists in new project directory, and if it does, bail out of the install right away to prevent this from occuring.

**Comment by YevhenZvieriev** [comment]
Good idea, I'll do it!

Please, feel free to check my [PR](https://github.com/markshust/docker-magento/pull/1127) to ensure it works as expected.
