### ISSUE TITLE
Incorrect link in the oneliner script

### ISSUE THREAD

**Issue by YevhenZvieriev** [markshust/docker-magento#1129]
After merging my [PR](https://github.com/markshust/docker-magento/pull/1127), I wanted to test if it works as expected.

Unfortunately, I got the error `mv: cannot move: Directory not empty` again and again, although the folder was not empty, and wasn't detected that it was not empty.

![Screenshot from 2024-04-18 00-39-37](https://github.com/markshust/docker-magento/assets/43544955/48b5f777-e6f5-4f7f-b6cf-7df0800fc69c)

And I noticed, that @markshust  changed the default branch from `master` to `release/next`  but didn't update the links and the one-line script still uses old links.

This is a gross mistake, I'll fix it ASAP!

**Comment by markshust** [comment]
See https://github.com/markshust/docker-magento/pull/1130#issuecomment-2065218945
