### ISSUE TITLE
Are you planning to include PWA studio in this docker?

### ISSUE THREAD

**Issue by MagePsycho** [markshust/docker-magento#113]
Magento 2.3 comes with PWA studio for frontend development which has some dependencies with node and other tools.
Do you have any plan to include PWA studio tools with this docker?

**Comment by markoshust** [comment]
Node and npm support are already in this docker build at bin/node and bin/npm. What specifically are you looking for?


________________________________

**Comment by hassanas** [comment]
Specially need to add pew studio and venia theme files.

**Comment by markshust** [comment]
i'm not sure if this is still a valid ticket. pwa studio runs as a node process and magento already supplies docker images for it.

**Comment by furan917** [comment]
@hassanas For what it is worth you can do ad the following (though you may well have found another way by now) to your setup, either in its own folder or within your current setup using Marks containers. The only thing you have to worry about is the context and dockerfiles being changed to what is right for your system. 

`
version: '3'
services:
  pwa:
    hostname: docker.pwa.local
    build:
      context: ./pwa-studio/
      dockerfile: ../pwa/Dockerfile
    container_name: pwa
    volumes:
      - ./pwa-studio/packages/:/usr/src/app/packages/:rw
      - ./pwa-studio/scripts/:/usr/src/app/scripts/:rw
      - ./pwa-studio/.env:/usr/src/app/.env:rw
      - ./pwa-studio/package.json:/usr/src/app/package.json:rw
      - ./pwa-studio/yarn.lock:/usr/src/app/yarn.lock:rw
      - ./pwa-studio/babel.config.js:/usr/src/app/babel.config.js:rw
      - ./pwa-studio/browserslist.js:/usr/src/app/browserslist.js:rw
      - ./pwa-studio/magento-compatibility.js:/usr/src/app/magento-compatibility.js:rw
    ports:
      - 10000:10000
      - 8992:8992
    links:
      - nginx // replace with your web server
    depends_on:
      - nginx // replace with your web server
    command: /bin/sh -c "cp -rf .env ./packages/venia-concept/.env && yarn run build && yarn run watch:venia"
`

Then your docker build can look like this 

`
FROM node:10.14.1-alpine
WORKDIR /usr/src/app

#Install needed tools
RUN apk --no-cache --virtual add \
    python \
    make \
    g++ \
    yarn \
    openssl \
    sudo

RUN sed -e 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/g' \
      -i /etc/sudoers
RUN sed -e 's/^wheel:\(.*\)/wheel:\1,node/g' -i /etc/group

# Copy just the dependency files and configs needed for install
COPY packages/peregrine/package.json ./packages/peregrine/package.json
COPY packages/pwa-buildpack/package.json ./packages/pwa-buildpack/package.json
COPY packages/upward-js/package.json ./packages/upward-js/package.json
COPY packages/upward-spec/package.json ./packages/upward-spec/package.json
COPY packages/venia-concept/package.json ./packages/venia-concept/package.json
COPY package.json ./
COPY yarn.lock ./
COPY babel.config.js ./
COPY browserslist.js ./
COPY magento-compatibility.js ./

# Install dependencies with yarn
RUN yarn install --frozen-lockfile
COPY . ./

# Ensure user permissions for folder is set
RUN chown -R node:node /usr/src/app

# Copy .env file needed for configuration
COPY .env ./packages/venia-concept/.env

USER node
`
then just a small addition of the passthrough to your nginx file

`
server {
    listen 80;
    server_name docker.pwa.local;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host 0.0.0.0;
        proxy_set_header X-NginX-Proxy true;

        proxy_redirect off;
        proxy_pass       http://pwa:10000;
    } 
}
`
and if you were in need of a working .env file? Well here is a sample one

`
ENABLE_SERVICE_WORKER_DEBUGGING=0
PWA_STUDIO_HOT_RELOAD_WITH_POLLING=0
MAGENTO_BACKEND_URL=http://nginx
MAGENTO_BUILDPACK_PROVIDE_SECURE_HOST=0
AVOID_ISTTY_CHECK=1
UPWARD_JS_UPWARD_PATH=venia-upward.yml
UPWARD_JS_BIND_LOCAL=1
UPWARD_JS_LOG_URL=1
BRAINTREE_TOKEN=SOMETOKEN
`

**Comment by markshust** [comment]
Closing out due to inactivity, I don't believe we need anything specific here for PWA support.
