### ISSUE TITLE
Pulling magento 2.2.7 using the automated script attempts to use the php-7.2-fpm container

### ISSUE THREAD

**Issue by uabassguy** [markshust/docker-magento#114]
when using the command shown in the readme, replacing 2.3.0 with 2.2.7, composer fails to install because of a dependency mismatch with php 7.2, it requires 7.1

curl -s https://raw.githubusercontent.com/markoshust/docker-magento/master/lib/onelinesetup|bash -s -- magento2.test 2.2.7

Log truncated:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for colinmollenhour/php-redis-session-abstract v1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - colinmollenhour/php-redis-session-abstract v1.3.4 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.12) does not satisfy that requirement.

As a resolution I have to change the php-fpm specified to 7.1 in yml and run docker-compose up, then ssh into the container with `docker exec -it dockermagento_phpfpm_1 /bin/bash`, then `su app`, then run `composer install`, then it works. Would be nice to have a more elegant solution if you have the time to implement such a fix. If not, at least the workaround is available.

**Comment by uabassguy** [comment]
Also the auth json fails to be stored when asked for magento repo credentials using this method. I had to manually create auth.json at /var/www/.composer/auth.json and change the owner:group to app:app

**Comment by markshust** [comment]
the one-liner assumes you will run the latest php scripts. it won't really work then on 2.2.x (you'll need to use manual setup instructions instead).

it does appear the `auth.json` instructions are outdated and a bit confusing -- i'll update & clarify

**Comment by markshust** [comment]
Clarified in commit above, closing out otherwise.
