### ISSUE TITLE
Magento page showing instead of Storefront

### ISSUE THREAD

**Issue by karthik1987** [markshust/docker-magento#1142]
Hi All,
I'm new to this vue storefront and trying to install own my self. 
I have installed everything successfully and my files are located in DigitalOcean server. 
After executing "yarn dev" and I got the final output "Listening on: http://localhost:3000/"
but when I visit the domain like https://domain.top it's showing only Magento page.

I dont know how to point to run the domain with vue store front? Please help me out.

**Comment by markshust** [comment]
Since this isn't an issue with this repo, I'll be closing it out, but you would access http://localhost:3000 to see your Vue Storefront instance.
