### ISSUE TITLE
Cron is not runing

### ISSUE THREAD

**Issue by luancschmitz** [markshust/docker-magento#1158]
**Description**
When I run bin/start or bin/cron start the terminal show this message: 
Starting periodic command scheduler: cron.
![image](https://github.com/markshust/docker-magento/assets/13907586/0676bbef-d809-45f1-86e3-3cfc646e2019)
but cron doesn't run.

If I type contrab -l in the terminal inside the container, the following screen appears:

![image](https://github.com/markshust/docker-magento/assets/13907586/4112752f-1855-4542-989b-4ed1f9a26894)

But if I run bin/magento cron:run, the following screen appears:
![image](https://github.com/markshust/docker-magento/assets/13907586/08eb3ba7-20fb-45d5-a156-39d8f94dcdfd)
with the message: 
Cron is disabled. Jobs were not run.

Magento Version: 2.4.6

**Steps To Reproduce**
1. Run bin/cron start

**Expected Result**
1. Cron works

**Actual Result**
1. Cron does not works.

**Comment by YevhenZvieriev** [comment]
Hi, @luancschmitz 

You can get the cron working by running:

```
bin/magento cron:install
```

**Comment by luancschmitz** [comment]
> Hi, @luancschmitz
> 
> You can get the cron working by running:
> 
> ```
> bin/magento cron:install
> ```

Hi, in the last print II had already do this. Without sucess

**Comment by sdouma** [comment]
This indicts in your deployment configuration(env.php) that cron/enabled is not set to 1
```
    'cron' => [
        'enabled' => 1, // Enable or disable cron jobs as needed
    ...
    ```

**Comment by luancschmitz** [comment]
> This indicts in your deployment configuration(env.php) that cron/enabled is not set to 1
> 
> ```
>     'cron' => [
>         'enabled' => 1, // Enable or disable cron jobs as needed
>     ...
> ```

Hello!
Thanks, now the crons is running.
