### ISSUE TITLE
Elasticsearch container using a lot of memory

### ISSUE THREAD

**Issue by abdel-aouby** [markshust/docker-magento#1162]
**Description**
I'm on UBUNTU 24.04 with the docker engine and not the docker desktop

Elasticsearch container uses a lot of memory. This may be a wrong configuration of docker on my part. please I will need help with that if possible.
My machine has 32 G of memory, and the Elasticsearch is using about half of it (this does not happen to me with other projects on the same machine)

**Steps To Reproduce**
1. bin/start
2. check the running processes

**Expected Result**
Elasticsearch container does not consume too much memory when runing

**Actual Result**
Elasticsearch container using a lot of memory (more than 50%)

![Screenshot from 2024-05-27 10-51-08](https://github.com/markshust/docker-magento/assets/56534840/c6daa843-ebd4-4375-8df0-37349eaf86f4)

![Screenshot from 2024-05-27 10-51-38](https://github.com/markshust/docker-magento/assets/56534840/3b374a2f-e470-402a-9d8c-19702180220f)

![Screenshot from 2024-05-27 10-52-11](https://github.com/markshust/docker-magento/assets/56534840/772bb7e0-9873-4de9-86e0-cf33cf9669b7)

**Comment by YevhenZvieriev** [comment]
Hi @abdel-aouby 

You can set the minimum and maximum heap size to an appropriate value in your `compose.yaml` file. For example, to limit Elasticsearch to 8GB of memory:

```
- "ES_JAVA_OPTS=-Xms8g -Xmx8g"
```

![Screenshot from 2024-05-27 18-11-15](https://github.com/markshust/docker-magento/assets/43544955/18d40166-87a4-4930-b181-259f8c18820d)

**Comment by abdel-aouby** [comment]
Hi @YevhenZvieriev 
it works fine I had an old version of the project that did not contain this value, thank you for your help
I'm closing the issue.
