### ISSUE TITLE
failed to created shim task

### ISSUE THREAD

**Issue by haerriz** [markshust/docker-magento#1176]
Error message
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/haerriz/.ssh/known_hosts" to rootfs at "/var/www/.ssh/known_hosts": mount /home/haerriz/.ssh/known_hosts:/var/www/.ssh/known_hosts (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Expected Result**
To run all containers

**Actual Result**
Containers not running and couldn't access on storefront

**Comment by its-leoeff511** [comment]
I ran `bin/remove` then `bin/start` and it worked for me

**Comment by markshust** [comment]
It looks like it's telling you how to fix it:

> error mounting "/home/haerriz/.ssh/known_hosts" to rootfs at "/var/www/.ssh/known_hosts": mount /home/haerriz/.ssh/known_hosts:/var/www/.ssh/known_hosts (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

There was an error mounting `/home/haerriz/.ssh/known_hosts`. "Check if the specified host path exists".

Does that directory (`/home/haerriz/.ssh`) and file within it (`known_hosts`) exist?
