### ISSUE TITLE
Error with PHPCSF

### ISSUE THREAD

**Issue by YevhenZvieriev** [markshust/docker-magento#1181]
### I am following this tutorial https://courses.m.academy/courses/487758/lectures/52642491 from M.Academy, but I get an error:

![Screenshot from 2024-06-24 01-16-27](https://github.com/markshust/docker-magento/assets/43544955/2320df87-bc5d-4ad8-8d79-5a3ae759731c)

### Before this I get an infinity loop when trying to refactor code:

![Screenshot from 2024-06-24 01-16-21](https://github.com/markshust/docker-magento/assets/43544955/af60a049-ed66-4f9f-a460-97de43885185)

### It is my PHPCSF and PHPCS configurations:
![Screenshot from 2024-06-23 21-03-53](https://github.com/markshust/docker-magento/assets/43544955/a7673706-1640-409a-ab75-abb685447262)

![Screenshot from 2024-06-24 01-15-57](https://github.com/markshust/docker-magento/assets/43544955/19649aab-a939-4566-a145-f05cbe1e4d72)

![Screenshot from 2024-06-24 01-16-38](https://github.com/markshust/docker-magento/assets/43544955/66a7881f-cfce-40ab-97fc-d912304d87d9)

### Has anyone experienced this?

**Comment by markshust** [comment]
Your screenshots show System PHP, not the phpfpm container settings. It needs to be set to phpfpm, not the system PHP binary.

Also note that you need to choose "Connect to existing container" in one of those configs, as "Always create new container" will add tremendous overhead to the setup, and can cause the issue that you are experiencing. This should all be documented in the course and related lessons.

**Comment by YevhenZvieriev** [comment]
Hi, @markshust 

Really! I changed the Lifecycle from "Always create new container" to "Connect to existing container" and it fixed the infinity loop.

It works for me, thanks!
