### ISSUE TITLE
Suggestion on how to run bin/xdebug very quickly

### ISSUE THREAD

**Issue by HoePe999** [markshust/docker-magento#1189]
We are happy and heavy users of your Docker environment for local development.
Of the many useful commands, bin/xdebug is certainly the most frequently used.
Enabling and disabling xdebug is achieved with
 
bin/restart phpfpm
 
As this takes a long time (too long for impatient developers), we have a suggestion on how to run bin/xdebug very quickly:
 
bin/cli kill -USR2 1

**Comment by YevhenZvieriev** [comment]
Hi, @HoePe999 

I understand that restarting php-fpm using bin/restart phpfpm takes too long. Your suggestion to use bin/cli kill -USR2 1 to speed up this process seems like a viable alternative, and this approach will be quicker if your system is configured to handle the USR2 signal for a quick php-fpm restart. Please make sure your system is properly set up to handle the USR2 signal before applying these changes to avoid any unintended side effects.

If it works for you, I'll implement this ASAP, thx.

**Comment by markshust** [comment]
This is awesome @HoePe999. All merged in https://github.com/markshust/docker-magento/pull/1245
