### ISSUE TITLE
how to create multi website using magento docker

### ISSUE THREAD

**Issue by bhushanmeetanshi** [markshust/docker-magento#1190]
**Description**
how to create multi website using magento docker

**Steps To Reproduce**
1. goto store.
2. create website.
3. allow store code url from the store configurations.
4. setup all config urls in DB.
5. set up test website folder with index.php and htaccess file in root directory.
6. execute` bin/magento c:f `&& `bin/magento c:c `command.
7. Check Front end URL magento.test/testwebsite. 

**Expected Result**
website should be created and accessible.

**Actual Result**
showing 404 page

**Comment by piotrkwiecinski** [comment]
You can check my comment here https://github.com/markshust/docker-magento/pull/869#issuecomment-1640198793 and see if it helps. I use it for a couple years now.

**Comment by bhushanmeetanshi** [comment]
@YevhenZvieriev  Do u have any idea how to create multi website in magento docker?

**Comment by YevhenZvieriev** [comment]
Hi, @bhushanmeetanshi 

Answer @piotrkwiecinski  didn't resolve your issue?

**Comment by bhushanmeetanshi** [comment]
> You can check my comment here [#869 (comment)](https://github.com/markshust/docker-magento/pull/869#issuecomment-1640198793) and see if it helps. I use it for a couple years now.

@piotrkwiecinski not able to find the path as per your mentioned path. how can i configure and set the path of this given code. can share the steps for this.

**Comment by bhushanmeetanshi** [comment]
> Hi, @bhushanmeetanshi
> 
> Answer @piotrkwiecinski didn't resolve your issue?
> 
> Feel free to check this one: https://courses.m.academy/courses/487758/lectures/14780970
> 
> I hope it will help you

Thanks @YevhenZvieriev your solution is working for me. Thanks a lot for help.
