### ISSUE TITLE
Manual insatllation - cp: cannot stat 'C:/Program Files/Git/var/www/.composer/auth.json': No such file or directory

### ISSUE THREAD

**Issue by margotr** [markshust/docker-magento#1198]
I am on Windows, doing the manual setup. After running `bin/download 2.4.7 community`, it runs until I reach  `cp: cannot stat 'C:/Program Files/Git/var/www/.composer/auth.json': No such file or directory`. 

The docker containers are created and running. 

I have tried: 
- Manually creating `'C:/Program Files/Git/var/www/.composer/auth.json'`, this makes no difference
- Making `C:/Program Files/Git` not read-only, this makes no difference. 

What else can I try?

**Edit: Additional info:**
If I go ahead and run `bin/setup magento.test` afterwards, it starts all containers but ends at 

```
Running, Magento setup:install...
Could not connect to the Amqp Server.

In InstallCommand.php line 282:

  Parameter validation failed
```

**Comment by Digital-Pig-LLC** [comment]
I have the same issue here, exactly the same error message. Also on Windows with WSL.

**Comment by markshust** [comment]
Note that the entire `.composer` directory is [mounted in `compose.yaml`](https://github.com/markshust/docker-magento/blob/release/next/compose/compose.yaml#L20), so if this directory doesn't exist on your host machine, the install will fail.

Is `~/.composer` the correct location for the Composer cache on Windows machines? I'm sorry, I don't know as I only run macOS. You can either set this to the proper location, or comment this line out in the `compose.yal` file and all should work as expected. It's not absolutely required to mount this directory, it's moreso to speed up caching on subsequent installs.

**Comment by Digital-Pig-LLC** [comment]
Sorry, I forgot I added to this ticket. I wiped the container and executed the steps in the script individually, and I ended up with a perfect working solution. It may have been how my WSL was set up, but all is well now. And you're awesome for saving us so much time. I worked with the Magento team originally when they first released it, and it was a cinch to install. Since Adobe took it over it's a nightmare for on-prem installs (funny I worked for Adobe as well and bitched like hell about it).
All is well now, anyway, so I will get on.

**Comment by joevayalil** [comment]
I also have the same issue in Windows - getting 
cp: cannot stat 'C:/Users/jjohn/AppData/Local/Programs/Git/var/www/.composer/auth.json': No such file or directory

**Comment by joevayalil** [comment]
I also have the same issue in Windows - getting
`cp: cannot stat 'C:/Users/jjohn/AppData/Local/Programs/Git/var/www/.composer/auth.json': No such file or directory`
while running  bin/download community 2.4.7-p3.

In compose.yaml, it is set as 
`- ~/.composer:/var/www/.composer:cached`
and  .composer exists in C:/Users/jjohn/, not in C:/Users/jjohn/AppData/Local/Programs/Git/var/www/. Where can I update this wrong path to point to the right one, if I have to do it outside of compose.yaml? Please help.
