### ISSUE TITLE
404: not found on automated setup

### ISSUE THREAD

**Issue by antwake** [markshust/docker-magento#120]

**Comment by antwake** [comment]
Tried the one line setup and got a 404 not found error

stack trace:
curl -s -v https://raw.githubusercontent.com/markoshust/docker-magento/master/lib/onelinesetup\|bash -s -- magento23.t

*   Trying 151.101.136.133...
* TCP_NODELAY set
* Connected to raw.githubusercontent.com (151.101.136.133) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=www.github.com
*  start date: Mar 23 00:00:00 2017 GMT
*  expire date: May 13 12:00:00 2020 GMT
*  subjectAltName: host "raw.githubusercontent.com" matched cert's "*.githubusercontent.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /markoshust/docker-magento/master/lib/onelinesetup|bash HTTP/1.1
> Host: raw.githubusercontent.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< X-GitHub-Request-Id: 1576:02C2:1536DC:16A9AD:5C53BD73
< Content-Length: 15
< Accept-Ranges: bytes
< Date: Fri, 01 Feb 2019 03:31:24 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-yul8921-YUL
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1548991885.778358,VS0,VE0
< Vary: Authorization,Accept-Encoding
< Access-Control-Allow-Origin: *
< X-Fastly-Request-ID: 1e96d13e4f9f2a019a0c3cd225664fca255ed949
< Expires: Fri, 01 Feb 2019 03:36:24 GMT
< Source-Age: 25
<
404: Not Found
* Connection #0 to host raw.githubusercontent.com left intact
* Rebuilt URL to: magento23.test/
* Could not resolve host: magento23.test
* Closing connection 1
* Rebuilt URL to: 2.3.0/
*   Trying 2.3.0.0...
* TCP_NODELAY set
* Connection failed
* connect to 2.3.0.0 port 80 failed: Operation timed out
* Failed to connect to 2.3.0 port 80: Operation timed out
* Closing connection 2

Can you help me with this?

**Comment by markshust** [comment]
my github username changed from markoshust to markshust. i think you are using the old github url. please see https://github.com/markshust/docker-magento#automated-setup-new-project for the updated one

**Comment by antwake** [comment]
I typed 
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup|bash -s -- magento2.test 2.3.0`

but it didn't change the result.

here's the stack trace

```
404: Not Found
* Connection #0 to host raw.githubusercontent.com left intact
* Rebuilt URL to: magento2.test/
* **Could not resolve host: magento2.test**
* Closing connection 1
* Rebuilt URL to: 2.3.0/
*   Trying 2.3.0.0...
* TCP_NODELAY set
```

**Comment by markshust** [comment]
are you using Terminal or iTerm? i noticed iTerm adds an additional slash before the pipe bash delimiter

the url https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup pulls up for me

**Comment by antwake** [comment]
Good call!

I'm using Hyper.js with zsh.

Removed the / at the end and it worked!

thank you

**Comment by markshust** [comment]
awesome! glad that fixed it
