### ISSUE TITLE
Configure Remote PHP Interpreter - cannot run program error

### ISSUE THREAD

**Issue by its-leofisher** [markshust/docker-magento#1203]
**Description**
While configuring remote php interpreter and adding composer.yaml files, docker compose is not found.

**Steps To Reproduce**
1. Following these steps: https://courses.m.academy/courses/set-up-magento-2-development-environment-docker/lectures/9748834

**Expected Result**
Able to select phpfpm

**Actual Result**
<img width="553" alt="image" src="https://github.com/user-attachments/assets/480a8532-6355-4308-8644-89f1eff44dd4">

**Comment by YevhenZvieriev** [comment]
Hi, @its-leofisher 

Make sure that Docker Compose is installed on your system. You can check this by running `docker-compose --version`

**Comment by its-leofisher** [comment]
> Hi, @its-leofisher
> 
> Make sure that Docker Compose is installed on your system. You can check this by running `docker-compose --version`

Thanks @YevhenZvieriev 

For someone in the future. I had to switch settings in Docker Desktop in Advanced settings from User to System, which made docker-compose available in CLI
Settings:
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/08a3e959-63ef-4ea6-a064-1bb83d419dce">

Location:
<img width="803" alt="image" src="https://github.com/user-attachments/assets/9898df74-c321-4a55-9f89-c1793f000576">

Restarted my computer, ran bin/start, went through the process in phpstorm again, and still receiving the error.

**Comment by its-leofisher** [comment]
Ah nevermind I'm getting this now:
<img width="827" alt="image" src="https://github.com/user-attachments/assets/7bf7fcae-b2bf-4c78-a1a2-1021057388b9">

**Comment by roneclay** [comment]
Hi everyone,

I followed the steps mentioned here, including **verifying the installation of Docker Compose** and **switching the settings in Docker Desktop from "User" to "System"** as suggested.

After making this change, everything is now working perfectly for me.

Thanks for the help!

**Comment by its-leofisher** [comment]
Finally resolved via using desktop-linux setting for docker on my Macbook pro I was able to validate for phpcodesniffer and other actions:

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/7956ddf9-319e-4613-9dbf-a8a3fd3db05a">
