### ISSUE TITLE
my current version is 2.4.6-p3 and how to update to 2.4.7-p2

### ISSUE THREAD

**Issue by sivajik34** [markshust/docker-magento#1208]
i have ran bin/update but it seems not working

**Comment by YevhenZvieriev** [comment]
Hi, @sivajik34 

The script you are running `bin/update` is designed to update your Docker environment for Magento, not Magento itself. To update Magento from version 2.4.6-p3 to 2.4.7-p2, you'll need to follow a different process.

### 1. Backup your files and database before starting the update process.

### 2. Update the Composer dependencies to the latest Magento version:

```
bin/composer require magento/product-community-edition=2.4.7-p2 --no-update
bin/composer update
```

### 3. Run Magento's upgrade commands:

```
bin/magento setup:upgrade
bin/magento cache:flush
bin/magento setup:di:compile
bin/magento setup:static-content:deploy -f
```

Let me know if you need any further assistance :)

**Comment by sivajik34** [comment]
Thank you so much
