### ISSUE TITLE
Autoload error

### ISSUE THREAD

**Issue by itsazzad** [markshust/docker-magento#122]
Vendor autoload is not found. Please run 'composer install' under application root directory.

**Comment by markshust** [comment]
did you run `bin/composer install`?

**Comment by itsazzad** [comment]
[UnexpectedValueException]                                                                                                                        
  The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/vertex/module-tax/vertex-module-tax-3.0.0.0.zip)

**Comment by itsazzad** [comment]
Now running:
`bin/cli composer update vertex/sdk`

**Comment by protzi** [comment]
@markshust had the same issue as @itsazzad 
after compose install and composer update/vertex/sdk have this...
<img width="1670" alt="screen shot 2019-02-04 at 10 04 52 pm" src="https://user-images.githubusercontent.com/17887536/52233995-3721a480-28c9-11e9-848c-ddae66a87ca6.png">

**Comment by markshust** [comment]
i'm closing this as a non-issue. please supply exact steps to replicate (i can't replicate).
