### ISSUE TITLE
Xdebug on bin/magento doesn't work (Docker on Mac)

### ISSUE THREAD

**Issue by gkopec** [markshust/docker-magento#1221]
I tried to use this video instructions:
 https://courses.m.academy/courses/set-up-magento-2-development-environment-docker/lectures/36677538 
to set up Xdebug on CLI commands. But PHPStorm is showing me this:

![image](https://github.com/user-attachments/assets/3a7dba5a-bbc8-4290-a5a7-f06b00dcec4c)

Here is the command it produced:
```
"[docker-compose://[/Users/genius-dev/Workspace/projects/tip/b2c/compose.yaml, /Users/genius-dev/Workspace/projects/tip/b2c/compose.dev.yaml]:phpfpm/]:php" -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=docker.for.mac.localhost /var/www/html/bin/magento
```

I already tried to set up `host.docker.internal` but it didn't resolve the issue:

![image](https://github.com/user-attachments/assets/9d7caf50-1bf9-46a5-9058-6dffff24de09)

Xdebug works with HTTP connection without any problems but I can not force it to debug CLI commands.

**Comment by Hawksama** [comment]
Can you try running cli command using this bash file?

https://github.com/Hawksama/docker-magento/blob/master/compose/bin/php-xdebug

**Comment by markshust** [comment]
Works for me
