### ISSUE TITLE
Xdebug not stopping at the breakpoints ( Linux ) 

### ISSUE THREAD

**Issue by postadelmaga** [markshust/docker-magento#1222]
I followed all the instruction on the video tutorial:

1. Enabled xdebug in the container installation `bin/xdebug enable`
2. Installed the Xdebug helper ( and set the key to `PHPSTORM`)
3. Configured Phpstorm, added the debug configuration and started it ( `Waiting for incoming connection with ide key 'PHPSTORM'` is correctly shown in the ide)

The **CLI script debug works fine** but the `index.php` doesn't stop on any breakpoints ( I used the `$bootstrap= ...` line as showed in the instruction )

I tried to add manually the parameter to the url `?XDEBUG_SESSION=PHPSTORM` but nothing :( 

What else can I try ?

**Comment by Hawksama** [comment]
Have you created the server and configured the absolute of the src folder to point to "/var/www/html/"?

**Comment by markshust** [comment]
I've tested out the Xdebug implementation numerous times and it works, so I'd recommend to open up a new discussion thread on the topic rather than an issue, because I'm unable to replicate.
