### ISSUE TITLE
Rebbitmq : deprecated environment variables

### ISSUE THREAD

**Issue by touqeerjalal1984** [markshust/docker-magento#1224]
**Description**
When trying to upgrade rabbitmq to [3.12-0] for Magento 2.4.7-p2 getting the following error
error: RABBITMQ_VM_MEMORY_HIGH_WATERMARK is set but deprecated
error: deprecated environment variables detected

**Steps To Reproduce**
1. update the rabbitmq version from docker-compose.yml and run bin/restart

**Expected Result**
Should be updated the version with no error

**Actual Result**
stop the container and logging the error.

**Comment by markshust** [comment]
I noticed you mentioned `docker-compose.yml`, so I'm assuming you are on a very old version of docker-magento. The version number should be found at the top of this file -- the current version is 48.0.0.

This env var [hasn't been present for a while](https://github.com/markshust/docker-magento/blob/release/next/compose/env/rabbitmq.env). You can just try removing it either in the `env/rabbitmq.env` file or in your compose yaml file.
