### ISSUE TITLE
Magento_ServicesConnector error: upgrade from 2.4.5-p7 to 2.4.7-p2

### ISSUE THREAD

**Issue by drew-bombard** [markshust/docker-magento#1229]
I've been using your Docker container/sandbox setup for about 2 years and have run into an issue that I haven't seen before.

Here's the process I've been employing with the local upgrade so far:

- Duplicating my local sandbox environment that (up until now) has been running 2.4.5-p7 with little/no issues.
- Updating `"magento/product-enterprise-edition": "2.4.5-p7",` in composer.json to `"magento/product-enterprise-edition": ">=2.4.7 <2.4.8",`
- Running `composer cc` and then `composer update -W`

Composer runs/installs just fine.  After that _**no**_ `bin/magento` commands will run due to the following error:

`There is an error in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php at line: 50
Cannot instantiate interface Magento\ServicesConnector\Api\ClientResolverInterface#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Service...')`

I have bin/bashed into the container and can confirm that /vendor/magento/services-connector does exist and it's registration.php file lists the name as `Magento_ServicesConnector`

I've tried completely nuking the vendor directory and installing it from scratch.  Same.

I've even tried running `bin/composer require magento/services-connector` which then adds it to the composer.json file of course.

Still nothing.  What am I missing here?!?

**Comment by danstaver** [comment]
@drew-bombard can it be your app/etc/di.xml? Make sure that your container is updated with the latest one from 2.4.7. Also, you can make sure you nuke the Setup folder as well, and get latest one from 2.4.7

**Comment by drew-bombard** [comment]
Honestlly... last week it just started working again.  I don't even recall what the hell I even did to get it to work.  And then today... poof.  Back to the ServicesConnector error again.  It's in the composer.lock file.  I can see it.  I can see the folder inside of vendor/...

The di.xml file has nothing specific about \ServicesConnector, but there were a few minor differences/changes that I pulled from https://github.com/magento/magento2/blob/2.4-develop/app/etc/di.xml... no idea if that will make any difference.

**Comment by markshust** [comment]
This is a code-related issue, doesn't seem to be related to docker-magento, so going to go ahead and close this one out.
