### ISSUE TITLE
 Laravel installation error Project directory "/var/www/lara" is not empty. How to fix?

### ISSUE THREAD

**Issue by ProAnanas7** [markshust/docker-magento#1232]
Powershell write
C:\Project> docker-compose up -d --force-recreate --build

C:\Project> docker compose exec php-cli bash

I have no name!@d3ed6c168a56:/var/www$ composer create-project laravel/laravel lara

The first installation of Laravel encountered errors

  Could not delete /var/www/lara/vendor/composer/4c05613e/FakerPHP-Faker-bfb4fe1/src/Faker/Provider/id_ID:
it was not possible to download the full package; when installing again, it gives the error

Project directory "/var/www/lara" is not empty.

Removing containers Docker, stopping, deleting the cache ,installing in a new directory

In CreateProjectCommand.php line 369:

  Project directory "/var/www/lara" is not empty.

I found information here but I don't understand 

bin/removeall
cd ..
rm -rf yourproject

![5](https://github.com/user-attachments/assets/204e6127-ac81-4a35-9c50-1c7e10014d64)
![4](https://github.com/user-attachments/assets/ff4acd23-0fe5-4d8d-8a22-d9cb5e3a214d)

**Comment by markshust** [comment]
WSL2 is not officially supported, so I'll really only take open PRs to fix this (won't keep open ticket issues for it). Thanks!
