### ISSUE TITLE
i get line 6 bc not found and 

### ISSUE THREAD

**Issue by sridharsikha** [markshust/docker-magento#1235]
**Description**
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
bin/start: line 6: bc: command not found

**Steps To Reproduce**
1. use the setup and the manual steps - on windows - using wsl --install and powershell.  

**Expected Result**
no warnings

**Actual Result**
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
bin/start: line 6: bc: command not found

**Comment by dusp2k** [comment]
After some research I got it working using wsl2. 

So don't run the script directly in windows or git-bash. Go into wsl and run the script there.

Also be sure docker desktop has wsl2 enabled.

**Comment by markshust** [comment]
WSL2 is not officially supported, so I'll really only take open PRs to fix this (won't keep open ticket issues for it). Thanks!

**Comment by viktarrama** [comment]
I had this problem in wsl2. It fixed by `sudo apt-get install bc`
