### ISSUE TITLE
403 Forbidden nginx/1.24.0

### ISSUE THREAD

**Issue by prashantmahabare** [markshust/docker-magento#1240]
**Description**
Thanks for the amazing script and help in setting up docker magento project. 
I am using Existing Setup & able to fix all the issues related to ssl, github, elastic search enabling, mysql errors.
Completed all the steps without any error. 
But I still get this error in browser
"403 Forbidden nginx/1.24.0"
Also I am not able to find any logs in /var/log/nginx its not there.
Also PHPMyADMIN does not launch http://localhost:8080.

**Steps To Reproduce**
1. Open url in browser

**Expected Result**
Should open home page

**Actual Result**
"403 Forbidden nginx/1.24.0"

**Comment by prashantmahabare** [comment]
I can see some errors in Docker Container:
[error] 29#29: *103 directory index of "/etc/nginx/html/" is forbidden, client: 172.18.0.1, server: , request: "GET / HTTP/2.0", host: "XXXXXXXX"

**Comment by prashantmahabare** [comment]
Hello @markshust ,

I fixed this myself by running bin/fixperms & bin/owns. Also by restarting my mac.

Thanks
You can close this issue.

**Comment by doob85** [comment]
sorry but error comes again here!
after completing installation and running docker compose up -d then docker compose stop and again docker compose up -d i get the same error

**Comment by doob85** [comment]
saw it on my own i had to use the bin/restart script thx anyway
