### ISSUE TITLE
Docker Issue on Port 80?

### ISSUE THREAD

**Issue by jonpfluger** [markshust/docker-magento#1248]
**Description**
Hello

I am new to Magento and Docker. I am trying to follow along with the "Set up Magento with automated script" video on M.academy. I run the script which generates a lot of files and starts the docker containers, however one of the containers, app-1, fails and gives an error about port 80 already being in use. I have tried to locate the source of what is using port 80, which it says is docker. I use the command to kill that process, and then I get an error saying daemon isn't running. So I restart docker desktop to get daemon running again, and its running on port 80 again so I get the first error again. I am confused and probably just because I'm new to this. 

Also, not sure if its related to this but I noticed it also is not generating a "src" folder with the app/code or the vendor or anything.

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**
"Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp4 0.0.0.0:80: bind: address already in use"
<img width="868" alt="Screenshot 2024-11-19 at 3 55 43 PM" src="https://github.com/user-attachments/assets/5ece3522-ec5a-4ee2-98b4-1b1bca434a02">

**Comment by jonpfluger** [comment]
I am using MacOS 15.1 Sequoia

The command I was using to find whats using port 80 was: "lsof -i :80"

The command I was using to kill that process was "sudo kill -9 12345".

That is when it would say Daemon is not running. Then I close and reopen Docker Desktop to get Daemon running again.

**Comment by rubenromao** [comment]
@jonpfluger try to run:
- bin/stop
- docker ps
The `docker ps` will output any running containers. if there is anything still running in the background binding port 80 run:
- docker stop <container hash id>
Then rerun the curl command.

**Comment by jonpfluger** [comment]
That worked, thank you!
