### ISSUE TITLE
Cron is not working.

### ISSUE THREAD

**Issue by gekamikh** [markshust/docker-magento#125]
I ran new Magento project.
1. I clone template: `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template|bash -s -- magento-2`
2. I download magento: `bin/download 2.3.0`
3. I add hosts: `echo "127.0.0.1 magento2.test" | sudo tee -a /etc/hosts`
4. In `docker-compose.dev.yml` I remove comments to enable `cron`
5. I run command `bin/start` to start magento
6. I run command `bin/setup magento2.test` to setup magento

I have 4 running containers, including `cron`
<img width="1280" alt="2019-02-13 10 20 37" src="https://user-images.githubusercontent.com/18705338/52696973-0ef50e00-2f79-11e9-8501-0bceba55823b.png">

But in db table `cron_schedule` still no registered cron jobs.
<img width="764" alt="2019-02-13 10 34 52" src="https://user-images.githubusercontent.com/18705338/52697867-08679600-2f7b-11e9-8b4e-9403ae2cb167.png">

If I connect to phpfpm container (where based on other issues cron running) by command `docker exec -it my-magento-store_phpfpm_1 /bin/bash` and run `crontab -l` the result will be `no crontab for app`.

Running `bin/magento cron:run` working as well. But how can I setup or enable cron to run jobs not manualy.
Thanks!

**Comment by markshust** [comment]
can you try again, but following exact steps at https://github.com/markshust/docker-magento#manual-setup

the steps you have taken differ from the readme. after magento is completely installed and running, then try enabling cron.

**Comment by markshust** [comment]
I did confirm the cron was not working. The above commit fixes it. New release will come out shortly.
