### ISSUE TITLE
bin/stop stop all container

### ISSUE THREAD

**Issue by frostblogNet** [markshust/docker-magento#126]
Hi @markshust 

I found out that bin/stop causing all container to stop regardless that they are not in the scope of this setup. You can reproduce this by starting a container elsewhere and run bin/stop.

Thanks
Jens

**Comment by markshust** [comment]
I'm unable to replicate.

Steps:
- Create new project at `~/Sites/magento-community-230`
- Create new project at `~/Sites/magento-community-230a`
- Run `bin/start` for `~/Sites/magento-community-230a`
- Go to `~/Sites/magento-community-230`
- Run `bin/stop`

Expected & Actual Result:
- No containers stop
- Containers for `~/Sites/magento-community-230a` are still running
