### ISSUE TITLE
Something wrong with Nginx - /etc/nginx/conf.d/default.conf differs from the packaged version

### ISSUE THREAD

**Issue by andkirby** [markshust/docker-magento#1266]
**Description**
For some reason `/etc/nginx/conf.d/default.conf` hasn't been read by nginx. This file wasn't changed.

**Steps To Reproduce**
1. Follow steps to install magento community version
2. Open https://magento.test/

**Expected Result**
Magento app page.

**Actual Result**
403 error

and in logs:
```
2024/12/09 02:54:28 [error] 29#29: *309 directory index of "/etc/nginx/html/" is forbidden, client: 172.18.0.1, server: , request: "GET / HTTP/2.0", host: "magento.test"
```

I was trying to check logs on start, and found these two strange lines:
```
app-1          | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
app-1          | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
```

#### UPD
Dug up in `10-listen-on-ipv6-by-default.sh`... It seems it does not break loading algorithm.

<details>
  <summary>`10-listen-on-ipv6-by-default.sh`</summary>

    case "$ID" in                                                                                                           
        "debian")                                                                                                           
            CHECKSUM=$(dpkg-query --show --showformat='${Conffiles}\n' nginx | grep $DEFAULT_CONF_FILE | cut -d' ' -f 3)    
            echo "$CHECKSUM  /$DEFAULT_CONF_FILE" | md5sum -c - >/dev/null 2>&1 || {                                        
                entrypoint_log "$ME: info: /$DEFAULT_CONF_FILE differs from the packaged version"                           
                exit 0                                                                                                      
            }                                                                                                               
            ;;                                                                                                              
        "alpine")                                                                                                           
            CHECKSUM=$(apk manifest nginx 2>/dev/null| grep $DEFAULT_CONF_FILE | cut -d' ' -f 1 | cut -d ':' -f 2)          
            echo "$CHECKSUM  /$DEFAULT_CONF_FILE" | sha1sum -c - >/dev/null 2>&1 || {                                       
                entrypoint_log "$ME: info: /$DEFAULT_CONF_FILE differs from the packaged version"                           
                exit 0                                                                                                      
            }                                                                                                               
            ;;                                                                                                              
        *)                                                                                                                  
            entrypoint_log "$ME: info: Unsupported distribution"                                                            
            exit 0                                                                                                          
            ;;                                                                                                              
    esac      

</details>

**Comment by dzhdan** [comment]
Same issue

**Comment by andkirby** [comment]
And just for the record
<details>
  <summary>`nginx -T` output:</summary>
    ```
    nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    nginx: configuration file /etc/nginx/nginx.conf test is successful
    # configuration file /etc/nginx/nginx.conf:
    # let's assume dual-core machine
    worker_processes 2;
    
    error_log /var/log/nginx/error.log debug;
    pid /var/run/nginx.pid;
    
    load_module /etc/nginx/modules/ngx_http_image_filter_module.so;
    
    events {
      # this should be equal to value of "ulimit -n"
      # reference: https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
      worker_connections 1048576;
    }
    
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
    
      log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    
      access_log /var/log/nginx/access.log main;
    
      sendfile on;
      #tcp_nopush on;
    
      keepalive_timeout 65;
    
      #gzip on;
    
      client_max_body_size 20M;
    
      include /etc/nginx/conf.d/*.conf;
    }
    
    # configuration file /etc/nginx/mime.types:
    
    types {
        text/html                                        html htm shtml;
        text/css                                         css;
        text/xml                                         xml;
        image/gif                                        gif;
        image/jpeg                                       jpeg jpg;
        application/javascript                           js;
        application/atom+xml                             atom;
        application/rss+xml                              rss;
    
        text/mathml                                      mml;
        text/plain                                       txt;
        text/vnd.sun.j2me.app-descriptor                 jad;
        text/vnd.wap.wml                                 wml;
        text/x-component                                 htc;
    
        image/avif                                       avif;
        image/png                                        png;
        image/svg+xml                                    svg svgz;
        image/tiff                                       tif tiff;
        image/vnd.wap.wbmp                               wbmp;
        image/webp                                       webp;
        image/x-icon                                     ico;
        image/x-jng                                      jng;
        image/x-ms-bmp                                   bmp;
    
        font/woff                                        woff;
        font/woff2                                       woff2;
    
        application/java-archive                         jar war ear;
        application/json                                 json;
        application/mac-binhex40                         hqx;
        application/msword                               doc;
        application/pdf                                  pdf;
        application/postscript                           ps eps ai;
        application/rtf                                  rtf;
        application/vnd.apple.mpegurl                    m3u8;
        application/vnd.google-earth.kml+xml             kml;
        application/vnd.google-earth.kmz                 kmz;
        application/vnd.ms-excel                         xls;
        application/vnd.ms-fontobject                    eot;
        application/vnd.ms-powerpoint                    ppt;
        application/vnd.oasis.opendocument.graphics      odg;
        application/vnd.oasis.opendocument.presentation  odp;
        application/vnd.oasis.opendocument.spreadsheet   ods;
        application/vnd.oasis.opendocument.text          odt;
        application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                         pptx;
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                                                         xlsx;
        application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                         docx;
        application/vnd.wap.wmlc                         wmlc;
        application/wasm                                 wasm;
        application/x-7z-compressed                      7z;
        application/x-cocoa                              cco;
        application/x-java-archive-diff                  jardiff;
        application/x-java-jnlp-file                     jnlp;
        application/x-makeself                           run;
        application/x-perl                               pl pm;
        application/x-pilot                              prc pdb;
        application/x-rar-compressed                     rar;
        application/x-redhat-package-manager             rpm;
        application/x-sea                                sea;
        application/x-shockwave-flash                    swf;
        application/x-stuffit                            sit;
        application/x-tcl                                tcl tk;
        application/x-x509-ca-cert                       der pem crt;
        application/x-xpinstall                          xpi;
        application/xhtml+xml                            xhtml;
        application/xspf+xml                             xspf;
        application/zip                                  zip;
    
        application/octet-stream                         bin exe dll;
        application/octet-stream                         deb;
        application/octet-stream                         dmg;
        application/octet-stream                         iso img;
        application/octet-stream                         msi msp msm;
    
        audio/midi                                       mid midi kar;
        audio/mpeg                                       mp3;
        audio/ogg                                        ogg;
        audio/x-m4a                                      m4a;
        audio/x-realaudio                                ra;
    
        video/3gpp                                       3gpp 3gp;
        video/mp2t                                       ts;
        video/mp4                                        mp4;
        video/mpeg                                       mpeg mpg;
        video/quicktime                                  mov;
        video/webm                                       webm;
        video/x-flv                                      flv;
        video/x-m4v                                      m4v;
        video/x-mng                                      mng;
        video/x-ms-asf                                   asx asf;
        video/x-ms-wmv                                   wmv;
        video/x-msvideo                                  avi;
    }
    
    # configuration file /etc/nginx/conf.d/default.conf:
    upstream fastcgi_backend {
      server unix:/sock/docker.sock;
    }
    
    server {
      listen 8000;
      return 301 https://$host$request_uri;
    }
    
    server {
      listen [::]:8443 ssl http2 ipv6only=on;
      listen 8443 ssl http2;
    
      ssl_certificate /etc/nginx/certs/nginx.crt;
      ssl_certificate_key /etc/nginx/certs/nginx.key;
    
      set $MAGE_ROOT /var/www/html;
    
      fastcgi_buffer_size 64k;
      fastcgi_buffers 8 128k;
    
      location /livereload.js {
        proxy_set_header Host $host;
        proxy_pass http://phpfpm:35729/livereload.js;
      }
    
      location /livereload {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://phpfpm:35729/livereload;
      }
    
      include /var/www/html/nginx[.]conf;
    }
    
    # configuration file /var/www/html/nginx.conf:
    ```
</details>

**Comment by markshust** [comment]
The `nginx.conf.sample` file is included in the default installation of Magento: https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample

If you delete this file, you are deviating from the expected, standard setup of Magento (especially since this file is copied over again with every upgraded version).

This file is mounted in the `compose.dev.yaml` file at https://github.com/markshust/docker-magento/blob/release/next/compose/compose.dev.yaml#L13

This mounts the file to `/var/www/html/nginx.conf` within the container.

That file is included in the standard Magento config for this setup at https://github.com/markshust/docker-magento/blob/release/next/images/nginx/1.24/conf/default.conf#L34

So, this setup relies on this `nginx.conf.sample` file to exist. So, I'd recommend download that file and add it back to your version control, which should fix your issue.

If you needed to change any parameters of this file, I'd recommend copying `nginx.conf.sample` to `nginx.conf`, and then updating the volume-mount reference in the `compose.dev.yaml` file. This will prevent your changes from being overridden after an upgrade.

**Comment by andkirby** [comment]
@markshust, thanks for your extended reply. I understand how nginx works, I just used to have _all_ nginx configuration within `/etc/nginx/conf.d` - that's where I was confused.

I see `nginx.conf.sample` usage in [docker-composer.dev.yaml]([compose.dev.yaml](https://github.com/markshust/docker-magento/blob/release/next/compose/compose.dev.yaml#L13)) file.
Usage of `nginx.conf.sample` file is mandatory to make Magento work, `compose.dev.yaml` is optional (according [to `--no-dev` option](https://github.com/markshust/docker-magento/blob/92c73343eb93afc80ba111e090fa490d95706fa1/compose/bin/docker-compose#L13C15-L13C23)). This is where things fall apart.

My question is, why it's not a part of main `docker-compose.yaml` file?
I just didn't use `bin/docker-compose` but used `docker compose`, this is why `dev` file was omitted.

**Comment by rubenromao** [comment]
Hi @andkirby it isn’t part of the compose.yml to let you choose what volumes you want to mount.
If you are using Linux most likely you'll mount the whole ./src/ but if you are on macOS you will need to use it for sure.

**Comment by andkirby** [comment]
Hi @rubenromao
I never use mounting for Magento app files. It is bad for performance. SSH is the best way to work with containers from my experience, and it works pretty well.
Even if I suppose to make this mounting, nothing says me I should map nginx.conf.sample into nginx.conf inside a container.

And in general, Magento won't work after the native `docker compose up -d` command.
The command `bin/docker-compose --no-dev` will break it as well.
_In general, it should not be up to "dev/nodev" mode, it should not be up to mounted external files or not mounted._
The rest is tuning for developer needs.

And probably, it worth to consider official documentation about nginx configuration.
https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/prerequisites/web-server/nginx
I don't like using *.sample files, it's a sample, it's suppose to be not used.
But the bright side, it will work in this case.

So, wasted hours to fix the issue. Here, I'm trying to help you to fix this issue and save other people time. 

@markshust Thanks for sharing this solution anyway. Not so many good implementations we have on GitHub.

**Comment by rubenromao** [comment]
Hi @andkirby, I understand,
But this is "docker-magento" by @markshust , and it was mainly designed for macOS devs.
It works perfectly fine for me and hundreds of other Magento developers so if it doesn't meet your needs you have other solutions. You can also create your own solution if you want to do something different.
Cheers

**Comment by markshust** [comment]
I agree with @rubenromao that this is all working as designed/architected. Feel free to fork & pull if you want to customize it for another setup! This is a heavily forked project, so I won't be offended 😄 I'm opinionated with the decisions I make and build things from my own personal experiences, knowledge, and daily working habits, and you may have a different take than me, but I have no desire to change out how Nginx works here.

I'd also recommend mounting the entire /src directory, on Linux, as it should have very minor, if any performance issues. This is documented at https://github.com/markshust/docker-magento?tab=readme-ov-file#linux, and I mount the entire directory at https://github.com/markshust/docker-magento/blob/release/next/compose/compose.dev-linux.yaml#L5. Performance issues are typically only present on non-Linux systems like macOS, as they don't share the underlying Linux architecture, which is really why Docker Desktop was created in the first place (and also why you don't need that on `Nix).

**Comment by andkirby** [comment]
@markshust 
I use macOS if it matters.
And It still changes nothing, because the same issue, faced by two people in the same day, is not related to an OS type.
If you have no desire, so am I! 😄 
I'm glad it works for you, guys. Ok, let's finish this :)
