### ISSUE TITLE
How to add SSL Certificate to Nginx?

### ISSUE THREAD

**Issue by datmieu204** [markshust/docker-magento#1268]
After I have the ssl certificate, I don't know how to add it to Nginx. 

![image](https://github.com/user-attachments/assets/af62cb61-4c95-4083-9b63-b48dbf3cdd54)

In addition, I ran 2 commands "bin/setup-ssl" and "bin/setup-ssl-ca" , I got the following:

![image](https://github.com/user-attachments/assets/b7fe47df-acc4-4f01-ad5a-5fa6bf412cdd)

Can you guide me how to do it?

**Comment by markshust** [comment]
It looks like you are referencing SSL certs that you created. This is a local dev environment, so you don't want to do this. Simply running `bin/setup-ssl` and `bin/setup-ssl-ca` should be enough to get everything working and applied to Nginx automatically. If you have an issue with this, please let me know.

**Comment by datmieu204** [comment]
@markshust  If I do it on the host, do I have to do anything else? Thanks, sir.

**Comment by markshust** [comment]
Running those commands in the project should take care of everything you need, as they will be ran within the container, and the certs should be copied back to the host.
