### ISSUE TITLE
MariaDB 10.4

### ISSUE THREAD

**Issue by GNUXDAR** [markshust/docker-magento#1272]
**Description**
Good morning, I hope you can help me.
I am trying to install a project with version 2.4.5, but since I was told that it is available from version 2.4.6, I am trying with that version. When I change the MariaDB version to a compatible one (image: mariadb:10.4 in compose.yaml), I get the following error.

compose.yaml
change code in:
  phpfpm:
    image: markoshust/magento-php:8.3-fpm-3     ->     markoshust/magento-php:8.1-fpm  ✅

  db:
    image: mariadb:10.6  ->  image: mariadb:10.4  ❌

<img src="https://github.com/user-attachments/assets/df5464b6-7593-4c85-be45-38bfe1c72e20" width="50%">

**Steps To Reproduce**
1. mkdir -p ~/Sites/magentoproject
2. cd $_
3. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
4. bin/download community 2.4.6
5. bin/setup magento.test

**Expected Result**

**Actual Result**
![image](https://github.com/user-attachments/assets/df5464b6-7593-4c85-be45-38bfe1c72e20)

**Comment by markshust** [comment]
Need a more detailed error log, aka as to why the db container is failing to start. Be sure you don't have anything else listening on port 3306 on your host, as simply changing the version number should get things to work.
