### ISSUE TITLE
How to Package Docker Containers into a Single Configuration

### ISSUE THREAD

**Issue by datmieu204** [markshust/docker-magento#1273]
I use Markshost's docker environment. And I want to repackage it into Docker to include my code, what should I do? Thanks

**Comment by rubenromao** [comment]
Hi @datmieu204 , let me see if I understand your question.
You have Markshust's docker-magento, and you want to "repackage" (not sure what you mean) it into what exactly?
Can you elaborate what you want to achieve exactly?

**Comment by datmieu204** [comment]
> Thank you sir,
> what I mean is that I want to package one more time and it includes docker-magento by author Markshost.

**Comment by datmieu204** [comment]
Thank you sir @rubenromao,
what I mean is that I want to package one more time and it includes docker-magento by author Markshost.

**Comment by markshust** [comment]
Unfortunately, this question is too vague to answer and needs some context and clarity. Secondly, this was opened as an issue, when you really want to open this as a Discussion. I'd recommend creating a discussion and including MUCH more context of what you are trying to accomplish.
