### ISSUE TITLE
Permission issues running the nginx container

### ISSUE THREAD

**Issue by shochdoerfer** [markshust/docker-magento#131]
I am using the `markoshust/magento-nginx:1.13-7` image for my setup. When trying to run the container, nginx would not start. I could reproduce this by running this command: `docker run -it markoshust/magento-nginx:1.13-7 bash` and then start nginx manually with `nginx -g "daemon off;"`. This leads to the following error:
```
2019/02/21 19:13:10 [emerg] 1#1: SSL_CTX_use_PrivateKey_file("/etc/nginx/certs/nginx.key") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/nginx/certs/nginx.key','r') error:20074002:BIO routines:file_ctrl:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/etc/nginx/certs/nginx.key") failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/nginx/certs/nginx.key','r') error:20074002:BIO routines:file_ctrl:system lib error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib)
```

Which makes sense as this is the ls output of `/etc/nginx/certs/`:
```
$ ls -al /etc/nginx/certs/
drwxr-xr-x 1 root app  4096 Dec 24 15:02 .
drwxr-xr-x 1 root root 4096 Dec 24 15:03 ..
-rw-r--r-- 1 root app  1233 Dec 24 15:02 nginx.crt
-rw------- 1 root app  1704 Dec 24 15:02 nginx.key
```

If I run the container as root `docker run --user="root" -it markoshust/magento-nginx:1.13-7 bash`, run the chmod command again and then execute nginx as mentioned above, everything works fine.

If I provide a custom `default.conf` file without ssl configuration, nginx will fail for a similar reason by claiming that different directories in `/var/cache/nginx/` are not writeable.

Do you have any idea how to fix this issue?

**Comment by markshust** [comment]
sorry, i can't replicate 🤷‍♂️ 

![screen shot 2019-02-26 at 11 26 22 am](https://user-images.githubusercontent.com/437029/53428819-75d2e800-39b9-11e9-9f3f-5373f9dfd493.png)

maybe there is something wonky going on with your setup. when i inspect permissions i'm seeing the correct `app:app` on `/etc/nginx/certs`:

![screen shot 2019-02-26 at 11 27 34 am](https://user-images.githubusercontent.com/437029/53428889-93a04d00-39b9-11e9-90b1-181bea3d5240.png)

**Comment by shochdoerfer** [comment]
Looks like this a problem due to my docker userns-remap settings. The user you create with the fixed id 1000 collides with my local configuration thus the wrong permissions got applied when the container was started.

**Comment by roma-glushko** [comment]
Getting the same issue on macOS:
![2020-02-09_17-41-42](https://user-images.githubusercontent.com/9402690/74105102-90b75180-4b63-11ea-8f05-d72ca28aa909.png)

![2020-02-09_17-39-44](https://user-images.githubusercontent.com/9402690/74105103-990f8c80-4b63-11ea-8193-38f6f7d16181.png)

![2020-02-09_17-40-50](https://user-images.githubusercontent.com/9402690/74105107-9dd44080-4b63-11ea-96b7-379344b8346e.png)

**Comment by markshust** [comment]
@roma-glushko what is the id tied to the app user in your container?

```
bin/cli id -u app
```

should output 1000. everyone else, same question, and why would this be different from other environments such as my own?

**Comment by roma-glushko** [comment]
@markshust it's 1000 in my case 🤔

![2020-02-11_08-55-45](https://user-images.githubusercontent.com/9402690/74216250-750b9280-4cac-11ea-8aca-4759a21674de.png)

**Comment by markshust** [comment]
@roma-glushko i think you should be able to fix this just by executing:

```bin/root chown -R app:app /etc/nginx```

if the user id is 1000, it should correctly map to app user and all be ok. it's possible you were using a previous version of docker-magento and the permissions weren't properly reset. i'll try to add in a patch for this scenario.

if the user is not 1000, i need to know why and how it can possibly be fixed (if it even can be).

**Comment by roma-glushko** [comment]
@markshust works for me, thank you 🙌 

Don't know how could I trigger this inconsistency, though 🤔

**Comment by markshust** [comment]
Going to close this out, as the issue was differing config from what Docker is out of the box
