### ISSUE TITLE
Can't curl to localhost

### ISSUE THREAD

**Issue by pmsteil** [markshust/docker-magento#140]
Hello, I am having a problem where we are trying to use curl to call the internal Magento rest api and i get "Connection Refused" no matter what I try.

Is there some trick to making this work?  I have tried using my hostname mag231c.test, 127.0.0.1, tried ports 80, 443 and even the docker ports 8000 and 8443.  

I am also using these curl options:

```
    $this->_curl->setOption(CURLOPT_HTTPHEADER, array('Host: mag231c.test'));
    $this->_curl->setOption(CURLOPT_SSL_VERIFYPEER, 0);
    $this->_curl->setOption(CURLOPT_SSL_VERIFYHOST, 0);
```

I am at a loss as to why this is happening.  Its like the docker can't address itself.

thanks for any clues!
patrick

**Comment by markshust** [comment]
where are you making this call from -- within the docker container itself?

**Comment by markshust** [comment]
try hosts `host.docker.internal` or `gateway.docker.internal` -- if that doesnt work you can also try `app`.

**Comment by pmsteil** [comment]
Oh hallelujah!

host.docker.internal worked!

So why can't we use the mag231c.test url that the site is running on?

Thanks for the quick reply!!!!

**Comment by markshust** [comment]
sure thing -- something how docker DNS resolution works. no clue, way over my head! ha

**Comment by pmsteil** [comment]
ok thanks!

**Comment by pmsteil** [comment]
@markshust I wonder if this suggestion would fix it:

https://stackoverflow.com/a/48806927/11223436

**Comment by emetik** [comment]
Hello All,
Same issue first but now I encounter : 
URL : https://host.docker.internal/rest/async/bulk/V1/products or using gateway.docker.internal
`In CurlFactory.php line 205:                                                                                                                                          
  cURL error 60: SSL certificate problem: unable to get local issuer certificate 
`
I've tried to add certificates with the `bin/setup-ssl host.docker.internal gateway.docker.internal ` and now it works !

But the error is related to the timeout: Failed to connect to gateway.docker.internal port 443: Connection timed out

Any help would be appreciated.

Thanks
