### ISSUE TITLE
Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by kirjeldus** [markshust/docker-magento#143]
One of my Magento 2.2.x template files uses file_get_contents to retrieve a file from theme folder like this: 
`file_get_contents($block->getViewFileUrl('folder/filename.extension')`

`Exception #0 (Exception): Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/app/design/frontend/Vendor/Theme/.../.. on line ...`

relevant images im using:
markoshust/magento-nginx:1.13-7
markoshust/magento-php:7.1-fpm

I've tried modifying the php image build by adding into the php.ini file: 
```
extension = php_openssl.dll
allow_url_fopen = on  
```
(see https://stackoverflow.com/questions/8423404/php-file-get-contents-does-not-work-on-localhost)

I also tried explicitly adding openssl to the apt-get command although phpinfo shows it's seems to be installed by default anyway.
```
RUN apt-get update && apt-get install -y \
  ...
  libssl-dev \
  ...

```

No luck so far with whatever I've tried. Unfortunately I'm new to both docker and nginx. Is there an issue between communication of the app (nginx) and the phpfm services or  something with the nginx configs?

Anyone got any ideas?
Cheers

**Comment by markshust** [comment]
`file_get_contents` is bad magento practice https://magento.stackexchange.com/questions/216579/magento-2-meqp2-warning-the-use-of-function-file-get-contents-is-discouraged?rq=1

definitely not planning on installing/modifying anything here because of bad practice in code. the code needs to be updated.

**Comment by kirjeldus** [comment]
framework/Filesystem/Driver/File.php uses file_get_contents in any case.
```
 /**
     * Retrieve file contents from given path
     *
     * @param string $path
     * @param string|null $flag
     * @param resource|null $context
     * @return string
     * @throws FileSystemException
     */
    public function fileGetContents($path, $flag = null, $context = null)
    {
        clearstatcache();
        $result = @file_get_contents($this->getScheme() . $path, $flag, $context);
        if (false === $result) {
            throw new FileSystemException(
                new \Magento\Framework\Phrase(
                    'Cannot read contents from file "%1" %2',
                    [$path, $this->getWarningMessage()]
                )
            );
        }
        return $result;
    }
```
```

1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): Cannot read contents from file "https://mage.local/static/version1556181292/frontend/Vendor/theme/folder/file.json" Warning!file_get_contents(https://mage.local/static/version1556181292/frontend/Vendor/theme/folder/file.json): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
```
