### ISSUE TITLE
502 error when using markoshust/magento-php:7.1-fpm-0

### ISSUE THREAD

**Issue by adamraya** [markshust/docker-magento#144]
This is purely for your information, choosing the image markoshust/magento-php:7.1-fpm-0 in docker-compose.yml gives a 502 Bad Gateway error. 

Since I don't require this specific version, it's easily solvable by simply choosing one of the many other fpm images like: markoshust/magento-php:7.1-fpm-9

**Comment by markshust** [comment]
this is non-issue -- just use `7.1-fpm-9`
