### ISSUE TITLE
Configure Redis page caching (FPC in Redis)

### ISSUE THREAD

**Issue by u-maxx** [markshust/docker-magento#145]
During my investigations and debugging of automated varnish configurations for FPC, I have found that your project does not have configurations to store FPC in Redis (https://devdocs.magento.com/guides/v2.3/config-guide/redis/redis-pg-cache.html#configure-redis-page-caching) 

I have implemented this improvement and added info to the README, please see the following PR

**Comment by markshust** [comment]
thanks @u-maxx! sorry it took so long to merge in -- crazy few weeks. looks good. merged.
