### ISSUE TITLE
404: New folder in src

### ISSUE THREAD

**Issue by Lyam** [markshust/docker-magento#147]
Hello, 

It's maybe a dumb question/issue but i tried to create a new folder /src/tools/index.php  i have a  404...
i already updated the file docker-compose.dev.yml with: 

services:
  app:
    volumes: &appvolumes
      - ./src/tools:/var/www/html/tools

and when i use bin/bash the folder and file are created.
But when i use the url https://magento.local/tools/index.php i have a 404...

any Ideas ?

**Comment by markshust** [comment]
try changing line to:

`- ./src/tools:/var/www/html/pub/tools`

the entry point in magento is `pub/index.php`, not the root `index.php`.

cheers,
mark
