### ISSUE TITLE
Database Credentials Valid?

### ISSUE THREAD

**Issue by jessicaFeigal** [markshust/docker-magento#148]
I am trying to install this on Ubuntu 16.04 as a local development environment.  I have an existing project that I'm trying to setup.  Everything was installing nicely until I got to this part:
bin/clinotty mysql -hdb -umagento -pmagento magento < ../databases/backup.sql
The error I get is: Access denied for user 'magento'@'172.21.0.5' (using password: YES)

So I tried to just access the database by doing this: 
bin/cli mysql -h db -umagento -pmagento magento
error: Access denied for user 'magento'@'172.21.0.5' (using password: YES)

I have checked the env/db.env file and I see login credientials for mysql, but I keep getting access denied.  What else should I be looking at?  What else should I try?  As of right now I cannot access mysql cli.  Any help would be appreciated.

**Comment by markshust** [comment]
so sorry for the delay, i think this came before imagine and i must have missed it during my travels.

is this still an issue for you? if so please reopen and i can take a look. not really sure what is going on here.
