### ISSUE TITLE
Updates to setup instructions

### ISSUE THREAD

**Issue by chfabbro** [markshust/docker-magento#151]
Hi!

Your repo is outstanding, and saved me a ton of time. Thank you!

I ran into some installation issues that I was able to fix, but I wanted to share with you in case others run into the same problems. I am running Xubuntu (Ubuntu) 16.04 on Windows 10 Pro, via VMWare Workstation.

- The link to Docker CE is broken: https://www.docker.com/community-edition#/download
  - Instead, I found this link: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce
- After installing the version above, you will need to run additional commands to add your user to the Docker user group. Otherwise, docker will need run as a `sudo` user, which is not part of your install script. I ran the commands here. Once I ran it, you need to log out/log in, or reboot (I am running in a VM).
  - https://docs.docker.com/install/linux/linux-postinstall/
- `docker-compose` is not installed using the above link, so I had to install that as well.
  - https://docs.docker.com/compose/install/

After correcting the 3 issues above, the installation ran as expected and the server started up. This setup was far quicker than the manual install (using Apache/PHP/MySql) on my Mac, and much easier.

Thanks again,
Christopher

**Comment by markshust** [comment]
@chfabbro just made a commit that contains these updates. many thanks!
