### ISSUE TITLE
compatibility with jwilder/nginx-proxy

### ISSUE THREAD

**Issue by Flyingmana** [markshust/docker-magento#152]
I tried out to get this project working in an environment using jwilder/nginx-proxy but had some issues of it redirecting always to the https url, which is not part of the setup

**Comment by markshust** [comment]
This may be due to the nginx config probably having that redirect someplace. I wouldn't say this is a bug but desired. You'll need to override the nginx file locally or remote mount a conf file that doesn't have that redirect in it.

**Comment by markshust** [comment]
See https://github.com/markshust/docker-magento/blob/master/images/nginx/1.13/conf/default.conf#L7
