### ISSUE TITLE
Xdebug not stopping at breakpoints

### ISSUE THREAD

**Issue by nfourteen** [markshust/docker-magento#154]
I've setup PhpStorm and xdebug as per the video course. I can connect and to xdebug and stop on a breakpoint set in `pub/index.php`, however no other breakpoints stop execution and to allow variable inspection. For example, a breakpoint in `\Magento\Framework\View\Page\Config\Structure.php::L184` or `\Magento\Cms\Controller\Index\Index.php::L74` is never stopped at. If I refresh the page and flip to PhpStorm, the debugger says **Connected** and little checkmarks appear on the breakpoints, but no variable data is ever shown. Any ideas what could cause this? I'm at a loss...

**Comment by markshust** [comment]
can you double check your path mappings?

also note that some breakpoints may not catch if certain caches are turned on.


________________________________

**Comment by nfourteen** [comment]
@markshust Thanks for the quick reply! Caching was the problem, which I didn't think to check because I just started using Docker and in the Vagrant box I used before (which is no longer working) cache was disabled by default. I also couldn't figure out why it would work for the `index.php` file, but no others. I'm back to debugging now. Thanks for all the work you put into this project!
