### ISSUE TITLE
How to change php.ini setting

### ISSUE THREAD

**Issue by pmsteil** [markshust/docker-magento#155]
Hello, 

Due to this problem:

https://community.magento.com/t5/Magento-2-x-Technical-Issues/Invalid-form-key-Magento-2/td-p/41751

I need to update my php.ini file and change the 

`max_input_vars`

setting.

What is best way to do this?  All the .ini files are readonly.

**Comment by markshust** [comment]
sure -- see this course lesson at https://m.academy/courses/487758/lectures/9064349

the lesson covers configuring an nginx.conf file, but the same ideology applies to php.ini file configs. let me know if that works for you and if not, please reopen this ticket.

**Comment by pmsteil** [comment]
Well, I reviewed the lesson twice, but I don't know enough about configuring PHP to make this info useful.

Also I am using the one liner to install, so not sure how to edit the yml file.

Any other hints?  Sorry...

**Comment by markshust** [comment]
you can copy https://github.com/markshust/docker-magento/blob/master/images/php/7.2/conf/php.ini to something like your project src folder (next to nginx.conf/nginx.conf.sample). add that line to it.

then open up `docker-compose.dev.yml` and add this line to volumes:

````
      - ./src/php.ini:/usr/local/etc/php/php.ini:delegated
```

then apply the update with:

`bin/restart`

this mounts your php.ini file over the base php.ini file, which should apply this config change to your environment. let me know if this works! (it should 😄 )

**Comment by pmsteil** [comment]
THANK YOU! 

That worked!!!

**Comment by markshust** [comment]
🎉
