### ISSUE TITLE
Document multi-site integration

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#157]

**Comment by magento2dev** [comment]
Hello @markshust,

Thanks a lot for this great repo !
I'm trying to install a wordpress beside this magento in a subdirectory wp. I can access the Magento correctly (mydomain.com) and I would like to access the Wordpress through (mydomain.com/wp/), I updated the nginx conf but it's not working.

Heres's my conf :
location ^~ /wp/ {
    root $MAGE_ROOT;
    fastcgi_pass   fastcgi_backend;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;

    index   index.html index.htm index.php;
    try_files $uri $uri/ /wp/index.php?$args;
}

**Comment by markshust** [comment]
@magento2dev you're going to want to run Wordpress in an entirely separate docker container, then update the nginx config to detect incoming requests for Wordpress and proxy them over to the appropriate docker container.

**Comment by sunilit42** [comment]
Hello,

following thing did for to work with multiple websites

Into nginx.conf.sample file added below line
```
fastcgi_param MAGE_RUN_TYPE $MAGE_RUN_TYPE;
fastcgi_param MAGE_RUN_CODE $MAGE_RUN_CODE;

```
add below two lines after 
`fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;`

so it should be
`# PHP entry point for main application
location ~ (index|get|static|report|404|503|health_check)\.php$ {
    try_files $uri =404;
    fastcgi_pass   fastcgi_backend;
    fastcgi_buffers 1024 4k;

    fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
    fastcgi_param  PHP_VALUE "memory_limit=756M \n max_execution_time=18000";
    fastcgi_read_timeout 600s;
    fastcgi_connect_timeout 600s;

    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    fastcgi_param MAGE_RUN_TYPE $MAGE_RUN_TYPE;
    fastcgi_param MAGE_RUN_CODE $MAGE_RUN_CODE;
    include        fastcgi_params;
}
`
now create another file for add code and website 
let's e.g with name 
multi.conf and it will contain below code
`upstream fastcgi_backend {
  server unix:/sock/docker.sock;
}

server {
  listen 8000;
  return 301 https://$host$request_uri;
}

map $http_host $MAGE_RUN_CODE {
   doamin.com domain // here you need to mention your domain name with your code
}

server {
  listen 8443 ssl;

  ssl_certificate /etc/nginx/certs/nginx.crt;
  ssl_certificate_key /etc/nginx/certs/nginx.key;

  set $MAGE_ROOT /var/www/html;
  set $MAGE_MODE developer;
  set $MAGE_RUN_TYPE website;

  include /var/www/html/nginx[.]conf;
}
`
now you need to copy that file into docker when you start so add below thing into 
docker-composer.dev.yml file

`- ./multi.conf:/etc/nginx/conf.d/default.conf:delegated`

hope it will help

**Comment by magento2dev** [comment]
Hello @sunilit42,

Thanks for your answer but I'm trying to run a Wordpress and a Magento, if I understand right your code is for two Magento ?

**Comment by sunilit42** [comment]
yes you are right 

for wordpress you code is right but have you checked your code added into docker

**Comment by magento2dev** [comment]
yes the code I sent above is correctly set in my nginx configuration file when I inspect the container.

**Comment by sunilit42** [comment]
have you added on top of Magento rule start?

**Comment by magento2dev** [comment]
Not sure to understand the question, I added my code at the beginning of the the default Magento nginx configuration file

**Comment by sunilit42** [comment]
Check below link it will help you
https://fishpig.co.uk/magento/wordpress-integration/nginx/

**Comment by magento2dev** [comment]
Thanks for your help !
I tried using this code but I'm getting the error :

`2020/02/17 10:03:22 [emerg] 1#1: open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:26
nginx: [emerg] open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:26`

**Comment by magento2dev** [comment]
With this configuration my Magento is working and my Wordpress is accessible (but only html files) the php just render blank pages with 200 status :

`upstream fastcgi_backend {
  server unix:/sock/docker.sock;
}

server {
  listen 8000;
  return 301 https://$host$request_uri;
}

server {
  listen 8443 ssl;

  ssl_certificate /etc/nginx/certs/nginx.crt;
  ssl_certificate_key /etc/nginx/certs/nginx.key;

  # Magento 2 base URL
  server_name mydomain;

  # Magento 2 root directory
  set $MAGE_ROOT /var/www/html;

  set $MAGE_DEBUG_SHOW_ARGS 1;

  include /var/www/html/nginx.conf.sample;

  # WordPress is installed in pub/wp
  location /wp/ {
    index index.html index.php;
    try_files $uri $uri/ /wp/index.php?q=$uri&args;

    location ~ \.php$ {
      fastcgi_pass   unix:/sock/docker.sock;
      fastcgi_index  /wp/index.php;
    }
  }
}`

**Comment by sunilit42** [comment]
try to do echo exit into wp/index.php and if works then enable error display and check it

**Comment by magento2dev** [comment]
sadly it's not working the page stills blank...

**Comment by magento2dev** [comment]
I achieved to display the echo in wp/index.php by setting my wordpress location php part like this : 
`location ~ \.php$ {`
      `fastcgi_pass   unix:/sock/docker.sock;`
      `fastcgi_index  /wp/index.php;`
     ` fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;`
     ` include        fastcgi_params;`
    `}`

but now I'm getting this error : 
`Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/pub/wp/wp-includes/wp-db.php`

**Comment by sunilit42** [comment]
Hello,

seems like extension missing from php
extension=php_mysql.dll

enable this extension

**Comment by magento2dev** [comment]
Yes I saw it could solve the error but I did not find how to custom my php.ini to add this extension

**Comment by sunilit42** [comment]
https://github.com/markshust/docker-magento/issues/155
check this one

**Comment by magento2dev** [comment]
Oh thanks !
Sadly I'm getting the same both issues even with the new php.ini file enabled : 

`Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/pub/wp/wp-includes/wp-db.php`

`Fatal error: Uncaught Error: Call to undefined function wp_kses_normalize_entities() in /var/www/html/pub/wp/wp-includes/formatting.php`

**Comment by magento2dev** [comment]
I'm using this image for php : image: markoshust/magento-php:7.1-fpm-2

**Comment by sunilit42** [comment]
Hello @magento2dev 
you can print phpinfo and you can check it

**Comment by magento2dev** [comment]
what configuration should I find ?

**Comment by sunilit42** [comment]
php_mysql extension enable or not

**Comment by magento2dev** [comment]
I found : 
**Configure Command**
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,

**mysqlnd**
Version | mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387

**pdo_mysql**
Client API version | mysqlnd 5.0.12-dev - 20150407

**Comment by sunilit42** [comment]
Please check your wp-config.php file for the following line:

define('WP_USE_EXT_MYSQL', true);

**Comment by magento2dev** [comment]
Still getting the same php errors even with this line.

(Thanks for your help !)

**Comment by magento2dev** [comment]
I tried [this solution ](https://stackoverflow.com/questions/45687848/docker-wordpress-get-this-error-fatal-error-uncaught-error-call-to-undefi) but when I'm running the Dockerfile I'm getting : 

`mkdir: cannot create directory '/usr/src/php': Permission denied`

**Comment by magento2dev** [comment]
Hello @markshust you do not have any idea on what could be the issue here ?

Thanks for your help !

**Comment by markshust** [comment]
Is something in your code referring to `/usr/src/php`? I'm not sure where that directory is coming from.

FYI this ticket is for multi-site integration, not a magento+wordpress install. That gets more difficult and not something I'd like to merge into this repo by any means.

Feel free to continue your discussion here, as this ticket doesn't really have any other comments. In the future though you'll want to open a new ticket to cover another topic.

**Comment by magento2dev** [comment]
Ok thanks for your reply @markshust !

I'm getting this message when I'm trying to add this command in Dockerfile : 
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

**Comment by markshust** [comment]
FYI you're using a very old image -- may want to check out the current 7.3 branch, here is where I add it. The 7.1 branch is deprecated as 7.1 is EOL, so not supporting that version anymore.

https://github.com/markshust/docker-magento/blob/master/images/php/7.3/Dockerfile#L35

**Comment by magento2dev** [comment]
Thanks for your help @markshust and @sunilit42  I achieved to do what I wanted by using this phpfpm image : markoshust/magento-php:7.2-fpm

**Comment by markshust** [comment]
I created a screencast on how to setup multi-sites. The direct link for this lesson is at https://courses.m.academy/courses/setup-magento-2-development-environment-docker/lectures/14780970 and I also added links to all of the course lessons at https://github.com/markshust/docker-magento/#course-curriculm

**Comment by tangar76** [comment]
It would be great if anyone can share fork of this docker repo with Wordpress instance installed near Magento instance.
Is there something like this on github?
