### ISSUE TITLE
Issue with Magento 2.3.2

### ISSUE THREAD

**Issue by rafal-kos** [markshust/docker-magento#159]
After update to 2.3.2 magento is not working. Related to this issue https://github.com/magento/magento2/issues/23405

I am running php-fpm on this image : markoshust/magento-php:7.2-fpm

**Comment by markshust** [comment]
Thank you, i can confirm and replicate the issue. working on fix now.

**Comment by pmsteil** [comment]
Thanks to both of you!  For the record, this was the same issue I opened here yesterday:
https://github.com/markshust/docker-magento/issues/158

I authored that issue in Magento also :)

patrick

**Comment by markshust** [comment]
@pmsteil thanks -- if you re-commented on #158 i would have reopened! that's ok, we'll get it all fixed regardless :)

**Comment by markshust** [comment]
update coming shortly -- got quite busy yesterday. i'm testing an install now then will push out the new code to compile the new docker images.

**Comment by markshust** [comment]
New PHP docker images: `7.1-fpm-10`, `7.2-fpm-1` to fix this

See here for when builds complete:
https://cloud.docker.com/repository/registry-1.docker.io/markoshust/magento-php/timeline

**Comment by markshust** [comment]
just made another commit to fix PHP 7.1 not working with sodium. if you look at that git diff, some weirdness needed to make it work. all fixed now and 7.1 will work after the current docker builds complete.

**Comment by pmsteil** [comment]
Thanks for the progress on this @markshust.  What do we do to update our existing install?  Or do we have to install fresh?

Thanks!

**Comment by markshust** [comment]
@pmsteil all you need to do is open your docker-compose.yml file and update the PHP version tags to the new one -- whichever one you want to use. then just `bin/restart`.
