### ISSUE TITLE
php-sodium module missing

### ISSUE THREAD

**Issue by ilamp** [markshust/docker-magento#161]
I'm getting following error when running code for Magento 2.3.2

Warning: Use of undefined constant SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13 - assumed 'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/magento/framework/Encryption/Encryptor.php on line 153
An error has happened during application run. See exception log for details.

It's because the docker image is missing the php-sodium extension.

**Comment by markshust** [comment]
this was fixed in a subsequent docker image. please see https://github.com/markshust/docker-magento/issues/159
