### ISSUE TITLE
In admin URI "The page isn’t redirecting properl"

### ISSUE THREAD

**Issue by livioweb** [markshust/docker-magento#163]
when i access the admin page, this return me this message
[The page isn’t redirecting properly]
I do not know how to solve this

![image](https://user-images.githubusercontent.com/209310/61083990-6ce03180-a403-11e9-902a-30c2554db3eb.png)

**Comment by DavisChang** [comment]
https://magento.stackexchange.com/questions/148312/magento-2-how-to-retrieve-admin-uri

**Comment by markshust** [comment]
It appears your domain ending in `com.br` is most likely the culrpit. This isn't a good TLD to use for local domains (or it's possible redirecting back to your live site). Try changing local dev domain to end in `.dev`.
