### ISSUE TITLE
unable to do a docker up after initial installation 

### ISSUE THREAD

**Issue by TheSearcher** [markshust/docker-magento#164]
Hi everyone. i managed to install the installation perfectly on MY MAC PRO.

However once i do a docker-compose down and then try to do a docker-compose up i.e

docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d

it no longer find it.

It return an error message of :

This site can’t be reached localhost refused to connect.

**Comment by markshust** [comment]
It sounds like it's possible you have another web server running in your local machine (either on port 80, port 443, or both). Try stopping the other services on port 80/443 and try to start up the containers again. You'll also want to instead use the `bin/start` and `bin/stop` helper scripts as it helps facilitate starting and stopping the containers and eliminates possible typos/errors. If you continue having issues please try reinstalling and/or posting logs of the error messages you are receiving on container start.
