### ISSUE TITLE
question: weird behaviour with composer on automatic install 

### ISSUE THREAD

**Issue by antwake** [markshust/docker-magento#166]
When the prompt appears to ask for Access Keys, there's a question to "Add authentication information to host composer config"

If I type "y", I have a credentials error for repo.magento.com and the Magento installation doesnt work.

If I type "n", the installation works.

I'm on macOs Sierra and have Composer 1.7.2 installed.

On my other Macbook (Mojave) where Composer isn't install, the installation worked flawlessly.

**Comment by markshust** [comment]
Is it possible the creds at your local machine file `~/.composer/auth.json` are being used and are incorrect? I think I'll need some more info to try to diagnose this, as the local:remote host bind mount seems to work for me for composer auth creds.

**Comment by antwake** [comment]
I don't have access to my problematic computer now but will look at my  ~/.composer/auth.json 

Thank you!
