### ISSUE TITLE
Mailhog service error: port already allocated

### ISSUE THREAD

**Issue by nfourteen** [markshust/docker-magento#168]
I've installed one instance and would like to install another with sample data deployed. However, upon installing using the `onelinesetup` script in a different directory (after installing another instance using the "Manual Setup" process), the Mailhog service wont' start due to the port `8025` already being allocated. Here's the actual error message:

```
ERROR: for mailhog  Cannot start service mailhog: driver failed programming external connectivity on endpoint [project-dir]_mailhog_1 (40f71a3e743ba264e1073bd25e7b05350bda610d643fab833e265a7ba9dc07f2): Bind for 0.0.0.0:8025 failed: port is already allocated
```

I've been Googling, but can seem to figure out why Docker won't release that port when `bin/stop` has been executed on the first instance. Any ideas?

**Comment by markshust** [comment]
Can you ensure your `bin/stop` file looks like this? I made an update to it a little while ago as it wasn't completely stopping the mailhog service.

https://github.com/markshust/docker-magento/blob/master/compose/magento-2/bin/stop

**Comment by nfourteen** [comment]
@markshust I had the old version. Seems to be working now after a reboot. Thanks!
