### ISSUE TITLE
Magento Cloud ECE Tools requires ext-sockets

### ISSUE THREAD

**Issue by joeshelton-wagento** [markshust/docker-magento#169]
> magento/ece-tools 2002.0.20 requires ext-sockets *

https://github.com/magento/ece-tools/pull/542/files

**Comment by markshust** [comment]
Thanks for the report, I'll look into adding this in.

**Comment by mark-gene** [comment]
I have created a PR with this in. Very simple change.

**Comment by joeshelton-wagento** [comment]
Ha! I tried and failed to add it myself. Maybe I'll try again an learn something. :)

Thanks!

**Comment by markshust** [comment]
@joeshelton-wagento thanks! would you mind also adding this to the 7.1 image?

**Comment by markshust** [comment]
This was added a little while ago in https://github.com/markshust/docker-magento/issues/186

Closing this one out
