### ISSUE TITLE
Process for Integrating Origin Updates Into Existing Project

### ISSUE THREAD

**Issue by carlos-reynosa** [markshust/docker-magento#174]
I would like to keep a project created with this setup updated with your latest changes. Do you have a recommended process for integrating your updates to master?

**Comment by markshust** [comment]
Right now I'd recommend just copying over the docker-compose.yml files and then issuing a `bin/restart`. I think we should have a better way to do this (automatically?)... I'll leave this ticket open for discussion.

**Comment by markshust** [comment]
i created the new `bin/update` command. see https://github.com/markshust/docker-magento#updates for details. thanks for the recommendation 😄
