### ISSUE TITLE
Failed to connect to magento-local.com port 80: Connection refused

### ISSUE THREAD

**Issue by mchuatak** [markshust/docker-magento#176]
I have setup 2 application inside PHP-FPM container 
- /var/www/html/App1
- /var/www/html/App2

Configured 2 instances under App Container(Nginx)
- /etc/nginx/conf.d/app1.conf
- /etc/nginx/conf.d/app2.conf

The issue was, inside the app1.com ther are some process that needs to curl call the app2.com.
When I am trying that right now, I am not sure why I am getting the error below.
"response_curl_error":"Failed to connect to magento-local.com port 80: Connection refused”.

Would really appreciate your help on this.
Let me know if you have any question/s.

**Comment by markshust** [comment]
The docker setup only supports one app per project -- you'll need to create an entirely separate docker setup for the second project.
