### ISSUE TITLE
/etc/nginx/certs not available on your images

### ISSUE THREAD

**Issue by freeyland** [markshust/docker-magento#180]
I see that in /etc/nginx/ your certs folder is not available in the images downloaded from Dockerhub.

However this is available in your Docker file:
```
RUN mkdir /etc/nginx/certs \
  && echo -e "\n\n\n\n\n\n\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/nginx.key -out /etc/nginx/certs/nginx.crt
```

It looks like there is something wrong when you builded your images

**Comment by markshust** [comment]
@freeyland is something not working for you?

**Comment by freeyland** [comment]
Yes. The rest API is not working because of missing certificaten.

**Comment by freeyland** [comment]
I've just build the images myself and now the certificates are availble. Looks like something went wrong when you build your images

**Comment by freeyland** [comment]
Hi Mark,

You are correct but the containers you are hosting on Docker hub do not have the certs.

Rgds,
Frederick

**Comment by markshust** [comment]
the above test used the images on Docker Hub. the certs are there, it's in the Dockerfile https://github.com/markshust/docker-magento/blob/master/images/nginx/1.13/Dockerfile#L10

**Comment by jaswinder97** [comment]
@freeyland  I am facing an issue related to certs https://github.com/markshust/docker-magento/issues/203

were you able to resolve your issue?
