### ISSUE TITLE
Vendor autoload is not found. Please run 'composer install' under application root directory.

### ISSUE THREAD

**Issue by HamidMaqsood56** [markshust/docker-magento#184]
im facing this issue during composer installion on magento2 . please help me how to solve this problem
![1](https://user-images.githubusercontent.com/56429959/66634632-e536d880-ec26-11e9-9ee4-5cbe623060a7.jpg)

**Comment by markshust** [comment]
need a lot more details about the issue. what command you are running, when this is happening, etc. i'll reopen when more details are provided, but i could not replicate this using the automated install setup documented in the readme.
