### ISSUE TITLE
Blank page after install

### ISSUE THREAD

**Issue by mlabate-digitouch** [markshust/docker-magento#185]
**Description**
Hi, after a fresh installation (finished without errors), Magento instance is not accessible at the url printed at the end of the process. System redir to setup page and an almost blank page and several errors on browser console are shown (see attachment).

![image](https://user-images.githubusercontent.com/56116209/66922483-72af6980-f027-11e9-9fcd-4e1c21b0bc15.png)

**Comment by surtin** [comment]
Having the same issue myself. Digging through the docker container logs, maybe its a php-fpm config issue since `FastCGI sent in stderr: "Access to the script '/var/www/html/setup/index.php/session/prolong' has been denied (see security.limit_extensions)" while reading response header from upstream,` is the relevant bit from preventing the setup script to run properly.

**Comment by gendosua** [comment]
Seems like it's related to `docker cp` command, at least for me on Mac OS 10.15.
For some reason, it does not copy `app` and `vendor` directories from container to host (even when ran manually). 

Although if you:
- comment the `bin/restart` command inside the `bin/setup` file 
- do the full copy from container `bin/copyfromcontainer --all`
- restart containers `bin/restart`

Then it works as expected, at least until you try to change some file :)

**Comment by gorkabeguiristain** [comment]
Same happened to me, the problem was partially solved following the instructions given by @gendosua but it's not a definitive solution

**Comment by markshust** [comment]
Thanks for the report, I believe this is tied to an update I pushed out a couple days ago. Looking at it.

**Comment by markshust** [comment]
I found a logic issue with the copy scripts when trying to copy subdirectories. Tagged in 24.2.0, run `bin/update` to update your local instance.
https://github.com/markshust/docker-magento/blob/master/CHANGELOG.md#2420---2019-10-18

I wanted to confirm this fixes your issue?

**Comment by markshust** [comment]
I ran the one line script:
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.3`

noted in the readme, and had no errors after the update. if you are still having issues, please reopen this ticket with full details and logs of the install.
