### ISSUE TITLE
Add ext-sockets to php image

### ISSUE THREAD

**Issue by josefbehr** [markshust/docker-magento#186]
**For local Magento core development, the github repo is cloned. Running bin/setup then results in the following error, since ext-sockets is required (see below for screenshot).**

**Steps To Reproduce**
1. Run the setup for "New Projects"
2. Instead of using composer create-project or using a zipfile get Magento by cloning the github repo
3. Continue setup running bin/setup HOST

**Expected Result**
It works as it does in the other cases.

**Actual Result**
It doesn't:
<img width="918" alt="Screenshot 2019-10-21 at 00 02 06" src="https://user-images.githubusercontent.com/4368880/67167102-387ef880-f396-11e9-8312-d7d51fee7a5b.png">

**Comment by markshust** [comment]
thank you. i'm going to use the reference and match what magento cloud installs (https://devdocs.magento.com/guides/v2.3/cloud/project/project-conf-files_magento-app.html#php-extensions). this will include not only sockets but anything else that is missing.

**Comment by markshust** [comment]
Fixed in release 25.0.0. Thanks!
