### ISSUE TITLE
Contents of .composer inaccessible

### ISSUE THREAD

**Issue by spendlebury-ldg** [markshust/docker-magento#187]
**Description**

All files within /var/www/.composer are inaccessible. Running composer fails due to be unable to read config.json. Files appear to have correct ownership and permissions.

**Steps To Reproduce**
1. `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash -s -- magento-2`
2. `bin/download 2.2.8`
3. `bin/setup magento2.test`

**Expected Result**

`composer install` runs as part of the setup script and creates a working M2 instance

**Actual Result**

Correcting filesystem ownerships...
chown: changing ownership of '/var/www/.composer/keys.dev.pub': Operation not permitted
chown: changing ownership of '/var/www/.composer/cache/.htaccess': Operation not permitted
chown: changing ownership of '/var/www/.composer/cache': Operation not permitted
chown: changing ownership of '/var/www/.composer/config.json': Operation not permitted
chown: changing ownership of '/var/www/.composer/keys.tags.pub': Operation not permitted
chown: changing ownership of '/var/www/.composer/auth.json': Operation not permitted
chown: changing ownership of '/var/www/.composer/.htaccess': Operation not permitted
chown: changing ownership of '/var/www/.composer': Operation not permitted

....

  [RuntimeException]
  Could not read /Users/.../.composer/config.json

  file_get_contents(/Users/.../.composer/config.j
  son): failed to open stream: Permission denied

Manually running `composer install` from a bash prompt results in the above exception.

**Comment by spendlebury-ldg** [comment]
To clarify, this seems to be an issue with Mac OS Catalina only. Reverting to Mojave works fine.

**Comment by markshust** [comment]
I'm unable to replicate (I'm on Catalina). Can you check two things on your system....

What are the permissions of the `~/.composer` directory on your host machine?

![Screen Shot 2019-11-06 at 8 04 51 AM](https://user-images.githubusercontent.com/437029/68300669-427a4a00-006c-11ea-80cb-49eeb4fe599e.png)

Then, are you sure the File Sharing tab of Docker Preferences looks like this, to ensure this folder is being shared?

![Screen Shot 2019-11-06 at 8 05 09 AM](https://user-images.githubusercontent.com/437029/68300722-5756dd80-006c-11ea-948d-027891e83a40.png)

**Comment by spendlebury-ldg** [comment]
Unfortunately, I'm now back on mojave and so can't test.

**Comment by markshust** [comment]
Ok thanks, I'll close out for now but we can re-open it if anyone else experiences this issue.

**Comment by pmsteil** [comment]
> Unfortunately, I'm now back on mojave and so can't test.

Hey @spendlebury-ldg any pointers on how you downgraded?  I can't figure it out!

**Comment by spendlebury-ldg** [comment]
Not a simple process. Had to download the mojave installer from the app store, copy to an external disk, control-R, delete existing partitions and then reinstall from scratch. if you google 'downgrade to mojave' you should find more detailed steps.

**Comment by pmsteil** [comment]
@spendlebury-ldg thanks!
