### ISSUE TITLE
magento2_elasticsearch_1 exited with code 78

### ISSUE THREAD

**Issue by asnodj** [markshust/docker-magento#190]
**Description**
I'm getting elasticsearch 78 error code.

elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2019-11-06T15:08:02,344][INFO ][o.e.n.Node               ] [W12Dg-4] stopping ...
elasticsearch_1  | [2019-11-06T15:08:02,441][INFO ][o.e.n.Node               ] [W12Dg-4] stopped
elasticsearch_1  | [2019-11-06T15:08:02,441][INFO ][o.e.n.Node               ] [W12Dg-4] closing ...
elasticsearch_1  | [2019-11-06T15:08:02,452][INFO ][o.e.n.Node               ] [W12Dg-4] closed
elasticsearch_1  | [2019-11-06T15:08:02,454][INFO ][o.e.x.m.j.p.NativeController] [W12Dg-4] Native controller process has stopped - no new native processes can be started
magento2_elasticsearch_1 exited with code 78

**Steps To Reproduce**
1. docker-compose up

**Expected Result**
elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2019-11-06T15:08:02,344][INFO ][o.e.n.Node               ] [W12Dg-4] stopping ...
elasticsearch_1  | [2019-11-06T15:08:02,441][INFO ][o.e.n.Node               ] [W12Dg-4] stopped
elasticsearch_1  | [2019-11-06T15:08:02,441][INFO ][o.e.n.Node               ] [W12Dg-4] closing ...
elasticsearch_1  | [2019-11-06T15:08:02,452][INFO ][o.e.n.Node               ] [W12Dg-4] closed
elasticsearch_1  | [2019-11-06T15:08:02,454][INFO ][o.e.x.m.j.p.NativeController] [W12Dg-4] Native controller process has stopped - no new native processes can be started
magento2_elasticsearch_1 exited with code 78

**Actual Result**
elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2019-11-06T15:08:02,344][INFO ][o.e.n.Node               ] [W12Dg-4] stopping ...
elasticsearch_1  | [2019-11-06T15:08:02,441][INFO ][o.e.n.Node               ] [W12Dg-4] stopped
elasticsearch_1  | [2019-11-06T15:08:02,441][INFO ][o.e.n.Node               ] [W12Dg-4] closing ...
elasticsearch_1  | [2019-11-06T15:08:02,452][INFO ][o.e.n.Node               ] [W12Dg-4] closed
elasticsearch_1  | [2019-11-06T15:08:02,454][INFO ][o.e.x.m.j.p.NativeController] [W12Dg-4] Native controller process has stopped - no new native processes can be started
magento2_elasticsearch_1 exited with code 78

**Comment by markshust** [comment]
need steps to replicate

**Comment by dmanners** [comment]
I had the same issue today. After some googling I seem to have found this is related to your host's `vm.max_map_count` setting.

After running `sudo sysctl -w vm.max_map_count=262144` and then `bin/restart` inside the project dir all the containers started without a problem.

https://github.com/elastic/elasticsearch/issues/21523#issuecomment-260297349

**Comment by markshust** [comment]
Thanks @dmanners -- I'll try to make this update shortly

**Comment by markshust** [comment]
What operating system are you two on? I am unable to replicate on macOS. The `vm.max_map_count` setting shouldn't have anything to do with the host, since this is a elasicsearch-container-specific setting.

**Comment by piotrkwiecinski** [comment]
It has to be set up on linux host. An additional reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

**Comment by markshust** [comment]
Thanks! Added to documentation. Closing this one out

**Comment by markshust** [comment]
@piotrkwiecinski totally missed your PR! hah. I reverted mine and merged your update in, thanks much! https://github.com/markshust/docker-magento/pull/208
