### ISSUE TITLE
Feature : Ability to use 'src' as a symlink to actual Magento project

### ISSUE THREAD

**Issue by Seb2nim** [markshust/docker-magento#194]
**Description**
I wanted to keep my Magento project where it resides on disk and simply use a synlink "src"->project_directory.

Unfortunatelly, bin/copyfromcontainer fails (as docker cp fails on doing that) as "src" is not a directory.

Same with bin/copytocontainer

There is pretty little effort for that to work (see below).

**Steps To Reproduce**
1. bin/copyfromcontainer vendor

**Expected Result**
Works

**Actual Result**
Doesnt work

Actually, pretty easy to achieve 

bin/copyfromcontainer
```bash
#!/bin/bash
[ -z "$1" ] && echo "Please specify a directory or file to copy from container (ex. vendor, --all)" && exit

REAL_SRC=$(cd -P "src" && pwd)
if [ "$1" == "--all" ]; then
  docker cp $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/./ $REAL_SRC/
  echo "Completed copying all files from container to host"
else
  docker cp $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/$1 $REAL_SRC/
  echo "Completed copying $1 from container to host"
fi
```

**Comment by markshust** [comment]
Hi @Seb2nim, thank you for this! Would you mind creating a PR for this? If not I can take care of it.

**Comment by Seb2nim** [comment]
Hi @markshust , created PR #196 (didnt made that for a while, my .gitignore cames with it :-)

**Comment by markshust** [comment]
Sorry didn't see the PR until now :) Merged in
