### ISSUE TITLE
bin/dev-urn-catalog-generate doesnt map paths to host paths (anymore)

### ISSUE THREAD

**Issue by Seb2nim** [markshust/docker-magento#195]
**Description**
Script `bin/dev-urn-catalog-generate` is supposed to 'remap' generated path accordingly to host's path.
From README : 
> Generate URN's for PHPStorm and remap paths to local host. Restart PHPStorm after running this command.

Actually, the sed command disapeared in a recent commit. So the path are kept container ones.

Note : Actually, the `bin/dev-urn-catalog-generate` will not work at all presently due to a change in copytocontainer not being able to copy single file.

**Steps To Reproduce**
1. `bin/dev-urn-catalog-generate`
2. Open '.idea/misc.xml' => path are still container ones (instead of host ones).

**Expected Result**
Path would be translated to host

**Actual Result**
Paths are container ones.

**Comment by wbfiretoss** [comment]
Confirmed. This doesn't work. Neither does Xdebug on Ubuntu.

**Comment by Seb2nim** [comment]
Created PR #197

**Comment by DavrosFl** [comment]
Is there a work-around for this? I'm having the same issue.

**Comment by Seb2nim** [comment]
@DavrosFl see PR #197

**Comment by DavrosFl** [comment]
> @DavrosFl see PR #197

Thank you @Seb2nim. I changed my bin/dev-urn-catalog-generate file to match your PR. However, I'm getting:
`cannot overwrite directory "/Users/asdf/projects/ss-demo/Sites/magento2/src/misc.xml" with non-directory "/Users/asdf/projects/ss-demo/Sites/magento2/src"
Completed copying misc.xml from container to host
sed: /Users/asdf/projects/ss-demo/Sites/magento2/src/misc.xml: in-place editing only works for regular files
rm: /Users/asdf/projects/ss-demo/Sites/magento2/src/misc.xml.bak: No such file or directory
mv: rename /Users/asdf/projects/ss-demo/Sites/magento2/src/misc.xml to /Users/asdf/projects/ss-demo/Sites/magento2/src/.idea/misc.xml: Not a directory
URN's have been generated, you may now restart PHPStorm`

Am I missing a step?

**Comment by Seb2nim** [comment]
@DavrosFl Sorry, things are mixed together and only clear to me :).
This bug report concerns "path mapping not done" - and related PR #197 as workaround.

But actually as mentioned in description, the script cannot currently work due to other bug #191 (copyfromcontainer : does not work with files).

Pick up these two fixes. And dont forget to remove the dummy 'scr/misc.xml' file before run.

If too complicated, i suggest wait for @markshust to merge PRs.

**Comment by DavrosFl** [comment]
@Seb2nim It appears to have worked. Thank you so much!

**Comment by markshust** [comment]
PR merged, this has been included in version 26.0.0 https://github.com/markshust/docker-magento/issues/191#issuecomment-568190107
