### ISSUE TITLE
Xdebug not connecting to IDE's on Ubuntu 18.04. Neither PHPSTORM or VSCode connect.

### ISSUE THREAD

**Issue by wbfiretoss** [markshust/docker-magento#199]
Run through new install and follow steps to reproduce.
I noticed vscode's launch.json has port 9000 set. 
Tried 9000 and 9001 still not working.
In the corresponding video "Configure PHPStorm for Xdebug Remote Debugging from Docker"
The add Servers window is using an older version of PHPSTORM without as many parameters to fill out as the newer versions. I'm very new to docker so I have no idea how to debug this. Back to vagrant I go :-1:

**Comment by markshust** [comment]
If you leave my thumbs down on tickets, I'm not going to work on them. Please be respectful.
