### ISSUE TITLE
Plugin magento/magento-composer-installer could not be initialized, class not found: MagentoHackathon\Composer\Magento\Plugin  

### ISSUE THREAD

**Issue by itsazzad** [markshust/docker-magento#200]
**Description**
vendor folder stays empty

**Steps To Reproduce**
1. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash -s -- magento-2
2. composer create-project --repository=https://repo.magento.com/ --ignore-platform-reqs magento/project-enterprise-edition=2.3.3 src

**Expected Result**
Create Magento EE 2.3.3 project

**Actual Result**
    Failed to execute unzip -qq  '/var/www/.../src/vendor/magento/magento-composer-installer/......' -d '/var/www/markshust/markshust-docker-magento/src/vendor/composer/...'

**Comment by markshust** [comment]
That "actual result" is truncated so I'm not able to read what actually went on. My guess is you need to run `rm -rf` before running `composer create-project`. I'll assume that is what happened here, if not please let me know and I will reopen the ticket.
