### ISSUE TITLE
Correct process to clone docker-magento to a new dev machine?

### ISSUE THREAD

**Issue by pmsteil** [markshust/docker-magento#201]
Hey Mark,

I have tried using docker save and docker load commands to move my magento setup to a new computer and what I got was all the correct containers, but magento didn't seem to be installed any more and I just got a 404.

Any ideas on what I need to do to correct this?

Do you have a step by step on how to move the magento setup correctly?

thanks!
patrick

**Comment by pmsteil** [comment]
Here are the details of what I did:


```
Run:
   docker images
Take the image_id of “markoshust/magento-php” and run:
   sudo docker save -o ../mag233b.tar 7e48618a3ba3
Copy the tar file to the new computer and then in your magento_infranet folder run:
   docker load -i mag233b.tar
cd into the magento folder
   bin/start

```

**Comment by pmsteil** [comment]
I just figured out to also run:

bin/composer install 

and it is downloading all the magento code, etc...

Will update after that completes

**Comment by pmsteil** [comment]
Still not working... apparently the process I used above didn't bring over everything I needed... any ideas?

**Comment by markshust** [comment]
You can't just clone this project out :)

Here is the documentation in the README https://github.com/markshust/docker-magento#setup

There is also a full free web course that covers this and many other topics at https://m.academy/p/setup-magento-2-development-environment-docker

**Comment by markshust** [comment]
I just noticed you mentioned a new dev machine. It's basically just same setup as a new install, but look at the "Existing Projects" section of the readme: https://github.com/markshust/docker-magento#existing-projects

**Comment by pmsteil** [comment]
@markshust with regards to this comment:
> You can't just clone this project out :)

I believe you, but don't know enough to understand why we can't move the docker containers/images to another machine. I thought that was part of the promise of using docker?

In terms of exporting the db so I can import it in your "Existing Projects" documentation, how would I go about getting an sql dump?

Thanks so much!
