### ISSUE TITLE
 SSL_do_handshake() failed (

### ISSUE THREAD

**Issue by jaswinder97** [markshust/docker-magento#203]
Not able to run stopped docker containers after a while
./bin/stop

./bin/start 

Getting these errors from nginx app container:

`SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.25.0.1, server: 0.0.0.0:8443`

**Comment by jaswinder97** [comment]
@markshust could you please help me on this ASAP

**Comment by markshust** [comment]
I'm sorry, I think I need more info to replicate? I've never seen this before. Perhaps try blowing away your setup and re-installing.

**Comment by markshust** [comment]
Closing as unable to replicate, SSL is working ok for me and I don't have steps to replicate,
