### ISSUE TITLE
Can't create a Magento Cloud Commerce local environment

### ISSUE THREAD

**Issue by wbfiretoss** [markshust/docker-magento#206]
**Description**
Can't create a Magento Cloud Commerce local environment
Ubuntu 18.04

**Steps To Reproduce**
1. Follow Existing Projects instructions.

**Expected Result**
To have a new dev environment

**Actual Result**
warren@asus:~/Sites/oliveandcocoa$ bin/restart
Stopping oliveandcocoa_phpfpm_1 ... done
Stopping oliveandcocoa_db_1 ... done
Stopping oliveandcocoa_redis_1 ... done
Starting oliveandcocoa_db_1 ...
Starting oliveandcocoa_db_1
Starting oliveandcocoa_elasticsearch_1 ...
Starting oliveandcocoa_elasticsearch_1
Starting oliveandcocoa_redis_1 ...
Starting oliveandcocoa_redis_1
Creating oliveandcocoa_mailhog_1 ...
Starting oliveandcocoa_db_1 ... done
Recreating oliveandcocoa_phpfpm_1 ...
Recreating oliveandcocoa_phpfpm_1 ... error

ERROR: for oliveandcocoa_phpfpm_1 Cannot start service phpfpm: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/warren/Sites/oliveandcocoa/src/composer.lock\\\" to rootfs \\\"/var/lib/docker/overlay2/4b0089daf6bd080f3a79ed8df613bc66a36e4369070e0e69cfc4f182c1746af6/merged\\\" at \\\"/var/lib/docker/overlay2/4b0089daf6bd080f3a79ed8df613bc66a36e4369070e0e69cfc4f182c1746af6/merged/var/www/html/composer.lock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directorCreating oliveandcocoa_mailhog_1 ... done

ERROR: for phpfpm Cannot start service phpfpm: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/warren/Sites/oliveandcocoa/src/composer.lock\\\" to rootfs \\\"/var/lib/docker/overlay2/4b0089daf6bd080f3a79ed8df613bc66a36e4369070e0e69cfc4f182c1746af6/merged\\\" at \\\"/var/lib/docker/overlay2/4b0089daf6bd080f3a79ed8df613bc66a36e4369070e0e69cfc4f182c1746af6/merged/var/www/html/composer.lock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by markshust** [comment]
Does a `composer.lock` file exist in your project root/repo?

**Comment by wbfiretoss** [comment]
I finally got it working. Many more complications but to get passed this part you simply run 

`composer update.`
