### ISSUE TITLE
Create instructions for PHPSTORM's Validate Debugger Configuration on Web Server.

### ISSUE THREAD

**Issue by wbfiretoss** [markshust/docker-magento#207]
**Description**
Create instructions for PHPSTORM's Validate Debugger Configuration on Web Server.
Lot's of googling IRC and Slack help. Leads me to believe it maybe a problem with nginx.conf.sample file. Could be path mappings in PHPSTORM. Not sure. 

**Steps To Reproduce**
1. Follow Xdebug instructions to setup, configure and validate Xdebug

**Expected Result**
Working Xdebug. With Validation tool 

**Actual Result**
Not Working Xdebug 

![Screenshot from 2019-12-23 11-15-14](https://user-images.githubusercontent.com/57146767/71374635-a8695500-2578-11ea-900c-5aa4de1ffa17.png)

**Comment by wbfiretoss** [comment]
Cannot confirm that xdebug is running after 

```
Welcome to Netshoot! (github.com/nicolaka/netshoot)                                                                   
root @ / 
 [2] 🐳  → ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:19:00:07  
          inet addr:172.25.0.7  Bcast:172.25.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19152 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14543 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10432217 (9.9 MiB)  TX bytes:39627880 (37.7 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


root @ / 
 [3] 🐳  → sudo tcpdump -i eth0 -nn -s0 -v port 9001
bash: sudo: command not found

root @ / 
 [4] 🐳  → tcpdump -i eth0 -nn -s0 -v port 9001
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes



^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
```

**Comment by wbfiretoss** [comment]
#get a list of all interfaces on localhost
ifconfig -a | sed 's/[ \t].*//;/^$/d'

#then check every interface for traffic on port 9001
tcpdump -i <interface> -nn -s0 -v port 9001

No interfaces have captured any packets on port 9001. 

Xdebug is not forwarding on Client or Host. Confirmed.

**Comment by markshust** [comment]
The validation tool never worked for me, I believe it's something specific to Docker in general. Not having the validation tool working doesn't seem to effect Xdebug connections.

The only way to very Xdebug is working is by running `bin/cli php -v`. Xdebug should be outputted to the CLI. It listens on port 9001 as phpfpm is listening on the default port 9000. As long as Xdebug is displayed in the PHP cli output, it is enabled. If it isn't, you must run `bin/xdebug enable` to enable it.

**Comment by wbfiretoss** [comment]
Without the validation tool being verified Phpstorm will not stop on break points.

**Comment by markshust** [comment]
I can confirm the validation tool doesn't work, but debugging works just fine. I don't see this as an issue so I'm closing out, as I'm still able to start xdebug, set breakpoints, get them triggered, etc.

**Comment by wbfiretoss** [comment]
glad it works for you buddy.
