### ISSUE TITLE
NPM executable file not found in $PATH

### ISSUE THREAD

**Issue by grll** [markshust/docker-magento#210]
**Description**
npm is not found in $PATH on the container. I am running docker under ubuntu 18.04.

**Steps To Reproduce**
1. follow install instruction
2. bin/npm --version

**Expected Result**
retrieve the version of npm installed in the container.

**Actual Result**
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"npm\": executable file not found in $PATH": unknown

**Comment by grll** [comment]
I actually can't find where is npm or node installed in the php container. It seems to me that node is here because it comes already packaged in the official php image ? 

I temporarily installed npm manually in the container and it is now working, the issue could be fixed by installing npm in the php Dockerfile.

If anyone has the same issue:
```bash
docker exec -it -u 0 a4c4501e71db apt-get install npm
```
where a4c4501e71db is the id of your php container that can be retrieved using `docker ps`

**Comment by markshust** [comment]
It appears I have node installed on the image but not npm. I'll see what I can do to get a new image out shortly which updates node and contains npm.

**Comment by markshust** [comment]
Resolved in commit above, will momentarily build new PHP images. What happened is that the node source changed/deprecated 8.x, and somehow removed npm from the build process. I updated the script to install node 10.x (the current LTS version) and have confirmed npm 6.x gets installed along with it.
