### ISSUE TITLE
Browser Error: Certification of Authority Invalid 

### ISSUE THREAD

**Issue by carlos-reynosa** [markshust/docker-magento#211]
**Description**
An initial automated install results in an SSL Cert Error when visiting the site for the first time. 

My test environment:

- macOS Desktop 10.14.6
- Chrome Version 79.0.3945.117 (Official Build) (64-bit) ( I got the same results on Safari)

**Steps To Reproduce**
1. Perform Automated Setup: 

`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.3
`

2. Visit install url magento2.test 

**Expected Result**
- I expect to see the Magento 2 home page when first navigating to the install URL after initial setup. 

**Actual Result**

Whenever I do a fresh install I see this Error:

![image](https://user-images.githubusercontent.com/926773/72644961-41488180-3927-11ea-9681-87c514affaa1.png)

Except for this first error after setup everything else seems to be working fine. I usually just ignore it and bypass the error but I figured I should finally try to address the issue. Thanks for your help!

**Comment by carlos-reynosa** [comment]
Here is additional info about the cert from the browser:

![image](https://user-images.githubusercontent.com/926773/72645782-45759e80-3929-11ea-93ab-a395a30c0e7b.png)

**Comment by markshust** [comment]
Thank you. This has been an ongoing issue for some time. I have worked on a fix and it will be out shortly.

**Comment by markshust** [comment]
Fixed, pushed out `27.1.0` docker compose version containing new SSL updates.

**Comment by carlos-reynosa** [comment]
That solved the issue! Thank you!!
