### ISSUE TITLE
URN misc.xml file not picked up by phpstorm

### ISSUE THREAD

**Issue by carlos-reynosa** [markshust/docker-magento#213]
**Description**
When generating a URN misc.xml file using `bin/dev-urn-catalog-generate` the file is placed within `src/.idea`. The file is not picked up by phpstorm  probably because it's in a sub directory and thus navigation hints for URN paths don't work within xml files. 

**Steps To Reproduce**
1. Run automated setup install `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.3`
2. run `bin/dev-urn-catalog-generate`
3. File is placed within src/.idea/misc.xml 
4. Open a layout file 
5. URN xsd schema location code navigation does not work 

**Expected Result**
Once the URN misc.xml file is generated and phpstorm is restarted, URN code navigation should work. 

**Actual Result**
URN code navigation within misc.xml files does not work. 

**ASSUMPTIONS**

- My project root is not `src `.

**Comment by carlos-reynosa** [comment]
1.  The URN resource file should be written to the project root configuration folder `.idea/misc.xml `
2.  Location paths within misc.xml file should point to xsd files relative to the project root and prefixed with: `location="$PROJECT_DIR$/src/vendor/`. 

Line where I think the issue is:

https://github.com/markshust/docker-magento/blob/8adc50958f639191029c63ea8aa6171a896b563b/compose/bin/dev-urn-catalog-generate#L11

**Comment by markshust** [comment]
Hi Carlos,

I think I need to make a note to use `src` as the project root? The src should be the root of the project.

**Comment by markshust** [comment]
I updated misc.xml to use `$PROJECT_DIR$`, however I kept the `src` reference out of it. This project is meant to work with `src` being the base root directory within phpstorm, I had it the other way a while back but it was confusing for a few reasons. Feel free to fork/edit this file locally if you need it to include `src`.

**Comment by carlos-reynosa** [comment]
Ok. That's good to know. Thank you!
