### ISSUE TITLE
What is the admin panel url ?

### ISSUE THREAD

**Issue by sidh01** [markshust/docker-magento#214]
I have tried to open admin panel with url https://magento2.test/admin
but it seems like admin panel not exist on this url
![image](https://user-images.githubusercontent.com/37957105/73172869-0403a100-412a-11ea-8b2d-dd49162ea6e7.png)

**Comment by markshust** [comment]
Hi @sidh01 - the admin URL is auto-generated at install time. To find it out you can run `bin/magento info:adminuri`

**Comment by sidh01** [comment]
> Hi @sidh01 - the admin URL is auto-generated at install time. To find it out you can run `bin/magento info:adminuri`

Thank you
