### ISSUE TITLE
docker-magento behind nginx reverse proxy doesnt work

### ISSUE THREAD

**Issue by outbackdingo** [markshust/docker-magento#215]
for the life of me, i cannot get this to work with docker compose behind an nginx reverse proxy
simply adding a few environment tags and removing the host exposed ports, as blow results in a 502 nginx bad gateway, where every other site works fine, even opencart. docker ps shows its opening ports on the host ive configured it not  too
5eb065eac330        markoshust/magento-nginx:1.13-8            "nginx -g 'daemon of…"   7 seconds ago       Up 5 seconds          80/tcp, 0.0.0.0:32920->8000/tcp, 0.0.0.0:32919->8443/tcp                                     optim_app_1

any ideas ?

services:
  app:
    image: markoshust/magento-nginx:1.13-8
    ports:
      - "8000"
      - "8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    environment:
      # WebProxy - Settings
      VIRTUAL_HOST: store.domain.com
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: store.domain.com
      LETSENCRYPT_EMAIL: email@domain.com

**Comment by markshust** [comment]
I'm going to close this ticket, as there isn't anything specifically wrong with this repo or setup.

The implementation to get nginx reverse proxy working is difficult, as there is a lot going on with Magento's config. I plan on working on this implementation in an upcoming sprint, but there shouldn't be anything preventing you from getting this to work at the moment. If there is, you can always fork+pull this repo down and make your updates locally, and report back with a PR to implement any changes that you come across.
