### ISSUE TITLE
Setup install with Mysql Error 

### ISSUE THREAD

**Issue by Elema82** [markshust/docker-magento#217]
Hi! I have an error when i run the setup command:
`bin/setup magento2.test`

the code return this errors:
<img width="660" alt="Captura de Pantalla 2020-02-06 a la(s) 09 51 08" src="https://user-images.githubusercontent.com/25822930/73938740-a4925780-48c6-11ea-9d52-527563e1d5f4.png">

<img width="552" alt="Captura de Pantalla 2020-02-06 a la(s) 09 51 29" src="https://user-images.githubusercontent.com/25822930/73938749-a825de80-48c6-11ea-9ebc-7f2f7aa5f696.png">

The process finish ok but my store is not running good because the database wasn't created

<img width="1058" alt="Captura de Pantalla 2020-02-06 a la(s) 09 57 08" src="https://user-images.githubusercontent.com/25822930/73938914-0c48a280-48c7-11ea-99a6-b7c999489831.png">

can you help me with this error?

regards

**Comment by markshust** [comment]
Hi there,

I'm not sure what happened during your install, but I would recommend blowing everything away and starting over. The steps for this are:

`bin/remove`
`bin/removevolumes`

Then remove your project directory and start the install over. Be sure there is nothing listening on port 80, 443 or 3306 of your host machine before starting the install.

**Comment by Elema82** [comment]
hello mark thanks for helping me, I started the installation again with the commands you sent me and my store is online now.

yesterday I had tried to erase everything but not the volumes.

Great, thanks!

**Comment by markshust** [comment]
Great, yes unfortunately things are messed up a bit on new installs unless that removevolumes script is run. I kept the remove volumes script separate in the event someone would want to keep the data around, but perhaps I'll move it until the remove script. Glad you got it working 😁
