### ISSUE TITLE
How to configure NGINX with docker-compose ? Elastisearch 6

### ISSUE THREAD

**Issue by maya5510** [markshust/docker-magento#220]
Where Can I find NGINX configure file ? I need to find this:
`location ~ (index|get|static|report|404|503)\.php${`
and then replace with this:
`location ~ (index|get|static|report|404|503|elastic)\.php${`
Can I add some line to docker-compose.yml to achieve same result ?

**Comment by markshust** [comment]
@maya5510 this can be easily overridden by the `nginx.conf.sample` file in the root of your Magento installation.

You should be able to copy this file to `nginx.conf`, make your updates, then run `bin/restart`.
