### ISSUE TITLE
Error during setup - ioncube_loader_lin_7.2.so not found

### ISSUE THREAD

**Issue by WestArjan** [markshust/docker-magento#228]
**Description**
When trying to setup docker with an existing magento 2 project I get stuck when i try the following command :

> bin/magento app:config:import

The error that is shown is 

> root@arjanwest-GL552VW:/home/arjanwest/Documents/m2-demo-dev-docker# bin/magento app:config:import
> Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20151012/ioncube_loader_lin_7.2.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20151012/ioncube_loader_lin_7.2.so: cannot open shared object file: No such file or directory
> 
> Warning: require(/var/www/html/vendor/composer/../baldwin/magento2-module-addresses/registration.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 70
> 
> Fatal error: require(): Failed opening required '/var/www/html/vendor/composer/../baldwin/magento2-module-addresses/registration.php' (include_path='/var/www/html/vendor/magento/zendframework1/library:.:/usr/local/lib/php') in /var/www/html/vendor/composer/autoload_real.php on line 70
> root@arjanwest-GL552VW:/home/arjanwest/Documents/m2-demo-dev-docker# 

When going in the docker CLI and navigating to the /extensions directory there is 1 no-debug directory but it is named differently and it does contain ioncube_loader_lin_7.2.so.

I am using the markoshust/magento-php:7.2-fpm-6 image.

**Comment by rangerz** [comment]
@WestArjan It's fixed on #226

**Comment by rangerz** [comment]
@WestArjan @markshust 
It's fixed on v30.0.0, this issue should be closed.

**Comment by markshust** [comment]
Thanks, closing it out
