### ISSUE TITLE
debug logs

### ISSUE THREAD

**Issue by immakdas** [markshust/docker-magento#230]
**Description**
magento 2.3.3
debug and exceptions logs in the var/errors/*.log are empty even with the forced dev and debug modes
```
bin/magento deploy:mode:set developer
bin/magento setup:config:set --enable-debug-logging=true
bin/magento cache:flush
```
pub/errors/local.xml.sample renamed to local.xml

/app/etc/env.php
`'dev' => [
        'debug' => [
            'debug_logging' => 1
        ]
    ]`

**Steps To Reproduce**
1.  install new
2. run terminal to enable debug
```
bin/magento deploy:mode:set developer
bin/magento setup:config:set --enable-debug-logging=true
bin/magento cache:flush
```

**Expected Result**
`$this->logger->debug('debug text');`
should write all debug to
/var/log/debug.log file
php exception errors to 
/var/log/exception.log

**Actual Result**
no log records in the /src/var/

**Comment by rangerz** [comment]
@immakdas I think you need uncomment them in docker-compose.dev.yml
`- ./src/var/log:/var/www/html/var/log:delegated`
`- ./src/var/report:/var/www/html/var/report:delegated`
and run `bin/restart`
or try into container to check the log file
`bin/cli ls var/log`

**Comment by markshust** [comment]
yea, the logs should be writing. you can uncomment the above as mentioned, or view the results with something like

```
bin/cli cat var/logs/debug.log
```

**Comment by ManishaVasani** [comment]
@markshust  @immakdas can you please provide a path of this file?  docker-compose.dev.yml
