### ISSUE TITLE
How to set fielddata="true on" with docker-compose and Elasticserach Server

### ISSUE THREAD

**Issue by maya5510** [markshust/docker-magento#231]
How to set fielddata=true on with docker-compose and Elasticserach Server. Is there an config file for elasticsearch ?

**Comment by rangerz** [comment]
@maya5510 
These links may be helpful.
[https://www.niceonecode.com/Question/20583/ElasticSearch-Error-Fielddata-is-disabled-on-text-fields-by-default](https://www.niceonecode.com/Question/20583/ElasticSearch-Error-Fielddata-is-disabled-on-text-fields-by-default)
[https://github.com/myparcelnl/magento/issues/258](https://github.com/myparcelnl/magento/issues/258)

**Comment by markshust** [comment]
Thanks, the link above by @rangerz should help.

You can run elasticsearch puts on the container with something like:

```
curl -XPUT 'http://localhost:9200/_all' -H 'Content-Type: application/json' -d '{"settings": {"index": {"max_shingle_diff": 10 }}}'
```
