### ISSUE TITLE
Using alternative port on dev

### ISSUE THREAD

**Issue by janssens** [markshust/docker-magento#240]
Hi,
Is there any way to use alternative ports on local machine ? 
I work with several projet and I've got a full web server already running locally (meaning ports 80,443 and 3306 are busy).
The setup is very convenient for production but cannot run in parallel with another server, which would be really useful for a developer.
Yes I can stop my local nginx and mysql instances, but then it's not easy to quickly switch between projects, and this is what I do all day.

**Comment by markshust** [comment]
Yes, you just need to change the ports in the `docker-compose.yml` file, like so:

```
    ports:
      - "80:8000"
      - "443:8443"
```

To change the site to listen on port 8080 and 8443, update it like so:

```
    ports:
      - "8080:8000"
      - "8443:8443"
```

... then restart the containers with `bin/restart`. You'll want to update every reference to a `ports` key that you want to run on a different port.

After doing so, you'll also want to update Magento's config values for `base_url`:

`SELECT * FROM core_config_data where path like '%base_url%'`

You can add the appropriate port number to the URL values like so:

`https://magento234.test/ >>> becomes >>> https://magento234.test:8443/`
