### ISSUE TITLE
Replace bin folder with global script

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#242]
I like how Warden implements the master `warden` command: https://github.com/davidalger/warden/blob/develop/bin/warden

This has numerous benefits:
- Single entry source means that many sites can share the same set of scripts, rather than entirely different copies existing for each install of Magento
- Makes upgrades easier. The `dm update` command could update the entire set of scripts.
- Increased portability to other systems. By having an umbrella command, for example `dm`, we could execute an entirely different set of scripts for mac and Linux if needed for certain things (such as setting up SSL certs which require completely different commands).
- Not path-dependent, which means we could traverse up the directory tree until we detect the main root folder of the project (ex. parent of `src`). This means you could be inside something like `vendor/magento` and still run the `dm` command, detect the root, and execute as usual.

Some tradeoffs:
- The `bin/magento` command is now consistent with Magento's way of calling `bin/magento`. We could still keep the `bin` folder around though and setup an alias `bin/magento >>> dm m`
- Local modifications would no longer be available, however one could still customize specific scripts in the local `bin` folder. It would be neat to allow others to "tap into" the `dm` script to create their own commands, for example `dm mycommand`. Essentially, I could have a custom script at `bin/mycommand`, and typing `dm mycommand` will not find the script in dm, but look up the parent path and execute the custom script if it finds it.
- We'd probably want to avoid many levels of nesting. I think one level down such as the previous `dm c whatever` command would be as deep as we want to go, for simplicity sake.

I also like how we can use 100% bash and avoid other languages such as ruby. This keeps things consistent with the current project and eliminates overhead/dependencies.

As this would be a major breaking change, I'd like to introduce this functionality into a new `100.x` version. This would essentially be docker-magento 2.0 and introduce other breaking changes of this milestone.

**Comment by gander** [comment]
I have created a script available in `$PATH` that runs commands from the `./bin/` directory if it runs in the path `./` or `./src/`.

_mbin_:
```bash
#!/usr/bin/env bash

[ ${#} -eq 0 ] && "Specify command" && exit 1
CMD="bin/$(basename "${1}")"; shift
[ $(basename "${PWD}") = "src" ] && cd ..
[ ! -x "${CMD}" ] && echo "Wrong command: ${CMD}" && exit 2
"${CMD}" "${@}"
```
Usage:
```bash
mbin magento --version
```

**Comment by markshust** [comment]
Going to close this out, I think everyone likes the bin scripts. They are simple and easy to understand.
