### ISSUE TITLE
Implement alpine/micro containers for all images, prod support

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#244]
The current images are quite large, and could potentially take up a couple of gigs of space. This probably isn't a big deal for local dev, however it makes sense to look into more efficient ways of creating these images so they can also be used on production.

We'd need a way to build base images which could be used in both dev & prod, and also the ability to override the images for dev-specific packages. For example, even though `vi` is a very small package (and this may be a construed example), it's fairly common practice to not include this package on prod as it's just really not needed, however it is needed a lot in dev. We'd also probably want things like xdebug installed & available in the dev images, but not required or needed on prod, so we should save the space on prod and not include it.

**Comment by shochdoerfer** [comment]
We extended the `bin/setup` script to install linux tools for local development but not have them in the images built for production. Was the best option than having to deal with multiple images and keep them in sync.
