### ISSUE TITLE
Create better documentation

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#245]
The current docs work ok, but the README is getting pretty long. There are also issues/tasks which I would like to document, but am avoiding because the doc is getting too long to follow.

Some resources to look into:
- GitHub Wiki https://github.com/markshust/docker-magento/wiki
- GitHub Pages https://pages.github.com/
- Read the Docs https://readthedocs.org/

**Comment by hitchhooker** [comment]
awesome idea. would also love to see setup documentation for production. Went through your academy guidance but not completely sure how to play around with nginx/certificates when in dockerized.

**Comment by hitchhooker** [comment]
I splitted README.md into Wiki form here: https://github.com/markshust/docker-magento/wiki

**Comment by markshust** [comment]
@hitchhooker that's awesome! can you make a PR? I can then update where needed and pull this in. looks great.

**Comment by markshust** [comment]
@hitchhooker never mind! I just noticed that is a link to this repo. you can tell I have no clue how these wiki's work :)

I'll close this out for now.

**Comment by hitchhooker** [comment]
> @hitchhooker that's awesome! can you make a PR? I can then update where needed and pull this in. looks great.

Seems like Wiki does not work as smooth as you could hope for. Did not give me a possibility to create PR or push to this repo(only web app) so logo is currently hosted at https://github.com/hitchhooker/docker-magento.wiki.git instead locally in this repos wiki.
