### ISSUE TITLE
Change the value of xdebug.remote_connect_back 

### ISSUE THREAD

**Issue by marcelo011982** [markshust/docker-magento#246]
Didn't achieve   to connect to my linux phpstorm with your oficial documentations. I started to dig and i found that the value of xdebug.remote_host  that is  host.docker.internal did not work properly in my SO.
Just when i changed the value of 
xdebug.remote_connect_back to on that i make it works. The problem is that everytime that i restart my container i have to make this change.
I'm new to docker, how can i change my yml and Docker files to build a new image with this change inside?
I'm improving my english sorry for misinterpretations or errors. 
Thanx in advance and take care.

**Comment by rangerz** [comment]
@marcelo011982 This course may be helpful for you
[Install extensions & packages](https://courses.m.academy/courses/setup-magento-2-development-environment-docker/lectures/9064350)

**Comment by marcelo011982** [comment]
@rangerz I've maded

Created a docker file inside images/php.. inserted:

`FROM markoshust/magento-php:7.3-fpm-5
USER root

RUN touch /usr/local/etc/php/php.ini \
    && echo "xdebug.remote_connect_back = On;" >> /usr/local/etc/php/php.ini


USER app`

And in docker-compose.yml ,inserted the reference to Dockerfile:

`
....
  phpfpm:
    #image: markoshust/magento-php:7.3-fpm-5
    build: images/php
    links:
      - db
    volumes: *appvolumes`
