### ISSUE TITLE
Error to copy file to container

### ISSUE THREAD

**Issue by marcelo011982** [markshust/docker-magento#247]
Hi, i just created the volumes and changed pub/index.php file to  see some configuratinos..
But when i do 
bin/copytocontainer --all
I have the response:

Error response from daemon: Error processing tar file(exit status 1): unlinkat /var/www/html/composer.json: device or resource busy
Completed copying all files from host to container
Correcting filesystem ownerships...
Filesystem ownerships corrected.
Correcting filesystem permissions...

And the file not change on container.
Thanx in advace.

**Comment by rangerz** [comment]
It's because your container exist  /var/www/html/composer.json (empty folder), and try to use this way to remove them:
```
# Stop container
bin/stop

# Start container without docker-compose.dev.yml
docker-compose up -d

# Remove empty folder
bin/cli rmdir composer.json
bin/cli rmdir composer.lock
bin/cli rmdir nginx.conf.sample

# Reset and try again copytocontainer
bin/restart
bin/copytocontainer --all
```

If `rmdir` is not work, try `rm -rf`.

**Comment by markshust** [comment]
@marcelo011982 @rangerz you shouldn’t need to remove containers if this happens!

This happens when the volume link gets disconnected from the container. Sometimes happens when switching between git branches or commits. If it does, all you need to do is restart everything with `bin/restart` and everything should be back to normal.

**Comment by marcelo011982** [comment]
Thanks.
@markshust just restart didn't work in my case . Actually i tried before -  so i attempted using @rangerz and almost worked . i did
# Start container without docker-compose.dev.yml
docker-compose up -d

# Remove empty folder
bin/cli rm -rf *

# Reset and try again copytocontainer
bin/restart
bin/copytocontainer --all  
But in the 'copytocontainer' command the issue persist.

One thing intersting is that 'unlinkat' in my error log is a command to delete a folder and that folder (composer.json) don't exist.

I keep digging out to find the  reason. If someone have an idea please share.

**Comment by rangerz** [comment]
@marcelo011982 
You can watching `docker-compose.dev.yml` that expected your project `src` should exsit `composer.json`, `composer.lock`, and `nginx.conf.sample`
If your project does not provide these file, docker start will failed in the second time ( the first time will generate a empty folder in container)
So you can comment `composer.json`, `composer.lock` ... in `docker-compose.dev.yml` and try restart again.

Fixed steps:
```
# Stop container
bin/stop

# Start container without docker-compose.dev.yml
docker-compose up -d

# Remove empty folder
bin/cli rmdir composer.json
bin/cli rmdir composer.lock
bin/cli rmdir nginx.conf.sample

# Copy to Container Here !!!
bin/copytocontainer --all

# Edit your docker-compose.dev.yml to fit your project
# Final restart
bin/restart
```
