### ISSUE TITLE
Error With Readme Config Set Command

### ISSUE THREAD

**Issue by carlos-reynosa** [markshust/docker-magento#248]
**Description**
The readme within the Existing Project section uses bin/magento config:set to set base urls. That command seems to be throwing an error. 

* https://github.com/markshust/docker-magento#existing-projects

**Steps To Reproduce**
1. Set base URL using readme Existing Projects section commands:

```
# Set base URLs to local environment URL (if not defined in env.php file):
bin/magento config:set web/secure/base_url https://yoursite.test/
bin/magento config:set web/unsecure/base_url https://yoursite.test/
```

**Expected Result*

No error is thrown and base urls are set. 

**Actual Result**
 
![image](https://user-images.githubusercontent.com/926773/78846846-fa1bdb00-79c1-11ea-9ba1-b449736eb9aa.png)

**Comment by rangerz** [comment]
I think this command is work for you if your magento database does not exist `web/secure/base_url` config
```
bin/magento setup:store-config:set --base-url-secure=https://magento2.test/
```

**Comment by markshust** [comment]
Hi @carlos-reynosa, did you import the database? After which step did you try to set those config vals? If Magento isn't able to connect to the database, there will not be `config` options when running `bin/magento`. @rangerz's suggestion may work for you if you didn't manually update `core_config_data` with the base URLs of your new project.

**Comment by markshust** [comment]
I believe your `app/etc/env.php` file isn't setup. Please ensure that is setup first before running the `bin/magento` command.

**Comment by o0mohd90o** [comment]
I had same issue. I had to use this command
`bin/copytocontainer --all`
after update .env file for the container configuration

**Comment by o0mohd0o** [comment]
I had same issue. I had to use this command
`bin/copytocontainer --all`
after update .env file for the container configuration
