### ISSUE TITLE
Delete composer.lock and copy it to container.

### ISSUE THREAD

**Issue by marcelo011982** [markshust/docker-magento#258]
**Description**
Trying to remove composer.lock file to install a new module inserted on composer.json require node.

**Steps To Reproduce**
1. Alter composer.json
2. delete composer.lock
3.  bin/copytocontainer --all

**Expected Result**
A message on cli after the second command saying:
Completed copying all files from container to host

**Actual Result**
A message saying that composer.lock was incorrectly  mapped

**Comment by marcelo011982** [comment]
Manage to work it out:
1)bin/stop
2)docker-compose up -d
3)bin/bash
4)rmdir composer.lock
5)exit container
6)comment on  docker-compose.dev.yml the line:
   ./src/composer.lock:/var/www/html/composer.lock:delegated
7)bin/restart
8)bin/copyfromcontainer --all
9)remove the comment on step 6 and restart containers.

**Comment by rangerz** [comment]
@marcelo011982  #256 will avoid this issue when `bin/start` to create the empty useless folder.

**Comment by marcelo011982** [comment]
I saw your PR, interesting how it would prevent some problems.
But not sure how it would avoid my issue because i delete my composer.lock after i started containers.  
 The modification on bin/start  of your PR , please correct me if i am wrong, prevents to map the volumes on docker-compos.dev.yml if a file do not exists on src local folder. 
So if i delete composer.lock on src , with your modification, it would not be able to run bin/start because my file don't exists. Unless i put my file on ignore list that you provided on you bin/start.
Am i right?

**Comment by rangerz** [comment]
@marcelo011982 
Ignore list is just for **folder**. After downloading magento `bin/download 2.3.5`, it does not exist in the `app/code` folder. When you start docker `bin/start`, the volume mapping in `docker-compose.dev.yml` will create the `./src/app/code` in your local and `/var/www/html/app/code` in docker container. It's ok, and they are folder mapping.

But **file** mapping will have problems, just is your situation.
When start docker, the file mapping is not match, docker will try to create empty folder to fix mapping issue. It's good for folder, but not good for file

This is my understanding and you also can do more test, and your steps is correct. when the issue happened, just unmount them and into container to remove the mapping empty folder.

or you can start docker by `docker-compose up -d` without any mount in `docker-compose.dev.yml`
