### ISSUE TITLE
Elasticsearch tutorial / usage guide / video available ? 

### ISSUE THREAD

**Issue by schroejahr2** [markshust/docker-magento#260]
Hi, im struggling with elasrticsearch.

Updated to the latest version via bin/update & bin/restart

When i activate Elasticsearch, the test connection succeeds, but on reindexing, it throws the error: 

`Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}`

Is there anywhere anything available which describes the usage / activation in any way ? 

Thanks !

**Comment by markshust** [comment]
I think this is something specific to your install. I just pushed out a new elasticsearch image, so please try running `bin/update` and try to reindex again.

See this article for this error:
https://stackoverflow.com/questions/55857956/types-cannot-be-provided-in-put-mapping-requests-unless-the-include-type-name-p

One can update the elasticsearch server by running a command such as:
```curl -XPUT 'http://localhost:9200/_all' -H 'Content-Type: application/json' -d '{"settings": {"index": {"max_shingle_diff": 10 }}}'
```
