### ISSUE TITLE
Delete folder from host doesn't reflect on container after bin/copytocontainer --all

### ISSUE THREAD

**Issue by marcelo011982** [markshust/docker-magento#261]
**Description**
Delete folder from host doesn't reflect on container after bin/copytocontainer --all

**Steps To Reproduce**
1)Delete a folder inside host
2).bin/copytocontainer --all
3)bin/bash
4)the folder still exist on ba

**Expected Result**
The folder remove on container too

**Actual Result**
The folder   exist

**Comment by markshust** [comment]
This is working as expected. The copytocontainer script just copies files/folders over, it's not like an `rsync` command which syncs from host:container
