### ISSUE TITLE
xdebug host.docker.internal remote host config not supported on linux

### ISSUE THREAD

**Issue by carlos-reynosa** [markshust/docker-magento#264]
**Description**
`host.docker.internal` php xdebug configuration value is not supported on Linux:

https://github.com/markshust/docker-magento/blob/1c52befbdb37a02276cb2de9ea6cc511072c9372/images/php/7.3/conf/php.ini#L9

Discussion:

- https://github.com/docker/for-linux/issues/264

My temp solution:

I added `xdebug.remote_connect_back = true`  to the php xdebug configuration to remove the need for a remote_host value. 

It seems that the `host.docker.internal` will be added to Linux soon. This is just  FYI for all. 

**Steps To Reproduce**
1. Setup project with enabled xdebug configuration on a linux host environment. 
2. Run xdebug configuration with break point 

**Expected Result**
Execution stops at break point. 

**Actual Result**
xdebug cannot connect to the remote host and the execution does not stop at the breakpoint.

**Comment by markshust** [comment]
Did you try to uncomment the extra_hosts lines in the docker compose?
https://github.com/markshust/docker-magento/blob/1c52befbdb37a02276cb2de9ea6cc511072c9372/compose/docker-compose.dev.yml#L31

**Comment by carlos-reynosa** [comment]
I did not notice that! Thank you!

**Comment by marcelo011982** [comment]
I've had the same problem:

https://github.com/markshust/docker-magento/issues/246#issuecomment-603222347

I've solved changing some directives on php container.

**Comment by markshust** [comment]
@carlos-reynosa cool, that should definitely resolve that for you. I'll close out this ticket.
