### ISSUE TITLE
 [error] 7#7: *1 directory index of "/etc/nginx/html/" is forbidden

### ISSUE THREAD

**Issue by boris1988** [markshust/docker-magento#265]
**###Description**
main page throw 401 - Forbidden
Physical file (robots.txt) provide 404

**Steps To Reproduce**
1. docker-compose up
But its happen from second time when I run containers

**Expected Result**
HTTP 200 status

**Actual Result**
401 Forbidden, 404 Not found

**Comment by markshust** [comment]
Are you following the Magento install setup instructions? I just ran this install and received no errors, so I'm unable to replicate.
https://github.com/markshust/docker-magento#setup

**Comment by boris1988** [comment]
Hi @markshust 
Same issue again.
1. Run `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.5-p1`
All works

2. Next time when I run `docer-compose up`  I got  403 status
![Screenshot from 2020-05-13 22-35-49](https://user-images.githubusercontent.com/2422927/81856994-3ff03400-956a-11ea-8d80-99727f191bbf.png)

OS: Ubuntu 16.04

**Comment by torhoehn** [comment]
@boris1988 Between `bin/stop` and `bin/start`, did you maybe `git pull` in your `src/` dir? Probably you have removed the `nginx.conf`. So building the image again will solve your problem: https://github.com/markshust/docker-magento/issues/333#issuecomment-720157909
