### ISSUE TITLE
[error] 7#7: *1 directory index of "/etc/nginx/html/" is forbidden

### ISSUE THREAD

**Issue by boris1988** [markshust/docker-magento#268]
**Description**
main page throw 401 - Forbidden
Physical file (robots.txt) provide 404

**Steps To Reproduce**

Run curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.5-p1
All works

Next time when I run docer-compose up I got 403 status
![Screenshot from 2020-05-13 22-35-49](https://user-images.githubusercontent.com/2422927/81978655-8316d980-9634-11ea-9137-77c564abe6e9.png)
OS: Ubuntu 16.04

**Expected Result**
HTTP 200 status

**Actual Result**
401 Forbidden, 404 Not found

**Comment by markshust** [comment]
Can you please stop all running containers, and instead run bin/start? You can’t just use docker compose up, other things are configured in bin/start to get things working right.

**Comment by boris1988** [comment]
thanks
Going to try

**Comment by scorpion2763** [comment]
> Can you please stop all running containers, and instead run bin/start? You can’t just use docker compose up, other things are configured in bin/start to get things working right.

thank you, "bin/start" worked for me
