### ISSUE TITLE
After installation, I keep on getting Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Cache\FrontendInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50

### ISSUE THREAD

**Issue by radhikagiri** [markshust/docker-magento#271]
Below is the stack trace

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Cache\FrontendInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cache', 'Magento\\Framewo...') #3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Framewo...', Array, Array) #4 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dyna in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

Not sure how to solve this issue. Any help?

**Comment by rangerz** [comment]
Just run composer update or install on the root directory.

```
bin/composer install
# or
bin/composer update
```

**Comment by radhikagiri** [comment]
It was PHP version issue. I updated my PHP to the latest version. After that it started working.
Thank you
