### ISSUE TITLE
Unable to see admin control panel

### ISSUE THREAD

**Issue by radhikagiri** [markshust/docker-magento#273]
I would like customise my store items. I tried opening admin console by the url - https://magento2.test/admin/index. But it is giving me 404 error. Any help?

**Comment by rangerz** [comment]
```
bin/magento info:adminuri
```

**Comment by markshust** [comment]
Thanks @rangerz - yes, you'll need to get the admin URL from the CLI tool. It isn't standardized to `/admin` but randomly generated upon install.

**Comment by eduardo-g-silva** [comment]
but what about the password do we need to user in the db or it is setup somewhere else ?

**Comment by rangerz** [comment]
If it's installed by `bin/setup` or `onelinesetup`, its user / password is `john.smith / password123` in [here](https://github.com/markshust/docker-magento/blob/master/compose/bin/setup#L60)

If you want to setup a new admin account, try to use this command
```
php bin/magento admin:user:create \
    --admin-user='new-admin' \
    --admin-password='!admin123!' \
    --admin-email='info@domain.com' \
    --admin-firstname='Jon' \
    --admin-lastname='Doe'
```

Welcome into Magento backend 👍
