### ISSUE TITLE
Not able to get a working installation when running from external disk

### ISSUE THREAD

**Issue by Vout** [markshust/docker-magento#274]
**Description**
For one or another reason it won't run from an external SSD. After various attempts i tried it to run it from my internal harddrive and it ran without issues.

Thing is, i don't have much space left on my Mac Mini internal SSD so i would like to run it from my Samsung T5 external SSD.

**Steps To Reproduce**
1. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
2. bin/download 2.3.5-p1
3. bin/setup tanita.local

**Expected Result**
An working Magento install

**Actual Result**
A redirect to /setup and some errors in the console.

![error](https://reind.nl/mage_1.png)

I also added the volume under the Docker preferences (should already work with the default /Volume i think),

![prefs](https://reind.nl/docker_1.png)

**Comment by markshust** [comment]
Did you try blowing everything away and reinstalling after adding the volume/resource to Docker prefs? Also, need to ensure you remove the volumes and etc. as well. The correct process is:

```
cd {YOUR_PROJECT}
bin/removeall
cd ..
rm -rf {YOUR_PROJECT}
mkdir {YOUR_PROJECT
cd {YOUR_PROJECT}
... then reinstall
```

**Comment by Vout** [comment]
Yep, i tried that already... multiple times.

Could it have something to do with the copy command? I just scrolled through the installation log and the only "thing" i noticed was this message,

`bin/copytocontainer --all
"docker cp" requires exactly 2 arguments.
See 'docker cp --help'.

Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
        docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH`

**Comment by markshust** [comment]
Are you using some kind of alternate bash/shell program? That is definitely the root of your issue.

What happens when you run `bin/copytocontainer --all`?

**Comment by Vout** [comment]
When running the whole procedure from start with default Mac OS terminal,

> Creating tanita_db_1            ... done
> Creating tanita_redis_1         ... done
> Creating tanita_rabbitmq_1      ... done
> Creating tanita_elasticsearch_1 ... done
> Creating tanita_phpfpm_1        ... done
> Creating tanita_app_1           ... done
> Copying all files from host to container...
> "docker cp" requires exactly 2 arguments.
> See 'docker cp --help'.
> 

> Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
> 	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH
> 
> Copy files/folders between a container and the local filesystem
> Completed copying all files from host to container
> Correcting filesystem ownerships...
> Filesystem ownerships corrected.
> Correcting filesystem permissions...
> find: 'var': No such file or directory
> find: 'vendor': No such file or directory
> find: 'pub/static': No such file or directory
> find: 'pub/media': No such file or directory
> find: 'app/etc': No such file or directory
> find: 'var': No such file or directory
> find: 'vendor': No such file or directory
> find: 'pub/static': No such file or directory
> find: 'pub/media': No such file or directory
> find: 'app/etc': No such file or directory
> chmod: cannot access 'bin/magento': No such file or directory
> Filesystem permissions corrected.
> chmod: cannot access 'bin/magento': No such file or directory

I have ZSH / Hyper installed but when going to the Terminal settings it just has the setting `Default login shell`.

Going to take some sleep first... struggling with it all evening and still couldn't get it to run from the external SSD. Strange thing is, i did the oneline installer on the internal drive and it worked immediately.

**Comment by Vout** [comment]
> Are you using some kind of alternate bash/shell program? That is definitely the root of your issue.

ZSH is default since Catalina if i am correct, i'll try tomorrow switching back to bash (just found this, https://www.howtogeek.com/444596/how-to-change-the-default-shell-to-bash-in-macos-catalina/)

However, that still doesn't explain why it does work on local drives and it doesn't on external drives.

**Comment by Vout** [comment]
Small update... fixed it.

Thing is that you can't use spaces in the name of your external drive, renamed the external drive to just "SSD" and it started to work.

Maybe something to mention in the docs?
