### ISSUE TITLE
There are no commands defined in the "app:config" namespace.

### ISSUE THREAD

**Issue by Vout** [markshust/docker-magento#275]
**Description**
When running the "Existing Projects" procedure everything works fine until the part where i need to run `bin/magento app:config:import`

**Actual Result**

> There are no commands defined in the "app:config" namespace.  
>                                                                 
>   Did you mean one of these?                                    
>       setup:config                                              
>       setup:store-config 

I found an [older issue](https://github.com/markshust/docker-magento/issues/248) (just closed 2 days ago) where the possibility of a missing env.php could be the case however i have that in place. Found one possible issue where the db location was `127.0.0.1:3306` in the original file and i noticed that when doing a fresh install this is just `db` so i changed it but without any luck.

Magento version i am trying to run in the docker container is 2.3.0, could that be the issue?

My db part inside the env.php looks like this

> 'db' => [
>         'table_prefix' => '',
>         'connection' => [
>             'default' => [
>                 'host' => 'db',
>                 'dbname' => 'magento',
>                 'username' => 'magento',
>                 'password' => 'magento',
>                 'model' => 'mysql4',
>                 'engine' => 'innodb',
>                 'initStatements' => 'SET NAMES utf8;',
>                 'active' => '1',
>                 'driver_options' => [
>                     1014 => false
>                 ]
>             ]
>         ]
>     ],

**Comment by bonanzadigger** [comment]
I have the same error...is here an answer possible, or do you just close unresolved issus?

**Comment by markshust** [comment]
@bonanzadigger this error almost always occurs when the database connection info is incorrect.
