### ISSUE TITLE
Installation fails saying MySQL tables do not exist

### ISSUE THREAD

**Issue by ae-smith** [markshust/docker-magento#276]
**Description**
I'm running into issues getting the database to install during the process.  Initially with the one-step install, I was able to get it working, and then again later after making some module extensions and sharing my repo with a teammate.  But now, running bin/setup always results in mysql errors. 

**Steps To Reproduce**
1. cd into a folder with some existing magento code. 
2. bin/setup domain.test

**Expected Result**
You can now access your site at ____.  With all configurations properly set.

**Actual Result**
...
Enabled developer mode.

In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_con
  fig_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config
  _data` AS `main_table`
...

Any ideas what could cause this?  Any other thoughts on how to collaborate without running into docker config errors?

**Comment by rangerz** [comment]
Is your port 3306 available? 
This looks like your db docker did not start successfully.
Please check the command `bin/status` for those docker status.

**Comment by thoiberg** [comment]
I'm also getting this same problem. I rebuilt my docker environment from scratch on Friday and it worked fine then, but when I try today I'm getting:
```
[Progress: 2 / 989]
Enabling Maintenance Mode...

In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_con
  fig_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config
  _data` AS `main_table`


In Mysql.php line 91:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_con
  fig_data' doesn't exist
```

I've run `docker system prune -all` and `docker volume prune` and rerunning the setup, but it's still not working.

Can reproduce with the following steps:
1. clone my repo: `git clone git@github.com:komoju/komoju-magento.git`
2. download Magento 2.3.4: `bin/download 2.3.4`
3. Run setup: `bin/setup magento2.test`

Once it gets up to the point of enabling maintenance mode I get the errors about the table missing.

Afterwards jumping into mysql on the db container shows none of the tables were created:
```
mysql> use magento;
Database changed
mysql> show tables;
Empty set (0.00 sec)
```

Currently using Docker version 2.3.1.0 (45408) on the edge channel.

**Comment by awedev** [comment]
Same here

**Comment by awedev** [comment]
Looks like the issue is related to installation directory, it has to be home directory (~).

**Comment by ae-smith** [comment]
Mine is in a home subdirectory, e.g. ~/code/[project]

**Comment by awedev** [comment]
> Mine is in a home subdirectory, e.g. ~/code/[project]
> […](#)

Try home directory

**Comment by thoiberg** [comment]
Ok, I think I found a work around to getting it functioning. I've found that when I remove all volumes, images and containers from my system with `docker system prune --all` and `docker volume prune` and start the process again I get a different error when install the database schema:
```
[Progress: 108 / 989]
Module 'Magento_InventoryCatalog':

Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryCatalogApi\Api\DefaultStockProviderInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...')
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'defaultStockPro...', 'Magento\\Invento...')
#3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Invento...', Array, Array)
#4 /var/www/html/vendor/magento/fra in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```
This doesn't complete the install, but it does create all the tables in the database.


Once the setup process is complete if I flush the redis cache with `bin/redis redis-cli flushall`, and jump into the magento container and rerun the setup command it works:
```
bin/bash
# now in the magento container
app@e8749b552137:~/html$ bin/magento setup:install \
  --db-host=db \
  --db-name=magento \
  --db-user=magento \
  --db-password=magento \
  --base-url=https://$BASE_URL/ \
  --admin-firstname=John \
  --admin-lastname=Smith \
  --admin-email=john.smith@gmail.com \
  --admin-user=john.smith \
  --admin-password=password123 \
  --language=en_US \
  --currency=JPY \
  --timezone=Asia/Tokyo \
  --amqp-host=rabbitmq \
  --amqp-port=5672 \
  --amqp-user=guest \
  --amqp-password=guest \
  --amqp-virtualhost=/ \
  --use-rewrites=1
```

I've just grabbed the setup command from the [setup script](https://github.com/markshust/docker-magento/blob/94221e33f93ea4b009458f547287df2d09186fba/compose/bin/setup#L52) and tweaked it for my particular install.

But if I destroy the containers and volumes and run setup again I end up in the same position I was in earlier, where the setup fails because there are no tables in the database. 

I'm guessing that something's being persisted somewhere that's not being removed with `bin/removeall` but I'm not really sure 🤷

**Comment by awedev** [comment]
Sharing logs here, the setup for setup db is missing if you install it other than home directory.
Forcing reinstall of composer deps to ensure perms & reqs...
Changed current directory to /var/www/.composer
    1/3:	http://repo.packagist.org/p/provider-latest$xxxx.json
    2/3:	http://repo.packagist.org/p/provider-2020-04$xxxx.json
    3/3:	http://repo.packagist.org/p/provider-2019$xxxx.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Using version ^0.3.10 for hirak/prestissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility,../../codeception,../../magento/magento-coding-standard
Starting Magento installation:
File permissions check...
[Progress: 1 / 993]
Required extensions check...
[Progress: 2 / 993]
Enabling Maintenance Mode...

In Mysql.php line 110:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_con  
  fig_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config  
  _data` AS `main_table`

**Comment by LetsTalkMedia** [comment]
same here

**Comment by markshust** [comment]
> **Steps To Reproduce**
> 
> 1. cd into a folder with some existing magento code.
> 2. bin/setup domain.test

why are you running `bin/setup` on an existing codebase?

**Comment by thoiberg** [comment]
@markshust In my case it's because a colleague that was also working on the project needed to be able to test the extension we were building locally, so they needed to get their dev environment working, including downloading Magento, starting the docker containers and configuring the local domain.

Is there a different way to do this than running `bin/setup`?

**Comment by markshust** [comment]
yes, for existing projects you don't want to run bin/setup. just import the SQL instead. 

see instructions at https://github.com/markshust/docker-magento#existing-projects
