### ISSUE TITLE
How to create second project with docker?

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#279]
How can I create a second third project in docker? For example magento2-2.test, magento2-3.test, magento2-4.test...? Need to duplicate docker? What files do I need to fix in order to run sites separately?
Thank!

**Comment by markshust** [comment]
Hi @artmouse - I noticed this was closed. I don't have this documented anyplace (I need to do that!), however the video tutorial to do this is at https://courses.m.academy/courses/setup-magento-2-development-environment-docker/lectures/14780970
