### ISSUE TITLE
Cannot start service phpfpm

### ISSUE THREAD

**Issue by Mausina** [markshust/docker-magento#280]
**Description**
I`m try install docker .. But phpfmp has error..
`Removing magento_phpfpm_1
magento_elasticsearch_1 is up-to-date
magento_db_1 is up-to-date
magento_redis_1 is up-to-date
Recreating 45f0f2f5d67b_magento_phpfpm_1 ...
Recreating 45f0f2f5d67b_magento_phpfpm_1 ... error                                                                                                                                                                                           
ERROR: for 45f0f2f5d67b_magento_phpfpm_1  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/c/WorkDirectori/Magento/src/composer.json\\\" to rootfs \\\"/var/lib/docker/overlay2/d486f6849c9d719f34546b4ce207c23007c6ecd1f9cafe0ed7c7561ac7c1e37a/merged\\\" at \\\"/var/lib/docker/overlay2/d486f6849c9d719f34546b4ce207c23007c6ecd1f9cafe0ed7c7561ac7c1e37a/merged/var/www/html/composer.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for phpfpm  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/c/WorkDirectori/Magento/src/composer.json\\\" to rootfs \\\"/var/lib/docker/overlay2/d486f6849c9d719f34546b4ce207c23007c6ecd1f9cafe0ed7c7561ac7c1e37a/merged\\\" at \\\"/var/lib/docker/overlay2/d486f6849c9d719f34546b4ce207c23007c6ecd1f9cafe0ed7c7561ac7c1e37a/merged/var/www/html/composer.json\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Steps To Reproduce**
1. Windows 10
2. WSL 1(Ubuntu 18.04)
3.bin\setup

**Comment by markshust** [comment]
@Mausina can you check to see if `/mnt/c/WorkDirectori/` has been added under Docker preferences as a file sharing resource?

![Screen Shot 2020-06-30 at 11 07 33 AM](https://user-images.githubusercontent.com/437029/86143021-e912cf80-bac1-11ea-8be9-a92169f5713d.png)

**Comment by Mausina** [comment]
> @Mausina can you check to see if `/mnt/c/WorkDirectori/` has been added under Docker preferences as a file sharing resource?
> 
> ![Screen Shot 2020-06-30 at 11 07 33 AM](https://user-images.githubusercontent.com/437029/86143021-e912cf80-bac1-11ea-8be9-a92169f5713d.png)

I am use WSL 1 (Ubuntu 18.04) .. I add thiw url http://prntscr.com/t9l0w4

**Comment by markshust** [comment]
ok, that looks correct

this is the actual error:

```\"/var/lib/docker/overlay2/d486f6849c9d719f34546b4ce207c23007c6ecd1f9cafe0ed7c7561ac7c1e37a/merged/var/www/html/composer.json\" caused \"not a directory\""": unknown:```

so it is trying to mount `/var/www/html/composer.json`, but it's expecting a directory for some reason. please also check the `docker-compose.dev.yml` file volume mount lines to ensure all of those files exist? if some of them don't exist, you'll get a similar error.

**Comment by Mausina** [comment]
I check all files in src directory

**Comment by Mausina** [comment]
I solved this problem ..

If use Windows.. You need start project from PowerShell
Like this 

start - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --remove-orphans
stop - docker-compose -f docker-compose.yml -f docker-compose.dev.yml stop
cli  - docker-compose exec phpfpm "<commannd>"

**Comment by markshust** [comment]
@Mausina how were you starting the containers before? the lines above are the only recommend way to start the containers and are the same as:

- `bin/start`
- `bin/stop`
- `bin/cli`

https://github.com/markshust/docker-magento/tree/master/compose/bin
