### ISSUE TITLE
502 Bad Gateway after upgrade to 2.3.5

### ISSUE THREAD

**Issue by magento2dev** [markshust/docker-magento#282]
Hello,

I'm getting a 502 Bad Gateway error from nginx after upgrade Magento to the latest version 2.3.5 from the 2.3.4. I'm using markoshust/magento-nginx:1.13-8 and markoshust/magento-php:7.3-fpm-6.
Where can I find the nginx error file ?

Thanks !

**Comment by markshust** [comment]
You'll probably want to update your image to `markoshust/magento-nginx:1.18-2` if possible.

I can confirm all of the current images run correctly on 2.3.5, so it could be a configuration issue. Unless I can replicate, I cannot fix.

Here is a video lesson on customizing Nginx configuration, which could be helpful? https://courses.m.academy/courses/setup-magento-2-development-environment-docker/lectures/9064349

You can also connect to the Nginx container with:
`docker-compose exec app bash`

and the error log is at:
`/var/log/nginx/error.log`
