### ISSUE TITLE
Increase max_allowed_packet to 64M for proper running of data migration tool

### ISSUE THREAD

**Issue by younkim** [markshust/docker-magento#285]
**Description**
I'm getting the error "To fix it set server name by environment variable PHP_IDE_CONFIG and restart debug session." in the debug window of phpstorm. Docker-Compose setup or the guide seems to be missing something to successfully accept incoming remote debugging connections.  

**Steps To Reproduce**
1. Follow all "Xdebug & PHPStorm" steps on phpstorm 2020.1. 
2. Remote debugging fails.

**Expected Result**
Xdebug should stop at the breakpoint of `src/pub/index.php`. e.g. at `$bootstrap->run($app);`.

**Actual Result**
1. Window pops up when loading the homepage of magento2.test. None of the fields are editable. Trying different options here does not seem to work.
![image](https://user-images.githubusercontent.com/8534941/88357781-7ef4ef80-cd3a-11ea-8d61-f2dbd316636c.png)

2. Then, this error
![image](https://user-images.githubusercontent.com/8534941/88357754-6258b780-cd3a-11ea-8f8f-9731da493d4e.png)

**Comment by younkim** [comment]
I added a env variable, `PHP_IDE_CONFIG=serverName=magento2.test` to `phpfpm`, and that seems to have resolved the issue. I had tried to add it to the nginx container (doh), and obviously.

Off topic, but I also set `max_allowed_packet=64M` to allow the Magento data migration tool to run. The default setting wasn't sufficient.

**Comment by markshust** [comment]
Hi @younkim. I apologize for not replying, I have been on vacation for a while. The `PHP_IDE_CONFIG` var should not need to be set for Xdebug to work. I have tested this many times and it all works out of the box as long as the other config is setup in PHPStorm.

As far as `max_allowed_packets`, I have reopened this ticket about this. I have noticed this a long time ago. I will make an update so that this config is set out of the box so we don't need to make this change. All of the built-in Magento code should be able to be worked with out of the box instead of needing to make one-off config changes 😄

**Comment by younkim** [comment]
@markshust I tried setting xdebug a few times over on my Mac and couldn't get it to work without the env var for some reason. But it's working without issues now. Thanks for offering this Docker setup!

**Comment by piotrkwiecinski** [comment]
`max_allowed_packets` can also be increased in the `docker-compose.yml`

```
  db:
    image: percona:5.7
    # line to change a packet size:
    command: --max_allowed_packet=128M 
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
```

Before:

```
MySQL [magento]> SHOW VARIABLES like '%max_allowed_packet%';
+--------------------------+------------+
| Variable_name            | Value      |
+--------------------------+------------+
| max_allowed_packet       | 4194304    |
```

After:

```
MySQL [magento]> SHOW VARIABLES like '%max_allowed_packet%';
+--------------------------+------------+
| Variable_name            | Value      |
+--------------------------+------------+
| max_allowed_packet       | 134217728  |

```

**Comment by markshust** [comment]
@piotrkwiecinski thanks for this, I'll try documenting this someplace

**Comment by piotrkwiecinski** [comment]
@markshust we could also add it to the default docker-compose.yml

**Comment by asannikov** [comment]
@younkim 
> I added a env variable, `PHP_IDE_CONFIG=serverName=magento2.test` to `phpfpm`, and that seems to have resolved the issue. I had tried to add it to the nginx container (doh), and obviously, that wasn't right.

have the same problem. Unfortunately, it does not still work for me too, even with PHP_IDE_CONFIG. How did you do that? just `export PHP_IDE_CONFIG=serverName=magento2.test?`

**Comment by younkim** [comment]
@asannikov that's exactly how I did it under the `phpfpm` service (sorry for getting back late).
