### ISSUE TITLE
How to create one rootCA.pem for many sites?

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#287]
I have generated rootCA.pem. Maybe copy it to /root/.local/share/mkcert/rootCA.pem. But how? And at what point?

**Comment by markshust** [comment]
The `bin/setup-ssl` script accepts multiple arguments as noted in the readme:

```
bin/setup-ssl: Generate an SSL certificate for one or more domains. Ex. bin/setup-ssl magento2.test magento3.test
```
