### ISSUE TITLE
Problem with the installation.

### ISSUE THREAD

**Issue by chrom** [markshust/docker-magento#289]
**Description**
Problem with the installation.
OS: macOS 10.15.5

**Steps To Reproduce**
1. Run: `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test with-samples-2.4.0`

**Expected Result**
Installed and running magento app

**Actual Result**
`ERROR: for 2950fe6aa73e_docker_phpfpm_1  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/user/projects/php/src/composer.lock\\\" to rootfs \\\"/var/lib/docker/overlay2/a4e61c29eec918e502f90eab165b96ca23ef7ee71d7d8061ce3ed0babf4eaa24/merged\\\" at \\\"/var/lib/docker/overlay2/a4e61c29eec918e502f90eab165b96ca23ef7ee71d7d8061ce3ed0babf4eaa24/merged/var/www/html/composer.lock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

```
ERROR: for phpfpm  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/user/projects/php/src/composer.lock\\\" to rootfs \\\"/var/lib/docker/overlay2/a4e61c29eec918e502f90eab165b96ca23ef7ee71d7d8061ce3ed0babf4eaa24/merged\\\" at \\\"/var/lib/docker/overlay2/a4e61c29eec918e502f90eab165b96ca23ef7ee71d7d8061ce3ed0babf4eaa24/merged/var/www/html/composer.lock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by markshust** [comment]
Looks like you are missing a composer.lock file from your install. This line is defined in the docker-compose.dev.yml file. You'll need to either comment out the line referencing that file or add that to your src/ directory.
