### ISSUE TITLE
Generated Directory is Empty in src folder

### ISSUE THREAD

**Issue by shuvoenr** [markshust/docker-magento#294]
**Description**
On generated directory no files found. I am not sure this is a issue or not but i face this. But without the generated directory folder class link not found

**Steps To Reproduce**
1. setup:di:compile

**Expected Result**
should be in generated directory

**Actual Result**
No file on generated directory

**Comment by piotrkwiecinski** [comment]
Hi @shuvoenr,
are you referring to the generated directory on your local src directory or the one on the container?
Does running `bin/cli ls generated` show any results?

Generated directory is not synced with local by default and is only generated on the container.

In your `docker-compose.dev.yml` you would have to add:
```
- ./src/app/generated:/var/www/html/app/generated:delegated
```
Somewhere arould like 12. Here how it would look like in the file: https://pastebin.com/QK057MUa

I hope that helps.

**Comment by shuvoenr** [comment]
Thanks @piotrkwiecinski 

Firstly bin/cli ls generated showing the two folder code & metadata

And thanks your docker composer hint working well.

I in my case the code work well for 

` - ./src/generated:/var/www/html/generated:delegated`

So working fully well but BTW seems slow while compile.

Later after creating issue i found command 

`bin/copyfromcontainer generated`

works for me and also for other files like pub directory.

this seems faster. first compile then copy command.
