### ISSUE TITLE
Getting issuw while installing at ubuntu 20.04

### ISSUE THREAD

**Issue by devamitbera** [markshust/docker-magento#297]
**Description**
Getting an issue while installing docker. error 
```
devamitbera@devamitbera-VivoBook-ASUSLaptop-X412FJC-X412FJ:~$ docker-compose -f docker/docker-compose.dev.yml up
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker/docker-compose.dev.yml'
devamitbera@devamitbera-VivoBook-ASUSLaptop-X412FJC-X412FJ:~$ curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento22.test 2.4.0
ERROR: No container found for phpfpm_1
(23) Failed writing body
```

**Steps To Reproduce**
1.  `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento22.test 2.4.0`

**Expected Result**

 Docker  should be run

**Actual Result**

```
ERROR: No container found for phpfpm_1
(23) Failed writing body
```

![Screenshot from 2020-08-09 15-16-17](https://user-images.githubusercontent.com/6008488/89729453-78ad8580-da53-11ea-8282-87de1ba130d2.png)

**Comment by paugnu** [comment]
Hi @devamitbera, I've just installed the stack in Ubuntu 20.04 and everything works fine.

Check the way you installed docker in your computer. You should follow this:
* https://docs.docker.com/engine/install/ubuntu/

And then this:
* https://docs.docker.com/engine/install/linux-postinstall/

Installing docker that way should be enough to get the script working.
