### ISSUE TITLE
Sending mail not working 

### ISSUE THREAD

**Issue by markosege** [markshust/docker-magento#298]
Try to send mail from my local store when customer create new account or reset password etc.. 

**Steps To Reproduce**

1. Enable Require Emails Confirmation on customer configuration from the backend

2. Create a new account 

**Expected Result**
A mail should get from the local Magento store 

**Actual Result**
Mail not sending from the store.

**Comment by markshust** [comment]
Mail is sent to mailhog -- you can view it at https://localhost:8025

**Comment by markosege** [comment]
is it possible to send mail to real account like gmail or yahoo

**Comment by markshust** [comment]
Yes, you can use a module such as this one https://github.com/mageplaza/magento-2-smtp
