### ISSUE TITLE
configuring certbot for letsencrypt ssl

### ISSUE THREAD

**Issue by jeffjarratt** [markshust/docker-magento#299]
Hello,

I'm trying to configure autorenewing ssl certs with Letsencrypt using certbot. I'm using the following guide: https://fabiomolinar.com/pt/blog/2019/01/26/using-lets-encrypt-and-certbot-nginx-enable-connections-over-https/

I'm having trouble at this part, where I'm supposed to add this to my nginx config:
![image](https://user-images.githubusercontent.com/18272844/90845190-36295a00-e32b-11ea-866a-b88316b4d1aa.png)
I see in our nginx.conf.sample file, the listen portion is commented out. I have tried just adding this to the end of the file:

location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

But certbot still fails to validate the domain:
![image](https://user-images.githubusercontent.com/18272844/90845443-b5b72900-e32b-11ea-92f8-0767d71245f0.png)

My volume configs are as follows:
![image](https://user-images.githubusercontent.com/18272844/90845565-ebf4a880-e32b-11ea-8918-d586638d22f7.png)
![image](https://user-images.githubusercontent.com/18272844/90845587-f616a700-e32b-11ea-86df-62ffb6bd4608.png)

any idea what may be causing this?

**Comment by markshust** [comment]
Is the domain you are trying to setup publicly accessible on the web? Lets Encrypt will only work on public domains (not private or local domains).
