### ISSUE TITLE
Magento 2.4 Elastic Search

### ISSUE THREAD

**Issue by magento2dev** [markshust/docker-magento#308]
Hello,

I upgraded my Magento to 2.4 but now when I am trying to execute the setup:upgrade command I am getting the following error :
`Could not validate a connection to Elasticsearch. No alive nodes found in your cluster`

The elastic search server seems to be up when I am doing curl elasticsearch:9200 from the docker I am getting this answer :
`{
  "name" : "aa2c7dda9a5c",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "ByV7w1tAT_O8M0uz5MVlHg",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }`

Thanks for your help !

**Comment by piotrkwiecinski** [comment]
Hi @magento2dev 

Are you able to run:
```
bin/n98-magerun2 config:store:get *elasticsearch*
```
To see what value you get if any?

Try running:

```
bin/n98-magerun2 config:store:set catalog/search/elasticsearch7_server_hostname elasticsearch
```

When you run a setup script it's added during installation process: https://github.com/markshust/docker-magento/blob/master/compose/bin/setup#L70-L71

**Comment by magento2dev** [comment]
Hi @piotrkwiecinski it solves my issue !
Thanks !

**Comment by fernandezl** [comment]
Hello,
I'm facing the same issue. I ran the commands, but :
```
bin/n98-magerun2` config:store:set catalog/search/elasticsearch7_server_hostname elasticsearch
catalog/search/elasticsearch7_server_hostname => elasticsearch
bin/n98-magerun2 config:store:get *elasticsearch*

+-----------------------------------------------+---------+----------+---------------+
| Path                                          | Scope   | Scope-ID | Value         |
+-----------------------------------------------+---------+----------+---------------+
| catalog/search/elasticsearch7_server_hostname | default | 0        | elasticsearch |
+-----------------------------------------------+---------+----------+---------------+
```

Thanks for the help

**Comment by walkwizus** [comment]
hi,

If you are using Smile_ElasticSuite you should follow this steps:

https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

Example:

`bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/servers elasticsearch:9200
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_https_mode 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_http_auth 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_user ""
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_pwd ""
bin/magento app:config:import`

**Comment by markshust** [comment]
Thanks for info, I'll try to add this all to the documentation/readme.

**Comment by eduardo-g-silva** [comment]
> Hello,
> I'm facing the same issue. I ran the commands, but :
> 
> ```
> bin/n98-magerun2` config:store:set catalog/search/elasticsearch7_server_hostname elasticsearch
> catalog/search/elasticsearch7_server_hostname => elasticsearch
> bin/n98-magerun2 config:store:get *elasticsearch*
> 
> +-----------------------------------------------+---------+----------+---------------+
> | Path                                          | Scope   | Scope-ID | Value         |
> +-----------------------------------------------+---------+----------+---------------+
> | catalog/search/elasticsearch7_server_hostname | default | 0        | elasticsearch |
> +-----------------------------------------------+---------+----------+---------------+
> ```
> 
> Thanks for the help

Why you add => ? it should be directly the value

**Comment by magento2dev** [comment]
Hello @eduardo-g-silva,

If it can helps you I have this in my env.php 

`'search' => [
                    'elasticsearch5_server_hostname' => 'elasticsearch',
                    'elasticsearch5_server_port' => '9200',
                    'elasticsearch5_index_prefix' => 'magento2',
                    'elasticsearch5_enable_auth' => '0',
                    'elasticsearch5_server_timeout' => '15',
                    'elasticsearch6_server_hostname' => 'elasticsearch',
                    'elasticsearch6_server_port' => '9200',
                    'elasticsearch6_index_prefix' => 'magento2',
                    'elasticsearch6_enable_auth' => '0',
                    'elasticsearch6_server_timeout' => '15',
                    'elasticsearch7_server_hostname' => 'elasticsearch',
                    'elasticsearch7_server_port' => '9200',
                    'elasticsearch7_index_prefix' => 'magento2',
                    'elasticsearch7_enable_auth' => '0',
                    'elasticsearch7_server_timeout' => '15'
],`

**Comment by markshust** [comment]
FYI this was resolved some while ago. The script waits until Elasticsearch is ready before continuing install...

```
...
Starting magento_phpfpm_1        ... done
Starting magento_app_1           ... done
Waiting for connection to Elasticsearch...
..Starting Magento installation:
File permissions check...
[Progress: 1 / 1314]
...
```

**Comment by hans2103** [comment]
update for ZSH users

```
➜  example git:(master) bin/n98-magerun2 config:store:get *elasticsearch*
zsh: no matches found: *elasticsearch*
➜  example git:(master) bin/n98-magerun2 config:store:get %elasticsearch%
+----------------------------------------------------+---------+----------+-----------------------------+
| Path                                               | Scope   | Scope-ID | Value                       |
+----------------------------------------------------+---------+----------+-----------------------------+
| catalog/search/elasticsearch7_enable_auth          | default | 0        | 0                           |
| catalog/search/elasticsearch7_index_prefix         | default | 0        | magento2                    |
| catalog/search/elasticsearch7_minimum_should_match | default | 0        | NULL (NULL/"unknown" value) |
| catalog/search/elasticsearch7_server_hostname      | default | 0        | elasticsearch               |
| catalog/search/elasticsearch7_server_port          | default | 0        | 9200                        |
| catalog/search/elasticsearch7_server_timeout       | default | 0        | 15                          |
+----------------------------------------------------+---------+----------+-----------------------------+
➜  example git:(master) 

```
