### ISSUE TITLE
Failed to start docker for missing volume files on bin/start (Ubuntu/Linux)

### ISSUE THREAD

**Issue by ennostuurman** [markshust/docker-magento#309]
**Description**

OS: 18.04.5 LTS 
Docker version 19.03.12
docker-compose version 1.24.0

When trying to start Docker containers with bin/start, the Docker containers don't start because of "missing volume files".
The files are there, and starting containers with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --remove-orphans` works fine.

Looks like that the additional check for existing folders in bin/start "Check if volume files exist to avoid creating an empty folder" causes the issue. The parseYaml function seems to remove a character in the volume paths: see below console output **./src/app/et:** instead of **./src/app/etc/** .

Console output

```./src/app/cod: No such file or directory
./src/app/desig: No such file or directory
./src/app/et: No such file or directory
./src/composer.jso: No such file or directory
./src/composer.loc: No such file or directory
./src/nginx.conf.sampl: No such file or directory
Failed to start docker for missing volume files
```

**Steps To Reproduce**
1. cd into the ~/Sites/magento2 folder
2. run bin/start

**Expected Result**
All Docker containers are started

**Actual Result**
Docker container don't start. Instead getting the error message "Failed to start docker for missing volume files"

**Comment by piotrkwiecinski** [comment]
Hi @ennostuurman,
would you be able to try: https://github.com/piotrkwiecinski/docker-magento/tree/scripts-improvements I've started reworking bash scripts. It includes some changes to the `bin/start`.

I'm on ubuntu 20.04 and I'm not able to replicate that problem.

Would you be able to provide all commands that you run before?

I'll try to setup a 18.04 on the VM to see if I can replicate it.
How did you set up your envirnoment? Have you used the one line setup script?

**Comment by piotrkwiecinski** [comment]
Ok I was able to replicate it on the 18.04 VM. I'm going to work on a fix.

**Comment by UrielHernandezR** [comment]
Hi @piotrkwiecinski  I have the same problem today when I tried to created a new environment. 
My Magento is 2.4.5-p1 version and I work with a MAC OS ventura M2.

`bin/start
./src/grunt-config.json.sample: No such file or directory
./src/Gruntfile.js.sample: No such file or directory
./src/dev/tools/grunt/configs: No such file or directory
./src/nginx.conf.sample: No such file or directory
./src/package.json.sample: No such file or directory
Failed to start docker for missing volume files`

**Comment by Jazyac** [comment]
@UrielHernandezR  were you able to solve your issue? I am getting this error as well. I have done the steps in https://github.com/markshust/docker-magento#misc-info to possibly debug it, but no luck.
Thanks

**Comment by UrielHernandezR** [comment]
Hi @Jazyac yes, my problem basically was the template i had downloaded was to the 2.4.6 version and my current project is 2.4.5-p1. I only downloaded the correct template  with this command  `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- my-domain-local.test 2.4.5-p1`
