### ISSUE TITLE
Introduce magento.env file to allow overriding magento install parameters

### ISSUE THREAD

**Issue by piotrkwiecinski** [markshust/docker-magento#312]
Currently admin user, admin front name, currency and locale are hardcoded in the `bin/setup` script.

Add support to load above values from `env/magento.env` file with fallback to previously hardcoded defaults.

![image](https://user-images.githubusercontent.com/2151333/92644140-c7607080-f2da-11ea-8a68-3c92e1ddf3d8.png)

**Comment by rangerz** [comment]
In my option, If these values are only used by `bin/setup`, they don’t have to move to `env/magento.env`

**Comment by markshust** [comment]
Just curious, how often would this be used, and when?

**Comment by rangerz** [comment]
I think `magento.env` is a good idea. for the m2 settings with custom and different m2 versions management
Except basic setting for `setup:install`
Magento version can be `bin/download` default version and help `bin/setup` for backward compatible with Magento 2.3 and 2.4.

For example: 
in `bin/setup` for `bin\magento setup:install` is not support the options
```
  --search-engine=elasticsearch7 \
  --elasticsearch-host=elasticsearch \
```

**Comment by piotrkwiecinski** [comment]
Another argument to add the magento.env is that it would allow to set locale other than en_US, login details if you don't want to be john smith anymore :).
