### ISSUE TITLE
Fatal error: Uncaught Exception: Warning: Declaration of Magefan\Blog\Model\ImageUploader

### ISSUE THREAD

**Issue by dfrankes** [markshust/docker-magento#313]
**Description**
Fatal error: Uncaught Exception: Warning: Declaration of Magefan\Blog\Model\ImageUploader

**System**
OS: macOS Catalina version 10.15.6
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.26.2, build eefe0d31

**Steps To Reproduce**
1. Install new project with command 
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.local 2.4.0`

**Expected Result**
open https://magento.local redirects to /setup

**Actual Result**
Error on the setup page after opening the url (redirects to /setup)

`
Fatal error: Uncaught Exception: Warning: Declaration of Magefan\Blog\Model\ImageUploader::moveFileFromTmp($imageName) should be compatible with Magento\Catalog\Model\ImageUploader::moveFileFromTmp($imageName, $returnRelativePath = false) in /var/www/html/app/code/Magefan/Blog/Model/ImageUploader.php on line 67 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 /var/www/html/app/code/Magefan/Blog/Model/ImageUploader.php(16): Magento\Framework\App\ErrorHandler->handler(2, 'Declaration of ...', '/var/www/html/a...', 67, Array) #1 /var/www/html/vendor/composer/ClassLoader.php(444): include('/var/www/html/a...') #2 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...') #3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magefan\\Blog\\Mo...') #4 [internal function]: spl_autoload_call('Magefan\\Blog\\Mo...') #5 /var/www/html/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists('Magefan\\Blog\\Mo...') #6 /var/ in /var/www/html/vendor/magento/framework/App/ErrorHandler.php on line 61`

**Comment by piotrkwiecinski** [comment]
@dfrankes it seems like it's a problem with the Magefan\Blog module compatibility with Magento 2.4.0 not with the installer.
I would suggest upgrading module to the latest version before attempting installation of m 2.4.

**Comment by dfrankes** [comment]
@piotrkwiecinski This is the first time using this installer, i have not added any modules to Magento, the only thing i did was run the new product command.

**Comment by dfrankes** [comment]
I did the install progress again and seems to be working fine now.
