### ISSUE TITLE
403 on https://magento2.test/setup/index.php/navigation when logging in initially

### ISSUE THREAD

**Issue by mikemainguy** [markshust/docker-magento#321]
**Steps To Reproduce**

1. Follow instructions to set up on mac.  
2. userid/password fails on initial setup
3. Continue setup.
4. update auth.json to have credentials
5. bin/composer update
6. bin/composer install
7. navigate to https://magento2.test

 

**Expected Result**
Some sort of setup screen

**Actual Result**
blank screen.  Looking at network activity, seems like a call to https://magento2.test/setup/index.php/navigation is returning a 403 (which might make sense because I was given no opportunity to log on).

**Comment by rangerz** [comment]
@mikemainguy What's the instructions for setup on mac ?

**Comment by mikemainguy** [comment]
> @mikemainguy What's the instructions for setup on mac ?

used this curlbash https://github.com/markshust/docker-magento#setup 

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.4.0

**Comment by markshust** [comment]
I cannot replicate using the automated one line setup script.

**Comment by mikemainguy** [comment]
OK, I see the problem.  when I originally set up, I had a bad character in the copy/paste for password.  it gave an error at the time for the repo, but continued so it loooked like maybe it was recoverable by updating in config and then running  update...it does not recover in that case.
