### ISSUE TITLE
Magento backward compatible

### ISSUE THREAD

**Issue by rangerz** [markshust/docker-magento#322]
Currently installing a new magento environment is only support 2.4.0 above

### 1. Backward compatible to which version ? 2.3 ?
Because `bin/download` can download a lot of version of magento, I think this project should maintain some logic for the differences with multiple magento versions.

### 2. `bin/magento setup:install` issue
For Magento 2.4 needs to add `--search-engine=elasticsearch7  --elasticsearch-host=elasticsearc` for ES setting
For Magento 2.3.5-p2 can add below commands after `setup:install` finished
```
bin/clinotty bin/magento config:set catalog/search/engine elasticsearch7
bin/clinotty bin/magento config:set catalog/search/elasticsearch7_server_hostname elasticsearch
```
### Ideal Logic
```
vercmp() {
    ver1=$1 ver2=$3 cond=$2

    IFS=. v1_arr=($ver1) v2_arr=($ver2)
    v1=$((v1_arr[0] * 10000 + v1_arr[1] * 100 + v1_arr[2]))
    v2=$((v2_arr[0] * 10000 + v2_arr[1] * 100 + v2_arr[2]))
    diff=$((v2 - v1))
    [[ $cond = '='  ]] && ((diff == 0)) && return 0
    [[ $cond = '!=' ]] && ((diff != 0)) && return 0
    [[ $cond = '<'  ]] && ((diff >  0)) && return 0
    [[ $cond = '<=' ]] && ((diff >= 0)) && return 0
    [[ $cond = '>'  ]] && ((diff <  0)) && return 0
    [[ $cond = '>=' ]] && ((diff <= 0)) && return 0
    return 1
}

if vercmp $M2_VER ">=" 2.4.0; then
  $OPTIONS="\
    --search-engine=elasticsearch7 \
    --elasticsearch-host=elasticsearch"
fi

bin/clinotty bin/magento setup:install \
   ... $(echo $OPTIONS)

if vercmp $M2_VER "<" 2.4.0; then
  bin/clinotty bin/magento config:set catalog/search/engine elasticsearch7
  bin/clinotty bin/magento config:set catalog/search/elasticsearch7_server_hostname elasticsearch
fi
```

### 3. `docekr-compose.yml` issue
This need to provide correct and compatible service version for PHP, elasticsearch, mysql, nginx, rabbitmq, and redis.

We can use env. variables for `docker-compose` for different magento version

For example: docker's `app` (php) image
<pre>
# env/m240.env
<b>APP_IMAGE=markoshust/magento-nginx:1.18-3</b>

# docker-compose.yml
version: "3"

services:
  app:
    <b>image: ${APP_IMAGE}</b>
    ports:
      - "80:8000"
   ...

# bin/start
docker-compose <b>--env-file ./env/m240.env</b> -f docker-compose.yml ...
</pre>

Refs:
[Install the Magento software](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html)
[Related M2 Service versions](https://devdocs.magento.com/cloud/project/services.html#service-versions)
[Environment variables in Compose](https://docs.docker.com/compose/environment-variables/)

**Comment by markshust** [comment]
I think this would work, but `bin/start` would need to be changed around to grab the current Magento version:

`MAGENTO_VERSION="bin/magento --version" piped to regex to get anything after second space`

and then load the related ENV file based on that value

`docker-compose --env-file ./env/magento-$MAGENTO_VERSION.env -f docker-compose.yml ...`

etc. `env/magento-2.4.1.env`

**Comment by julesbravo** [comment]
I think it'd be fair to even have a tag system that allows for checking out a tag for installing a previous version.

**Comment by markshust** [comment]
The introduction of Elasticsearch in 2.4.0 really through things for a loop. Before 2.4.0, all versions were able to be installed & worked out of the box with zero config changes. So, I think we need a way to install 2.3-specific installer from some sort of flag.

@julesbravo everything should be tagged already, but it's currently a bit convoluted to try to run a specific tag. Try running the following commands from a new directory:

```
git init -qqq
git remote add origin https://github.com/markshust/docker-magento
git fetch origin -qqq
git checkout 24.2.0 -- compose/magento-2
mv compose/magento-2/* ./
mv compose/magento-2/.vscode ./
rm -rf compose .git
git init

bin/download 2.3.3
bin/setup m233.test
```

https://m233.test/

This should put you at the 24.2.0 tag, which has compatibility with the 2.3 install. I just ran this, and 2.3.3 installed with no probs. Then one can run `bin/update` to get all the scripts up to date with the latest version of docker-magento (note that this could change the PHP version though and make it incompatible, so it's up to you to review this update).

I'll see if I can automate this for older versions. We'll need to update the onelineinstaller and template scripts.

**Comment by julesbravo** [comment]
@markshust I was more referring to having a precise tag matched to the magento version like "magento-v2.3.5" instead of having to look up the associated tag (in this case 24.2.0).

**Comment by markshust** [comment]
@julesbravo I'm not sure that would make sense, as the current version of docker-magento supports many versions of Magento.

**Comment by julesbravo** [comment]
@markshust fair enough, I'm running your commands now, I'll update you to let you know if it works or not

**Comment by shyaaam** [comment]
> The introduction of Elasticsearch in 2.4.0 really through things for a loop. Before 2.4.0, all versions were able to be installed & worked out of the box with zero config changes. So, I think we need a way to install 2.3-specific installer from some sort of flag.
> 
> @julesbravo everything should be tagged already, but it's currently a bit convoluted to try to run a specific tag. Try running the following commands from a new directory:
> 
> ```
> git init -qqq
> git remote add origin https://github.com/markshust/docker-magento
> git fetch origin -qqq
> git checkout 24.2.0 -- compose/magento-2
> mv compose/magento-2/* ./
> mv compose/magento-2/.vscode ./
> rm -rf compose .git
> git init
> 
> bin/download 2.3.3
> bin/setup m233.test
> ```
> 
> https://m233.test/
> 
> This should put you at the 24.2.0 tag, which has compatibility with the 2.3 install. I just ran this, and 2.3.3 installed with no probs. Then one can run `bin/update` to get all the scripts up to date with the latest version of docker-magento (note that this could change the PHP version though and make it incompatible, so it's up to you to review this update).
> 
> I'll see if I can automate this for older versions. We'll need to update the onelineinstaller and template scripts.

I tried to run theses steps, and it got installed, but when i ping the url, i get the error 
`We can't read some files that are required to run the Magento application. This usually means file permissions are set incorrectly.`

**Comment by markshust** [comment]
Linking issue https://github.com/markshust/docker-magento/issues/377 for reference

**Comment by markshust** [comment]
Because of the updates to Xdebug 3, Composer 2, etc... I'm afraid it will be too much work to offer backwards-compatibility with older versions, especially since we are now on the third release of 2.4.x branch.

I really think those that need older versions can just use older tags & versions of this repo. This is where git tags and Docker labels come into play. You wouldn't get the most recent updates for older versions, but I think that's ok, as this setup works just fine on older tags and there is no maintenance involved.

I don't want this project to become a burden on me, and having backwards-compatibility sort of adds fuel to that fire, so going to make the tough decision to not support backwards-compatibility and close one ticket out.

**Comment by markshust** [comment]
I just thought, this would be a form of backwards-compatibility with not much additional work. Add to the documentation:

For Magento 2.3.5, run these versions/tags: xxx
For Magento 2.4.0, run these versions/tags: xxx
etc.

I have no interest bringing new Docker features to these old versions.

**Comment by mikemccoy** [comment]
> > The introduction of Elasticsearch in 2.4.0 really through things for a loop. Before 2.4.0, all versions were able to be installed & worked out of the box with zero config changes. So, I think we need a way to install 2.3-specific installer from some sort of flag.
> > @julesbravo everything should be tagged already, but it's currently a bit convoluted to try to run a specific tag. Try running the following commands from a new directory:
> > ```
> > git init -qqq
> > git remote add origin https://github.com/markshust/docker-magento
> > git fetch origin -qqq
> > git checkout 24.2.0 -- compose/magento-2
> > mv compose/magento-2/* ./
> > mv compose/magento-2/.vscode ./
> > rm -rf compose .git
> > git init
> > 
> > bin/download 2.3.3
> > bin/setup m233.test
> > ```
> > 
> > 
> > https://m233.test/
> > This should put you at the 24.2.0 tag, which has compatibility with the 2.3 install. I just ran this, and 2.3.3 installed with no probs. Then one can run `bin/update` to get all the scripts up to date with the latest version of docker-magento (note that this could change the PHP version though and make it incompatible, so it's up to you to review this update).
> > I'll see if I can automate this for older versions. We'll need to update the onelineinstaller and template scripts.
> 
> I tried to run theses steps, and it got installed, but when i ping the url, i get the error
> `We can't read some files that are required to run the Magento application. This usually means file permissions are set incorrectly.`

I have a similar problem. I followed these steps and it says my Magento Instance is available at my specified URL but it's a blank Magento /setup page and I'm getting forbidden errors. I set permissions to 777 but it still fails.  Any suggestions to for a reason or a fix? The steps described seemed so simple but obviously something is missing....

<img width="1416" alt="Screen Shot 2021-02-25 at 10 02 01 PM" src="https://user-images.githubusercontent.com/427370/109249192-36f8e800-77b5-11eb-88c3-061939b5f1ae.png">

**Comment by markshust** [comment]
Hi @mikemccoy - hope all has been well! I don't think your issue is specific to anything regarding this build, but rather a general docker-magento error. When you are thrown to /setup, it means your env.php file or data within it is not processed, and/or your database is blank.
