### ISSUE TITLE
Download script version 2.4.1

### ISSUE THREAD

**Issue by wesleyalmd** [markshust/docker-magento#325]
The Nexcess and Hypernode repositories have not yet released the new release of Magento 2.4.1, but still the download script on line 6 downloads a broken file and stores it in the folder ~ /.docker-magento.
`cd ~ / .docker-magento && curl -OL http://pubfiles.nexcess.net/magento/ce-packages/magento2-$1.tar.gz`
`ls -la`
`-rw-rw-r--  1 - - 1716 out 16 14:24 magento2-2.4.1.tar.gz`
`
File size: **1716**

To solve the problem, I increased the limit on checking files from 1MB to 10MB, thus forcing the download of the version via composer. line 10 and 15
`$ (find ~ / .docker-magento / magento2- $ 1.tar.gz -size -10M)`

**Comment by carylewis** [comment]
Which file is this in?

**Comment by markshust** [comment]
Thanks @piotrkwiecinski, like the `-f` flag, didn't know about that one! Much better than checking the file size.
