### ISSUE TITLE
Permission denied when trying to self-update composer

### ISSUE THREAD

**Issue by younkim** [markshust/docker-magento#334]
**Description**
Getting a warning when using `bin/composer`: 

> Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.

So, I tried to update composer itself, but there's a permission error. Composer seems to be designed to be used through `bin/composer`, so not sure how to go about update it.

**Steps To Reproduce**
1. Running `bin/composer self-update` yields `rename(/usr/local/bin/composer): failed to open stream: Permission denied`.

**Expected Result**

Composer should be updated to v2

**Actual Result**
Permission error

**Comment by rangerz** [comment]
You need root permission

```
bin/root bash
curl -sS https://getcomposer.org/installer | \
  php -- --version=1.10.15 --install-dir=/usr/local/bin --filename=composer
```
or you can use newer version php docker container cfb914120b3143167403ed243daeda6f809cac0e by 7.4-fpm-2 or 7.3-fpm-9
```
# Try to edit the image in docker-compose.yml or run bin/update
bin/stop
bin/update
bin/start
```

**Comment by younkim** [comment]
Thanks!

**Comment by markshust** [comment]
Yea, the most recent version of the images should be on the last version of Composer 1 available. I purposely didn't update things to Composer 2.0 yet just to make sure it is fully compatible with M2.
