### ISSUE TITLE
Why does composer --create-project in bin/download run locally?

### ISSUE THREAD

**Issue by carylewis** [markshust/docker-magento#336]
I have a question as to how bin/download uses composer to download the source from magneto's repo vs. the archive.

It appears as though it attempting to use the docker host's local composer to do the download. I wanted to know what the motivation for this was? It seems to me that using the container's composer would be better as that would be more portal across docker desktop for Windows and docker-ce running on linux.

**Comment by rangerz** [comment]
I also think using container's composer is a better choice for `bin/download`

**Comment by markshust** [comment]
I'm not sure about the ramifications, but with Composer 2.0 perhaps it's possibly time to switch to using the official Docker image for Composer rather than installing it locally? https://hub.docker.com/_/composer

**Comment by Webicultor** [comment]
I think I'll need further instructions to install composer locally O:)
Some current tutorial,maybe?
Or... which keywords must I use to find it? Because my first searches drive me to quite a wide list of information :(

**Comment by markshust** [comment]
@Webicultor first few lines on the site https://getcomposer.org/download/

**Comment by Webicultor** [comment]
> @Webicultor first few lines on the site https://getcomposer.org/download/

ok, I'll try it ASAP :)

**Comment by carylewis** [comment]
I haven't had to time to clone the repo and make the changes I would like to see.

But there are a lot of clones of this repo already, and some already do the docker container based composer install.

I would also like to have the /var/www/html directory in the container be a data volume or a mount point of the host's local directory, so that you can use a host based IDE, like visual studio code, or eclipse, and have access to the source code while debugging, etc.

**Comment by Webicultor** [comment]
> > @Webicultor first few lines on the site https://getcomposer.org/download/
> 
> ok, I'll try it ASAP :)

![image](https://user-images.githubusercontent.com/34300888/97459361-fd65bc80-193b-11eb-9e05-944c173d3650.png)

I don't understand how tis "unwritable" this directory. I've just downloaded composer-setup.php there!
:(

**Comment by Webicultor** [comment]
Maybe I'd better try to do it inside Ubuntu

**Comment by carylewis** [comment]
I was able to get this to work by installing cygwin, and the cygwin version of php, and then installing composer, but I had to tweak the bin/copyfromcontainer and bin/copytocontainer utilities, because docker uses windows pathnames and cygwin uses posix.

I am working on a pull request  so that cygwin will be automatically supported:

Here is the updated copyfromcontainer:
`#!/bin/bash
[ -z "$1" ] && echo "Please specify a directory or file to copy from container (ex. vendor, --all)" && exit

REAL_SRC=$(cd -P "src" && pwd)
if [ "$1" == "--all" ]; then
  #docker cp $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/./ $REAL_SRC/
   docker cp  $(docker-compose ps -q phpfpm|dos2unix):/var/www/html/./ $(cygpath -w $REAL_SRC)
  echo "Completed copying all files from container to host"
else
  if [ -f "$1" ] ; then
   # docker cp $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/$1 $REAL_SRC/$1
    docker cp  $(docker-compose ps -q phpfpm|dos2unix):/var/www/html/$1 $(cygpath -w $REAL_SRC)\$1
  else
#    docker cp $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/$1 $REAL_SRC/$(dirname $1)
    docker cp  $(docker-compose ps -q phpfpm|dos2unix):/var/www/html/$1 $(cygpath -w $REAL_SRC)\\$(dirname $1)
  fi
  echo "Completed copying $1 from container to host"
fi
`

and  copytocontainer

`#!/bin/bash
[ -z "$1" ] && echo "Please specify a directory or file to copy to container (ex. vendor, --all)" && exit

REAL_SRC=$(cd -P "src" && pwd)
if [ "$1" == "--all" ]; then
  #docker cp $REAL_SRC/./ $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/
  docker cp $(cygpath -w $REAL_SRC)/.  $(docker-compose ps -q phpfpm|dos2unix):/var/www/html
  echo "Completed copying all files from host to container"
  bin/fixowns
  bin/fixperms
else
  if [ -f "$REAL_SRC/$1" ]; then
  #  docker cp $REAL_SRC/$1 $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/$1
     docker cp $(cygpath -w $REAL_SRC)\$1  $(docker-compose ps -q phpfpm|dos2unix):/var/www/html/$1
  else
    #docker cp $REAL_SRC/$1 $(docker-compose ps -q phpfpm|awk '{print $1}'):/var/www/html/$(dirname $1)
     docker cp $(cygpath -w $REAL_SRC)\$1  $(docker-compose ps -q phpfpm|dos2unix):/var/www/html/$1/$(dirname $1)

  fi
  echo "Completed copying $1 from host to container"
  bin/fixowns $1
  bin/fixperms $1
fi
`

The commented out docker lines are the original lines, and the lines below them are the cygwin versions.

**Comment by markshust** [comment]
Thank you. I'd like to get Windows support in here, but I really know nothing about it. Is cygwin a part of WSL2? 

I would think we would do an if/else when the `REAL_SRC` var is defined and check if it's WSL. If it is, set the cygwin. If it's a part of WSL?

**Comment by carylewis** [comment]
Cygwin is a posix emulation layer. It is not WSL2.

I still plan on creating a pull request and of course I will make the copyfrom and copyto utilities work on systems where docker supports posix style paths and on windows where docker supports the c:\ style paths.

**Comment by markshust** [comment]
The `bin/download` script has been updated to use the Composer binary within the Docker container, so local Composer is no longer needed.

I'm sick of dealing with archives not being uploaded immediately upon the release of new Magento versions, so I just eliminated the archives completely. Every download will use Composer from now on. This greatly simplified the `bin/download` script. The only trade-off is that you need to run a couple lines to install sample data after the base Magento install (README has been updated https://github.com/markshust/docker-magento/commit/65a2161d3f7ab60b4955f1ae10781695b65e5030), but I don't think it's a big deal. This will greatly cut down on these requests coming in every time there is a new Magento release

If anyone wants to go back to archives, I need a 100% automated solution in place for building/tarring up these archives, automatically uploading them someplace, and supporting these on day zero of a new Magento release.
