### ISSUE TITLE
Same DB is shared between multiple projects

### ISSUE THREAD

**Issue by manafpm** [markshust/docker-magento#337]
Hi ,

I have created 2 separate folders for 2 projects . Both of them are having unique docker-compose.yml files.

Issue:
When I create a DB inside the docker of folder1, I can see the same DB in the docker container of folder2.
When I remove a DB from folder1 docker, the DB with the same name in folder2 is also getting removed.

Due to this I am not able to create databases with same name in different docker projects.

Thanks and Regards,
Manaf

**Comment by rangerz** [comment]
You can check the container name by `bin/status`

The container name is based on the previous level ...

For example:
```
cd ~/Sites/magento2.test
bin/status
# output
magento2test_app_1 ...
magento2test_db_1 ...
magento2test_elasticsearch_1 ...
magento2test_mailhog_1 ...
magento2test_phpfpm_1 ....
magento2test_rabbitmq_1 ...
magento2test_redis_1 ...

cd ~/Sites_bak/magento2.test
bin/status
# output will be the same with above ...
```

**Workaround**: create a different folder name for the parent folder of `docker-compose.yml`


To @markshust 

For avoiding this case we may need to use `project name` for `docker-compose`

For example

```
# Use -p ( --project-name) for docker-compose
docker-compose -p m2test up -d

# Use COMPOSE_PROJECT_NAME environment variable
export COMPOSE_PROJECT_NAME=m2test
docker-compose up -d
```

It will need to adjust lots of util script in `bin`, and save the `project name` to somewhere, ex: `.env` or `env/docker-compose.env`

For `bin/setup` will need to accept a new parameter for project name, if no set, just put the folder name for prefix and then random a suffix. ex: `magento2test_12345`
```
# In bin/setup

touch env/docker-compose.env
source env/docker-compose.env

if [ -z "$COMPOSE_PROJECT_NAME" ]; then
  COMPOSE_PROJECT_NAME=$(basename $PWD)_$RANDOM
  echo "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME" >> env/docker-compose.env
fi
```

Refs:
[Proposal: make project-name persistent](https://github.com/docker/compose/issues/745)
[Multiple isolated environments on a single host](https://docs.docker.com/compose/#features)

**Comment by manafpm** [comment]
@rangerz , Thank you very much for the quick response. I was able to resolve the issue with the above work-around

**Comment by markshust** [comment]
@rangerz I don't like doing any change like this that affects lots of files, especially since is the first time I've heard of someone having this issue in the last 5 years 😁 This seems to be already resolved, so closing it out.

**Comment by Kailashlambe** [comment]
Hi @manafpm, I am trying to run the multiple projects with the Docker, I have changed the ports and volume names in each compose.yaml file to avoid any issues, however it's not working.

Can you guide me with the compose.yaml file changes? thanks in advance!
