### ISSUE TITLE
mojave 10.14.6

### ISSUE THREAD

**Issue by immakdas** [markshust/docker-magento#338]
**Description**
Fail to run the Magento 2.4.0 without sample data

**Steps To Reproduce**
1. terminal sudo -s
2. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.4.0

**Expected Result**
magento2.test up and run

**Actual Result**
`Vendor autoload is not found. Please run 'composer install' under application root directory.`

Next I run composer install but fail. Have no problems with the onelinesetup  2.3.3 or 2.3.4

```
Ken-mb:mage4 miw$ bin/restart
Stopping mage4_app_1           ... done
Stopping mage4_phpfpm_1        ... done
Stopping mage4_rabbitmq_1      ... done
Stopping mage4_mailhog_1       ... done
Stopping mage4_db_1            ... done
Stopping mage4_redis_1         ... done
Stopping mage4_elasticsearch_1 ... done
Starting mage4_redis_1         ... done
Starting mage4_rabbitmq_1      ... done
Starting mage4_elasticsearch_1 ... done
Starting mage4_mailhog_1       ... done
Starting mage4_db_1            ... done
Starting mage4_phpfpm_1        ... done
Starting mage4_app_1           ... done
Ken-mb:mage4 miw$ sudo -s
Password:
bash-3.2# bin/composer install
```
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file

                                                                                                                                                   
  [ErrorException]                                                                                                                                 
  fopen(/var/www/.composer/cache/files/dasprid/enum/6e906468397d606a1656256f6df994ada97561d2.zip): failed to open stream: Operation not permitted  
```
                                                                                                                                                   

```
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

bash-3.2# bin/fixowns
Correcting filesystem ownerships...
chown: changing ownership of '/var/www/html/nginx.conf': Input/output error
```
.....
....
....
```
chown: changing ownership of '/var/www/.composer/cache/repo/https---repo.packagist.org/provider-zendframework~zend-uri.json': Input/output error
chown: changing ownership of '/var/www/.composer/cache/repo/https---repo.packagist.org/provider-zendframework~zend-validator.json': Input/output 
bash-3.2# bin/fixperms
Correcting filesystem permissions...
find: 'vendor': No such file or directory
chmod: changing permissions of 'app/etc': Operation not permitted
chmod: changing permissions of 'app/etc/NonComposerComponentRegistration.php': Operation not permitted
chmod: changing permissions of 'app/etc/db_schema.xml': Operation not permitted
chmod: changing permissions of 'app/etc/di.xml': Operation not permitted
chmod: changing permissions of 'app/etc/registration_globlist.php': Operation not permitted
chmod: changing permissions of 'app/etc/vendor_path.php': Operation not permitted
Filesystem permissions corrected.
bash-3.2# bin/fixowns
Correcting filesystem ownerships...
chown: changing ownership of '/var/www/html/nginx.conf': Input/output error
```

**Comment by markshust** [comment]
I don't think this has anything to do with Mojave. What folder do you have your Docker project setup under on your Mac/host machine? I typically recommend putting projects within a subdirectory of `~/Sites` on a Mac. It's possible you are mounting your project from a folder which Docker does not have permission to read files from. If you are using a non-standard directory, you must add it to Docker Preferences > Resources > File Sharing and then restart the Docker service. But, I'd recommend using a folder within one of their default options.

**Comment by immakdas** [comment]
I did create ~/Sites and add to the file share in the docker, restart as well. No affect.

`chown: changing ownership of /var/www/.composer/cache/repo/https---repo.packagist.org/provider-zendframework~zend-validator.json: Input/output error

Filesystem ownerships corrected.
Correcting filesystem permissions...
find: 'var': No such file or directory
find: 'vendor': No such file or directory
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory

chmod: cannot access 'bin/magento': No such file or directory`

**Comment by markshust** [comment]
It looks like something major is failing on your system, since `bin/magento` isn't even there. Can you try:
`bin/copytocontainer bin/magento` and see what happens?
