### ISSUE TITLE
Autoload error: Autoload error: Vendor autoload is not found. 

### ISSUE THREAD

**Issue by ikevinsolomon** [markshust/docker-magento#340]
**Description**
Unable to install magento 2.3.6
Running Mac OS X catalina and docker

**Steps To Reproduce**
1. Run oneline command as follows:
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.6

**Expected Result**
Magento 2.3.6 up and running

**Actual Result**
ilesystem ownerships corrected.
Correcting filesystem permissions...
find: 'vendor': No such file or directory
Filesystem permissions corrected.
Forcing reinstall of composer deps to ensure perms & reqs...
Changed current directory to /var/www/.composer
    1/1:	http://repo.packagist.org/p/provider-latest$253c5a8304ba3428cf24f44806fdb8776abd0ef8e6c9b15aed8ee4da192edc69.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Using version ^0.3.10 for hirak/prestissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package hirak/prestissimo is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
Loading composer repositories with package information
Updating dependencies (including require-dev)
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Turning on developer mode..
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Forcing deploy of static content to speed up initial requests...
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Re-indexing with Elasticsearch...
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Clearing the cache to apply updates...
Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.Copying files from container to host after install...
Completed copying app from container to host
Error: No such container:path: 10a7ded1fc74a3e7a2f7e1db26be451574d51f7b1fb116b577d5605aa07fddd2:/var/www/html/vendor
Completed copying vendor from container to host
Generating SSL certificate...
cat: can't open '/root/.local/share/mkcert/rootCA.pem': No such file or directory
Created a new local CA at "/root/.local/share/mkcert" 💥
The local CA is now installed in the system trust store! ⚡️

System password requested to install certificate authority on host...
Password:
^[[AUsing the local CA at "/root/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "magento2.test"

The certificate is at "nginx.crt" and the key at "nginx.key" ✅

**Comment by ikevinsolomon** [comment]
@rangerz can I get your thoughts on this please :)

**Comment by ikevinsolomon** [comment]
it has something to do with bin/setup instructions with regards to removing the vendor directory, if I comment it and run it runs fine.

**Comment by rangerz** [comment]
lol

Because current `bin/setup` support magento. 2.4 only

For magento 2.3, you need to use manual setup

```
# FIrst, remove the original one
bin/removeall

# Re-install all
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash

bin/download 2.3.6

echo "127.0.0.1 ::1 magento2.test" | sudo tee -a /etc/hosts

# You need to replace 'bin/setup' using old version one
curl https://raw.githubusercontent.com/markshust/docker-magento/12ce5eff69872a29b7ad89b000ae6e7b882a197c/compose/bin/setup -o ./bin/setup

bin/setup magento2.test

open https://magento2.test
```

Good Luck

**Comment by ikevinsolomon** [comment]
@rangerz you the maaaannnn!!! thank you closing this issue given I have a resolution!
