### ISSUE TITLE
After Running setup-ssl I get an error 

### ISSUE THREAD

**Issue by riccardofinkers** [markshust/docker-magento#342]
**Description**
I've used this markshust/docker-magento for a lot of projects and I simply love it ! I just ran in to an unexpected issue with just one project. 
I've already done an composer install and upgrade, bin/redis redis-cli flushall .. I can't access bin/magento then I get the following message as do I get that message on the front-end

**Steps To Reproduce**
1. Setup a fresh install
2. run setup-ssl

**Expected Result**
Everything works fine

**Actual Result**
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Config\CacheInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create(‘Magento\\Framewo...’)
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get(‘Magento\\Framewo...’)
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, ‘Magento\\Framewo...’, NULL, ‘cache’, ‘Magento\\Framewo...’)
#3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument(‘Magento\\Framewo...’, Array, Array)
#4 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynami in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

**Comment by markshust** [comment]
Thanks for the kind words!

I don't think your issue has anything to do with `bin/setup-ssl`, as it doesn't have to do with code. Since this also seems project-specific, my guess is that this has something to do with source code on this specific project. Perhaps try clear the generated files with `bin/cli rm -rf generated`? I'd also check your custom third-party code by searching for implementations of `CacheInterface` to see what is going on there.

**Comment by riccardofinkers** [comment]
Hello Mark, 

Sorry for the fuzz I see my colleague accidentally removed app/etc/di.xml from the GIT repository so that was the issue.
If anyone gets this error or somewhat similar it's because of a bad di.xml or missing .xml.

**Comment by markshust** [comment]
Cool thanks for the update. I'll try to document this somewhere in an upcoming "common Magento errors" lesson over at https://M.academy
