### ISSUE TITLE
Nginxx container not starting when we use custom default.conf file

### ISSUE THREAD

**Issue by manafpm** [markshust/docker-magento#343]
Hi there,

When we use customized nginx conf file, the app container is not starting. It shows the below error in the logs
2020/11/04 11:34:22 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)

yaml entry:
- ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

**Comment by markshust** [comment]
This issue is because something else is running on your port 80. You need to make sure apache/nginx/whatever is not also running on port 80 on your host machine.

`bind() to 0.0.0.0:80 failed (13: Permission denied)`
