### ISSUE TITLE
No nginx or php-fpm logs

### ISSUE THREAD

**Issue by niziou** [markshust/docker-magento#353]
**Description**
I am using php-fpm7.2 image and I was trying to add a patch which is adding a product attributes (type multiselect) but it was returning 502 nginx error without saying what's wrong. I was trying to find a ngingx/php-fpm logs inside docker container but there were no such log files.

**Steps To Reproduce**
1. php-fpm72
2. Create patch adding product attribute
3. Added options inside source class file
4. 502 on product page and inside admin edit product page.

**Expected Result**
After 502 error I can see at least inside the logs what happend.

**Actual Result**
There were not logs for nginx or php-fpm inside '/var/log/' directory

**Comment by ivanaugustobd** [comment]
Did you find the log location @niziou?

**Comment by ivanaugustobd** [comment]
Nevermind, found it https://github.com/markshust/docker-magento/issues/282#issuecomment-652388858
