### ISSUE TITLE
index of "/etc/nginx/html/" is forbidden  403 forbiddan error how to resolve 

### ISSUE THREAD

**Issue by asd99557** [markshust/docker-magento#354]
**Description**

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**

**Comment by Stefan386** [comment]
I had the same problem. Probably you have to edit your docker-compose.dev.yml to fix it. This is my yml:
[docker-compose.dev.zip](https://github.com/markshust/docker-magento/files/5687588/docker-compose.dev.zip)

**Comment by asd99557** [comment]
Hello Stefan,
Thanks for the update, but just let me know what kind of changes are
required in docker-compose.dev.yml file.


Thanks & Regards

**Comment by asd99557** [comment]
if you can let me know what kind of changes are required in docker-compose-dev.yml file If you can provide me guide it is so helpful for  me.

**Comment by Stefan386** [comment]
Just make a diff of both files. As far is I know, you only need to remove line 11 - 25, and remove # on line 26.

**Comment by asd99557** [comment]
Little confusion here please clear that
Remove line 11-25 ?
remove only # from 11-25 and 26 ?

**Comment by martinslaganovskis** [comment]
The problem for me was that the Magento installation was not complete. Installed using composer but something must have failed since src directory did not contain all of Magento files. Once I installed correctly this particular error was gone. So for me it was to make sure that all Magento files like app/ bin/ are there.

**Comment by markshust** [comment]
Closing out as I cannot replicate this issue. Perhaps your nginx.conf.sample or nginx.conf file in the Magento root is missing.

**Comment by Magesh-B** [comment]
I faced the same issue, For me, my nginx.conf was empty, I had to copy the nginx.conf.sample contents to the actual file for it to work.

**Comment by markshust** [comment]
That shouldn't be needed, so long as the `nginx.conf.sample` file hasn't been deleted, since it's mounted at https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.dev.yml#L12

Many delete this file though, which could definitely cause this issue.

**Comment by msalmenius** [comment]
> The problem for me was that the Magento installation was not complete. Installed using composer but something must have failed since src directory did not contain all of Magento files. Once I installed correctly this particular error was gone. So for me it was to make sure that all host Magento files like app/ bin/ are there. Afterwards ran the bin/setup once again and everything was fine.

Yes indeed, needed running bin/setup for me as well.

**Comment by ESCA7A** [comment]
@markshust hi!
can you advise? How to use this repo for my project (not magento 2) ? What settings to change to make the server work?

[error] 29#29: *1 directory index of "/etc/nginx/html/" is forbidden, client: 172.23.0.1, server: , request: "GET / HTTP/2.0", host: "172.17.0.1"

**Comment by markshust** [comment]
@ESCA7A the default web server path changed many years ago to `/var/www/html`. As this is a very old ticket, please create a new issue if you are having any issues.

**Comment by ESCA7A** [comment]
> @ESCA7A the default web server path changed many years ago to `/var/www/html`. As this is a very old ticket, please create a new issue if you are having any issues.

okay, thanks a lot :)

**Comment by elvishuges** [comment]
@ESCA7A How did you fix that error? which file a need to change and how to do that ?
