### ISSUE TITLE
Extra content for readme

### ISSUE THREAD

**Issue by ctohster** [markshust/docker-magento#356]
Extra content to add to readme.

Not an issue exactly but looking for some clarification that would be useful to have in the readme. Thought I'd post it here to help others in the future.

For deployment, I'm planning to use AWS and put the phpfpm and app containers into one EC2 instance. The other instances will be by themselves (db in RDS, Redis in Elasticache etc.), I'm just confused about the need for Redis and RabbitMq. I'm assuming RabbitMq is used for Cron and Redis is caching but couldn't you use Redis for both?

I thought it would be useful to add to the readme a brief description of what each container does and also any security issues in using this repo in prod. Some small advice on deployment would be amazing too but that might be too much to ask for :D

Also just want to say thanks for taking the time to setup this repo!

**Comment by GamesmenJordan** [comment]
The intention of this repo is to set up a *development environment* for Magento 2. It's not intended to be used in a production environment -- of course, if you wanted to you could configure it that way, but it is beyond the scope of this repo.

Yes Redis can be used as a message broker, but RabbitMQ is a first-class citizen for the message queue framework (see: https://devdocs.magento.com/guides/v2.4/config-guide/mq/rabbitmq-overview.html)

Again, the repo isn't meant for production so addressing production security concerns is probably beyond the scope of this repo.

**Comment by markshust** [comment]
Yes @GamesmenJordan summed up nicely. I'm going to close this out as there isn't really anything specific/actionable for me to take here.
