### ISSUE TITLE
Docker volume "file check" message is not that apparent

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#358]
**Description**
Here's the error that shows when attempting to run bin/start with volume files missing:

```
Moving key and cert to /etc/nginx/certs/...
Restarting containers to apply updates...
Stopping magento2_app_1           ... done
Stopping magento2_phpfpm_1        ... done
Stopping magento2_rabbitmq_1      ... done
Stopping magento2_db_1            ... done
Stopping magento2_redis_1         ... done
Stopping magento2_elasticsearch_1 ... done
./src/nginx.conf.sample: No such file or directory
Failed to start docker for missing volume files
Docker development environment setup complete.
You may now access your Magento instance at https://magento.test/
```

The line: `Failed to start docker for missing volume files` is not that apparent. Let's add some lines before/after the text to make it stand out some more, along with possible steps to take to fix.

**Comment by piotrkwiecinski** [comment]
@markshust I believe could stop scripts on error using: `set -o errexit`, so Failed start should be the last like and wouldn't be burried in the output.

I had it originally in https://github.com/markshust/docker-magento/pull/307/files I could extract it and PR separately.

**Comment by markshust** [comment]
This has been resolved.
