### ISSUE TITLE
bin/start error on MacOs BigSur

### ISSUE THREAD

**Issue by riccardofinkers** [markshust/docker-magento#366]
**Description**
When starting the environment in MacOs BigSur it gives an error (see beneath), but the environment seems to work so that is the most important thing, just wanted to report this. 

> bin/start
sed: 2: "s|^\([[:space:]]*\)-[[: ...": unused label '1;s|^\([[:space:]]*\)-[[:space:]]*{[[:space:]]*\(.*\)[[:space:]]*,[[:space:]]*\([a-zA-Z0-9_]*\)[[:space:]]*:[[:space:]]*\(.*\)[[:space:]]*}|\1- {\2}\n\1  \3: \4|;t1'
sed: 2: "s|^\([[:space:]]*\)\([a ...": unused label '1;s|^\([[:space:]]*\)\([a-zA-Z0-9_]*\)[[:space:]]*:[[:space:]]*\[[[:space:]]*\(.*\)[[:space:]]*,[[:space:]]*\(.*\)[[:space:]]*\]|\1\2: [\3]\n\1  - \4|;t1'
Starting magento_db_1            ... done
Starting magento_rabbitmq_1      ... done
Starting magento_mailhog_1       ... done
Starting magento_redis_1         ... done
Starting magento_elasticsearch_1 ... done
Starting magento_phpfpm_1        ... done
Starting magento_app_1           ... done

**Steps To Reproduce**
1. just hit up bin/start in MacOs BigSur

**Comment by markshust** [comment]
Hi @riccardofinkers, thanks for the report, but a ticket has already been filed about this at https://github.com/markshust/docker-magento/issues/351

Closing this issue as a dupe.
