### ISSUE TITLE
How to install previous versions of Magento

### ISSUE THREAD

**Issue by carylewis** [markshust/docker-magento#377]
I attempted to download / install Magento 2.3.5p1 EE.

bin/download 2.3.5p1 enterprise

worked fine, but when I ran bin/setup, there were errors:

First the version of php was incorrect, so I edited the 

docker-compose.yml and updated the phpfm section to this:
```
 phpfpm:
    image: markoshust/magento-php:7.3-fpm-9
```

but when I ran bin/setup, there were many errors:

```
The "--search-engine" option does not exist.

Turning on developer mode..

There are no commands defined in the "deploy:mode" namespace.
```

Are there any tags in the docker-magento repo that will work for magneto 2.3.5p1?

**Comment by rangerz** [comment]
Remove these in `bin/setup` 
```
    --search-engine=elasticsearch7 \
    --elasticsearch-host=elasticsearch"
```

Ref: #322

**Comment by carylewis** [comment]
Thank you - is it worth doing a fix for this, or are people not likely going to want to download old versions?
