### ISSUE TITLE
Fatal error: Out of memory (allocated 28307456) (tried to allocate 7864352 bytes) in /var/www/html/vendor/colinmollenhour/credis/Client.php on line 1457

### ISSUE THREAD

**Issue by plamenh** [markshust/docker-magento#378]
**Description**

Getting out of memory errors in admin.

**Steps To Reproduce**
1. Open admin->stores->configuration

**Expected Result**
Show configuration options.

**Actual Result**
Fatal error: Out of memory (allocated 28307456) (tried to allocate 7864352 bytes) in /var/www/html/vendor/colinmollenhour/credis/Client.php on line 1457

I see that memory limit is 768M as set in nginx.conf (and several other places). Therefore, this ~28M allocated is extremely strange. I've allocated 3 GBs of ram + 3 GBs of virtual memory in docker, still the same error.

I am using mariadb 10.4 (as opposed to Percona 5.7 coming in the standard docker-compose file), because Percona does not work on Apple Silicon yet.

UPDATE: Same thing happens in CLI

```
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 87625728) (tried to allocate 4262240 bytes) in phar:///var/www/html/composer.phar/src/Composer/Util/RemoteFilesystem.php on line 462
```

This is despite using php -d memory_limit=-1 (even manually checking the memory limit, it is 4G, as defined in php.ini).

**Comment by markshust** [comment]
FYI this error is being thrown with PHP, not Nginx.

The mem limit is set at https://github.com/markshust/docker-magento/blob/master/images/php/7.4/conf/php.ini#L1 but it's set to 4GB. Odd, your error appears to be less than 3GB. You want to at least up your mem to 4GB ram/vm docker mem.

**Comment by plamenh** [comment]
I have tried increasing the memory. Right now I believe this might be an issue with Docker Preview for Apple Silicon (https://github.com/docker/for-mac/issues/5204).

**Comment by markshust** [comment]
Ok, I'm going to close this one out as I cannot replicate, but feel free to reopen if you have more info about this.
