### ISSUE TITLE
bin/copytocontainer fails for directory paths containing spaces on MacOS (Catalina)

### ISSUE THREAD

**Issue by andru** [markshust/docker-magento#379]
`bin/copytocontainer` doesn't seem to play nice where the path has spaces in it

**Steps To Reproduce**
1. Use MacOS (encountered on Catalina, but presumably affects all versions)
2. Create a path with spaces in, and follow the manual install procedure
3. Run `bin/copytocontainer --all` or `bin/copytocontainer file.txt`, or any script which uses it, like `bin/setup`

**Expected Result**
It copies the files to the container

**Actual Result**
Error output is `"docker cp" requires exactly 2 arguments.` as the spaces in the path are interpreted as separate arguments.

**Fix**
Wrap $REAL_SRC and appended path parts in quotes.

Example error from `bin/setup`:
```
Copying all files from host to container...
"docker cp" requires exactly 2 arguments.
See 'docker cp --help'.

Usage:  docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH

Copy files/folders between a container and the local filesystem
Completed copying all files from host to container
Correcting filesystem ownerships...
Filesystem ownerships corrected.
Correcting filesystem permissions...
find: 'var': No such file or directory
find: 'vendor': No such file or directory
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory
find: 'app/etc': No such file or directory
chmod: cannot access 'bin/magento': No such file or directory
``` 

Just to help people find this issue until it's resolved, I'll add that this leads to a 404 error when attempting to load magente after bin/setup.

**Comment by markshust** [comment]
Thanks, all merged in. I'll gage a new release shortly.

**Comment by geoffjukes** [comment]
How do I pull a tagged version? Master has this change, and I think it's causing `fixowns` to fail:

```
chown: changing ownership of ‘/var/www/.composer/cache/files/wikimedia/less.php’: Operation not permitted
```

Because `/var/www` is not where I'm executing the script

**Comment by markshust** [comment]
No worries. This was tagged on 35.0.0 so closing this out. I'll probably have another build out shortly as well with the updates that came in the last few days.
