### ISSUE TITLE
Can not get debugging to work: xdebug 3 with phpstorm

### ISSUE THREAD

**Issue by carylewis** [markshust/docker-magento#383]
**The latest version of phpfpm incorporates xdebug3, and phpstorm does not work**

**Steps To Reproduce**
1. install per instructions
2. set phpstorm to listen to port 9003
3. Attempt to debug

**Expected Result**

phpstrom breaks on selected breakpoint

**Actual Result**

No breakpoints

I'm not sure how to troubleshoot this, phpstorm is listening on port 9003, but phpfpm doesn't have indication that it is attempting to connect to the remote port (I installed net tools in the container).

Any help would be appreciated.

Note: switching back to fpm-2 restores debugging

**Comment by markshust** [comment]
I just tested on PHPStorm 2020.3.2 and Xdebug properly caught the breakpoint. Note that this setup is still using Xdebug 2. I'll create a ticket for the upgrade to Xdebug 3.

Please see the config of my PHPStorm setup, as this project listens on port 9001. You can listen on both ports with a comma:

![Screen Shot 2021-02-03 at 9 42 53 AM](https://user-images.githubusercontent.com/437029/106762949-5ceefa80-6604-11eb-9a9c-272c0efa36ce.png)

Please let me know if you still have an issue after making this update and we can reopen this ticket.

**Comment by markshust** [comment]
https://github.com/markshust/docker-magento/issues/390

**Comment by carylewis** [comment]
xdebug 2 works fine. I am running this on Windows using docker with WSL2, so I am happy to help troubleshoot xdebug3 on that configuration.
