### ISSUE TITLE
`fixowns` fails with "Operation not permitted"

### ISSUE THREAD

**Issue by geoffjukes** [markshust/docker-magento#385]
On Big Sur, in `/Users/geoff/magento`, execute:
```
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test with-samples-2.4.1
```
the `fixowns` process fails with a screen full of:

```
chown: changing ownership of ‘/var/www/.composer/cache/files/wikimedia/less.php’: Operation not permitted
```
Then the next processes fail with similar issues.

**Comment by markshust** [comment]
Comment left in PR.

**Comment by markshust** [comment]
Closing per https://github.com/markshust/docker-magento/pull/386#issuecomment-772932552
