### ISSUE TITLE
Xdebug 3 support

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#390]
Let's drop support for Xdebug 2, and get Xdebug 3 in this project https://xdebug.org/announcements/2020-11-25

**Comment by piotrkwiecinski** [comment]
There is a compatibility issue with older versions of MFTF and xdebug 3.
Only the latest version support it:
https://github.com/magento/magento2-functional-testing-framework/blob/2.6.6/CHANGELOG.md#266

People using previous version would have to apply a patch: https://github.com/magento/magento2-functional-testing-framework/commit/e95fb10d3a55d72af5d60e07703d09201812599e.diff

**Comment by luancschmitz** [comment]
I needed to go back to xdebug 2 for the debug to work again.

I followed the video tutorial on how to set up xdebug in phpstorm, but even following exactly the steps in the video, don't fall into any breakpoints. I just switched to version 2 on the docker running:
pecl instal -f xdebug-2.9.8
after doing this and running a "bin/restart" xdebug worked the first time.

**Comment by frankmohaupt** [comment]
To get the xdebug v3 working you have to do the following:
Login as root
`bin/root bash`
Edit the file php.ini in the container
`vim /usr/local/etc/php/php.ini`

change the following content:
```
#xdebug.remote_autostart = 1
#xdebug.remote_enable = 1
#xdebug.remote_host = host.docker.internal
#xdebug.remote_port = 9001
#xdebug.idekey = PHPSTORM

# xdebug v3
xdebug.mode=debug
xdebug.client_host=host.docker.internal
xdebug.client_port=9001
xdebug.idekey=PHPSTORM
```

**Comment by markshust** [comment]
Thanks everyone. For some reason between the time I built the last PHP images and the time I pushed them up to DockerHub, Xdebug apparently got updated to 3 and I didn't even know.

I have confirmed @frankmohaupt's updates work. I'm ok moving to Xdebug 3 at this point as I confirmed it's working and there is a patch available for older versions as @piotrkwiecinski has pointed out. If there are issues in the future I can always revert, but if someone wants to use Xdebug 2 they can revert it to that version as @luancschmitz pointed out and set a custom php.ini file.

I'm rebuilding the images now and they should be out shortly.

**Comment by markshust** [comment]
Actually, because the update is so recent I'm going to also re-build the current images on Xdebug 2. I'll push and build that image up, and then re-published another version for Xdebug 3. This way someone can still use the most updated versions of this setup on Xdebug 2 if they wish and will give them some time to upgrade.

**Comment by markshust** [comment]
I tagged and released new PHP images that revert Xdebug back to version 2.

Xdebug 3 has a new listening port (9003, which I'm thankful for as phpfpm listens on 9000!), and a simplified configuration. I'm walking through different things now to make sure we have the simplest configuration possible with PHPStorm, and also VSCode support.

**Comment by markshust** [comment]
Xdebug 3 support in place https://github.com/markshust/docker-magento/commit/089bcbf3a4156431022acecfeb303b7621124f6a

It'll be tagged shortly under docker-magento 37.0.0.

**Comment by frankmohaupt** [comment]
To be mentioned, the debug port in Phpstorm need to be set to 9003, since the default port is used.

**Comment by GamesmenJordan** [comment]
It should be noted that `host.docker.internal` does not work on Linux platforms.

See: https://github.com/docker/for-linux/issues/264

**Comment by LucScu** [comment]
> I needed to go back to xdebug 2 for the debug to work again.
> 
> I followed the video tutorial on how to set up xdebug in phpstorm, but even following exactly the steps in the video, don't fall into any breakpoints. I just switched to version 2 on the docker running: pecl instal -f xdebug-2.9.8 after doing this and running a "bin/restart" xdebug worked the first time.

i used command outside container
`bin/root pecl instal -f xdebug-2.9.8`
then restart.
