### ISSUE TITLE
403 after docker compose up on localhost.

### ISSUE THREAD

**Issue by BartoszCoyote** [markshust/docker-magento#397]
I run docker-compose from example and i got 403 on localhost page. What wrong?

**Comment by markshust** [comment]
You need to start project with `bin/start`.

**Comment by danmentzer** [comment]
I also have this issue and bin/start just leads to these errors.
`$ bin/start
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
bin/start: line 6: bc: command not found
./src/app/design: No such file or directory
./src/app/etc: No such file or directory
./src/composer.json: No such file or directory
./src/composer.lock: No such file or directory
./src/nginx.conf.sample: No such file or directory
Failed to start docker for missing volume files
`

**Comment by phillipesouza** [comment]
Same problem here, anyone had found a solution?

**Comment by teuwsenjung** [comment]
Same Problem, is there a solution?

**Comment by markshust** [comment]
These lines are non-standard, and shouldn't be appearing:

```
   WARNING: No blkio throttle.read_bps_device support
   WARNING: No blkio throttle.write_bps_device support
   WARNING: No blkio throttle.read_iops_device support
   WARNING: No blkio throttle.write_iops_device support
   bin/start: line 6: bc: command not found
```

If you find out why those lines are being output, you'll solve your issue. I've never experienced this.
