### ISSUE TITLE
Blank Setup Page After 2.4.1 Installation

### ISSUE THREAD

**Issue by blhylton** [markshust/docker-magento#398]
**Description**
I'm unable to complete the setup after running either the one-line or manual install of 2.4.1.

**Steps To Reproduce**
After first installing, I'm greeted with a privacy error because of a malformed SSL certificate. This is fixed by running `bin/setup-ssl $DOMAIN`. Two peculiarities here:

* The mailhog container doesn't get created until after I rum `bin/setup-ssl`.
* I get an error after running it that states: "[ERROR] Unable to determine the Magento directory"

![Screen Shot 2021-02-05 at 12 04 26 PM](https://user-images.githubusercontent.com/1297591/107065401-b98c1a00-67aa-11eb-9094-efdcabfac5e8.png)
(Blacked out the domain name because it's the company/client's name and I'm not sure if I'm under an NDA in this instance.)

Then, when trying to access the site the first time, I get a screen stating:

> Autoload Error
> Vendor autoload is not found. Please run 'composer install' under application root directory.

I can fix this by running `bin/composer install`.

Once this is complete, I come to a mostly blank setup screen with a 403 in the inspector console.

![Screen Shot 2021-02-05 at 12 12 09 PM](https://user-images.githubusercontent.com/1297591/107066158-9ca41680-67ab-11eb-8719-29c2ec69f44d.png)

![Screen Shot 2021-02-05 at 12 12 25 PM](https://user-images.githubusercontent.com/1297591/107066193-a7f74200-67ab-11eb-82a9-46db69059996.png)

No combination of `bin/fixown` and `bin/fixperms` seems to correct this, with or without a restart. I did run across #185 in trying to sort this out and tried the suggestions there but to no avail.

ETA:

**System Info**

MacBook Pro 2017 (Intel CPU)
macOS Big Sur
Docker version 20.10.2

**Comment by markshust** [comment]
Where is the project located on your computer?

One thing I notice with a lot of users is that they put the project in a directory outside of their home directory. This will cause issues with Docker and file/volume resources. You shouldn't need to run composer install, fiwons, fixperms, or anything like that... it should work directly after running the one liner (albiet after a while).

**Comment by blhylton** [comment]
~/Projects/<project-name> is where I currently have it stored. Is there a particular directory structure I should try to troubleshoot if this is related?

**Comment by blhylton** [comment]
Quick update, removing and reinstalling Docker had no effect either.

**Comment by blhylton** [comment]
It looks like something is killing the `bin/setup` script on line 27.

```
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test with-samples-2.4.1
Initialized empty Git repository in /Users/bhylton/Projects/magento2.test/.git/
Extracting magento2-with-samples-2.4.1.tar.gz to ./src
Your system password has been requested to add an entry to /etc/hosts...
Password:
127.0.0.1 ::1 magento2.test
Creating network "magento2test_default" with the default driver
Creating volume "magento2test_appdata" with default driver
Creating volume "magento2test_dbdata" with default driver
Creating volume "magento2test_rabbitmqdata" with default driver
Creating volume "magento2test_sockdata" with default driver
Creating volume "magento2test_ssldata" with default driver
Creating magento2test_elasticsearch_1 ... done
Creating magento2test_redis_1         ... done
Creating magento2test_rabbitmq_1      ... done
Creating magento2test_db_1            ... done
Creating magento2test_phpfpm_1        ... done
Creating magento2test_app_1           ... done
Copying all files from host to container...
Completed copying all files from host to container
Correcting filesystem ownerships...
chown: changing ownership of '/var/www/.composer/2020-12-03_17-20-38-2.0.8-old.phar': Operation not permitted
Filesystem ownerships corrected.
Correcting filesystem permissions...
find: 'vendor': No such file or directory
Filesystem permissions corrected.
Global composer auth already exists
Forcing reinstall of composer deps to ensure perms & reqs...
Changed current directory to /var/www/.composer
Using version ^0.3.10 for hirak/prestissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

This is all I get and then it drops back to prompt without any (additional) errors. There are a couple of errors in the midst of all of that:

* `chown: changing ownership of '/var/www/.composer/2020-12-03_17-20-38-2.0.8-old.phar': Operation not permitted`
* `find: 'vendor': No such file or directory`

**Comment by markshust** [comment]
Perhaps there is something going on with your Composer cache files, as I'm unable to replicate this.

Try removing the Compose cache on your local machine `rm -rf ~/.composer/*`

**Comment by blhylton** [comment]
It wasn't the cache, but this was ultimately on me. I apparently can't read.

> This setup assumes you are running Docker on a computer with at least 4GB of **allocated** RAM

I had glossed over the word "allocated" when I was reading through the docs originally and thought it was simply "a computer with 4GB of RAM". It's kind of strange that it didn't give some sort of error message when the process was killed, but this was entirely my fault. Sorry for sending you down a rabbit hole.
