### ISSUE TITLE
How to change Magento base URL

### ISSUE THREAD

**Issue by younkim** [markshust/docker-magento#406]
Having trouble figuring how to change my instance's domain url. I got a new theme, and its license requires my local instance's URL matches a pattern of the production site, but already have a stable local instance running.

Tried looking around (`bin/setup` script, `app` container for nginx config, etc.), but I don't understand how nginx server name is set up in this docker setup. `bin/setup` doesn't seem to take `$BASE_URL` for setting up nginx.

Is this something simple to do, or should I just re-create the whole thing from scratch?

**Comment by rangerz** [comment]
```
bin/magento config:set web/secure/base_url https://$BASE_URL/
bin/magento config:set web/unsecure/base_url https://$BASE_URL/
```

**Comment by younkim** [comment]
> ```
> bin/magento config:set web/secure/base_url https://$BASE_URL/
> bin/magento config:set web/unsecure/base_url https://$BASE_URL/
> ```
Thanks! I actually already updated the store configs. I totally forgot to update my machine's host file. It seems that was the missing piece.

**Comment by younkim** [comment]
@rangerz do you know how re-create the ssl certificate when I change url? Running `bin/setup-ssl base_url` doesn't seem to establish the new cert even though the CLI output says `Moving key and cert to /etc/nginx/certs/...`. I'm unable to securely the local site.

**Comment by rangerz** [comment]
@younkim 
This command is work for me.
```
YOUR_SITE=magento.test
echo "127.0.0.1 ::1 $YOUR_SITE" | sudo tee -a /etc/hosts
bin/magento config:set web/secure/base_url https://$YOUR_SITE/
bin/magento config:set web/unsecure/base_url https://$YOUR_SITE/
bin/setup-ssl $YOUR_SITE
```

**Comment by markshust** [comment]
Merged this in!
