### ISSUE TITLE
bin/download doesn't run into composer section

### ISSUE THREAD

**Issue by dirkreitz** [markshust/docker-magento#407]
tried today with v2.4.2 which is not uploaded on the mirror sites yet.
Originally the job should try to download from nexcess or hypernode, finally should try to use composer.
Due to 'set -o errexit' this doesn't happen anymore ...

**Comment by markshust** [comment]
Thank you @dirkreitz for reporting this and @piotrkwiecinski for the contribution, all merged and working like before now.

I did notice that if you pass the `with-samples-` prefix in during the one-line install, it errors out with:

```                                                                                                
  [UnexpectedValueException]                                                                          
  Could not parse version constraint with-samples-2.4.2: Invalid version string "with-samples-2.4.2"
```

I think in this case we should prompt the user that the version is not yet available with sample data, and ask if they should proceed:

```
The Magento version you requested is not yet available with sample data, possibly due to a new version release.
You can still install Magento but will need to install sample data after installation.
Would you like to proceed? Y/n
```

I think we should truncate out the `with-samples-` prefix in this case so it can continue with the install (without sample data) after a user accepts the above prompt, or exits out if they select N.

**Comment by seanjeanc** [comment]
even installing sample data after a fresh installation of 2.4.2 is not working. Any clues?

**Comment by markshust** [comment]
@seanjeanc it's working for me. The steps after installing a clean Magento instance are:

```
bin/magento sampledata:deploy
bin/magento setup:upgrade
```

**Comment by seanjeanc** [comment]
strange, im doing the following: sh onelinesetup csmage.ddns.net:4438 2.4.2

after everything installs, I run sampledata:deploy and setup:upgrade commands, they run correctly but the database still has no sample data. Can you recommend anything else I could try?

Thank you

**Comment by markshust** [comment]
I'm unable to replicate using the steps in the documentation. You are using non-standard ports, non-standard command, etc. Need to follow instructions in readme *exactly*. I don't support fixing tickets when you are running the commands that differ from the documentation.

**Comment by seanjeanc** [comment]
just modifying the docker-compose.yml to change the ports so they don't conflict with existing ones on the system, and then running the setup by commenting the download commands so that docker-compose.yml does not get replaced. There are no errors, setup runs correctly, it's just when deploying the sample data, nothing changes in the database, even though it runs successfully.

**Comment by dirkreitz** [comment]
I tried Mark's commands regarding sample data - it is working like a charm ...
