### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#409]
This is a placeholder ticket to get "upgrade" this setup to use Composer 2. I'd like to remove the current Composer 1 dependency from the PHP image, and instead add the official Composer Docker image at https://hub.docker.com/_/composer/ to the docker-compose.yml file. This will involve updating bin/composer to use this new image.

I'm ok dropping Composer 1 support as long as there is some documentation on this project on how to use it with Magento 2.4.0, etc. as noted here https://github.com/markshust/docker-magento/issues/322#issuecomment-779364383

**Comment by gabs77** [comment]
I can suggest to replace in docker-compose.yml

`image: markoshust/magento-php:7.4-fpm-5`  by `build: ./php` 

And create php/Dockerfile
With 
`FROM markoshust/magento-php:7.4-fpm-5`
`COPY --from=composer:2 /usr/bin/composer /usr/bin/composer #Composer2`
`# COPY --from=composer:1 /usr/bin/composer /usr/bin/composer #Composer1`

**Comment by rangerz** [comment]
Another way to switch `composer` version
```
# To version 2
composer self-update --2

# To version 1
composer self-update --1
```

**Comment by hanhpv** [comment]
Why don't we update to Composer 2 in PHP image as now Magento already supports Composer 2?

**Comment by markshust** [comment]
Now that 2.4.2-p1 is out, I think this opens the door to make Composer 2 the default. I'll do this soon.

**Comment by hans2103** [comment]
@markshust did you manage to get some time to dig into upgrading to Composer 2? Would be nice

**Comment by markshust** [comment]
@hans2103 Hi Hans, I'll try to get this up after I finish working on my current project, should be real soon 👍

**Comment by markshust** [comment]
Looks like 2.4.3 is now available to Commerce merchants. I'm working on this right now.

**Comment by markshust** [comment]
Added to release 38.0.0 https://github.com/markshust/docker-magento/blob/master/CHANGELOG.md#3800---2021-07-27

**Comment by maxacarvalho** [comment]
Hi, is it possible to force `composer version 1`?

**Comment by markshust** [comment]
> COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

I think this is how you do it @maxacarvalho

**Comment by maxacarvalho** [comment]
Got it, thanks!

**Comment by virensachdev786** [comment]
> > COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
> 
> I think this is how you do it @maxacarvalho

Worked for everyone ??? Does not work for me. Let me know if there is another way, self-upgrade give write permission errors.
