### ISSUE TITLE
Error after latest update (v37.0.1): chmod: cannot access 'bin/magento': No such file or directory

### ISSUE THREAD

**Issue by HaidarZ** [markshust/docker-magento#410]
**Description**
Error after latest update : chmod: cannot access 'bin/magento': No such file or directory

**Steps To Reproduce**
1. Update to the latest version of the repository (v37.0.1)
2. bin/download 2.4.2
3. Go through the steps and apply the setpu command

**Expected Result**
Setup the magento docker workspace

**Actual Result**
```
Creating volume "workspace_appdata" with default driver
Creating volume "workspace_dbdata" with default driver
Creating volume "workspace_rabbitmqdata" with default driver
Creating volume "workspace_sockdata" with default driver
Creating volume "workspace_ssldata" with default driver
Creating workspace_redis_1         ... done
Creating workspace_rabbitmq_1      ... done
Creating workspace_db_1            ... done
Creating workspace_elasticsearch_1 ... done
Creating workspace_phpfpm_1        ... done
Creating workspace_app_1           ... done
chmod: cannot access 'bin/magento': No such file or directory
```

**Comment by kevintvh** [comment]
Hi @HaidarZ,
How did you fix this issue?

Thanks,
Kevin.

**Comment by HaidarZ** [comment]
I figured out that I wasn't  using the `bin/download 2.4.2` command. I was using the composer version of magento (it shoud be the same, don't know why it crashed).
Anyways, I've deleted the src and downloaded magento all over again using the command above and everything was back to normal.
