### ISSUE TITLE
 ERROR: failed shelling out to php for reading the module list

### ISSUE THREAD

**Issue by isyan** [markshust/docker-magento#417]
Hi, I don't understand this error.. I tried searching for it but doesn't have any leads..

![Screen Shot 2021-02-28 at 10 43 08 PM](https://user-images.githubusercontent.com/463743/109456615-75d9a880-7a16-11eb-8f69-400470036e0d.png)

This is the only changes that I've applied..
![Screen Shot 2021-02-28 at 10 44 58 PM](https://user-images.githubusercontent.com/463743/109456710-a4578380-7a16-11eb-9a4b-e2895cd02f72.png)

**Comment by markshust** [comment]
I can't replicate those so will be closing it out. Please try the install again, and if it still errors let me know :)

**Comment by FadelChafai** [comment]
I have the same error  ...

**Comment by isyan** [comment]
> I have the same error ...

check your db logs..

**Comment by frankmohaupt** [comment]
Try to run `bin/composer install`. This fixed it for me.
