### ISSUE TITLE
Project directory "/var/www/html/." is not empty.

### ISSUE THREAD

**Issue by pdsuk** [markshust/docker-magento#421]
**Description**
After a failed installation (ran out of memory so increased now), I deleted all files and containers in Docker Desktop (MacOS) to start again... When I now run the install script (or do a manual install) I get the following error:

```
Composer auth has been setup.
Creating a "magento/project-community-edition=2.4.2" project at "./"


  [InvalidArgumentException]
  Project directory "/var/www/html/." is not empty.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

I've tried restarting docker, making sure there's no containers or images left laying about and clearing composer cache etc but nothing seems to work to clear the error.

**Steps To Reproduce**
1. Run installation script under docker desktop (MacOS) but with small swap size so installation fails on composer install (Just says: Killed)
2. Stop and delete all containers created during the original installation
3. Delete all files in target dir (rm -rf *      I also removed all hidden files/folder)
4. Run installer again

**Expected Result**
Installer should behave as a new installation

**Actual Result**
Installer says that a folder (/var/www/html) is not empty

**Comment by draper87** [comment]
Same issue here.

**Comment by dirkreitz** [comment]
in case of a crash during the installation, you also have to erase the docker volumes ...

**Comment by pdsuk** [comment]
> in case of a crash during the installation, you also have to erase the docker volumes ...

Yes thank you, that's worked for me. Another couple of issues now with Elasticsearch seeming to bomb out and Nginx 403 but I'll work on that myself before posting anything on GitHub. Thanks again!

**Comment by appelmoesje** [comment]
I have the same problem. Where are the volumes that I should delete to get it to work?

**Comment by dirkreitz** [comment]
enter 'docker volume ls' in your terminal. Here you should see *_appdata, *_dbdata, etc. At least *_appdata should be deleted

**Comment by markshust** [comment]
This should be able to be handled by running:
`bin/removeall`
