### ISSUE TITLE
onelinesetup - cannot save magento keys (workaround)

### ISSUE THREAD

**Issue by RotateAt60MPH** [markshust/docker-magento#424]
I tried the onelinesetup script to create a fresh magento development environment (Ubuntu 20.04, with docker 20.10.5).  

Everything appeared to work until it gets to connecting to the magento repo. It appears the keys are not being saved as part of the composer global config.

Here's a run of the onelinesetup - all looks good until it tries to authenticate with the magento repo.

```
[wirunc@everest new-project]$ curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2
Initialized empty Git repository in /home/wirunc/new-project/.git/
Creating volume "newproject_sockdata" with default driver
Creating volume "newproject_ssldata" with default driver
Creating volume "newproject_appdata" with default driver
Pulling redis (redis:5.0-alpine)...
...
Pulling db (percona:5.7)...
5.7: Pulling from library/percona
...
Pulling phpfpm (markoshust/magento-php:7.4-fpm-5)...
...
Pulling app (markoshust/magento-nginx:1.18-4)...
...
Pulling rabbitmq (rabbitmq:3.7-management-alpine)...
...
Pulling elasticsearch (markoshust/magento-elasticsearch:7.7.1-0)...
...
Creating newproject_rabbitmq_1 ...
Creating newproject_redis_1 ...
Creating newproject_db_1 ...
Creating newproject_elasticsearch_1 ...
Creating newproject_redis_1
Creating newproject_rabbitmq_1
Creating newproject_db_1
Creating newproject_db_1 ... done
Creating newproject_phpfpm_1 ...
Creating newproject_phpfpm_1 ... done
Creating newproject_app_1 ...
Creating newproject_app_1 ... done

Composer authentication required (repo.magento.com public and private keys):
    Username: <redacted>193dc
    Password: <redacted>de2d1

Composer auth has been setup.
Creating a "magento/project-community-edition=2.4.2" project at "./"
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html


  [Composer\Downloader\TransportException]
  The 'https://repo.magento.com/packages.json' URL required authentication.
  You must be using the interactive console to authenticate


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

```

I looked in the (host) .composer directory (which is mounted into the containers) and it appears the magento creds are not being saved to the auth.json file.  I found that I had to run the command scraped out of bin/setup-composer-auth manually (in the host):

$ PUBLIC_KEY=_key_
$ PRIVATE_KEY=_key_
$ composer config --global  http-basic.repo.magento.com ${PUBLIC_KEY} ${PRIVATE_KEY}

Then the onelinesetup was able to run to completion.  I don't know enough about how the bin/cli command line redirection works, but at least I was able to continue with the above.

This assumes, of course, that I had composer installed in the docker host (which is Ubuntu 20.04, with docker 20.10.5).

Hope this helps someone.

**Comment by markshust** [comment]
Thanks for this report @RotateAt60MPH (and patiently waiting for my belated reply). I've noticed this for some time, but didn't take the time to figure this out until right now.

It seems Magento looks in an alternate directory for auth.json, and I placed a fix at https://github.com/markshust/docker-magento/commit/edafd37e267bb1e25c6cbe07695fcf08d6ac2471#diff-736d957a5ff14078b1155db9b10525462c2b9c9cf8b68dce5db61ccdb3348709R29 --- it should now be corrected for new installs.
