### ISSUE TITLE
onelinesetup - Could not connect to Amqp Server on WSL2

### ISSUE THREAD

**Issue by RotateAt60MPH** [markshust/docker-magento#426]
I'm trying to run onelinesetup on a Windows 10 machine with WSL2 as the docker backend.    I'm getting the following error after the containers are bounced following running Composer:

```
+ bin/setup magento.test
Stopping new-project_app_1           ...
Stopping new-project_phpfpm_1        ...
Stopping new-project_redis_1         ...
Stopping new-project_db_1            ...
Stopping new-project_elasticsearch_1 ...
Stopping new-project_rabbitmq_1      ...
Stopping new-project_redis_1         ... done
Stopping new-project_elasticsearch_1 ... done
Stopping new-project_rabbitmq_1      ... done
Stopping new-project_app_1           ... done
Stopping new-project_phpfpm_1        ... done
Stopping new-project_db_1            ... done
Starting new-project_rabbitmq_1 ...
Starting new-project_db_1       ...
Starting new-project_elasticsearch_1 ...
Starting new-project_redis_1         ...
Starting new-project_redis_1         ... done
Starting new-project_db_1            ... done
Starting new-project_phpfpm_1        ...
Starting new-project_elasticsearch_1 ... done
Starting new-project_rabbitmq_1      ... done
Starting new-project_phpfpm_1        ... done
Starting new-project_app_1           ...
Starting new-project_app_1           ... done
Waiting for connection to Elasticsearch...
.Could not connect to the Amqp Server.
```

When I had a look at the logs for the rabbitmq container (which appears to be starting and running), I see:
```

2021-03-09 16:55:02.653 [info] <0.9.0> Server startup complete; 3 plugins started.
* rabbitmq_management
* rabbitmq_management_agent
* rabbitmq_web_dispatch
2021-03-09 16:55:07.557 [info] <0.624.0> accepting AMQP connection <0.624.0> (172.23.0.6:36534 -> 172.23.0.4:5672)
2021-03-09 16:55:07.563 [error] <0.624.0> Error on AMQP connection <0.624.0> (172.23.0.6:36534 -> 172.23.0.4:5672, user: 'guest', state: opening): vhost C:/Program Files/Git/ not found
2021-03-09 16:55:07.563 [info] <0.624.0> closing AMQP connection <0.624.0> (172.23.0.6:36534 -> 172.23.0.4:5672, vhost: 'none', user: 'guest')
```

So it's trying to run GIT to pull something, but it's looking for a DOS directory path.  I do have GIT installed in  C:/Program Files/Git/, but I'm wondering if mount points are confused that it's looking for a DOS path.  

Is the fact that I'm using WSL2 the problem here?  Has anyone else got this to work?

**Comment by leeratyou** [comment]
Same here
```
bin/setup magento.test
Starting mg_db_1            ... done
Starting mg_elasticsearch_1 ... done
Starting mg_redis_1         ... done
Starting mg_rabbitmq_1      ... done
Starting mg_phpfpm_1        ... done
Starting mg_app_1           ... done
Could not connect to the Amqp Server.
```
macos

**Comment by Keydose** [comment]
I'm getting the same on Windows 10. Issue occurs either way whether I use one line or do it manually instead... so I'm unable to use.

`Starting magento2develop_app_1           ... done
Docker Compose is now in the Docker CLI, try `docker compose up`

Waiting for connection to Elasticsearch...
..Could not connect to the Amqp Server.

In InstallCommand.php line 274:

  Parameter validation failed
`

**Comment by markshust** [comment]
I'm unable to replicate this. Is this still occurring? I'm on Docker Desktop 20.10.7, Docker Compose v2.0.0-beta.6

**Comment by reducetomax** [comment]
I'm on Docker Desktop 20.10.7, Docker Compose v2.0.0-beta.6 and this is still occurring for me.

**Comment by markshust** [comment]
I tried this on a completely fresh install of Docker Desktop using the same versions as your last comment (and also, on another computer), and I'm still unable to replicate it.

That said, I'm on a Mac, so this is definitely specific to Windows/WSL2. I'll keep this open as I'm unable to test on this platform at the moment, so perhaps someone else can chime in with a fix.

**Comment by Almusamim** [comment]
same error here!

Win 10
Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c

**Comment by markshust** [comment]
Everyone on this issue... I just noticed the line erroring: "vhost C:/Program Files/Git/ not found"

Do you have Git installed on your Windows machines?

**Comment by vernard** [comment]
+1 on this error. And yes I have git installed.

I was able to get it fixed by changing the bin/setup command
```
  --amqp-host=rabbitmq \
  --amqp-port=5672 \
  --amqp-user=admin \
  --amqp-password=YjJiOTY0NDAxNWRkNmI1Y2Yx \
  --amqp-virtualhost=DSrabbitmq \
```

And also added the environment configuration in the docker image

```

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=YjJiOTY0NDAxNWRkNmI1Y2Yx
      - RABBITMQ_DEFAULT_VHOST=DSrabbitmq
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MB
```

I'm not sure if the error was because we used a guest account, or it's because we used the default (no) vhost. Anyhow, try the solution I wrote above if you're getting the same error.

**Comment by markshust** [comment]
Thanks a lot @vernard. If anyone can confirm this as a fix (I cannot as I was not previously experiencing a bug), there are little downsides to implement something like this if it resolves your problems.

**Comment by markshust** [comment]
I was finally able to replicate this! But only once or twice, then it didn't happen again.

That said, the only thing from @vernard's update that would make a difference would be the `RABBITMQ_VM_MEMORY_HIGH_WATERMARK` setting. This doesn't really appear to have any adverse side-effects, so I added it in at https://github.com/markshust/docker-magento/commit/935a0b7e3f4c6e2082355f28764958f0b6847fb1

I'll be tagging a new version of docker-magento very soon. That said, if this continues to happen with this update in place, please let me know so I can reopen this ticket!

**Comment by aleganesh1993** [comment]
Hello everyone,

I'm getting errors while installation of Magento in Windows 10 Docker machine 

Stopping magento_phpfpm_1        ...
Stopping magento_app_1           ...
Stopping magento_db_1            ...
Stopping magento_mailcatcher_1   ...
Stopping magento_redis_1         ...
Stopping magento_rabbitmq_1      ...
Stopping magento_elasticsearch_1 ...
Stopping magento_phpfpm_1        ... done
Stopping magento_redis_1         ... done
Stopping magento_mailcatcher_1   ... done
Stopping magento_elasticsearch_1 ... done
Stopping magento_app_1           ... done
Stopping magento_db_1            ... done
Stopping magento_rabbitmq_1      ... done
Starting magento_redis_1 ...
Starting magento_mailcatcher_1 ...
Starting magento_app_1         ...
Starting magento_rabbitmq_1    ...
Starting magento_elasticsearch_1 ...
Starting magento_phpfpm_1        ...
Starting magento_db_1            ...
Starting magento_redis_1         ... done
Starting magento_mailcatcher_1   ... done
Starting magento_phpfpm_1        ... done
Starting magento_rabbitmq_1      ... done
Starting magento_db_1            ... done
Starting magento_elasticsearch_1 ... done
Starting magento_app_1           ... done
Waiting for connection to Elasticsearch...
.......
Waiting for connection to RabbitMQ...
....Could not connect to the Amqp Server.

In InstallCommand.php line 274:

  Parameter validation failed


setup:install [--backend-frontname BACKEND-FRONTNAME] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--remote-storage-driver REMOTE-STORAGE-DRIVER] [--remote-storage-prefix REMOTE-STORAGE-PREFIX] [--remote-storage-bucket REMOTE-STORAGE-BUCKET] [--remote-storage-region REMOTE-STORAGE-REGION] [--remote-storage-key REMOTE-STORAGE-KEY] [--remote-storage-secret REMOTE-STORAGE-SECRET] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retries SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETRIES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--allow-parallel-generation] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--document-root-is-pub DOCUMENT-ROOT-IS-PUB] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--search-engine SEARCH-ENGINE] [--elasticsearch-host ELASTICSEARCH-HOST] [--elasticsearch-port ELASTICSEARCH-PORT] [--elasticsearch-enable-auth ELASTICSEARCH-ENABLE-AUTH] [--elasticsearch-username ELASTICSEARCH-USERNAME] [--elasticsearch-password ELASTICSEARCH-PASSWORD] [--elasticsearch-index-prefix ELASTICSEARCH-INDEX-PREFIX] [--elasticsearch-timeout ELASTICSEARCH-TIMEOUT] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]

![image](https://user-images.githubusercontent.com/87162116/143269081-61aef2e8-a387-4bda-9059-6ef50e9bbb48.png)

**Comment by markshust** [comment]
@aleganesh1993 right after that fails, try running `bin/setup yourdomain.test` again. Almost every time for me, it succeeded the second time. I'm not sure what is going on with Windows, but if this comes up again I'll re-open the ticket. The timeout was enough for things to start working for me.

**Comment by aleganesh1993** [comment]
Hello @markshust , Thank you response,

I tried to run the bin/setup yourdomain.test multiple times but still faced the same issue.

**Comment by markshust** [comment]
I'll re-open for visibility... is anyone else getting this error?

**Comment by ioancatanoaiaosf** [comment]
@markshust , yes I confirm I have the same problem on Win 11 / WSL 2

**Comment by markshust** [comment]
Thanks @ioancatanoaiaosf! @aleganesh1993 I just updated the RabbitMQ timeout to 10... can you try again?

**Comment by kd-labs** [comment]
Hi @markshust - still getting the same issue on windows even after timeout set to 10

**Comment by Rasmuskrogh** [comment]
Had the same problem on Windows. The solution by @vernard worked.

**Comment by markshust** [comment]
@Rasmuskrogh I don't see a solution posted by @vernard -- can you please let me know which fix this is so that I can implement it in this project? Thank you! -Mark

**Comment by Hemp-Blockchain-MSA** [comment]
@markshust - The [comment](https://github.com/markshust/docker-magento/issues/426#issuecomment-922491266) by @vernard proposing the fix is the one being referred,

**Comment by Rasmuskrogh** [comment]
https://github.com/markshust/docker-magento/issues/426#issuecomment-922491266that worked for me

Here is @vernards fix

**Comment by markshust** [comment]
@Rasmuskrogh I noticed @vernard's update was using rabbitmq 3.7. The most recent tag is `rabbitmq:3.8.22-management-alpine`. Perhaps y'all are using an outdated version of docker-magento?

I think simply running `bin/update` would resolve it for you. The only param that could have possibly "fixed" anything is the vhost/virtualhost directive, but I can't see that being the case, as if it is not defined it falls back to `/` which is the default vhost.

**Comment by Ginga86** [comment]
@markshust 

I am seeing the same issue as above (Waiting for connection to RabbitMQ... ....Could not connect to the Amqp Server.)

I am W10 and have tried all solutions above with no joy.

**Comment by Inbary-s** [comment]
Had the same issue as well. W10. Checked all versions and updated but none of that worked. I ran some other tests and found out my rabbitmq and erlang were not installed properly. I had to uninstall them completely, re-install and create my own user. guest user did not do the trick here. Once I did that, I updated the user info in the setup and docker files mentioned above: 
bin/setup:
`  --amqp-host=rabbitmq \
  --amqp-port=5672 \
  --amqp-user={user}\
  --amqp-password={password}\`

docker-compose.yml:

  `rabbitmq:
    image: rabbitmq:3.8.22-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER={user}
      - RABBITMQ_DEFAULT_PASS={password}`

**Comment by markshust** [comment]
@Inbary-s thanks SO MUCH for the update -- so the commonality between your setup and @vernard's was the "default" user & password. For some reason, I was missing the default designation/purpose from the previous posts. So, for an odd reason, it appears that the Windows-based docker image for rabbitmq is somehow not properly setting the default user/pass to the guest properly, or the guest account just isn't working. 

I pushed an update (see above commit), can someone attempt a fresh, blank install now and see if it works? I baked this "default" setting into the images, and moved everything to a new env file.

**Comment by markshust** [comment]
For my own future reference, these env vars are changing in RabbitMQ 3.9 (https://stackoverflow.com/questions/68600215/dropping-container-with-rabbitmq-in-docker). Magento does not support or recommend this version yet, but when they do, these envvars will need to be updated. That issue also seems to correlated with what everyone says above 👍

**Comment by Inbary-s** [comment]
I didn't have too long to play with it yet, but this is the error I got on the automated setup after your commit
![image](https://user-images.githubusercontent.com/55555231/146814820-28d3f75a-98f9-4279-819d-3083d7ce2a78.png)

**Comment by markshust** [comment]
@Inbary-s sorry about this! Can you try again now?

**Comment by Inbary-s** [comment]
That worked for me! 😄

**Comment by Inbary-s** [comment]
@markshust something happened and I'm hitting this error again.
Somehow Rabbit got uninstalled (a weird power outage issue probably caused it, it doesn't make much sense), I reinstalled but no luck. The only thing changed is it's now on version 3.9.11 and not supporting downgrades. Could you please advise?

**Comment by markshust** [comment]
Sorry, not sure what to go on here. It shouldn't have been uninstalled, but if it was, just running `bin/start` should get it back up & running.

**Comment by visahardik** [comment]
Hi, @markshust I am still facing the same issue in win10.
Can you please help?

![image](https://user-images.githubusercontent.com/35291561/151649962-7d35f5a5-9da4-454d-942b-bdc64f1edece.png)

![image](https://user-images.githubusercontent.com/35291561/151649970-2b6ed3e6-0f78-4b78-a487-efa153f00a6b.png)

**Comment by markshust** [comment]
@visahardik Are you using the most recent version of docker-magento? Note that the onelinesetup script won't work on Windows.

**Comment by visahardik** [comment]
> @visahardik Are you using the most recent version of docker-magento? Note that the onelinesetup script won't work on Windows.

@markshust, Yes I am using the latest version of docker, and I used following link to setup Magento in window

[D:\wamp64\www\purdys-chocolate\app\code\Mageplaza\DeleteOrders](https://github.com/markshust/docker-magento#manual-setup)

**Comment by markshust** [comment]
@visahardik have you seen the [Documentation for WSL2](https://github.com/markshust/docker-magento/discussions/372)? Some additional steps are needed to get things working on Windows. Also, from the screenshot above, it appears that `git` is missing from your WSL2 box.

**Comment by visahardik** [comment]
Hello @markshust 
Thank you for your quick response!
I was successfully able to install the Magento using docker but now there is some other error while trying to run the Magento default command. Please check the attached screenshot. 
![image](https://user-images.githubusercontent.com/35291561/154277049-bedf9c8d-ad5e-48b4-833b-e1a6f1460bef.png)
Note: I went into container and tried to run the same command but it is also not working.

**Comment by mgonzalezurbano** [comment]
I faced the same issue with WSL2 using ubuntu , after I remove ubuntu and install Debian in WSL2 , it worked
