### ISSUE TITLE
`/bin/start` fails due to no content in `src` folder 

### ISSUE THREAD

**Issue by ijemmy** [markshust/docker-magento#428]
**Description**
I use one-line setup script. The containers were started properly and I was able to run `bin/bash` to get in and see files in `var/www/html` folder.  However. I cannot run `bin/start` again and always get a complaint from docker that the mapped path to volume (e.g. `./src/app`, `src/compose.json`, etc) couldn't be found

**Steps To Reproduce**

1. Run `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.4.2`
2. Run `/bin/stop`
3. Run `/bin/start`

**Expected Result**
Expect docker-compose to succeed and has all containers.

**Actual Result**
Get an error that `src/app` folder and all mapped files aren't found.  

Where could I get the content in src folder? The only file I have is `launch.json`  I expect some instruction in `README.md` on where to get them.

**Comment by markshust** [comment]
I'm unable to replicate. The install process should error out if the files don't exist somewhere, I don't know why they wouldn't exist though, as the automated process automatically downloads and creates them for you.

I'd suggest blowing your install away and trying again. If it still doesn't work, I'll need you to post the full console output here (from the line that starts with `curl`, all the way through the "installation is complete" message).

**Comment by ijemmy** [comment]
Thanks, Mark.  

I've gone through it again and found the root cause. The issue comes from ElasticSearch wasn't ready after the wait has expired (in `bin/setup`). Thus, the `bin/copyfromcontainer` and the rest of the script wasn't executed.   

I modified the wait time to 300 sec and ran `bin/setup` manually again. That solves the problem.
