### ISSUE TITLE
Implement livereload support

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#430]
Anyone has experience in running liveload for this docker?

**Comment by artmouse** [comment]
I'm rebuild php images. Add in dockerfile: "EXPOSE 9001 35729" but xdebug not working...

**Comment by markshust** [comment]
This is more of a question, rather than an issue. I'd recommend to open up a Discussion instead of an Issue.

**Comment by markshust** [comment]
This was discussed in https://github.com/markshust/docker-magento/discussions/496 and will be implemented momentarily.

**Comment by artmouse** [comment]
Very tricky

**Comment by artmouse** [comment]
Why not just open the required port in yml and run the "npm install livereload" command??

**Comment by markshust** [comment]
@artmouse no need, `grunt watch` automatically spawns off the livereload server, so it's already installed.

It's all set and documented at https://github.com/markshust/docker-magento#grunt--livereload-for-frontend-development

Just ran through the documentation with a fresh site install, went really smooth!

**Comment by artmouse** [comment]
https://github.com/markshust/docker-magento/issues/635
