### ISSUE TITLE
Xdebug not working (Ubuntu)

### ISSUE THREAD

**Issue by boris1988** [markshust/docker-magento#431]
I did all steps from Xdebug & PHPStorm (also video lessons)

**Steps To Reproduce**
1. Enable xdebug (Ubuntu)
2. sudo iptables -A INPUT -p tcp --dport 9001 -j ACCEPT
3. phpinfo output port xdebug.client_port | 9003 | 9003
4. I tested for 9001 and 9003 ports
![Screenshot from 2021-03-22 21-50-56](https://user-images.githubusercontent.com/2422927/112049771-bda4a900-8b58-11eb-95d2-d9d2b9002957.png)
![Screenshot from 2021-03-22 21-49-35](https://user-images.githubusercontent.com/2422927/112049774-be3d3f80-8b58-11eb-8c34-7c91fb4a3d73.png)
![Screenshot from 2021-03-22 21-49-13](https://user-images.githubusercontent.com/2422927/112049776-bed5d600-8b58-11eb-830f-cd2060d7bf05.png)
![Screenshot from 2021-03-22 21-49-05](https://user-images.githubusercontent.com/2422927/112049779-bf6e6c80-8b58-11eb-9f46-f62e9ad882d4.png)

**Expected Result**
Xdebug working

**Actual Result**
Xdebug not works

**Comment by munkhulzii** [comment]
try additional ports in config: 9000,9001,9003

Additionally I have to click on debug button (green bug)

How is your config for remote debug?

**Comment by EmperorKonstantin** [comment]
I also for the life of me cannot get Xdebug working over Docker. It's maddening. I've triple-checked all settings.

I've run 

    docker run --rm alpine ip route | awk 'NR==1 {print $3}'

and added 
```
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
```

I've even directly added the more xdebug settings to php.ini:

```bash
➜ bin/cli grep 'xdebug' /usr/local/etc/php/php.ini
xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM
xdebug.profiler_enable=1
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_port=9001
xdebug.remote_autostart=1
xdebug.remote_connect_back=1
```

Nothing. How the heck do I _troubleshoot_ Xdebug not connecting:

![image](https://user-images.githubusercontent.com/3018990/112730999-e7abf180-8ef1-11eb-83f4-e8e586da95cd.png)

**Comment by markshust** [comment]
Before digging into this, just wanted to confirm that you both read the comments here, and set the `extra_hosts` param from that documentation?
https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.dev.yml#L30

**Comment by danielcbell** [comment]
I'm also having this issue but I'm using macOS where this param is not needed.

I've gone through the readme, videos and info at https://www.jetbrains.com/help/phpstorm/configuring-xdebug.html#configuring-xdebug-docker to check my PHPStorm config and I can't get Xdebug to work at all (I have had it working previously)

I even tried setting up on Windows via WSL2 and Visual Studio Code and it wasn't working there either.

> Before digging into this, just wanted to confirm that you both read the comments here, and set the `extra_hosts` param from that documentation?
> https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.dev.yml#L30

**Comment by EmperorKonstantin** [comment]
@markshust That's affirmative. I mention that in my comment.

**Comment by bhargavmehta** [comment]
I also have the same configurations in WSL 2 but still its not working for CLI. I was able to see xDebug 3.0.0 in `php -v` command

**Comment by pablobae** [comment]
I think that the problem comes from xdebug 3 and the new parameters.

> I've even directly added the more xdebug settings to php.ini:
> 
> ```shell
> ➜ bin/cli grep 'xdebug' /usr/local/etc/php/php.ini
> xdebug.mode = debug
> xdebug.client_host = host.docker.internal
> xdebug.idekey = PHPSTORM
> xdebug.profiler_enable=1
> xdebug.remote_enable=1
> xdebug.remote_handler=dbgp
> xdebug.remote_mode=req
> xdebug.remote_port=9001
> xdebug.remote_autostart=1
> xdebug.remote_connect_back=1
> ```
> 
 Some of those parameters have changed in xdebug v3. It works with:
 
 
```
xdebug.start_with_request = yes
xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.client_port = 9001
xdebug.idekey = PHPSTORM
xdebug.start_upon_error = yes
```

**Comment by markshust** [comment]
I don't think `xdebug.start_with_request` should be added, as I've always had issues with that rather than using path mapping. This is probably what made your request trigger, but I'm wondering if this would have triggered if path mappings were setup properly (unless they were, then perhaps we need to go down that rabbit hole).

Note that `mode`, `client_host` and `idekey` are all set in https://github.com/markshust/docker-magento/blob/master/images/php/7.4/conf/php.ini#L7

`start_upon_error` also doesn't seem right, as there shouldn't be any errors here. 

Xdebug 3 changed from port 9001 to port 9003, which is great because phpfpm uses port 9001 https://github.com/markshust/docker-magento/blob/master/images/php/7.4/Dockerfile#L118

So, I'd say lets find out why `start_with_request` was needed for your breakpoint to trigger.

**Comment by danielcbell** [comment]
> Note that `mode`, `client_host` and `idekey` are all set in https://github.com/markshust/docker-magento/blob/master/images/php/7.4/conf/php.ini#L7

[phpinfo.pdf](https://github.com/markshust/docker-magento/files/6335201/phpinfo.pdf)

Mark, unless I mount a custom php.ini, the value for xdebug.mode does not get set (no value). I have attached a copy of the Xdebug variables as they show without the custom file.

**Comment by EmperorKonstantin** [comment]
I got it working. Xdebug 3 isn't enabled by default for some reason, even if you run bin/xdebug.

Here's what I had to do to get Xdebug 3 enabled (settings are different from 2) after troubleshooting:

```bash
    docker-compose exec -u root phpfpm vi /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
```

```
zend_extension=xdebug

[xdebug]
xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
xdebug.start_with_request=yes
xdebug.idekey=PHPSTORM
```

and in docker-compose.dev.yml you need to have:

```yaml
  phpfpm:
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
```

@markshust I think we need to make some modifications to the bin/xdebug setup script and also any updates to the docker image will wipe the changes to docker-php-ext-xdebug.ini

**Comment by boris1988** [comment]
Hm, I have Xdebug 2.9.2

**Comment by markshust** [comment]
@EmperorKonstantin works for me? Perhaps something was lingering on your machine. Note that the config changed with Xdebug 3, it's different from Xdebug 2. Even when it's "disabled" with `bin/xdebug disable`, it's still really enabled, just the `xdebug.mode` changes.

![Screen Shot 2021-06-15 at 11 20 49 AM](https://user-images.githubusercontent.com/437029/122080190-14bec080-cdcc-11eb-99b6-987f7852fdfe.png)

![Screen Shot 2021-06-15 at 11 22 34 AM](https://user-images.githubusercontent.com/437029/122080208-18eade00-cdcc-11eb-8395-e4e1e624f4e0.png)

**Comment by taylordipentino** [comment]
> EDIT: After further investigation I managed to fix my variation of this issue by mounting a custom php.ini to /usr/local/etc/php/php.ini
> 
> The default project php.ini was setting the xdebug.mode param to off. It should be: xdebug.mode = debug

This fixed it for me, thanks!

**Comment by EmperorKonstantin** [comment]
@taylordipentino Yep, that was one of the issues, I just directly edited php.ini in the docker container instead, but it's a good idea to mount it instead. 

@markshust I think we can mark this closed at this point.

**Comment by sarojpant** [comment]
In my case, I noticed php.ini had these values 
```
xdebug.mode = off
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM
```
and `bin/xdebug enable` was not changing it. Thanks to Mark's comments above, I realized something is wrong with my setup.

I noticed that I had an earlier version of `bin/xdebug` which was not touching the php.ini file and changing docker-php-ext-xdebug.ini like so:
```
xdebug_enable() {
    if [[ $S == 1 ]]; then
        bin/cli sed -i -e 's/^\;zend_extension/zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        sleep 1
        bin/restart phpfpm
        echo "Xdebug has been enabled."
    else
        echo "Xdebug is already enabled."
    fi
}
```

I ended up copying the latest source code for `[bin/xdebug ](https://github.com/markshust/docker-magento/blob/master/compose/bin/xdebug)` code which updates the php.ini file

```
xdebug_enable() {
    if [[ $S == 1 ]]; then
        bin/root sed -i -e 's/^xdebug.mode = off/xdebug.mode = debug/g' /usr/local/etc/php/php.ini
        sleep 1
        bin/restart phpfpm
        echo "Xdebug debug mode has been enabled."
    else
        echo "Xdebug debug mode is already enabled."
    fi
}
```

And that did it for me :)

**Comment by markshust** [comment]
Ok thanks, I think this was specific to your setup so I'll close this one out. Glad you got it resolved!

**Comment by alwinjoseph02** [comment]
Hi @markshust. The issue still exists. Using the windows with wsl2.  currently using the below images
image: markoshust/magento-nginx:1.18-5
image: markoshust/magento-php:7.4-fpm-11

The same setup works for my different website but not for the new one. 

Note : have setup the following env too i.e PHP_IDE_CONFIG=serverName={{domain.name}}

It would be very helpful if you can take a look on the issue because it will very hard for developer to debug without xdebug

Manythanks

**Comment by dazz397** [comment]
I ran into this problem today uisng WSL.  I would type bin/xdebug enable and it would not enable. I resolved it by copying the php.ini to a different file, running sed, and copying it back. I am leaving it here for others if they run into the same issue.

Edit bin/xdebug and change the following lines:

xdebug_enable() {
    if [[ $S == 1 ]]; then
        bin/root cp /usr/local/etc/php/php.ini /usr/local/etc/php/php.new
        bin/root sed -i -e 's/^xdebug.mode = off/xdebug.mode = debug/g' /usr/local/etc/php/php.new
        bin/root cp /usr/local/etc/php/php.new /usr/local/etc/php/php.ini
        sleep 1
        bin/restart phpfpm
        echo "Xdebug debug mode has been enabled."
    else
        echo "Xdebug debug mode is already enabled."
    fi
}

xdebug_disable() {
    if [[ $S == 0 ]]; then
        bin/root cp /usr/local/etc/php/php.ini /usr/local/etc/php/php.new
        bin/root sed -i -e 's/^xdebug.mode = debug/xdebug.mode = off/g' /usr/local/etc/php/php.new
        bin/root cp /usr/local/etc/php/php.new /usr/local/etc/php/php.ini
        sleep 1
        bin/restart phpfpm
        echo "Xdebug debug mode has been disabled."
    else
        echo "Xdebug debug mode is already disabled."
    fi
}

**Comment by ldmichiels** [comment]
For Linux users, when you use docker probably need to replace `xdebug.client_host with` your machine IP address. 
See [PHP Storm documentation.](https://www.jetbrains.com/help/phpstorm/configuring-xdebug.html#configuring-xdebug-docker)

With Xdebug disable, i just replace the line in `php.ini` with the next `sed` command:
```
bin/root sed -i -e 's/^xdebug.client_host = host.docker.internal/xdebug.client_host = 172.17.0.1/g' /usr/local/etc/php/php.ini
```
And then start the xdebug
```
bin/xdebug enable
```
If you never configure PHPStorm for Xdebug connections please see the [MAcademy videos here](https://courses.m.academy/courses/set-up-magento-2-development-environment-docker/lectures/9064478) first.

**Comment by avra911** [comment]
Adding
```
firewall-cmd --zone=public --add-masquerade --permanent
firewall-cmd --reload
systemctl restart docker.service
```

as seen on https://stackoverflow.com/questions/40214617/docker-no-route-to-host#comment112139149_57502873 worked for me on ubuntu 20 lts.
