### ISSUE TITLE
Sybase module installation

### ISSUE THREAD

**Issue by zachwreed** [markshust/docker-magento#438]
**Description**
I'm fairly new to Magento and using Docker, perhaps someone can point me in the right direction. 

I'm needing to install [php7.4-sybase](https://packages.debian.org/sid/main/php7.4-sybase) to connect to an external mssql database with Zend_Db_Adapter_Pdo_Mssql. I can't seem to install the package in the Docker container using the bin/root commands. Is there a way to add this in with the `docker-compose.dev.yml`

Thanks.

**Comment by rangerz** [comment]
May install `sqlsrv pdo_sqlsrv` to connect mssql server

You can into php container to test them first, `bin/root bash`

https://github.com/coopTilleuls/php-mssql-alpine/blob/master/7.2/cli/Dockerfile

Good Luck

**Comment by zachwreed** [comment]
@rangerz  Thanks for the advice. 

I've tried dropping into the container and installing `sqlsrv` and `pdo_sqlsrv`. I added them as extensions in the `php.ini` file used. I still get a "missing mssql driver" error. Any recommendation on incorporating that Dockerfile you linked into the image/container?

**Comment by rangerz** [comment]
@zachwreed I tested and it work for me

```
# use root into docker contaioner
bin/root bash

# Run them
apt-get update \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        locales \
        apt-transport-https \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        unixodbc-dev \
        msodbcsql17 \
    && docker-php-ext-install mbstring pdo pdo_mysql \
    && pecl install sqlsrv pdo_sqlsrv \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv \
    && sed -i 's,^\(MinProtocol[ ]*=\).*,\1'TLSv1.0',g' /etc/ssl/openssl.cnf \
    && sed -i 's,^\(CipherString[ ]*=\).*,\1'DEFAULT@SECLEVEL=1',g' /etc/ssl/openssl.cnf
```

`php connect.php`
```
<?php
$serverName = "serverName\\sqlexpress"; //serverName\instanceName
$connectionInfo = array( "Database"=>"dbName", "UID"=>"userName", "PWD"=>"password");
$conn = sqlsrv_connect( $serverName, $connectionInfo);

if ($conn) {
    echo "Connection established.<br />";
} else {
    echo "Connection could not be established.<br />";
    die( print_r( sqlsrv_errors(), true));
}
?>
```


Ref:
https://laravel-news.com/install-microsoft-sql-drivers-php-7-docker
https://github.com/microsoft/msphpsql/issues/1056
https://www.php.net/manual/en/function.sqlsrv-connect.php

**Comment by markshust** [comment]
Closing as this is not an issue with this repo, possibly better served as a Discussion (resolution is in ticket as well).
