### ISSUE TITLE
Elasticsearch open to the world

### ISSUE THREAD

**Issue by plamenh** [markshust/docker-magento#439]
**Description**

I recently got a warning from my cloud provider that it is not a good practice to have the elasticsearch server open to the world. Is there any way to restrict it only to the docker containers? 

**Steps To Reproduce**
1. Follow installations steps and launch (e.g., bin/start)

**Expected Result**

Elasticsearch only accessible from within containers or at least from localhost.

**Actual Result**

Elasticsearch is accessible from everywhere at ports 9200 & 9300

**Comment by rangerz** [comment]
Edit `docker-compose.yml` and comment the ports for elasticsearch

```
elasticsearch:
    image: markoshust/magento-elasticsearch:7.6.2-2
    #ports:                # comment here
    #  - "9200:9200"       # comment here
    #  - "9300:9300"       # comment here
    environment:
      - "discovery.type=single-node"
```

And `bin/restart` it
