### ISSUE TITLE
mv: cannot stat '.vscode': No such file or directory

### ISSUE THREAD

**Issue by boris1988** [markshust/docker-magento#443]
**Description**
mv: cannot stat '.vscode': No such file or directory

**Steps To Reproduce**
1. bin/setup site.test

**Expected Result**
magento installed

**Actual Result**
mv: cannot stat '.vscode': No such file or directory

**Comment by robingram** [comment]
It looks like the `.vscode` directory is created when initialising the directory from the template. If you ran something like `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash` to get started then run it again. This may have happened if you ran the setup multiple times and it was moved successfully the first time.

**Comment by markshust** [comment]
Closing out as non-issue
