### ISSUE TITLE
How to view Nginx logs?

### ISSUE THREAD

**Issue by Asitis** [markshust/docker-magento#444]
I'm wondering if i'm able to tail the nginx logs for this docker install? I see some logs using `bin/bash` and `tail -f /var/log*` but I'm having issues on my frontend that Magento won't log, so I'm hoping the server catches whatever it is.

**Comment by rangerz** [comment]
```
docker-compose logs -f --tail="10" app
```
Ref: https://docs.docker.com/compose/reference/logs/

You also can view the log in Docker Desktop

**Comment by Asitis** [comment]
That's awesome. Thanks!
