### ISSUE TITLE
Ubuntu 20.04 problem with php 7.4

### ISSUE THREAD

**Issue by maya5510** [markshust/docker-magento#445]
**Description**
I am unable to install Magento 2.3.4 version on Ubuntu 20.04 which have php 7.4. On Ubuntu 19.10 I was using 29 version of Mark Shust's Docker Configuration for Magento. Where Can I find it ? 

**Steps To Reproduce**
1. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
2. bin/download 2.3.4

**Expected Result**

**Actual Result**
 "   - magento/product-community-edition 2.3.4 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.15) does not satisfy that requirement."

**Comment by rangerz** [comment]
Magento 2.3.4 is not support PHP 7.4

Ref: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

**Comment by daniloaldm** [comment]
Hello, I recommend you create a new folder docker and follow the setup steps: 

[https://github.com/markshust/docker-magento#manual-setup](https://github.com/markshust/docker-magento#manual-setup)

**Comment by maya5510** [comment]
So I have to edit docker-compose.yml ? In the newest version there is:
"  phpfpm:
    image: markoshust/magento-php:7.4-fpm-5
    links:
      - db
    volumes: *appvolumes"

**Comment by rangerz** [comment]
Yes, edit them to `7.3-fpm-12`

**Comment by maya5510** [comment]
So I tried edit 
"# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 37.0.2" 
and I think there are other differences so it may cause other errors. Where I can find original docker-magento version #29 ? 
"# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 29.0.0" This configuartion was for Magento 2.3.3.

**Comment by maya5510** [comment]
I have the same error trying instal 2.3.3 or 2.3.4 version 
"In Mysql.php line 110:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_con  
  fig_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config  
  _data` AS `main_table`                                                       
                                                                               

In Mysql.php line 91:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_con  
  fig_data' doesn't exist  "

**Comment by maya5510** [comment]
I tried 3 more times and same result. Maybe someone has copy of 29 version of docker-magento by Mark Shust and can help me ? I think my version have some bugs. I need veriosn to install Magento 2.3.3 or Magento 2.3.4.

**Comment by maya5510** [comment]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_config_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config_data` AS `main_table`  

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_config_data' doesn't exist  

I manully copy old project to Magento 2 folder and then use: 
docker-compose -f docker-compose.yml up -d
bin/copytocontainer --all
bin/restart

And have this errror with DB. How conect this DB to docker ?
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS         PORTS                                                                                        NAMES
4522b65d6050   markoshust/magento-nginx:1.13-8    "nginx -g 'daemon of…"   6 minutes ago   Up 6 minutes   80/tcp, 0.0.0.0:80->8000/tcp, 0.0.0.0:443->8443/tcp                                          magento2_app_1
92ce9fedde4f   markoshust/magento-php:7.3-fpm-4   "docker-php-entrypoi…"   6 minutes ago   Up 6 minutes   9000-9001/tcp                                                                                magento2_cron_1
9adf812137b4   markoshust/magento-php:7.3-fpm-4   "docker-php-entrypoi…"   6 minutes ago   Up 6 minutes   9000-9001/tcp                                                                                magento2_phpfpm_1
d9a91312a267   rabbitmq:3.7-management            "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   magento2_rabbitmq_1
33e1b80da4c3   mailhog/mailhog                    "MailHog"                6 minutes ago   Up 6 minutes   0.0.0.0:8025->8025/tcp, 0.0.0.0:49162->1025/tcp                                              magento2_mailhog_1
d8eb280118c0   percona:5.7                        "/docker-entrypoint.…"   8 minutes ago   Up 6 minutes   0.0.0.0:3306->3306/tcp                                                                       magento2_db_1
6d72861b6fa0   redis:5.0                          "docker-entrypoint.s…"   8 minutes ago   Up 6 minutes   6379/tcp                                                                                     magento2_redis_1

**Comment by maya5510** [comment]
MySQL [magento]> status
--------------
mysql  Ver 15.1 Distrib 10.3.18-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:		47
Current database:	magento
Current user:		magento@172.24.0.7
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server:			MySQL
Server version:		5.7.33-36 Percona Server (GPL), Release 36, Revision 7e403c5
Protocol version:	10
Connection:		db via TCP/IP
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	utf8mb4
Conn.  characterset:	utf8mb4
TCP port:		3306
Uptime:			46 min 39 sec

Threads: 1  Questions: 286  Slow queries: 0  Opens: 107  Flush tables: 1  Open tables: 100  Queries per second avg: 0.102

Is there "magento@172.24.0.7" should be "magento@localhost" ?

**Comment by markshust** [comment]
Try re-installing Magento from scratch starting with the 7.3 images, the errors you are receiving are because the Magento database doesn't exist.
