### ISSUE TITLE
Stopping containers causes Elasticsearch container to Exit 143

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#450]
**Description**
Running `bin/stop` causes an ERROR: 137 message to be displayed. Checking the status, it appears it is in an "Exit 143" state.

```
magento $ bin/stop
Stopping magento_app_1           ... done
Stopping magento_phpfpm_1        ... 
Stopping magento_phpfpm_1        ... done
Stopping magento_rabbitmq_1      ... done
Stopping magento_db_1            ... 
Stopping magento_db_1            ... done
Stopping magento_elasticsearch_1 ... done
ERROR: 137
magento $ bin/status
         Name                        Command                State     Ports
---------------------------------------------------------------------------
magento_app_1             /docker-entrypoint.sh ngin ...   Exit 0          
magento_db_1              /docker-entrypoint.sh --ma ...   Exit 0          
magento_elasticsearch_1   /tini -- /usr/local/bin/do ...   Exit 143        
magento_mailhog_1         MailHog                          Exit 2          
magento_phpfpm_1          docker-php-entrypoint php-fpm    Exit 0          
magento_rabbitmq_1        docker-entrypoint.sh rabbi ...   Exit 0          
magento_redis_1           docker-entrypoint.sh redis ...   Exit 0 
```

**Steps To Reproduce**
1. `bin/stop`

**Expected Result**
Elasticsearch container to exit with Exit 0 (no errors)

**Actual Result**
Elasticsearch container exists with Exit 143

**Comment by rangerz** [comment]
Some one said it is expected behavior.
https://github.com/elastic/elasticsearch/issues/31847

**Comment by markshust** [comment]
@rangerz thank you, figured something like that since nothing has changed with this project. Oddly enough, this only recently started happening to me.

Is there any way we can "quiet" this error from appearing in the console? It's ugly & presents as though something is wrong.

**Comment by markshust** [comment]
I haven't seen this in a while, so perhaps Docker fixed this in a recent update.
