### ISSUE TITLE
onelinestep gets killed

### ISSUE THREAD

**Issue by joannehoaz** [markshust/docker-magento#451]
I'm trying to run the script as stated in the README 
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2
but every time, the script seems to be killed automatically with the following error messages:
Created project in /var/www/html/.
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Killed
ERROR: 137
Anyone know how to get around this error?

**Comment by rangerz** [comment]
Set more resource for docker-desktop
![image](https://user-images.githubusercontent.com/3338473/115093125-0133ce00-9edf-11eb-858f-e2e06d50abfd.png)

Set memory limit for composer in `docker-compose.yml`
```
services:
  phpfpm:
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
```

**Comment by markshust** [comment]
I updated the README, as I just experienced this myself on a fresh install. It seems the old requirements of 4GB are not enough, but 6GB allocated seem to work.
