### ISSUE TITLE
ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)

### ISSUE THREAD

**Issue by GNUXDAR** [markshust/docker-magento#452]
**Description**
Yesterday all work, today the container my_project_db_1 not work and show ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2) were run command bin/mysql

**Steps To Reproduce**
1. docker-compose start

**Expected Result**
all containers working but _db_1 not work

**Actual Result**
with command bin/mysql ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)

$ bin/restart
done
done
done
donde
done
done
$ [ERROR] ENOSPC: System limit for number of file watchers reached, watch '/var/www/html/vendor/magento/module-asynchronous-operations'

**Comment by markshust** [comment]
Sorry, unable to replicate this. All is working as expected.
