### ISSUE TITLE
Reindex error

### ISSUE THREAD

**Issue by niketkanoi** [markshust/docker-magento#457]
Hello - Running into this error when doing a reindex 

Catalog Search index process unknown error:
{“error”:{“root_cause”:[{“type”:“cluster_block_exception”,“reason”:“index [magento2_fillrite_store_view_catalog_product_20210514_145430] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];“}],“type”:“cluster_block_exception”,“reason”:“index [magento2_fillrite_store_view_catalog_product_20210514_145430] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];“},“status”:429}
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index process unknown error:
{“error”:{“root_cause”:[{“type”:“cluster_block_exception”,“reason”:“index [magento2_fillrite_store_view_catalog_category_test] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];“}],“type”:“cluster_block_exception”,“reason”:“index [magento2_fillrite_store_view_catalog_category_test] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];“},“status”:429}
ElasticSuite Thesaurus Indexing index process unknown error:
{“error”:{“root_cause”:[{“type”:“cluster_block_exception”,“reason”:“index [magento2_fillrite_store_view_thesaurus_20210514_145452] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];“}],“type”:“cluster_block_exception”,“reason”:“index [magento2_fillrite_store_view_thesaurus_20210514_145452] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];“},“status”:429}

Can anyone help?

**Comment by rangerz** [comment]
Your disk may be full

Ref: https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Catalog-Search-index-process-unknown-error/td-p/456306
