### ISSUE TITLE
Error after bin/restart

### ISSUE THREAD

**Issue by niketkanoi** [markshust/docker-magento#458]
I am getting the below error after bin/restart 

niket@Nikets-MBP-2 fedex % bin/restart
Stopping fedex_app_1           ... done
Stopping fedex_rabbitmq_1      ... done
Stopping fedex_phpfpm_1        ... done
Stopping fedex_mailhog_1       ... done
Stopping fedex_redis_1         ... done
Stopping fedex_db_1            ... done
Stopping fedex_elasticsearch_1 ... done
Docker Compose is now in the Docker CLI, try `docker compose up`

Starting fedex_redis_1         ... done
Starting fedex_mailhog_1       ... done
Starting fedex_rabbitmq_1      ... done
Starting fedex_elasticsearch_1 ... done
Starting fedex_db_1            ... done
Starting fedex_phpfpm_1        ... done
Starting fedex_app_1           ... done
niket@Nikets-MBP-2 fedex % [ERROR] Unable to determine the Magento directory

Any ideas?

**Comment by MrKovalski** [comment]
@niketkanoi Had same issue. Missing env.php was causing the issue. The problem for me was that I have a master and a develop branch. Master has no env.php file. So when I switched back to develop all is good again.

**Comment by markshust** [comment]
Unable to replicate.
