### ISSUE TITLE
Docker is not working on VPN

### ISSUE THREAD

**Issue by manaftryzens** [markshust/docker-magento#462]
**Description**
The site is not loading on local if we are on VPN

**Steps To Reproduce**
1. Connect to VPN
2. restart docker by bin/restart
3. Try to load the site

**Expected Result**
1. Site should load

**Actual Result**
Site is not loading. It says below
Your connection was interrupted
A network change was detected.
ERR_NETWORK_CHANGED

**Comment by markshust** [comment]
This is an issue with your VPN, not this setup
