### ISSUE TITLE
MFA - Login Error

### ISSUE THREAD

**Issue by Mozart409** [markshust/docker-magento#464]
**Description**
When I login via the default admin and password I get this message.

> You need to configure Two-Factor Authorization in order to proceed to your store's admin area. An E-mail was sent to you with further instructions

Even with a admin I created (via the cli) with a valid email I still get the mfa message and no email in my inbox.

**Steps To Reproduce**
1. Install via quick install script
2. Login via magento.test/admin

**Expected Result**
Open Admin Panel

**Actual Result**

Message 2fa needs to be enabled

**Comment by hanhpv** [comment]
You need to enable the MailHog service in `docker-compose.dev.yml`, then check the email in `locahost:8025`.
Or you can disable module `Magento_TwoFactorAuth` to bypass this:
```
bin/magento module:disable Magento_TwoFactorAuth
bin/magento setup:upgrade
```

**Comment by Mozart409** [comment]
oh my god. Thank you. I will try it now

**Comment by Mozart409** [comment]
it works. This should definitly be in the readme. I will add a pr

**Comment by Mozart409** [comment]
added pr https://github.com/markshust/docker-magento/pull/465
