### ISSUE TITLE
how can I connect to mysql dbeaver from mysql container?

### ISSUE THREAD

**Issue by daniloab** [markshust/docker-magento#469]
HI, I want to know if I can connect to MySQL from dbeaver to get a better experience with docker-magento.

**Comment by rangerz** [comment]
Yes, I think so. Follow the info of `db.env` and docker-compose.yml`.

https://github.com/markshust/docker-magento/blob/3f8b3cb736c15d6f921e4b31c552ed4d4717c270/compose/env/db.env#L1-L5

https://github.com/markshust/docker-magento/blob/3f8b3cb736c15d6f921e4b31c552ed4d4717c270/compose/docker-compose.yml#L29-L33

```
Host: 127.0.0.1
Port: 3306
User: magento
Password: magento
Database: magento
```

**Comment by daniloab** [comment]
Yes, I just realize now and this is the way, thanks @rangerz 

On Arch Linux I downloaded dbeaver and use it
