### ISSUE TITLE
Connection to Redis fails without php-redis extension

### ISSUE THREAD

**Issue by tw-ec** [markshust/docker-magento#474]
On a MacBook High Sierra

I'm getting the following error when trying to set up an existing project, when I try to run 'app:config:import'

```
bin/magento app:config:import
Connection to Redis 127.0.0.1:6379 failed after 2 failures.Last Error : (111) Connection refused
```

Redis appears to be running in Docker desktop, but there is no port mentioned, it just says 'Running'

Running the following:
`bin/redis redis-cli`

returns a prompt `'127.0.0.1:6379>'`

**Comment by Hoszi** [comment]
@tw-ec 
This caused by a mssing php-redis extension.
This link maybe can help you
[https://olvlvl.com/2019-06-install-php-ext-source]
@markshust Please update the right docker to install php-redis extension! Thank You!
