### ISSUE TITLE
Security bug may or may not

### ISSUE THREAD

**Issue by hk1313** [markshust/docker-magento#477]
As per best practice, We should not have to save secrets or sensitive data in docker image but it should pass during runtime as container variables. I go through a lot of magento repo but did not find such repo. Per my docker practice, magento config or magento setup command should be run from entry point so it will set db credentials on right file inside container during runtime. You have a lot of scripts to setup environment so did not track what you add in image. Can you let me know, if we build docker image using method in this repo, will it be safe?

**Comment by rangerz** [comment]
No.
This repo is designed for development I think.

For docker setting is in here:
https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml
https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.dev.yml
https://github.com/markshust/docker-magento/tree/master/images

If you want a secure magento in docker environment, I think official magento-cloud is secure enough.
https://github.com/magento/magento-cloud
https://github.com/magento/magento-cloud-docker/tree/develop/images

**Comment by markshust** [comment]
Yes, this repo is made for dev, so I didn't want to make or even think of anything production-related, as that opens up a wormhole that I don't want to go down. At the moment I'm leaving production environments up to devops teams to build, configure & maintain.

**Comment by EmperorKonstantin** [comment]
@markshust Totally reasonable, DevOps is a headache and a half. [Serverless PHP](https://bref.sh/) is a bigdeal and then [Serverless](https://www.serverless.com/) JS frontend. Especially with Serverless Aurora V2 coming. 

I started learning Kubernetes and realized that it would be a total waste of time.
