### ISSUE TITLE
[feature request] add variable to bin/setup-grunt to adjust locale

### ISSUE THREAD

**Issue by hans2103** [markshust/docker-magento#483]
https://github.com/markshust/docker-magento/blob/3f8b3cb736c15d6f921e4b31c552ed4d4717c270/compose/bin/setup-grunt#L16

When running `bin/setup-grunt` the locale of local-themes.js is hardcoded set to `en_US`
Would be possible to add a parameter to adjust this hard coded value?
`bin/setup-grunt --locale nl_NL` or `bin/setup-grunt -l nl_NL`

**Comment by rangerz** [comment]
Or detect system setting.
```
./bin/magento config:show general/locale/code
```

**Comment by hans2103** [comment]
closing this issue in favor of the pull request https://github.com/markshust/docker-magento/pull/484
