### ISSUE TITLE
ERROR: for phpfpm  Cannot start service phpfpm: OCI runtime create failed (SOLVED)

### ISSUE THREAD

**Issue by r-martins** [markshust/docker-magento#487]
**Description**
When starting the services I started to get the following error:

> ERROR: for phpfpm  Cannot start service phpfpm: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/martins/Docker/pagseguro-exemplo-m2/src/composer.lock" to rootfs at "/var/www/html/composer.lock" caused: stat /host_mnt/Users/martins/Docker/pagseguro-exemplo-m2/src/composer.lock: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

I could confirm files were correct (they were not directories).

**Steps To Reproduce**
1. type `bin/restart` or `bin/start`

**Expected Result**
Start services sucessfully

**Actual Result**
Error. The first start was succesfull but I couldn't read any of the mapped files in .yml inside the container (using bin/bash).
Even with bin/root I didn't have permissions and it said "permission denied".

**Comment by r-martins** [comment]
The solution that worked for me was described [here](https://stackoverflow.com/a/68011729/529403).
I had to uncheck the box "Use gRPC FUSE for file sharing" in Settings -> General
![image](https://user-images.githubusercontent.com/191149/125043491-53e7e500-e0de-11eb-96c5-224ef8f8763e.png)

**Comment by rajatdubey1991** [comment]
I am getting the same error ,When starting the services I started to get the following error:

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/host_mnt/home/encora/Desktop/tates-docker/src/nginx.conf.sample" to rootfs at "/var/www/html/nginx.conf": mount /host_mnt/home/encora/Desktop/tates-docker/src/nginx.conf.sample:/var/www/html/nginx.conf (via /proc/self/fd/9), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

Steps To Reproduce: type bin/restart or bin/start

Currently i am using Docker version 24.0.4 version, I have checked the above solution but i didn't fount the "Use gRPC FUSE for file sharing" option in Settings -> General

**Comment by markshust** [comment]
@rajatdubey1991 it looks like your install got bonked for some reason. I'd recommend trying to completely remove the project with the instructions at https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty and re-install, which should take care of your issue.

FYI I've been using OrbStack instead of Docker Desktop for many months now, and there seem to be many less issues, it's faster, and consumes 90% less battery & resources. I'd highly recommend it over Docker Desktop! https://orbstack.dev/
