### ISSUE TITLE
Error on Ubuntu While Copying src Directory

### ISSUE THREAD

**Issue by dineshprima** [markshust/docker-magento#490]
**Description**
I am using your magento2 docker to configure existing website on my local environment. My laptop is ubuntu 18.04 version. 

**Steps To Reproduce**
1. When i tried to run the command "bin/copytocontainer -all" , it needs to copy all src files to docker container.

**Expected Result**
Completed copying -all from host to container

**Actual Result**
dirname: invalid option -- 'a'
Try 'dirname --help' for more information.
lstat /var/www/html/myproj/src/-all: no such file or directory
Completed copying -all from host to container
Fixing filesystem ownerships...
chown: cannot access '/var/www/html/-all': No such file or directory
Filesystem ownerships fixed.
Fixing filesystem permissions...
find: unknown predicate `-all'
Filesystem permissions fixed.

Can any body help me on this?

**Comment by jwlatech** [comment]
Its --all instead of -a
