### ISSUE TITLE
listen tcp4 0.0.0.0:443: bind: address already in use

### ISSUE THREAD

**Issue by maryammodir** [markshust/docker-magento#494]
Hi , I have a problem with run below command:
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2
I get thid error:
ERROR: for mark_app_1  Cannot start service app: driver failed programming external connectivity on endpoint mark_app_1 (6af754d00d069988e585b75592c894f52d4ed8175f6aa75398ccc4f9a0b81476): listen tcp4 0.0.0.0:443: bind: address already in use

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint mark_app_1 (6af754d00d069988e585b75592c894f52d4ed8175f6aa75398ccc4f9a0b81476): listen tcp4 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by dawidofed** [comment]
Podejrzewam, że jakaś usługa działa na porcie 443 (HTTPS). Apache2? NGINX?

**Comment by markshust** [comment]
Yes, this isn't an issue with this repo. Something is running on port 443, and you will need to kill that service in order to run another service on that port.
