### ISSUE TITLE
Xdebug enable : not activating

### ISSUE THREAD

**Issue by emetik** [markshust/docker-magento#502]
When I use the command to activate the xdebug is always returns it's enabled.
Version 38.0.0

**Steps To Reproduce**
1. bin/xdebug enable returns always  'Xdebug debug mode is already enabled.'
2. Test via the cli : 
```
 bin/cli php -v                                                                                                                                                                    
PHP 7.4.14 (cli) (built: Jan 12 2021 02:26:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with blackfire v1.49.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

It should launch the bin/xdebug process to activate xdebug but It only says Xdebug debug mode is already enabled.
Even when I try to launch the :
```
 bin/root sed -i -e 's/^xdebug.mode = off/xdebug.mode = debug/g' /usr/local/etc/php/php.ini
sleep 1
bin/restart phpfpm
bin/cli php -v
```
It doesn't mention the xdebug in the result

Thanks for your help

**Comment by markshust** [comment]
Xdebug 3 has some enhancements in that when `xdebug.mode = off`, it doesn't really affect performance. So rather than disabling Xdebug completely, the mode is just set to off.

This is working as expected. To find out if Xdebug debugging is enabled or disabled, you can run `bin/xdebug status`. This will read the xdebug.mode and let you know if debugging is enabled or not.

**Comment by emetik** [comment]
Thanks for you reply.
Just to make sure, the port is 9300 or 9001 ?

**Comment by jponeill** [comment]
I'm probably missing something but I can't get "bin/xdebug enable" to set the "xdebug.mode = debug". Below, I run "bin/xdebug disable" then "bin/xdebug enable" and then "bin/xdebug status" and for all 3 it says "xdebug.mode = off". Commands and output are below. 

*** bin/xdebug disable

bin/xdebug disable
memory_limit = 4G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

xdebug.mode = off
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM

upload_max_filesize = 100M
post_max_size = 100M
max_input_vars = 10000

sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"
[+] Running 1/1
 ⠿ Container magento2-phpfpm-1  Stopped                                                                                                                  0.1s
[+] Running 2/2
 ⠿ Container magento2-db-1      Running                                                                                                                  0.0s
 ⠿ Container magento2-phpfpm-1  Started                                                                                                                  0.2s
Xdebug debug mode has been disabled.

** bin/xdebug enable

bin/xdebug enable 
memory_limit = 4G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

xdebug.mode = off
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM

upload_max_filesize = 100M
post_max_size = 100M
max_input_vars = 10000

sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"
Xdebug debug mode is already enabled.

**bin/xdebug status 

bin/xdebug status 
memory_limit = 4G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

xdebug.mode = off
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM

upload_max_filesize = 100M
post_max_size = 100M
max_input_vars = 10000

sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"
Xdebug debug mode is enabled.
jimoneill@Jims-MBP magento2 %

**Comment by markshust** [comment]
@jponeill I'll re-open this. Anyone else experiencing this issue?

**Comment by jponeill** [comment]
I'm still looking into this, Mark. It might be related to  #619

**Comment by markshust** [comment]
Closing this ticket in favor of https://github.com/markshust/docker-magento/issues/623 and https://github.com/markshust/docker-magento/issues/619
