### ISSUE TITLE
Xdebug error after bin/update

### ISSUE THREAD

**Issue by munkhulzii** [markshust/docker-magento#503]
**Description**
I had a working environment and made and update with running of "bin/update". So after the update started containers and called the shop on browser.  And I see there is an error something like 
`Fatal error: Uncaught Error: Call to undefined function xdebug_disable() in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php:81 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(73): require() #1 /var/www/html/vendor/composer/autoload_real.php(63): co ...
`

Tried with bin/xdebug enable and disable. Unfortunately it seems to be no function. 

**Steps To Reproduce**
1. Running older installement of docker
2. Make update with bin/update
3. Start containers
3. Call the shop frontend on browser.

**Expected Result**
Shop frontend should be shown as usual

**Actual Result**
Error something like 
`Fatal error: Uncaught Error: Call to undefined function xdebug_disable() in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php:81 Stack trace: #0 /var/www/html/vendor/composer/autoload_real.php(73): require() #1 /var/www/html/vendor/composer/autoload_real.php(63): co ...
`

**Comment by markshust** [comment]
Are you on Magento 2.3 or 2.4? If you are on the former, this could be the issue: https://magento.stackexchange.com/questions/327971/uncaught-error-call-to-undefined-function-xdebug-disable

In this case, it appears only Xdebug 2 is supported for Magento 2.3. I believe you should be able to downgrade to Xdebug 2 using the `pecl` command from the link above (after running `bin/bash` to get into the container).

If you are on Magento 2.4, that is another story. Let me know and I can re-open this ticket. Hope this helps!

**Comment by daniloab** [comment]
HI there, Im with this error while trying to implement an existing project.

Right after importing the MySQL file, I start to get the same error. So, follow the comment above from Mark I started to try to fix it.

Steps to reproduce:

```
## trying 1 from docker-magento existing project step
- Download the Docker Compose template: ok
- Replace with existing source code of your existing Magento instance: ok
- Create a DNS host entry for the site: ok
- Start some containers, copy files to them and then restart the containers: ok
- Import existing database: ok
- Import app-specific environment settings: non ok
  error: 
  
  Fatal error: Uncaught Error: Call to undefined function xdebug_disable() in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php:73
  Stack trace:
  #0 /var/www/html/vendor/composer/autoload_real.php(70): require()
  #1 /var/www/html/vendor/composer/autoload_real.php(60): composerRequirefabeccfb0b2fd0dfa4b82eda2300a2fd('eda65932675b68b...', '/var/www/html/v...')
  #2 /var/www/html/vendor/autoload.php(7): ComposerAutoloaderInitfabeccfb0b2fd0dfa4b82eda2300a2fd::getLoader()
  #3 /var/www/html/app/autoload.php(30): include('/var/www/html/v...')
  #4 /var/www/html/app/bootstrap.php(31): require_once('/var/www/html/a...')
  #5 /var/www/html/bin/magento(14): require('/var/www/html/a...')
  #6 {main}
    thrown in /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php on line 73
```

## Solution Attempts
### first attempt
I followed the issue above (https://magento.stackexchange.com/questions/327971/uncaught-error-call-to-undefined-function-xdebug-disable) and replace the if for the related on it.

After that, I started to get the following error:

```terminal
[daniloab@daniloabarch magento-sttore]$ bin/magento app:config:import
An exception was raised while creating "Request"; no instance returned
```
