### ISSUE TITLE
When using bin/download getting JSON error

### ISSUE THREAD

**Issue by gl0b4nt** [markshust/docker-magento#506]
[Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:

  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

cp: cannot create regular file './var/composer_home/auth.json': No such file or directory
Composer auth has been setup.

  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:

  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by gl0b4nt** [comment]
At first I removed auth.json, didn't work so then I tried {}. Works as expected.  As always thank you.

**Comment by markshust** [comment]
@gl0b4nt great, glad that worked for you!
