### ISSUE TITLE
Trying to setup in my fresh ubnuntu 20.04

### ISSUE THREAD

**Issue by zaheerbadi** [markshust/docker-magento#508]
I am trying to setup this docker-magento in my linux(ubuntu) machine.But everytime i endup with the error.

First i was trying this in my `/var/www/html` but was not working so tried at /home direcotry but still getting this issue.
I am already running local apache/php in my machine.

Can you please guide me to setup it please?
![Selection_480](https://user-images.githubusercontent.com/9264676/129445767-fb8856fe-ff3a-4c65-b066-1c17531b325a.png)

**Comment by zaheerbadi** [comment]
issue fixed now it was causing due to my local elasticsearc/apache/mysql was running so it was conflicting IPs.

But one more question i would like to know that i have modified my file but it won't reflect in the frontend.
How can i check my changes? @markshust please advice

**Comment by zaheerbadi** [comment]
I come to know that we have to copytocontainer our changes but how would it be automated process whenever we change any file from our host take place changes to container.
Everytime we have to push our change to container to make it reflect on magento frontend?

**Comment by markshust** [comment]
The volume set at https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.dev.yml#L26 should set the volume sync -- no need for copyto/fromcontainer script for normal dev workflow.
