### ISSUE TITLE
After install in browser display 404 Not Found

### ISSUE THREAD

**Issue by jmikepm** [markshust/docker-magento#519]
**Description**
After install magento execute bin/start no show issues but try open the project in my browser but display a issue 404

**Steps To Reproduce**
1. After install magento following manual instalation

**Expected Result**
Application of magento

**Actual Result**
A issue of "404 Not Found"

**Comment by markshust** [comment]
Unable to replicate, need more details

**Comment by bhavin786** [comment]
I'm also faing this, earlier it was running fine but suddenly turned to 404 errors
