### ISSUE TITLE
Downgrade composer

### ISSUE THREAD

**Issue by niketkanoi** [markshust/docker-magento#525]
How can we downgrade to using Composer 1? 

I tried bin/composer self-update --1 which resulted in below error

[Composer\Downloader\FilesystemException]                                  
  Filesystem exception:                                                      
  Composer update failed: "/usr/local/bin/composer" could not be written.    
  rename(/usr/local/bin/composer): failed to open stream: Permission denied

**Comment by Asitis** [comment]
I am having the same issue, would also like to know.
Even tried just starting over with a clean install but it also seems to come with 2.1.0..

**Comment by Asitis** [comment]
Figured it out, try this - it worked for me:
`bin/root composer self-update --1`

**Comment by markshust** [comment]
@Asitis yes, that line is totally ok to run and the right way to do this 👍
