### ISSUE TITLE
bin/magento not found on bin/setup magento.dev

### ISSUE THREAD

**Issue by CrazyICT** [markshust/docker-magento#526]
magento % bin/setup magento.dev
Starting dirksenscooters_magento_rabbitmq_1      ... done
Starting dirksenscooters_magento_db_1            ... done
Starting dirksenscooters_magento_elasticsearch_1 ... done
Starting dirksenscooters_magento_redis_1         ... done
Starting dirksenscooters_magento_phpfpm_1        ... done
Starting dirksenscooters_magento_app_1           ... done
chmod: cannot access 'bin/magento': No such file or directory

(MacOs big sur 11.5.2, docker engine 20.10.8)

**Comment by markshust** [comment]
@CrazyICT were you able to get this working following the instructions at https://github.com/markshust/docker-magento#setup ? This setup requires very specific instructions to get installed. I'm unable to replicate this (tested on 2 computers and both installed successfully), so I'll be closing this out, pending more details about your specific setup or operating system.
