### ISSUE TITLE
automated setup breaks in composer auth setup

### ISSUE THREAD

**Issue by daniloab** [markshust/docker-magento#534]
**Description**
Im trying to install a new store locally using the automated setup. But, breaks giving the following error:

```terminal
/bin/cp: cannot create regular file './var/composer_home/auth.json': No such file or directory
Composer auth has been setup.
Creating a "magento/project-community-edition=2.4.3" project at "./"

                                                     
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.  
                                                     

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

I have been trying to do the instructions from this issue https://github.com/markshust/docker-magento/issues/506
- set an empty object inside `~/.composer/auth.json`
- remove the ``~/.composer/auth.json`

But still returning this error above to me.

I also did a docker system prune to try install everything from a zero environment and give the same error.

Could be a problem with permission inside of the container? 

**Steps To Reproduce**
1. run automated setup inside a MacBook m1

**Expected Result**
Generates a new store and opens normally.

**Actual Result**
Breaking right after `the bin/setup-composer-auth`

**Comment by bakerml** [comment]
I don't know if this will fix your issue, but I have an m1 mac and had a few similar issues with permissions etc.. after my first couple failed attempts. I ended up following this fork that has a couple different images for m1 and using the manual steps and it seemed to work. https://github.com/luancschmitz/docker-magento-mac-m1

**Comment by daniloab** [comment]
same error even running with this repo focused for mac m1 =/

```bash
cp: cannot create regular file './var/composer_home/auth.json': No such file or directory
Composer auth has been setup.
Creating a "magento/project-community-edition=2.4.3" project at "./"

                                                     
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.  
                                                     

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

**Comment by arthurelad** [comment]
Same issue here with Intel chip:

```
cp: cannot create regular file './var/composer_home/auth.json': No such file or directory
ERROR: 1
Composer auth has been setup.
Creating a "magento/project-community-edition=2.4.3" project at "./"

                                                     
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.  
```

This ticket #506 doesn't help!

**Comment by luancschmitz** [comment]
Hi @daniloab try delete all docker images, and try again.

**Comment by daniloab** [comment]
> Hi @daniloab try delete all docker images, and try again.

Already did it. Still giving the same error.

**Comment by daniloab** [comment]
I just change the order of `bin/setup-composer-auth` to be called before the docker-compose inside the `bin/download` file

This fixed and works the composer auth.

final result: 
```bash
#!/bin/bash
set -o errexit

VERSION=${1:-2.4.2}
EDITION=${2:-community}

bin/setup-composer-auth

bin/stop
docker-compose -f docker-compose.yml up -d
[ $? != 0 ] && echo "Failed to start Docker services" && exit

bin/clinotty composer create-project --repository=https://repo.magento.com/ magento/project-"${EDITION}"-edition="${VERSION}" .
```

Now, Im having trouble with nginx. When I try to access my page returns to me:

![Screen Shot 2021-09-28 at 13 08 25](https://user-images.githubusercontent.com/19939822/135124655-67d5ea67-fd8d-4e1a-a4b7-fb9db681738a.png)

Any help is accepted.

**Comment by daniloab** [comment]
Fixed!

It was missing memory on my docker. So, I add more to ram and swap and works normally.

To fix the main problem, composer auth, just change the order of commands

**Comment by ip-agency-git** [comment]
After failed installation only fix for this issue was "bin/removeall" and then re-install
