### ISSUE TITLE
Selenium test is not working

### ISSUE THREAD

**Issue by asannikov** [markshust/docker-magento#549]
**Description**
Selenium says that it cannot resolve the domain. 
`docker logs -f magento_selenium_1` shows nothing.

`bin/bash` and then  `curl -I https://magento.test` says: 
curl: (6) Could not resolve host: magento.test

But `curl -I -k https://app:8443` gives the correct response. 

I tried to replace MAGENTO_BASE_URL on https://app:8433 in .env.

Then it says:
`ERROR: 1 Test(s) failed to generate. See mftf.log for details. Generate Tests Command Run (with errors)...`

And there is an error in the mftf.log then:
```[2021-10-17 08:52:04] Magento\FunctionalTestingFramework\DataTransport\Protocol\CurlTransport.ERROR: Error HTTP response code: 500    Response:{"message":"Requested service is not available: \"twoFactorAuthAdminTokenServiceV1\"","trace":"#0 \/var\/www\/html\/generated\/code\/Magento\/Webapi\/Model\/ServiceMetadata\/Interceptor.php(50): Magento\\Webapi\\Model\\ServiceMetadata->getRouteMetadata('twoFactorAuthAd...')\n#1 \/var\/www\/html\/vendor\/magento\/module-webapi\/Model\/Rest\/Swagger\/Generator.php(675): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->getRouteMetadata('twoFactorAuthAd...')\n#2 \/var\/www\/html\/vendor\/magento\/module-webapi\/Model\/AbstractSchemaGenerator.php(172): Magento\\Webapi\\Model\\Rest\\Swagger\\Generator->getServiceMetadata('twoFactorAuthAd...')\n#3 \/var\/www\/html\/vendor\/magento\/module-webapi\/Model\/AbstractSchemaGenerator.php(107): Magento\\Webapi\\Model\\AbstractSchemaGenerator->getAllowedServicesMetadata(Array)\n#4 \/var\/www\/html\/vendor\/magento\/module-webapi\/Controller\/Rest\/SchemaRequestProcessor.php(59): Magento\\Webapi\\Model\\AbstractSchemaGenerator->generate(Array, 'https', 'app:8443', '\/rest\/schema?se...')\n#5 \/var\/www\/html\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SchemaRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#6 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#8 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/html\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#10 \/var\/www\/html\/vendor\/magento\/framework\/App\/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(23): Magento\\Framework\\App\\Http->launch()\n#12 \/var\/www\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#13 \/var\/www\/html\/pub\/index.php(29): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#14 {main}"} [] []```

and many warnings and errors in mftf.log:

```[2021-10-17 08:52:23] Magento\FunctionalTestingFramework\Test\Handlers\TestObjectHandler.ERROR: Line 43: Test AddSimpleProductBySkuFromCustomerAccountTest not defined in xml. [] []```

**System environment**
MacOS 11.4
Docker Desktop 4.1.0

**Steps To Reproduce**

install demo project:
```
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
bin/download 2.4.3-p1
bin/setup magento.test
```

then prepare selenium env:
1) uncomment part in docker compose file:
```
  selenium:
    image: selenium/standalone-chrome-debug:3.8.1
    ports:
      - "5900:5900"
    links:
      - app
    extra_hosts:
      - "magento.test:172.17.0.1"
```
domain and ip are checked.

2) bin/restart
3) bin/mftf build:project
4) edit config `dev/tests/acceptance/.env` in container:
```
MAGENTO_BASE_URL=https://magento.test/
MAGENTO_BACKEND_NAME=admin
MAGENTO_ADMIN_USERNAME={replaced username}
MAGENTO_ADMIN_PASSWORD= {replaced password}
SELENIUM_CLOSE_ALL_SESSIONS=true
BROWSER=chrome
MODULE_ALLOWLIST=Magento_Framework,ConfigurableProductWishlist,ConfigurableProductCatalogSearch
BROWSER_LOG_BLOCKLIST=other
ELASTICSEARCH_VERSION=7
SELENIUM_HOST=selenium
```
5) Run `bin/mftf run:test AdminLoginTest`

**Expected Result**
Test passed

**Actual Result**
```
In SuiteObjectHandler.php line 132:

  Suite Data Parser Error: Cannot retrieve API token with credentials. Please
   check the following configurations:
  username: {replaced username}
  password: {replaced password}
  Could not resolve host: magento.test

run:test [-k|--skip-generate] [-r|--remove] [-f|--force] [-a|--allow-skipped] [-d|--debug [DEBUG]] [--] <name>...
```

**Comment by markshust** [comment]
Hi @asannikov, thank you for all of the info. I forgot to note that the addition of Selenium is really "alpha" at best. I merged in a PR since it didn't have breaking updates, but didn't have time to flush out all of the info and details regarding testing and how to get things working.

I'll take another look at this, unless someone else wants to do it and open up a PR with updated documentation & fixes 🤓

**Comment by markshust** [comment]
Merged in your PR!

**Comment by xing120** [comment]
Hi @asannikov @markshust , I just trying to set up the mftf, but each time I run `vendor/bin/mftf run:test AdminLoginSuccessfulTest --remove` and I monitor the process through VNC, I saw that the chrome won't accept the https request, any idea how to fix this? THX
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/15187534/208550598-75c57db2-4df6-4e16-9d95-a288180c23d5.png">

**Comment by markshust** [comment]
@xing120 looks like it probably has to do with SSL not working on Linux? There are a couple issues open for that, as I don't think this is directly an issue with Selenium.
