### ISSUE TITLE
One line setup is failing in the end

### ISSUE THREAD

**Issue by drpayyne** [markshust/docker-magento#564]
**Description**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/22623301/139257174-da24e420-8b0a-48ab-8423-5f5ac8fc038c.png">

**Steps To Reproduce**
1. Run `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.3-p1` as described in the docs.
2. Command fails towards the end as in the screenshot. I tried in both the default macOS terminal and a third party terminal called Warp.

**Expected Result**
One line setup should complete successfully.

**Actual Result**
One line setup fails with a TTY error.

**Comment by ishanrakitha** [comment]
Tested just now on Ubuntu and its working as expected. 

![Fixed](https://user-images.githubusercontent.com/3178753/144807117-9b39a99d-b19d-4294-a2fc-0167abf02974.jpg)
