### ISSUE TITLE
Running bin/magento on Apple Silicone has ~5 second delay

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#566]
**Description**
Running bin/magento on Apple Silicone has ~4 second delay. This happens when running it either through the helper script, or after entering the container with `bin/bash`.

**Steps To Reproduce**
1. Run `bin/magento` on a Mac with Apple Silicone. I tested this on the new M1 MBP.

**Expected Result**
Running `bin/magento` should output fairly quick (1 sec or less).

**Actual Result**
Running `bin/magento` takes a few seconds to run any command.

**Comment by markshust** [comment]
Is this happening for anyone else on an M1 mac? M1 or M1X?

**Comment by markshust** [comment]
Seemingly related issue https://github.com/docker/for-mac/issues/5626

**Comment by markshust** [comment]
There's a fix in https://github.com/docker/for-mac/issues/5626 -- I'll implement shortly, as that 5 sec lag is *extremely* aggravating.

**Comment by kevinvarley** [comment]
Just confirming same issue replicated here.

M1X Macbook Pro

**Comment by markshust** [comment]
Hoping a fix is out today 😁. It's really an issue with Docker for Mac, but I'll add a workaround here so we don't need to deal with it or wait for a fix from Docker, because we all know that may take a while.

**Comment by markshust** [comment]
Fixed in `41.0.0`

**Comment by o0mohd0o** [comment]
Hello,

Wow  I was getting very slow docker Magento before update. I was thinking to roll back to Mamp pro actually. My production was got affected by this slowness. I told my self to search your repo if someone experience my same issue. I found solution.
Thanks so much.
