### ISSUE TITLE
Link to extended setup readme not working

### ISSUE THREAD

**Issue by kamephis** [markshust/docker-magento#568]
**Description**
The url to the extended setup readme was not found.

**Steps To Reproduce**
1. Klick on link "setup readme" in the README.md "Extended Setup Section" which points to https://github.com/markshust/docker-magento/blob/master/SETUP.md

**Expected Result**
The correct url to the extended setup readme is shown.

**Actual Result**
A 404 page is shown

**Comment by markshust** [comment]
Thanks for letting me know, this is an old link so I just removed this. Also removed the Wiki pages, as those were very outdated. All documentation is in the main README.
