### ISSUE TITLE
Elasticsearch timeout

### ISSUE THREAD

**Issue by skyw4Iker** [markshust/docker-magento#570]
**Description**
After bin/start the last container is timing out

Waiting for connection to Elasticsearch...
..................................................%

In the end, it times out and fails to start the docker instance

I did update to Mac OS Big Sur, not sure if that would be the issue. I've also tried re-installing docker entirely. 

**Steps To Reproduce**
1.  run the automated setup command-
2. you will see the error if its reproducible 

**Expected Result**
Starting docker_elasticsearch_1           ... done

**Actual Result**
Waiting for connection to Elasticsearch...
..................................................%

**Comment by markshust** [comment]
Can you let me know which operating system, hardware specs, etc. you are running. I have had issues in the past with Elasticsearch, but since the recent updates haven't been able to replicate any of them.

**Comment by skyw4Iker** [comment]
Apologize Mark I know you're super busy. Actually it was after a Mac update it reset my docker settings to 2GB! So it was memory issues.

Thanks!

**Comment by markshust** [comment]
Ah ok, glad to hear! I had a feeling it was a memory issue.
