### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by sanjayjethva** [markshust/docker-magento#573]
**On my MacBook Pro, when running a command then its shows "Error response from daemon: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use Failed to start Docker services" **

**Steps To Reproduce**
1. run curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.3-p1

**Expected Result**
The command runs without any error.

**Actual Result**
Error response from daemon: Ports are not available: listen tcp 0.0.0.0:80: bind: address already in use Failed to start Docker services

**Comment by markshust** [comment]
This error means that you have another service running on port 80 (not a bug with this project). You'll need to find Apache/Nginx or whatever other service you have running on your machine, and kill that service before attempting to execute this project.
