### ISSUE TITLE
Error copying file to container

### ISSUE THREAD

**Issue by JRomeoSalazar** [markshust/docker-magento#578]
**Description**
Whenever I try to copy composer.json or even when I copy all files it return an error:

"Error response from daemon: Error processing tar file(exit status 1): unlinkat /var/www/html/composer.json: device or resource busy"

**Steps To Reproduce**
1. bin/copytocontainer composer.json

or

2. bin/copytocontainer --all

**Expected Result**
File is copied to container and permissions get fixed.

**Actual Result**
Error response from daemon: Error processing tar file(exit status 1): unlinkat /var/www/html/composer.json: device or resource busy
Completed copying composer.json from host to container
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Fixing filesystem permissions...
Filesystem permissions fixed.

**Comment by rangerz** [comment]
It's because the file, `composer.json` is linked by `docker-compose.dev.yml`
https://github.com/markshust/docker-magento/blob/248242e28c7e86781bd402d63616d364ab9d5cfa/compose/docker-compose.dev.yml#L10

**Comment by markshust** [comment]
Yea, this file is already mounted, so no reason to copy it to/from the container (it's bi-directionally synced).

**Comment by JRomeoSalazar** [comment]
Thank you. It's strange because when I run bin/copytocontainer --all it
returns this error. Should the command ignore the file?

**Comment by markshust** [comment]
@JRomeoSalazar hmm, this never happened for me. Does it happen for anyone else?

**Comment by JRomeoSalazar** [comment]
Hi Mark, sorry it was my fault. I was trying to run "bin/copytocontainer
--all" command after "bin/start" and so, composer.json was "linked" to
docker-compose.dev.yml.
The correct command sequence is:

docker-compose -f docker-compose.yml up -d
bin/copytocontainer --all

As it's specified in your documentation.

Thank you!
