### ISSUE TITLE
Unable to Install Sample Data via composer

### ISSUE THREAD

**Issue by mkadsv** [markshust/docker-magento#580]
**Description**
I successfully installed Magento via the manual setup and ran into an issue with installing the sample data.

**Steps To Reproduce**
1. Followed the Manual Setup (Used the 2.4-develop branch for core development and successfully got test site up w/ no sample data)
2. After successfully completed installation, I ran `bin/magento sampledata:deploy` 

**Expected Result**
pull required modules for sample data

**Actual Result*
![mark-magento_—_-zsh_—_172×35_and_docker-compose_yml_—_mark-magento](https://user-images.githubusercontent.com/60241457/142508369-c554eb81-2801-416b-9252-3b89be1919dc.png)

**Comment by sirugh** [comment]
I have this same issue. Followed the manual setup steps using git for core development. Got the same error. Here's my history:

```
 5058  mkdir magento
 5059  cd magento
 5060  curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
 5063  docker-compose -f docker-compose.yml up -d
 5065  bin/setup-composer-auth
 5066  bin/cli git clone git@github.com:magento/magento2.git .
 5067  bin/cli git checkout 2.4-develop
 5068  bin/composer install
 5069  bin/setup localhost
 5074  bin/magento sampledata:deploy
 ```

**Comment by markshust** [comment]
Is this still an issue? I'm going to close this out as it's an old ticket and I'm unable to replicate it, but if you are still having this issue please let me know and I'll reopen it.

**Comment by MayurBagwe** [comment]
@markshust I'm still have the issue

**Comment by medmek** [comment]
yup still an issue, for me it returns : 

```bash
mekmed@DESKTOP-LOL:~/Sites/magento$ bin/magento sampledata:deploy
In VersionParser.php line 521:

  Could not parse version constraint : Invalid version string ""  

sampledata:deploy [--no-update]
```

**Comment by medmek** [comment]
> I never touched this file after the **Automated Setup (New Project)**, and it's not been long since I started using this project. So couldn't say if it was caused by a script in `bin` folder.

@markshust @sirugh @MayurBagwe @mkadsv 
Based on my phpstorm local history, it seems like the **Automated Setup (New Project)** is not a culprit because the empty line `"": ""` wasn't present initially : 

```patch
Index: composer.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/composer.json b/composer.json
--- a/composer.json	
+++ b/composer.json	
@@ -22,7 +22,8 @@
     "require": {
         "magento/product-community-edition": "2.4.7",
         "magento/composer-dependency-version-audit-plugin": "~0.1",
-        "magento/composer-root-update-plugin": "^2.0.4"
+        "magento/composer-root-update-plugin": "^2.0.4",
+        "": ""
     },
     "autoload": {
         "exclude-from-classmap": [

```

I guess some other command then.
