### ISSUE TITLE
Ensuring Composer auth.json is setup... Composer authentication required (repo.magento.com public and private keys):

### ISSUE THREAD

**Issue by ishanrakitha** [markshust/docker-magento#587]
Hi,

I'm getting the below error at the end of the automated process. 
Please advise, appreciate your support in advance. 

![image](https://user-images.githubusercontent.com/3178753/144010677-849dc184-da43-45c0-b574-f12baef91575.png)

Thank You,
Ishan.

**Comment by markshust** [comment]
I noticed this was closed, but was able to replicate this issue recently. I have a fix in place that will be pushed out momentarily.
