### ISSUE TITLE
Xdebug not working on 2.3.5 and php7.3

### ISSUE THREAD

**Issue by niziou** [markshust/docker-magento#588]
**Description**
I installed for a local development of my client. WIth magento 2.3.5-p1 with php7.3. My local docker image has xdebug loaded in version 3.1.1 but it is not triggering breakpoints. I am dead positive I have setup the phpstorm correclty. I have second project on magento 2.4. with php7.4 and it works as a charm. I have no problem on this second instance.

**Steps To Reproduce**
1. Install docker images with php7.3
2. Configure phpstorm for xdebug
3. enable xdebug

**Expected Result**
Xdebug is triggered and stop the php execution in the breakpoint

**Actual Result**
Nothing happens

**Comment by markshust** [comment]
Are you on Mac or Linux/Ubuntu? I had a couple report this issue, and may have a fix about ready.

**Comment by markshust** [comment]
Possible related to https://github.com/markshust/docker-magento/issues/350

This should be fully resolved in 41.0.2 master/CHANGELOG.md#4102---2021-12-09

There is a new PHP image that should also expose port 9003, which may resolve some issues.
