### ISSUE TITLE
bin/composer bin/magento and surfing on local website not so fast on new M1 Pro 10-core 32GBRAM

### ISSUE THREAD

**Issue by riccardofinkers** [markshust/docker-magento#590]
**Description**
I'm coming from the Macbook pro 2018 intel i7 and I'm now using the Macbook pro M1 PRO 10-core CPU and 32GB ram. I've setup docker(using the Apple silicon version) to use 5 CPU cores + 16GB RAM + 4GB SWAP and enought disk space (on local macbook SSD) but the bin/composer(using composer V1) bin/magento and surfing on the site is a bit slow. It takes a few seconds before it does something or so it seems.

**Steps To Reproduce**
1. anybody with an M1 pro of M1 Max that can confirm this ? 

**Expected Result**
do everything fast

**Actual Result**
not so very quick

I think maybe there could be some optimization

**Comment by markshust** [comment]
There was this issue that I noticed right away https://github.com/markshust/docker-magento/issues/566 -- but it was fixed a little while ago. Are you on an older version of docker-magento?

If so, you need to add all of the host entries into your docker-compose.yml file like so: https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml#L28-L37

Then, add these `extra_hosts` properties to each service, like so: https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.yml#L42

**Comment by riccardofinkers** [comment]
I do have those in my docker-compose.yml thanks for the quick awnser ! 

I do use old phpfpm images does that matter anything ? We use scripts to setup a new local environment automaticly and thereby we don't switch to the newest phpfpm images because sometimes there are issues with newer versions. 

<img width="388" alt="afbeelding" src="https://user-images.githubusercontent.com/34197329/145038146-1ba9b3c3-b423-4f30-8cd2-b4fd6a5d81b8.png">

**Comment by riccardofinkers** [comment]
Maybe for other people that land on this ticket, it really HAS to do with the new versions. WOW I'm running on the latest versions of Mark Shust php-fpm 7.3 and 7.4 and now they are blazingly fast thanks Mark :D

**Comment by markshust** [comment]
@riccardofinkers awesome, yea definitely, the old versions will be super slow on M1 macs because this update isn't in them. You can always backport, but docker-magento gets more stable & mature with every release, so there is no reason not to upgrade.
