### ISSUE TITLE
Xdebug not working on 3.1.2 and php7.4.

### ISSUE THREAD

**Issue by niners52** [markshust/docker-magento#591]
I am working through setting up xDebug. I have the test site and and running and all sample data up and running with no problems. When I am trying to run xdebug all I get is waiting for incoming connection with ide key PHPSTORM. I am on Ubuntu 20.4. More info- https://stackoverflow.com/questions/70267681/xdebug-for-docker-not-connecting

**Steps To Reproduce**
1. Install docker container. 
2. Setup XDebug. 
3. Set breakpoint
4. Refresh webpage.

**Expected Result**
Xdebug is triggered and stop the php execution in the breakpoint

**Actual Result**
Nothing happens

**Comment by markshust** [comment]
Possible related to https://github.com/markshust/docker-magento/issues/350

This should be fully resolved in 41.0.2 [master/CHANGELOG.md#4102---2021-12-09](https://github.com/markshust/docker-magento/blob/master/CHANGELOG.md#4102---2021-12-09)

There is a new PHP image that should also expose port 9003, which may resolve some issues.
