### ISSUE TITLE
Waiting for connection to RabbitMQ... ....Could not connect to the Amqp Server.

### ISSUE THREAD

**Issue by niziou** [markshust/docker-magento#592]
**Description**
During automatic script setup with fresh magento2.4.3-p1 I have an error that Rabbit is not there. I docker ps and I cannot see a docker container with rabbit

Waiting for connection to RabbitMQ...
....Could not connect to the Amqp Server.

**Steps To Reproduce**
1. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.3-p1

**Expected Result**
clean magento2 installation has been successfully installed.

**Actual Result**
Installation failed.

**Comment by niziou** [comment]
I was able to install, but using bin/setup magento.test command after it failed for the first time.

**Comment by markshust** [comment]
Thanks @niziou -- this ticket appears related https://github.com/markshust/docker-magento/issues/426

I just updated the timeout from 4 to 10 seconds for RabbitMQ... I think this should resolve your issue in the future.

**Comment by ManrahulBajwa** [comment]
Hi @markshust ,
What If I don't want to use RabbitMQ can't I remove it so error go away? seems like this config tightly bounded..

<img width="1289" alt="Image" src="https://github.com/user-attachments/assets/7b8c0663-a8de-4495-91a6-1cdc4fd93158" />
