### ISSUE TITLE
can't install sampledata

### ISSUE THREAD

**Issue by leafmaple** [markshust/docker-magento#593]
**Description**
install sampledata warning

**Steps To Reproduce**
1. bin/magento sampledata:deploy

**Expected Result**
install sampledata

**Actual Result**
<warning>Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/</warning>

**Comment by markshust** [comment]
@leafmaple that message is actually just a "warning", and isn't really an issue with either Composer or docker-magento.

Magento's internal Composer binary is still stuck on Composer 1 for some reason (I'm guessing this will change in Magento 2.4.4). That said, you can upgrade that internal binary to Composer 2 by adding this to your composer.json's `require` object:

```
"magento/composer": "1.7.0 as 1.6.0"
```

... then run `bin/composer install`. Afterwards, any command you run in this project will use Composer 2.
