### ISSUE TITLE
Wrong Xdebug settings for macOS Catalina with Docker Desktop 4.1.1 and VS Code?

### ISSUE THREAD

**Issue by rasmuswikman** [markshust/docker-magento#594]
**Description**
Out of the box, can't get Xdebug to work. Resolution below.

**Steps To Reproduce**
Add below to `/src/.vscode/launch.json`:
```
"pathMappings": {
  "/var/www/html": "${workspaceFolder}"
},
```
And enable with `bin/xdebug enable`.

**Expected Result**
Xdebug works.

**Actual Result**
Xdebug doesn't work.

**Resolution**
It starts working when replacing the following in `/usr/local/etc/php/php.ini` on `phpfpm`:
```
xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM
```
...with:
```
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = docker.for.mac.host.internal
```

Ping results:
```
root@f7acb96742be:/var/www/html# ping host.docker.internal
PING host.docker.internal (172.17.0.1) 56(84) bytes of data.
64 bytes from app (172.17.0.1): icmp_seq=1 ttl=64 time=0.120 ms
```
```
root@f7acb96742be:/var/www/html# ping docker.for.mac.host.internal
PING docker.for.mac.host.internal (192.168.65.2) 56(84) bytes of data.
64 bytes from 192.168.65.2 (192.168.65.2): icmp_seq=1 ttl=37 time=3.16 ms
```

**Comment by markshust** [comment]
@rasmuswikman is it possible you were not setting the IDE KEY with the Chrome Xdebug Helper extension? 

The `docker.for.mac.host.internal` hostname is very old and a deprecated (I think no longer working) way to access the client from the container. `host.docker.internal` is the standard hostname to do that. 

`xdebug.start_with_request = yes` will trigger Xdebug to send every request to the Xdebug client, which I believe is what got things working for you. However, the same should be able to be accomplished by setting the IDE_KEY value to PHPSTORM (even if you are using VSCode).

**Comment by markshust** [comment]
FYI it's very possible I messed `host.docker.internal` up for you when I added it to the docker-compose.yml file. I just backed out that update here https://github.com/markshust/docker-magento/commit/4efef7ac2c6742201ab0ac49995ef774bad5a89e

If you want to try to run `bin/update` and try the default settings now, I bet they will work for you, so long as you are setting that IDE KEY to `PHPSTORM` with the browser plugin.

**Comment by rasmuswikman** [comment]
@markshust Correct, it was the Chrome extension. Thank you for a superb project! 🙏🏼

**Comment by markshust** [comment]
@rasmuswikman awesome, great to hear! 🤜🤛
