### ISSUE TITLE
Can't make xdebug works

### ISSUE THREAD

**Issue by nverhoye** [markshust/docker-magento#595]
Hello,

I'm using lastest version of docker-magento repository (thought bin/update)
Usually I don't have any worries, but for some reasons that I don't know xdebug stopped working.
My breaking point are simply ignored now.

Here is my xdebug_info : 
<img width="971" alt="Capture d’écran 2021-12-16 à 22 14 32" src="https://user-images.githubusercontent.com/11976842/146450078-9ed82870-3406-4c70-a01f-72ea933cb1f7.png">

Following line is on /etc/host on my phpfpm containers 
172.17.0.1      host.docker.internal

I have message on phpstorm panel : "Waiting for incoming connection with ide key 'PHPSTORM'" 
I'm using macos.
My port 9003 is configurated on phpstorm
And also debug confiration host on phpstorm 

I tried to do : 
docker-compose down
bin/update
bin/start
bin/xdebug enable

Please, could you help me ?
What information do you need ?

**Comment by markshust** [comment]
@nverhoye I just made a quick update to the docker-compose.yml file above. I believe the `host.docker.internal` hostname was causing issues with Xdebug working within non-Linux environments.

Can you run `bin/update`, confirm Xdebug is all enabled and try again?

**Comment by nverhoye** [comment]
@markshust works better now. Thanks !

**Comment by nverhoye** [comment]
Hello, 

Have there been any updates recently?
I do regularly bin/update and it seems that xdebug does'nt work anymore.

This time i'm using Ubuntu.

I tried to do :
docker-compose down
bin/update
bin/start
bin/xdebug enable

**Comment by nverhoye** [comment]
Reinstalling project resolved issue :confused:
