### ISSUE TITLE
Problem vith elasticsearch .env "unexpected character"

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#597]
**Description**
unexpected character "." in variable name near "discovery.type=single-node\n\n# Set custom heap size to avoid memory errors\nES_JAVA_OPTS=-Xms1g -Xmx1g\n\n# Avoid test failures due to small disks\n# More info at https://github.com/markshust/docker-magento/issues/488\ncluster.routing.allocation.disk.threshold_enabled=false\nindex.blocks.read_only_allow_delete\n"

**Comment by torhoehn** [comment]
Yes, got the same error while creating a new project.

The environment variables aren't working as env_file. I'll create a PR to rollback this change.

**Comment by petskratt** [comment]
The reason it does not work: shell variable name can contain [a-zA-Z0-9_] but not dot.

Bash gives "env/elasticsearch.env: line 4: discovery.type=single-node: command not found" (to make issue findable by this error message as well)

**Comment by markshust** [comment]
Sorry about this! That's what happens when I make changes and forget to test a new config myself. Thanks @torhoehn for the PR, this should be all fixed.

**Comment by encryptblockr** [comment]
> The reason it does not work: shell variable name can contain [a-zA-Z0-9_] but not dot.
> 
> Bash gives "env/elasticsearch.env: line 4: discovery.type=single-node: command not found" (to make issue findable by this error message as well)

so why are we using dots in variable name if not supported with shell variable name?!!!?

**Comment by encryptblockr** [comment]
> Sorry about this! That's what happens when I make changes and forget to test a new config myself. Thanks @torhoehn for the PR, this should be all fixed.

your MR does not work with using `env_file:` with docker-compose
