### ISSUE TITLE
oneline setup script

### ISSUE THREAD

**Issue by bendan7** [markshust/docker-magento#603]
**Description**
After I entered my composer authentication username & password i got the next message:

The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.
fork/exec /usr/local/bin/com.docker.cli: bad file descriptor
Composer auth has been setup.
The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.
Creating a "magento/project-community-edition=2.4.3-p1" project at "./"

  [InvalidArgumentException]
  Project directory "/var/www/html/." is not empty.

**Comment by 4j4yk** [comment]
you might have composer v2, that's why it's failing. 

`hirak/prestissimo` requirements are  
```composer >=1.0.0 <2.0
PHP >=5.3, (suggest >=5.5, because curl_share_init)
ext-curl```

**Comment by markshust** [comment]
@bendan7 I think you are using an old version of docker-magento, because `prestissimo` hasn't been installed in the images since the release of Composer 2.
