### ISSUE TITLE
Support Image optimization based on query parameters image url option

### ISSUE THREAD

**Issue by PhilipRowe** [markshust/docker-magento#611]
**Description**
Magneto supports "Image optimization based on query parameters" which requires some Nginx changes to the magento sample  nginx.conf.sample defined here: https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-image-resize.html. This also needs:

`load_module /etc/nginx/modules/ngx_http_image_filter_module.so;`

to be added to the top of the https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/conf/nginx.conf, otherwise the docker app will fail to start as the Nginx module is not available.

**Steps To Reproduce**
1. Set the "Catalog media URL format" to "Image optimization based on query parameters" Stores > Settings > Configuration > General > Web > Url options
2. Update the nginx.conf.sample as per the guide: https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-image-resize.html
3. Restart the docker containers

**Expected Result**
Magento 2 Catalog product images will be resized by Nginx based on the query params in the URL.

**Actual Result**
The app container won't start due to the ngx_http_image_filter_module.so not being loaded

**Comment by markshust** [comment]
Hi @PhilipRowe, thanks for this ticket.

Where exactly does this line need to be added to the `nginx.conf` file?

`load_module /etc/nginx/modules/ngx_http_image_filter_module.so;`

The `nginx.conf.sample` file is installed when Magento is installed, so it's a project-level file and not a global file. For that reason, I can't make any updates to this file. That said, I believe adding the load_module line above should make it possible for anyone to add this update to their project, just by updating their `nginx.conf.sample` file?

Cheers,
Mark

**Comment by PhilipRowe** [comment]
Hi @markshust, Thanks for the response.

I believe it can't be added into the nginx.conf.sample if you look at this comment here: https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample#L29 I think it can only be added at the top of the main nginx conf, so this one: https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/conf/nginx.conf

I did add it at the top of here the main nginx conf file in the container and was able to get the module to load and process the images correctly.

Thanks,
Phil

**Comment by markshust** [comment]
Ok thanks for the updated info. I'll get this module added & loaded in the main Nginx config file 👍

**Comment by markshust** [comment]
@PhilipRowe appreciate your patience. I tested this update and it worked just as expected 👌.

Just built the new `markoshust/magento-nginx:1.18-6` image, so just updating to that image in your `docker-compose.yml` file should be all you need.
