### ISSUE TITLE
MacOs 12.1 SSL certificate error on fresh install

### ISSUE THREAD

**Issue by ahusar92** [markshust/docker-magento#615]
**Description**

When trying to install the docker setup, the SSL certificate is not correctly added in the system and the browsers throw a SSL certificate error (both Firefox and Chrome).

**Steps To Reproduce**
1. Run the one line install script `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.3-p1`
2. Open the local setup URL in browser (Firefox / Chrome)

**Expected Result**
The local installation works fine

**Actual Result**
There is an error regarding the SSL certificates for the local install
- on Firefox - Error code: SSL_ERROR_RX_RECORD_TOO_LONG
- on Chrome - ERR_SSL_PROTOCOL_ERROR

Info:
Chrome version: Version 97.0.4692.71
Firefox version: 96.0
OS Version: MacOs 12.1 on Mac M1Pro

**Comment by ahusar92** [comment]
Will close this issue - after more debugging, it seems that the errors are caused by antivirus system which is messing the SSL communication

**Comment by markshust** [comment]
@ahusar92 thanks, this issue will be helpful to others who have this same problem and stumble across this 👍
