### ISSUE TITLE
CMD wont allow Username input

### ISSUE THREAD

**Issue by cooperRjp** [markshust/docker-magento#620]
Trying to run on windows and at the Username stage I can't type anything. Tried running CMD as admin but no change.

Composer authentication required (repo.magento.com public and private keys):
    Username:

**Comment by cooperRjp** [comment]
Tried on another PC but have the same issue

**Comment by cooperRjp** [comment]
My work around was to run the install in the wsl environment instead

**Comment by artmouse** [comment]
> My work around was to run the install in the wsl environment instead

Use WSL2. Files place under WSL2. Use Win Terminal
No problems!

**Comment by markshust** [comment]
How were you trying to install it before? Yes I believe you *have* to run those commands in the WSL environment, since Windows doesn't have any knowledge of linux/etc.
