### ISSUE TITLE
missing parametr "debug" for xdebug

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#621]
**Description**

1. bin/xdebug enable
2. bin/xdebug status -> Xdebug debug mode has been enabled.
3. bin/cli cat /usr/local/etc/php/php.ini -> xdebug.mode = off
4. PHPStorm -> 
![xdebug](https://user-images.githubusercontent.com/527232/150572219-56d7262e-a6fd-4a8b-ac21-f3620aac1d2c.jpg)

**Comment by artmouse** [comment]
**bin/xdebug status** if **'xdebug.mode = debug'** 
![изображение](https://user-images.githubusercontent.com/527232/150588374-a257a403-8d92-441c-86e2-ceef155bab10.png)

**bin/xdebug status** if **'xdebug.mode = off'**
![изображение](https://user-images.githubusercontent.com/527232/150588917-f75789cf-525c-4916-91ea-c67b4ff723d2.png)

but if use bin/clinotty in xdebug script all OK

p.s. Windows 10 WSL2

**Comment by markshust** [comment]
You need to run `bin/xdebug enable` to enable it. It's turned off for performance reasons.

**Comment by markshust** [comment]
Sorry just re-read your post. I believe Windows may have an issue with `bin/cli`, but have been unable to verify this.
