### ISSUE TITLE
Setting up xdebug with WSL2 and VS Code

### ISSUE THREAD

**Issue by felipebazza** [markshust/docker-magento#623]
**Description**
Hey guys, just followed this [documentation ](https://github.com/markshust/docker-magento/discussions/372) and set up an existing Magento 2 2.4+ project succesfully. It all works like a charm, except for the debug function. 

Tried some things:
- Run bin/xdebug enable
- Install chrome debug extension and set IDE to PHPStorm
- Install PHP Debug extension on VS Code as requested ( Installed on the WSL env, not local )
- Manually created the launch.json and copied the same as it is [mentioned ](https://github.com/markshust/docker-magento/blame/master/compose/.vscode/launch.json) on the readme of this project 
- As I already worked with linux-based environments, started the debug function on VS Code typing F5, and it started listening to requests
- Flushed Magento cache using bin/magento c:f
- Tried to restart the page, it never stops at any breakpoint
- Last thing I tried was uninstalling the chrome extension and test it all over again - no success.

Maybe I'm doing something wrong or forgetting a step, can you help me set xdebug with VSCode within an WSL2 env ?

**Comment by artmouse** [comment]
> **Description** Hey guys, just followed this [documentation ](https://github.com/markshust/docker-magento/discussions/372) and set up an existing Magento 2 2.4+ project succesfully. It all works like a charm, except for the debug function.
> 
> Tried some things:
> 
>     * Install chrome debug extension and set IDE to PHPStorm
> 
>     * Install PHP Debug extension on VS Code as requested ( Installed on the WSL env, not local )
> 
>     * Manually created the launch.json and copied the same as it is [mentioned ](https://github.com/markshust/docker-magento/blame/master/compose/.vscode/launch.json) on the readme of this project
> 
>     * As I already worked with linux-based environments, started the debug function on VS Code typing F5, and it started listening to requests
> 
>     * Flushed Magento cache using bin/magento c:f
> 
>     * Tried to restart the page, it never stops at any breakpoint
> 
>     * Last thing I tried was uninstalling the chrome extension and test it all over again - no success.
> 
> 
> Maybe I'm doing something wrong or forgetting a step, can you help me set xdebug with VSCode within an WSL2 env ?

bin/xdebug enable ???

**Comment by felipebazza** [comment]
> bin/xdebug enable ???

Hey! Thanks for replying. Yes, already did bin/xdebug enable 

A php -v inside the container gives me
`PHP 7.4.26 (cli) (built: Dec  2 2021 14:46:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
    with the ionCube PHP Loader + ionCube24 v11.0.0, Copyright (c) 2002-2021, by ionCube Ltd.
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.71.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire`

**Comment by artmouse** [comment]
> > bin/xdebug enable ???
> 
> Hey! Thanks for replying. Yes, already did bin/xdebug enable
> 
> A php -v inside the container gives me
> 
> ```
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
>     with the ionCube PHP Loader + ionCube24 v11.0.0, Copyright (c) 2002-2021, by ionCube Ltd.
>     with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
>     with blackfire v1.71.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire```
> ```
what output when:
bin/cli cat /usr/local/etc/php/php.ini

**Comment by felipebazza** [comment]
> what output after bin/xdebug enable: bin/cli cat /usr/local/etc/php/php.ini

```
memory_limit = 4G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM

upload_max_filesize = 100M
post_max_size = 100M
max_input_vars = 10000

sendmail_path = "/usr/bin/msmtp -t"
```

**Comment by artmouse** [comment]
> > what output after bin/xdebug enable: bin/cli cat /usr/local/etc/php/php.ini
> 
> ```
> memory_limit = 4G
> max_execution_time = 1800
> zlib.output_compression = On
> cgi.fix_pathinfo = 0
> date.timezone = UTC
> 
> xdebug.mode = debug
> xdebug.client_host = host.docker.internal
> xdebug.idekey = PHPSTORM
> 
> upload_max_filesize = 100M
> post_max_size = 100M
> max_input_vars = 10000
> 
> sendmail_path = "/usr/bin/msmtp -t"
> ```

All OK - xdebug.mode = debug

Try add "host.docker.internal:172.17.0.1" to the app.extra_hosts parameter of docker-compose.yml, replacing 172.17.0.1 with the result of:

docker run --rm alpine ip route | awk 'NR==1 {print $3}'

**Comment by artmouse** [comment]
https://github.com/markshust/docker-magento/commit/4efef7ac2c6742201ab0ac49995ef774bad5a89e#diff-6279b4379956d40a7c808ee22b5f1005cb7d1f6bfa77d45adc2e004f7ef3e6f9

**Comment by felipebazza** [comment]
> Try add "host.docker.internal:172.17.0.1" to the app.extra_hosts parameter of docker-compose.yml, replacing 172.17.0.1 with the result of:
> 
> docker run --rm alpine ip route | awk 'NR==1 {print $3}'

The result of your command:
```
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
59bf1c3509f3: Already exists
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
172.17.0.1
```

This is the new chunk on docker-compose.yml 
```
services:
  app:
    image: markoshust/magento-nginx:1.18-5
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    extra_hosts: &appextrahosts
      - "host.docker.internal:172.17.0.1"
      ## M1 Mac support to fix Docker delay, see #566
```

Trying with xdebug helper extension activated and deactivated and with launch.json with the two options below for pathMappings (which I read from another issue yesterday)
`"/var/www/html": "${workspaceFolder}/src/"`
and
`"/var/www/html": "${workspaceFolder}"`

No stopping on my breakpoint yet

**Comment by felipebazza** [comment]
Oh I did a bin/restart after changing docker-compose.yml

**Comment by artmouse** [comment]
> Oh I did a bin/restart after changing docker-compose.yml

And?.....

**Comment by felipebazza** [comment]
> And?.....

Not working yet!

**Comment by artmouse** [comment]
I'm install VScode on Win and run debug...
All working!
![изображение](https://user-images.githubusercontent.com/527232/150976036-5d091866-6f5b-418c-b4ca-db56d61a0678.png)

**Comment by felipebazza** [comment]
I noted some differences between your screen and mine.

- It seems your VSCode isn't "inside" the WSL. Mine is, since it's appearing on the inferior left side with a green background

Can it be this difference that is making my debug don't work?

![image](https://user-images.githubusercontent.com/31210648/150977338-27f7d183-77e1-4498-be79-527deaef97ec.png)

**Comment by felipebazza** [comment]
Just tested trying to open a local VSCode window but the debug didn't work as well. It's something else

**Comment by felipebazza** [comment]
up

**Comment by artmouse** [comment]
> up

Show your hosts file from windows...
Must have entries:
![изображение](https://user-images.githubusercontent.com/527232/152816873-9989ce1b-3bc7-4ad9-9925-7a48c6659019.png)

**Comment by markshust** [comment]
Related issue https://github.com/markshust/docker-magento/issues/634

**Comment by markshust** [comment]
> I'm install VScode on Win and run debug... I use WSL2 All working! ![изображение](https://user-images.githubusercontent.com/527232/150976036-5d091866-6f5b-418c-b4ca-db56d61a0678.png)

What exactly did you change to get this working? This proves that it's very possible to run Xdebug with WSL2 (on both PhpStorm & VSCode, since they most likely use the same method of connecting), but there is probably a change someplace happening we are unaware about.

**Comment by artmouse** [comment]
> 

I work with PhpStorm. There debug works fine. I installed VScode only to check the debug work.
I use WSL2 and Docker desktop. Didn't make any changes. Only add magento domain to the hosts file.

**Comment by felipebazza** [comment]
Indeed my host file doesn't have this last line pointing to the magento domain. I will add it and test soon.

**Comment by felipebazza** [comment]
It didn't work again. 
I think it's time to wrap up things for we to actually see what's going on right now.

My environment right now:
WSL2
Magento 2.4
PHP 7.4
xDebug enabled, v3.1.2
Using [this file](https://github.com/markshust/docker-magento/blame/master/compose/.vscode/launch.json) as launch.json
Added 127.0.0.1 magento.test on windows hosts file
PHP Debug v1.23.0 from Xdebug installed on WSL2 environment through VSCode
Xdebug helper installed on Chrome, PhpStorm IDE key selected

**Comment by artmouse** [comment]
I remembered. I also added a file: 

c:\Users\userтфьу\.wslconfig

```
[wsl2]
memory=6GB
swap=0
localhostForwarding=true
```

**Comment by markshust** [comment]
@felipebazza something else for you to check, see last comment 👆

**Comment by felipebazza** [comment]
Yeah, so my file only had the memory attr, then I copied these attributes, restarted the host and wsl2, but it didnt' work yet.

**Comment by felipebazza** [comment]
I finally got how to run xdebug with docker magento in a WSL environment using VC Code
@markshust I can write a documentation, just let me know where you think is better to do so. Maybe on the WSL page? https://github.com/markshust/docker-magento/discussions/372

**Comment by josesoaresif** [comment]
> I finally got how to run xdebug with docker magento in a WSL environment using VC Code @markshust I can write a documentation, just let me know where you think is better to do so. Maybe on the WSL page? #372

A wsl2 debug guide would be very well received.
I followed the mentioned issue, but didn't quite get what I needed to do in order to debug the container.
I know I'm talking about getting my "food chewed for me" but I have been trying without success.

**Comment by felipebazza** [comment]
> > I finally got how to run xdebug with docker magento in a WSL environment using VC Code @markshust I can write a documentation, just let me know where you think is better to do so. Maybe on the WSL page? #372
> 
> A wsl2 debug guide would be very well received. I followed the mentioned issue, but didn't quite get what I needed to do in order to debug the container. I know I'm talking about getting my "food chewed for me" but I have been trying without success.

Hey Jose no worries! we should help each other whenever is possible. If @markshust doesn't pick a place for me to document it until Monday, I'll do it here, ok?

**Comment by josesoaresif** [comment]
> I finally got how to run xdebug with docker magento in a WSL environment using VC Code @markshust I can write a documentation, just let me know where you think is better to do so. Maybe on the WSL page? #372

A wsl2 debug guide would be very well received.
I followed the mentioned issue, but didn't quite get what I needed to do in order to debug the container.
I know I'm talking about getting my "food chewed for me" but I have been trying without success.

**Comment by josesoaresif** [comment]
> Hey Jose no worries! we should help each other whenever is possible. If @markshust doesn't pick a place for me to document it until Monday, I'll do it here, ok?

OK. Thank you very much.

**Comment by markshust** [comment]
@felipebazza if you can make a PR right on the main readme, that would be great! Or you can create a new Discussion thread at https://github.com/markshust/docker-magento/discussions and I can link the readme into it (that may be easier).

**Comment by josesoaresif** [comment]
Just got it to work on my set-up using the following:

1st - I added a volume to docker-compose.dev.yml 

```yml
version: "3"

services:
  app:
    volumes: &appvolumes
      ## Host mounts with performance penalty, only put what is necessary here
 
      - ./images/php/conf/php.ini:/usr/local/etc/php/php.ini:cached
```

2nd - add a php.ini file as instructed by @markshust at root of project images/php/conf/php.ini with content:

```ini
memory_limit = 4G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.discover_client_host=false
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey="VSCODE"

upload_max_filesize = 100M
post_max_size = 100M
max_input_vars = 10000

sendmail_path = "/usr/bin/msmtp -t"
``` 

3rd - use the following config for launch.json. Note that the "pathMappings" is pointing the computer folder to the src which has the magento code and not the main project root.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for Xdebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "hostname": "localhost",
      "pathMappings": {
        "/var/www/html/":"${workspaceRoot}/src"
      }
    }
  ]
}
```

**Comment by felipebazza** [comment]
Great to hear you manage to solve the issue too @josesoaresif !
@markshust I created a PR with the changes on the README: 
https://github.com/markshust/docker-magento/pull/810

**Comment by markshust** [comment]
Great @felipebazza! Really appreciate the documentation, all merged in 🎉

**Comment by itdecowood** [comment]
> Just got it to work on my set-up using the following:
> 
> 1st - I added a volume to docker-compose.dev.yml
> 
> version: "3"
> 
> services:
>   app:
>     volumes: &appvolumes
>       ## Host mounts with performance penalty, only put what is necessary here
>  
>       - ./images/php/conf/php.ini:/usr/local/etc/php/php.ini:cached
> 2nd - add a php.ini file as instructed by [@markshust](https://github.com/markshust) at root of project images/php/conf/php.ini with content:
> 
> memory_limit = 4G
> max_execution_time = 1800
> zlib.output_compression = On
> cgi.fix_pathinfo = 0
> date.timezone = UTC
> 
> [xdebug]
> xdebug.mode=debug
> xdebug.start_with_request=yes
> xdebug.discover_client_host=false
> xdebug.client_host=host.docker.internal
> xdebug.client_port=9003
> xdebug.idekey="VSCODE"
> 
> upload_max_filesize = 100M
> post_max_size = 100M
> max_input_vars = 10000
> 
> sendmail_path = "/usr/bin/msmtp -t"
> 3rd - use the following config for launch.json. Note that the "pathMappings" is pointing the computer folder to the src which has the magento code and not the main project root.
> 
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "name": "Listen for Xdebug",
>       "type": "php",
>       "request": "launch",
>       "port": 9003,
>       "hostname": "localhost",
>       "pathMappings": {
>         "/var/www/html/":"${workspaceRoot}/src"
>       }
>     }
>   ]
> }

Works for me! thanks, i think must be documented in readme or something

**Comment by os3albert** [comment]
I had your same problem, I did what you have written in the readme but didn't work, I added a VSCode extension called PHP from DEVSENSE
