### ISSUE TITLE
uninterruptible sleep(D) state on all bin/magento commands

### ISSUE THREAD

**Issue by sanaeefar-saeed** [markshust/docker-magento#637]
**Description**
uninterruptible sleep state on all bin/magento commands

**Steps To Reproduce**
1. local setup a magento project && bin/start && run 1 command eg bin/magento se:up
**Expected Result**
you should be able to continue working!

**Actual Result**
stuck on all bin/magento commands from cli
few notes:
bin/composer works
all containers are up and running 
checked it on different magento versions and different projects
if you check the PID relates to the command you will see all bin/magento command have "D"(uninterruptible sleep state) under the stats column
you cant even abort the the prev command you entered 
the only way you could make it works just restart the docker engine and it works for few mins and the again....

**here is the output of this command: docker-compose --verbose up**

compose.cli.verbose_proxy.proxy_callable: docker create_container <- (image='markoshust/magento-php:7.2-fpm', tty=True, volumes={'/var/www/.composer': {}, '/var/www/html': {}, '/sock': {}, '/etc/nginx/certs': {}}, name='shops_phpfpm_1', detach=True, environment=['affinity:container==bfce8542053cbf3b0f45fe2d0d9ad2e08b206a27dc87a30c5c2cc3b8aeb15c03'], labels={'com.docker.compose.project': 'shops', 'com.docker.compose.service': 'phpfpm', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.project.working_dir': '/Users/devall/Sites/shops', 'com.docker.compose.project.config_files': 'docker-compose.yml', 'com.docker.compose.container-number': '1', 'com.docker.compose.version': '1.29.2', 'com.docker.compose.config-hash': '87f0f92870fe77db702d5393200a0d979657fbfae3fbe14d856b8a3afb502b63'}, host_config={'NetworkMode': 'shops_default', 'VolumesFrom': [], 'Binds': ['/Users/devall/.composer:/var/www/.composer:delegated', 'shops_appdata:/var/www/html:rw', 'shops_sockdata:/sock:rw', 'shops_ssldata:/etc/nginx/certs:rw', 'c749aa50dc4c271ed75919b451dfb8062794a018b16794d01f1bb089a1104d23:/var/www:rw'], 'PortBindings': {}, 'Links': ['shops_db_1:shops_db_1', 'shops_db_1:db', 'shops_db_1:db_1'], 'LogConfig': {'Type': '', 'Config': {}}}, networking_config={'EndpointsConfig': {'shops_default': {'Aliases': ['phpfpm'], 'IPAMConfig': {}}}})
compose.parallel.feed_queue: Pending: {<Service: app>}
compose.parallel.feed_queue: Pending: set()
compose.cli.verbose_proxy.proxy_callable: docker create_container -> {'Id': '7188c99d057c825ef1ca6f5774c3785f8921bc40edc32f4db4825418888e9681',
 'Warnings': []}
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('7188c99d057c825ef1ca6f5774c3785f8921bc40edc32f4db4825418888e9681')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
 'Args': ['php-fpm'],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['php-fpm'],
            'Domainname': '',
            'Entrypoint': ['docker-php-entrypoint'],
            'Env': ['affinity:container==bfce8542053cbf3b0f45fe2d0d9ad2e08b206a27dc87a30c5c2cc3b8aeb15c03',
                    'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
...
compose.cli.verbose_proxy.proxy_callable: docker attach <- ('7188c99d057c825ef1ca6f5774c3785f8921bc40edc32f4db4825418888e9681', stdout=True, stderr=True, stream=True)
compose.cli.verbose_proxy.proxy_callable: docker attach -> <docker.types.daemon.CancellableStream object at 0x1040a4640>
compose.cli.verbose_proxy.proxy_callable: docker disconnect_container_from_network <- ('7188c99d057c825ef1ca6f5774c3785f8921bc40edc32f4db4825418888e9681', 'shops_default')
compose.cli.verbose_proxy.proxy_callable: docker disconnect_container_from_network -> None
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=shops', 'com.docker.compose.service=db', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('201246f29156396c4b2abaaeba216124680d67d0cb1f2e9f2df07a359b3fe61e')
compose.parallel.feed_queue: Pending: {<Service: app>}
compose.parallel.feed_queue: Pending: set()
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
 'Args': ['mysqld'],
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['mysqld'],
            'Domainname': '',
            'Entrypoint': ['/docker-entrypoint.sh'],
            'Env': ['MYSQL_ROOT_PASSWORD=magento',
                    'MYSQL_DATABASE=magento',
...
compose.cli.verbose_proxy.proxy_callable: docker connect_container_to_network <- ('7188c99d057c825ef1ca6f5774c3785f8921bc40edc32f4db4825418888e9681', 'shops_default', aliases=['phpfpm', '7188c99d057c'], ipv4_address=None, ipv6_address=None, links=[('shops_db_1', 'db'), ('shops_db_1', 'shops_db_1'), ('shops_db_1', 'db_1')], link_local_ips=None)
compose.cli.verbose_proxy.proxy_callable: docker connect_container_to_network -> None
compose.cli.verbose_proxy.proxy_callable: docker start <- ('7188c99d057c825ef1ca6f5774c3785f8921bc40edc32f4db4825418888e9681')
compose.parallel.feed_queue: Pending: {<Service: app>}
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: {<Service: app>}
.
.
.
compose.parallel.parallel_execute_iter: Failed: <Container: bfce8542053c_shops_phpfpm_1 (bfce85)>
compose.parallel.feed_queue: Pending: set()

ERROR: for bfce8542053c_shops_phpfpm_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
compose.parallel.parallel_execute_iter: Failed: <Service: phpfpm>
compose.parallel.feed_queue: Pending: {<Service: app>}
compose.parallel.feed_queue: <Service: app> has upstream errors - not processing
compose.parallel.parallel_execute_iter: Failed: <Service: app>
compose.parallel.feed_queue: Pending: set()

ERROR: for phpfpm  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: compose.cli.errors.log_timeout_error: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by sanaeefar-saeed** [comment]
Solved by check the "Use gRPC FUSE for file sharing" checkbox on docker configuration  
preference -> general -> Use gRPC FUSE for file sharing

**Comment by rangerz** [comment]
> Solved by check the "Use gRPC FUSE for file sharing" checkbox on docker configuration preference -> general -> Use gRPC FUSE for file sharing

Good to know

**Comment by markshust** [comment]
gRPC should be the default on new installs also 👍 You don't want to deviate from the default settings unless you had a very specific use-case.
