### ISSUE TITLE
Using Manual Setup > Existing Projects with Magento cloud 2.4

### ISSUE THREAD

**Issue by isyan** [markshust/docker-magento#644]
I tried setting up my magento cloud local setup on this but I'm encountering an error that says: 
> Vendor autoload is not found. Please run 'composer install' under application root directory.

Which I already did and it installed the composer stuffs on src > vendor.  How should I troubleshoot this? Thanks

**Comment by markshust** [comment]
Have you executed `bin/composer install`? `bin/composer` is different from `composer`. The former runs the command within the Docker container, the latter runs the command on your host machine.
