### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by alam-ejaz** [markshust/docker-magento#648]
**Description**
![image](https://user-images.githubusercontent.com/72202738/155516687-66d1cc6f-8314-4a10-aee7-542905372ed5.png)

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**

**Comment by markshust** [comment]
"Ports are not available" is the error... looks like you have something running on port 80. You'll need to kill that (most likely Apache or Nginx running on your host) before attempting to run this project.
