### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown

### ISSUE THREAD

**Issue by divictor06** [markshust/docker-magento#650]
**Description**
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown

I was try setup existing enviroment, I copy the folder proyect in the src path and all good, but when I was try change the domain with the command bin/magento setup-domain, return this error

**Steps To Reproduce**
1. bin/setup-domain mydomain.test

**Expected Result**
domain created

**Actual Result**
Your system password has been requested to add an entry to /etc/hosts...
127.0.0.1 ::1 mydomain.test
Set https://mydomain.test/ to web/secure/base_url and web/secure/base_url
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown

System Pop OS 21

**Comment by markshust** [comment]
I'm unable to replicate, and I've never heard of Pop OS and probably don't want to support it because it's market share is close to 0%. However, if you wanted to make a PR to fix this and it's backwards-compat with all of the other systems, I'll take it in.

**Comment by LiamKarlMitchell** [comment]
Having same issue on WSL 2 Ubuntu 21.04

**Comment by markshust** [comment]
Possible dupe of https://github.com/markshust/docker-magento/issues/731
