### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by mao3li** [markshust/docker-magento#654]
system: ubuntu vps
When i execute "bin/cli git clone git@github.com:magento/magento2.git ."

Tips: 
Cloning into '.'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/var/www/.ssh/known_hosts).
Load key "/var/www/.ssh/id_rsa": Is a directory
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by markshust** [comment]
Do you have an SSH key set up on your local machine within the `~/.ssh` directory? If not, you can create one with `ssh-keygen`.

This isn't an issue with this project, so going to close this ticket out.

**Comment by mao3li** [comment]
> 

I tried it, but it didn't work

**Comment by markshust** [comment]
@mao3li try to clone the repo out from your host, rather than doing it with `bin/cli` which would only run it in the container.
