### ISSUE TITLE
Multiple domain setup with magento docker setup

### ISSUE THREAD

**Issue by malikabid** [markshust/docker-magento#655]
**Description**

1. I have setup magento 2.4 with the markshust/docker-magento and it is working fine.
2. Now my setup is multi-website with different domains (e.g. **https://ukwebsite.local** and **https://usawebsite.local**)
3. **_How can I setup this?_**

**Comment by markshust** [comment]
Hi @malikabid, have you seen this lesson? https://courses.m.academy/courses/487758/lectures/14780970

This should document how to accomplish this. If you are still having trouble after follow the steps in this lesson, please let me know and I can re-open this ticket.

**Comment by malikabid** [comment]
Hi @markshust 
Thank you for the reference.
I did a little differently - 
I added the following line to the `docker-compose.dev.yml` file
`- ./src/nginx.default.conf:/etc/nginx/conf.d/default.conf:cached`
instead of adding a new Dockerfile.

This and add the Nginx configuration in the file.

The rest of the steps are the same.

Will it have any bad/good impact overall?

**Comment by markshust** [comment]
That method is totally ok 👍 No performance implications, since it's just use in the Nginx config.
