### ISSUE TITLE
Disable SSL on local environment

### ISSUE THREAD

**Issue by shankar15498** [markshust/docker-magento#659]
I ran the setup using the following command in Ubuntu 21 and I was facing some issues regarding SSL certificates. Due to this, am not able to connect to the Magento server from my custom program. I would like to disable SSL and use `HTTP` instead of `HTTPS` since I don't really need a secure connection in my local setup. Is there a way to do that?

Command: `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento24.test 2.4.3-p1`

**Steps To Reproduce**
1. Run: `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento24.test 2.4.3-p1`
2. Open magento24.test on Chrome

**Expected Result**
HTTPS connection loads in the browser without any warnings

**Actual Result**
![image](https://user-images.githubusercontent.com/55386291/157699911-40f36211-95c5-4998-b04e-670b0001a8c1.png)

Possible duplicate of issue #222

**Comment by markshust** [comment]
I don't ever want to disable SSL for this dev environment, as there are just too many reasons why not to do this. If you are having issues creating SSL for Linux though, please open up a ticket for that with all of the info of what operating system, version, etc you are using, as that SSL cert should be auto-installed when this env is set up.

**Comment by ivanaugustobd** [comment]
I agree with @markshust, but I'm also 100% pro-freedom of doing whatever you want in open source, so there you go (a friend of mine ask me about it today):
```
docker compose exec -it app sh
cd /etc/nginx/conf.d/
vi default.conf
```

Now comment these lines:
![image](https://github.com/markshust/docker-magento/assets/4603111/26abddbe-0d87-4f98-978a-7ea5cf27d113)

Run a `bin/restart app`, make sure to update the base_url on your _app/etc/env.php_ properly and _voi là_:
![image](https://github.com/markshust/docker-magento/assets/4603111/11635ff3-cd1a-433d-9d06-ca07db039ebb)

> 💡 You can create a custom image based on [Mark's one](https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/Dockerfile) changing its [default.conf](https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/conf/default.conf) file for making this permanent for all of your projects

Have fun and do **_not_** use this as your daily drive for local development, instead manually import the cert authority  in your browser if needed (chrome://settings/certificates if you're using Chrome, tab "Authorities" -> click on "Import" and choose the file generated by the `bin/setup-ssl some-domain.test` command) 😉

**Comment by maximst** [comment]
> I agree with Mark, but I'm also 100% pro-freedom of doing whatever you want in open source, so there you go (a friend of mine ask me about it today):
> 
> ```
> docker-compose exec -it app sh
> vi /etc/nginx/conf.d/default.conf
> ```
> 
> Now comment these lines: ![image](https://private-user-images.githubusercontent.com/4603111/253692205-0320bcac-e803-4134-b5cf-1f8fed859ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODgxODIsIm5iZiI6MTcwMjM4Nzg4MiwicGF0aCI6Ii80NjAzMTExLzI1MzY5MjIwNS0wMzIwYmNhYy1lODAzLTQxMzQtYjVjZi0xZjhmZWQ4NTlmZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTMzMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ5ODI2YzA4NGMyZWY4MjA0NDU5ZDRkZjFkNTA2NzNmNmM2ZDI4NTdmZjNhZjhiODAwNDVmMjE1N2JhNWVlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oYS1CxJIw23xR17Q63bKWmmD8lfSPnoZ7rKWStyGEB0)
> 
> Run a `bin/restart app`, make sure to update the base_url on your _app/etc/env.php_ properly and _voi là_: ![image](https://private-user-images.githubusercontent.com/4603111/253689231-11635ff3-cd1a-433d-9d06-ca07db039ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODgxODIsIm5iZiI6MTcwMjM4Nzg4MiwicGF0aCI6Ii80NjAzMTExLzI1MzY4OTIzMS0xMTYzNWZmMy1jZDFhLTQzM2QtOWQwNi1jYTA3ZGIwMzllYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTMzMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU3OTQ4M2JlMGY5NmVhMmFjYjA5NmQ1YjExNGM3M2JhZTU3ZTQ0NmEzOWRlMGJhYmNkZWQxOGFlYWU0ZDkyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.doDfbCO50bNys0qvtUehDtz-k5l2W1Adc5WQke1GxkQ) (be aware of browser redirect cache, let your devtools open with the "Disable Cache" checked on Network tab, while also explicitly inputting http://your-domain.test on the url as modern browsers use the https:// protocol by default)
> 
> > 💡 You can create a custom docker image based on [Mark's one](https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/Dockerfile) changing its [default.conf](https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/conf/default.conf) file
> 
> Have fun and do **_not_** use this as your daily drive for local development, instead manually import the cert authority in your browser if needed (chrome://settings/certificates if you're using Chrome, tab "Authorities" -> click on "Import" and choose the file generated by the `bin/setup-ssl some-domain.test` command) 😉

No, this is not enough to use HTTP
The redirection is done inside Magento.
`
curl "http://localhost" -v
...
< X-Powered-By: PHP/8.2.12
...
< Location: https://<somedomain>/
...
`
