### ISSUE TITLE
Trying to get this to run on my macbook pro- getting Could not validate a connection to Elasticsearch.

### ISSUE THREAD

**Issue by randyparies** [markshust/docker-magento#660]
**Description**
I have tried the one line install and the manual install on a new MacBook Pro M1
I get the error  during bin/setup magento.test

In SearchConfig.php line 81:

  Could not validate a connection to Elasticsearch. No alive nodes found in y
  our cluster

**Steps To Reproduce**
1. following the doc for manual  setup
2. bin/download 2.4.3-p1
3. bin/setup magento.test and this generates the error

In SearchConfig.php line 81:

  Could not validate a connection to Elasticsearch. No alive nodes found in y
  our cluster

**Expected Result**

**Actual Result**

**Comment by randyparies** [comment]
@aashishgurung i have moved on to something else, but it was only 4.5 gb or something like that

**Comment by aashishgurung** [comment]
@randyparies Thanks for the reply. Don't know what went wrong before. It worked after I removed everything and started from scratch.
