### ISSUE TITLE
access to app directory from host machine on an M1 mac

### ISSUE THREAD

**Issue by randyparies** [markshust/docker-magento#663]
**Description**
Hello,

I am trying to access the app/code directory from the host computer.

There is the named volume appdata, but i can not find where it lives on the host. 

I am writing an extension for magento and trying to point/link my source to /var/www/html/app/code

This is really not a bug but not sure where else to ask.  

Thanks for any help

**Comment by markshust** [comment]
Answered above so going to close this one out 👍
