### ISSUE TITLE
XDebug Performance - latest Docker Desktop

### ISSUE THREAD

**Issue by leeethompson** [markshust/docker-magento#665]
Hi,

I've (in the last couple of days) updated Docker Desktop to the latest version (on Mac).  Since the update, performance with Xdebug is abysmal - bordering on unworkable in some instances if I clear the cache c. 5 - 7 minutes to get to a point where I can get to a breakpoint.  If I need to go into admin to check some configuration settings, I just disable Xdebug because the wait time is just silly.

Disabling Xdebug alleviates this issue immediately.  I was wondering if anyone else has had any issues recently?  I've always noticed performance degradation whilst having Xdebug enabled but its always been manageable.  This latest version of Docker Desktop seems to have done **something**.  

Are there additional settings that I've just overlooked?

Thanks,
Lee.

**Comment by leeethompson** [comment]
Seems I've been a little hasty and just needed to be a little more clever with the google search:
https://github.com/docker/for-mac/issues/3455

This has just transformed the environment back to something thats workable using Xdebug again - hopefully this helps anyone else searching around this issue!

**Comment by markshust** [comment]
Thanks for making us aware of this. Was the issue only prevalent for a specific version of Docker Desktop? I have yet to experience any slowdowns (perhaps I'm on another version).

**Comment by leeethompson** [comment]
I upgraded to 4.6.1 (76265) last week.  It could possibly just be because I don't shut my mac down properly each time. 
 When restarted all was ok until the screen went to sleep and performance collapsed when I brought it back to life.  Hopefully that should be the end of it though - I've not noticed any major issues as of yet :)

**Comment by kerryj89** [comment]
> I upgraded to 4.6.1 (76265) last week. It could possibly just be because I don't shut my mac down properly each time. When restarted all was ok until the screen went to sleep and performance collapsed when I brought it back to life. Hopefully that should be the end of it though - I've not noticed any major issues as of yet :)

The upgrade might've replace the `tsc=reliable` in cmdline.  I downloaded the new Docker release and it doesn't have that line or expose itself as an option yet.
