### ISSUE TITLE
Cant get the one line script to run. It asks for Uri

### ISSUE THREAD

**Issue by ikrowni** [markshust/docker-magento#674]
**Description**
Windows 10 with docker desktop installed.
After entering the 1 line script i get this

```
cmdlet Invoke-WebRequest at command pipeline position 1
Supply values for the following parameters:
Uri:
```

**Steps To Reproduce**
1.  Create directory called `magento`
2. bring powershell up into that directory and use the line `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- compumax.test 2.4.3-p1`

**Expected Result**
The installer should begin running

**Actual Result**
Asks for Uri

**Comment by steveberrill** [comment]
I have the same issue on Windows 10, Hyper-v and containers are enabled, also confirmed WLS2 is installed

getting this

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.4

cmdlet Invoke-WebRequest at command pipeline position 1
Supply values for the following parameters:
Uri:

**Comment by markshust** [comment]
I remember some sort of weird issue cropping up when copying/pasting the pipe delimiter `|` on specific operating systems. Maybe try manually typing the entire line, or just that character to see if it resolves this?

**Comment by steveberrill** [comment]
> I remember some sort of weird issue cropping up when copying/pasting the pipe delimiter `|` on specific operating systems. Maybe try manually typing the entire line, or just that character to see if it resolves this?

I tried this but still no use. Here is what else i tried

- typed out manually
- re-install docker
- switch to Hype-V

**Comment by tvaughan73** [comment]
I am having the same issue.  Did anyone ever get it resolved?

**Comment by steveberrill** [comment]
> Use WSL for Windows.

I already tried this but doesn't work for me.

**Comment by artmouse** [comment]
> > Use WSL for Windows.
> 
> I already tried this but doesn't work for me.

What exactly doesn't work?

**Comment by steveberrill** [comment]
> > > Use WSL for Windows.
> > 
> > 
> > I already tried this but doesn't work for me.
> 
> What exactly doesn't work?

see my post above
https://github.com/markshust/docker-magento/issues/674#issuecomment-1193299360

**Comment by artmouse** [comment]
> > > > Use WSL for Windows.
> > > 
> > > 
> > > I already tried this but doesn't work for me.
> > 
> > 
> > What exactly doesn't work?
> 
> see my post above [#674 (comment)](https://github.com/markshust/docker-magento/issues/674#issuecomment-1193299360)

I hope you ran the command from the Ubuntu terminal?

**Comment by steveberrill** [comment]
> > > > > Use WSL for Windows.
> > > > 
> > > > 
> > > > I already tried this but doesn't work for me.
> > > 
> > > 
> > > What exactly doesn't work?
> > 
> > 
> > see my post above [#674 (comment)](https://github.com/markshust/docker-magento/issues/674#issuecomment-1193299360)
> 
> I hope you ran the command from the Ubuntu terminal?

yes i did and also tried BASH. I will give it another go tonight ;)

**Comment by markshust** [comment]
Closing this as unable to replicate

**Comment by Quentin-Sch** [comment]
Same

**Comment by nickyichov** [comment]
I had the same issue but [this](https://stackoverflow.com/a/27723225/14558555) fixed it for me

**Comment by mblaw1011** [comment]
Same issue
