### ISSUE TITLE
Page Builder was rendering for 5 seconds without releasing locks

### ISSUE THREAD

**Issue by sibelius** [markshust/docker-magento#679]
**Description**
I'm having the same issue as this https://github.com/magento/magento2/issues/34898

the fix is in this blog post https://webkul.com/blog/fixed-page-builder-was-rendering-for-5-seconds-without-releasing-locks-error-in-magento-2-4-3-p1/

**Steps To Reproduce**
1. try to modify page layout on admin

**Expected Result**
it saves

**Actual Result**
it keeps loading

How can I modify nginx config using this docker-magento?

**Comment by markshust** [comment]
This isn't an issue with this project, so I'm closing it out. You can open up a Discussion next time to ask how to do something, but for this one you can refer to the video at https://courses.m.academy/courses/set-up-magento-2-development-environment-docker/lectures/9064349 for info on how to modify the nginx.conf file.
