### ISSUE TITLE
Magento data-migration-tool is not PHP 8.1 compatible

### ISSUE THREAD

**Issue by andyt** [markshust/docker-magento#683]
The data migration tool produces deprecation errors when run using PHP 8.1.

Obviously not an issue with this code base, but it is a significant blocker when migrating a site that could be documented.

To reproduce:

- add data-migration-tool to project as per instructions
- run data-migration-tool

Expected result: no deprecated functionality warnings.

Actual result: many warnings!

**Comment by andyt** [comment]
My solution - downgrade to PHP 7.4 during migration.

**Comment by markshust** [comment]
Yea, going to close this one out as it's not an issue with this repo. But that said, Magento 2.4.4 seems to work just fine on PHP 7.4, so your solution to downgrade during the migration is appropriate 👍
