### ISSUE TITLE
Blackfire APM attempting to run even if not configured about docker

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#700]
**Description**
We are seeing `[Error] APM: Locking APM for 300 seconds for reason: Cannot connect to the agent` very frequently in our logs. I assume this is coming from Blackfire, as it is installed in these php images.

Also at this different point in time, there is a delay of 10s when opening a web page.

https://coder.social/craftcms/docker/issues/55

**Steps To Reproduce**
1. Start Docker
2. Open web page

**Expected Result**
When disabled Blackfire php extension
![изображение](https://user-images.githubusercontent.com/527232/167404507-7dffb0ac-10ec-4e5a-9ba6-1e00b6bb5d4e.png)

**Actual Result**
When enabled Blackfire php extension
![изображение](https://user-images.githubusercontent.com/527232/167404119-cc706d47-892e-426b-92ad-8f106b515107.png)

![изображение](https://user-images.githubusercontent.com/527232/167404156-3d955e89-c00f-4359-b973-fcaeffaba493.png)

**Comment by markshust** [comment]
I'm unable to replicate any issue, and cannot get requests to delay 10 seconds. What specific docker-magento images are you running, and are there steps to follow to replicate this? What O/S are you running? Blackfire should be disabled by default.

**Comment by artmouse** [comment]
Someone can confirm?

**Comment by markshust** [comment]
> The delay appears only when there is an error in the logs associated with the Blackfire extension.

Why do you have a blackfire log file? Can you not just delete it? 😀

**Comment by artmouse** [comment]
> > The delay appears only when there is an error in the logs associated with the Blackfire extension.
> 
> Why do you have a blackfire log file? Can you not just delete it? 😀

Mark, I'm just tired of deleting it every time. 😀

**Comment by markshust** [comment]
Tagging with wontfix due to lazyness of the ticket filer 😆

**Comment by mironsoft75** [comment]
I get the same error:

[27-Dec-2023 21:37:33] WARNING: [pool www] child 16 said into stderr: "Wed Dec 27 21:37:33 2023 (16): [Error] APM: Locking APM for 300 seconds for reason: Cannot connect to the agent"

Windows 11. WSL2, Ubuntu 22.04  PHP8.2 Latest Image

**Comment by mpchadwick** [comment]
Just noting that I spun up a vanilla environment last Friday with this and Blackfire _was_ initially enabled. Performance was abysmal for me until I disabled Blackfire and it instantly got better. I am running an Intel Mac
