### ISSUE TITLE
There must be at lest 6GB of RAM allocated to docker to continue.

### ISSUE THREAD

**Issue by wuhui3344** [markshust/docker-magento#708]
**Description**
MAC Pro 8GB

**Steps To Reproduce**
1. Bin/setup magento.test

**Expected Result**
There must be at lest 6GB of RAM allocated to docker to continue.

**Actual Result**

**Comment by rangerz** [comment]
The 6GB setting is for Docker Desktop setting, not your OS capability

![image](https://user-images.githubusercontent.com/3338473/168515030-6cc107e6-8913-4921-abb6-8b021b7b7a96.png)

**Comment by wuhui3344** [comment]
thanks .
