### ISSUE TITLE
Same steps are not working for UBUNTU 18 LTS

### ISSUE THREAD

**Issue by krunal2212** [markshust/docker-magento#709]
**Description**
Its great example to start in a minutes but when we talk about Ubuntu then its not working at all, Can anyone please share those steps ?

**Comment by artmouse** [comment]
> 

Working like a charm!
Install docker according to instructions and follow the Mark Shust docker-magento instructions step by step.

**Comment by markshust** [comment]
@krunal2212 have you seen the Linux instructions at https://github.com/markshust/docker-magento#linux ?

I'm closing this one out, as @artmouse confirmed it was working. Please let me know if you have any other issues though.
