### ISSUE TITLE
Can't start xdebug (device or ressource busy)

### ISSUE THREAD

**Issue by amokato** [markshust/docker-magento#713]
**Description**
When I run `bin/xdebug enable` I am suddenly getting the error:
`sed: cannot rename /usr/local/etc/php/sed9ap3Fe: Device or resource busy
` I restarted the docker env etc but nothing helped so far. I am running the latest env on MacOS Monterrey (Intel Macbook Pro)

**Steps To Reproduce**
1. run bin/xdebug enable

**Expected Result**
xdebug is enabled

**Actual Result**
Error: `sed: cannot rename /usr/local/etc/php/sed9ap3Fe: Device or resource busy
` xdebug is still disabled

The file sed9ap3Fe does not exist in the container nor in the local system.

**Comment by markshust** [comment]
I'm unable to replicate this on a fresh build, all works as expected. The `/usr/local/etc/php` dir should only exist in a local Docker volume, so there's really no reason this should be happening. I'd suggest to blow away your current install with `bin/removeall`, remove the entire project directory, and install it again from scratch.
