### ISSUE TITLE
bin/start fails - There must be at least 6GB of RAM allocated to Docker to continue.

### ISSUE THREAD

**Issue by carylewis** [markshust/docker-magento#720]
On Windows with 6GB of RAM allocated to wsl2, docker info displays:

`Total Memory: 5.795GiB`

So the check in bin/start fails.

I propose that bin/start be modified to reduce the memory required be reduced to 5.6 GB?

**Comment by markshust** [comment]
@carylewis @powelles ah, that may be due to an update for Docker Desktop! Probably a rounding error, as 5.795 is really 5.8.

I just updated this from 5.8 to 5.7 -- can you confirm it works now after running `bin/update`?

**Comment by carylewis** [comment]
The containers now start, thanks.

**Comment by markshust** [comment]
Awesome, glad that fixed it for you!

**Comment by anthonysan95** [comment]
Could you change it here too? Thanks.
https://github.com/markshust/docker-magento/blob/4591b68c46667d4015e728392b813ec42939ae67/compose/bin/setup#L6

**Comment by markshust** [comment]
@anthonysan95 Nice catch! Just did 😁
