### ISSUE TITLE
SSL certificate doesn't work

### ISSUE THREAD

**Issue by Gen0106** [markshust/docker-magento#722]
Hello
I have a magento project so I only followed the readme, the part "Existing Project"
I created a droplet(Ubuntu 20.04.4 LTS)
And I installed git, docker, composer and executed the commands in the "Existing Project" part.
The docker containers are running.
But I can't reach the site.
Please check https://staging.wallaceheron.co.nz

I got "SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 125.227.90.115, server: 0.0.0.0:8443" in the nginx log
I don't know how to fix this problem
Please let me know the solution.

Thanks in advance.

**Comment by diegobonagurio** [comment]
same problem

**Comment by markshust** [comment]
It sounds like you are trying to run this site on a staging/production environment. It's really only meant for local development, which uses mkcert to generate local https certs. I'd recommend not running this on staging/production environments and using something like Kubernetes, or some sort of other managed solution. As this project doesn't support production environments like this, I'll be closing it out as not an issue, however if you manage to "fix" this please let us know and I'll add it to the documentation.
