### ISSUE TITLE
trying to get an old version of Magento 2.2.2 to work

### ISSUE THREAD

**Issue by ivancunha** [markshust/docker-magento#723]
**Description**
I going to give some support to an old version Magento 2.2.2... but it's not working.

**Steps To Reproduce**
I run this: curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
Then I edit docker-compose.yml and change php to 7.1     image: markoshust/magento-php:7.1-fpm-0
Then run this command bin/download 2.2.2
Then run bin/setup magento.test

Then error....
Waiting for connection to RabbitMQ...                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--amqp-host" option does not exist.    

Then in docker-compose.yml I change the version of rabbitmq    image: rabbitmq:3.5.0-management

And same thing....

Then I edit bin/setup and comment this line  # --amqp-host="$RABBITMQ_HOST" \

And almost get to the end of instalation... but another error...
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Nothing to import.
bin/setup: line 62: --amqp-port=5672: command not found

So, I'm stuck, and limited knowledge to to anything else.

**Expected Result**
Expect to finish the instalation.

**Actual Result**
Getting described error.

**Comment by markshust** [comment]
Older versions of Magento are no longer supported. However, you can see the instructions at https://github.com/markshust/docker-magento/issues/322#issuecomment-724786750 for info on how to potentially get things working for your instance.
