### ISSUE TITLE
SSH: Changing files through SSH access does not always propagate to docker copy of Magento

### ISSUE THREAD

**Issue by nkajic** [markshust/docker-magento#726]
**Description**
Hi Mark. Thank you for this Magento Docker setup you created. It is really easy to work with Magento with this, but only if I am on same machine running docker. I some times need to work from MBP and sync changes to Mac Mini running docker. **Changing files through SSH access does not always propagate to docker copy running Magento.**

**Steps To Reproduce**
1.  Login to SSH and try to create file in app/design/frontent/Vendor/theme-identifier/some-file.txt  and app/code/Vendor/SomeModule/some-file.txt

**Expected Result**
1. Files app/design/frontent/Vendor/theme-identifier/some-file.txt and app/code/Vendor/SomeModule/some-file.txt **are created** on running container (picked by Magento if real theme or module file).

**Actual Result**
1. Mentioned files **are not created** / propagated to docker container running Magento and thus not picked by Magento.

**Some info**
Maybe it is unclear how to enable SSH access properly. Copy what where? Copy contents from docker-compose.dev-ssh.yml to docker-compose.dev.yml? Or whole file? What if I forgot to do it before installing or we used existing Magento instance? Files from pub/ are synced properly for example. If it is not possible for you to debug it or reproduce can you please give me hint how this "sync" thing works so I can maybe debug it myself.

Thanks,
Neven

**Comment by markshust** [comment]
I don't normally work with SSH, so I'm not sure I can speak to this issue. I'll tag this as help needed, and perhaps someone can help out.

On a side note, usually when working with two machines, I'd check out each project separately, then work with remote branches to propagate changes. So, you can push the branch upstream when working on one computer, and pull it down from upstream on the second computer. I'd definitely recommend this approach over trying to sync two computers locally over SSH.

**Comment by nkajic** [comment]
Hi. It did't happen to me recently so I  am closing this.
