### ISSUE TITLE
unknown shorthand flag: 'f' in -f + Issue Linuxmint 20

### ISSUE THREAD

**Issue by Mage2developer** [markshust/docker-magento#740]
**Description**
Try to auto setup in a Linux mint system with auto setup script and face an issue like the screenshot below. **unknown shorthand flag: 'f' in -f**

![Screenshot-from-2022-07-25-11-44-45](https://user-images.githubusercontent.com/26230770/180721949-350ae933-b2f1-4229-9b4c-d6b607db08ce.png)

My docker and Linux mint information

![Screenshot-from-2022-07-25-11-47-28](https://user-images.githubusercontent.com/26230770/180722353-8df02aff-4653-4e3d-b8c5-ff254f485b42.png)

**Comment by Mage2developer** [comment]
@markshust No
![Screenshot-from-2022-07-25-19-08-06](https://user-images.githubusercontent.com/26230770/180790834-e2cc0398-3bc6-4ab7-a6c4-8a3733523769.png)

**Comment by Viper9x** [comment]
@Mage2developer looks like this command will help you:
`sudo apt-get install docker-compose-plugin`
after that, run the install script again.

**Comment by markshust** [comment]
@Mage2developer this is the issue -- `docker compose` only works on the most recent BETA version of Docker Desktop for Linux, so try installing that and see if that fixes it.

**Comment by Mage2developer** [comment]
@Viper9x thanks it's worked. @markshust thanks for reply, it can be closed.

**Comment by ivanaugustobd** [comment]
For Fedora users that want to avoid the Docker Desktop app, the plugin mentioned by @Viper9x can be found in the official ce repo: https://docs.docker.com/engine/install/fedora/#install-using-the-repository

And installed normally: `sudo dnf install -y docker-compose-plugin`

**Comment by beljic** [comment]
I have one project installed in July - all works fine. I have just created a new project and I am getting unknown shorthand flag: 'f' in -f error so I assume something was updated in the code base recently.
