### ISSUE TITLE
Composer ownership problem

### ISSUE THREAD

**Issue by guilhermes027** [markshust/docker-magento#751]
**Description**
Hi, i'm trying to import an existing project that is build in Magento 2.4.3-p1 version. During the process that will be described below i receive this error:  

(a lot of attempts above of changing the ownership of the files)
chown: changing ownership of '/var/www/.composer/cache/files': Operation not permitted
chown: changing ownership of '/var/www/.composer/cache': Operation not permitted
chown: changing ownership of '/var/www/.composer/config.json': Operation not permitted
chown: changing ownership of '/var/www/.composer': Operation not permitted
chown: changing ownership of '/var/www/.ssh/id_rsa': Operation not permitted
chown: changing ownership of '/var/www/.ssh/known_hosts': Operation not permitted
Filesystem ownerships fixed.

                                                                                               
  [RuntimeException]                                                                           
  Could not read /var/www/.composer/config.json                                                
                                                                                               
  file_get_contents(/var/www/.composer/config.json): failed to open stream: Permission denied  
                                                                                               

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

cp: cannot open '/var/www/.composer/auth.json' for reading: Permission denied

I've already tried changing the ownership of the current directorie (/var/www/) with the command: 
sudo chown -R pc07:pc07 .

**Steps To Reproduce**
in your root type those commands below:
mkdir Sites
cd Sites
mkdir "my_store"
cd "my_store"

now you type:
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
and
bin/download magento 2.4.3-p1 community

and the error appears.

**Comment by markshust** [comment]
Closing as non-issue. Please see https://github.com/markshust/docker-magento/issues/447#issuecomment-818699538
