### ISSUE TITLE
Fatal Error abstract

### ISSUE THREAD

**Issue by 3rsin3rgul** [markshust/docker-magento#752]
**Description**
Fatal error: Class Magento\Setup\Mvc\Bootstrap\InitParamListener contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laminas\ServiceManager\Factory\FactoryInterface::__invoke) in /var/www/html/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php on line 32

**Steps To Reproduce**
Trying to run existing project and this error comes at this step -> 
# Import app-specific environment settings:
bin/magento app:config:import

**Expected Result**
Pass

**Actual Result**
Fatal Error

**Comment by markshust** [comment]
This doesn't appear to be related to the docker-magento project, so closing it out.
