### ISSUE TITLE
Lagging 5-7s on Mac M1

### ISSUE THREAD

**Issue by spalewski** [markshust/docker-magento#753]
**Description**
Hi. I have problem on MacBook Pro with M1. Everything works fine except lagging on every run. Looks like no matter what I run, it takes 5-7s to start. It's visible when I try to open url, call cli cmd. Docker dashboard also shows no ram and processor use in this 5-7s.

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**

**Comment by spalewski** [comment]
It was caused by mapped vendor folder. It looks like it's still too much for Mac OS docker.

**Comment by markshust** [comment]
The `vendor` directory is not meant to be mounted on Macs. It's not too much for Mac + Docker -- it's just how the virtualization system works. I've been using this setup for 5+ years now, daily with no issues, it's just a change in workflow.

You can read more about the volume mounting for performance reasons at https://markshust.com/2018/12/30/docker-mac-filesystem-volume-mount-approach-performance/
