### ISSUE TITLE
SSL issues on MacOS

### ISSUE THREAD

**Issue by franciskim** [markshust/docker-magento#761]
**Description**
I am trying to use GraphCommerce with markshust/docker-magento as its backend. Browsers recognise the self-signed certificate no issues however, when it is accessed via terminal there seem to be errors.

**Steps To Reproduce**
1. macOS 12.5.1
2. Install `markshust/docker-magento` with Magento 2.4.5
3. `curl https://magento.test`

**Expected Result**
`curl` should render the same result that the browser sees.

**Actual Result**
```
curl https://magento.test
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by rangerz** [comment]
There are two ways to use curl to get the result.

```bash
# 1. Ignore CA check
curl --insecure https://magento.test/

# 2. Use CA file
docker cp "$(docker compose ps -q app|awk '{print $1}')":/root/.local/share/mkcert/rootCA.pem .
curl --cacert rootCA.pem https://magento.test/
```

**Comment by markshust** [comment]
I'm unable to replicate 

<img width="849" alt="Screen Shot 2022-09-13 at 1 55 46 PM" src="https://user-images.githubusercontent.com/437029/189975577-6c27795d-4def-4b17-9745-c2178fc2f690.png">

**Comment by markshust** [comment]
Closing this one out as unable to replicate.
