### ISSUE TITLE
mysqldump output not on stdout

### ISSUE THREAD

**Issue by nietoga** [markshust/docker-magento#771]
**Description**
Commands output is not in stdout. It's particularly important for mysqldump

**Steps To Reproduce**
1. This is the script I ran. I think the only thing required is a simple setup of magento 2.4.5 enterprise

```
# Create folder
mkdir -p ./site-$RANDOM
cd $_

# One-line setup
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5 enterprise

# Install required dependencies
bin/composer require magento/extension-b2b \
                     magepal/magento2-reindex \
                     mageplaza/module-smtp \
                     smile/elasticsuite:~2.10.0 \
                     smile/module-elasticsuite-shared-catalog:~2.10.0 \
                     smile/module-elasticsuite-quick-order:~2.10.0
bin/magento sampledata:deploy

# Configure modules
bin/magento module:enable --all
bin/magento module:disable Magento_TwoFactorAuth

# Admin configurations
bin/magento config:set -le catalog/search/engine elasticsuite
bin/magento config:set -le smile_elasticsuite_core_base_settings/es_client/servers elasticsearch:9200
bin/magento app:config:import

# Setup
bin/magento setup:upgrade
bin/magento deploy:mode:set production
bin/magento indexer:reindex
bin/cron start
```

2. Run `bin/mysqldump 0>stdin 1> stoud 2> stderr`, there's nothing on stdout.

**Expected Result**

Commands output should be on stdout, allowing for redirection and pipe.

**Actual Result**

Commands output is not on stdout, stderr or even stdin.

**Comment by nietoga** [comment]
Notice the issue is not related to mysqldump in particular. All commands output is not found on stdin, stderr or stdout

<img width="522" alt="image" src="https://user-images.githubusercontent.com/30280788/189800264-3360921c-2def-425f-b4f9-ba8e66f45787.png">

**Comment by nietoga** [comment]
Running `bin/clinotty bin/n98-magerun2.phar db:dump --stdout > magento.sql` works

**Comment by markshust** [comment]
Hi @nietoga -- the `bin/mysqldump` script already has the `--stdout` flag, per https://github.com/markshust/docker-magento/blob/master/compose/bin/mysqldump:

```
bin/n98-magerun2 db:dump --stdout "$@"
```

Is there something not working for you in particular, or in a specific scenario?

**Comment by nietoga** [comment]
Hi @markshust, the dump is working properly and I was able to successfully dump my database using the following command:

```
bin/clinotty bin/n98-magerun2.phar db:dump --stdout > magento.sql
```

For some reason the command `bin/cli` in particular is not sending it's output to stdout so basically I can't pipe the output from most already existing commands.

**Comment by nietoga** [comment]
Hi @markshust, I'm closing this issue because it's not related to this project but was a bug with Docker itself.

See: https://stackoverflow.com/a/73208522 -- this user was facing the same issue

I was using Docker Desktop `4.5.0`
