### ISSUE TITLE
Mac os m1 php-fpm permissions error

### ISSUE THREAD

**Issue by Gopj3** [markshust/docker-magento#781]
**Description**
Hello! Using oneliner code to install magento 2.4.5 with: 
**curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5**

It seems when executing inside of the container strike the point of:
**composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.5 .**
I got the permissions error inside the container complains about permissions: 

_[RuntimeException]                                                                                 
  Could not read /var/www/.composer/config.json                                                      
                                                                                                     
  file_get_contents(/var/www/.composer/config.json): Failed to open stream: Operation not permitted  
                                                                                                     

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [-j|--json] [-m|--merge] [--append] [--source] [--] [<setting-key>] [<setting-value>]...

Composer auth has been set up.
Fixing filesystem ownerships...
chown: changing ownership of '/var/www/.composer/.htaccess': Operation not permitted
chown: changing ownership of '/var/www/.composer/auth.json': Operation not permitted
chown: changing ownership of '/var/www/.composer/config.json': Operation not permitted
chown: changing ownership of '/var/www/.composer': Operation not permitted
Filesystem ownerships fixed.

                                                                                                     
  [RuntimeException]                                                                                 
  Could not read /var/www/.composer/config.json                                                      
                                                                                                     
  file_get_contents(/var/www/.composer/config.json): Failed to open stream: Operation not permitted  
                                                                                                     

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

cp: cannot open '/var/www/.composer/auth.json' for reading: Operation not permitted_

Also it is no possibility to change permissions directly inside the container, cause no rights as SU (don't know pass ofc)
I didn't find any solution on this, mb some thoughts about this ? 

Thank you in advance!

**Comment by markshust** [comment]
This error is due to the `~/.composer` folder on your host machine having incorrect permissions (owned by root). ~/.composer should never be owned by root! Try setting them back to your home user:

```
chown -R myuser:myuser ~/.composer
```

Then restart your computer, containers, and run:

```
bin/fixowns
bin/fixperms
```
