### ISSUE TITLE
Xdebug Breakpoint in Data Patch Script doesn't trigger

### ISSUE THREAD

**Issue by radub** [markshust/docker-magento#782]
### Discussed in https://github.com/markshust/docker-magento/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **radub** September 20, 2022</sup>
Based on [Trigger an Xdebug breakpoint for CLI commands in PhpStorm](https://courses.m.academy/courses/487758/lectures/36677538).

I'm trying to debug a data patch which creates a product attribute. The debugger stops at the breakpoint I've set in bin/magento (like in the tut mentioned above) but it doesn't stop in the data patch class. I've made sure that the data patch is not present in the patch_list db table so that the data patch script is executed. 

One thing I noticed is that if I run the [setup:upgrade] command from cli, the attribute is created and the data patch class is added to the patch_list table. However, **when I run the Debug Script from PhpStorm**, the data patch class is not inserted into the patch_list table.

I've also tried to set the File Configuration to /var/www/html/bin/magento (in the tut the path specified is a local project path)  
<img width="718" alt="Screenshot 2022-09-20 at 11 25 28" src="https://user-images.githubusercontent.com/60108/191212684-c0f64287-e7f3-454d-a32a-ef450775bb8a.png"> 
and as soon as I did that I got an error regarding Path Mappings not being configured
<img width="1741" alt="Screenshot 2022-09-20 at 12 03 21" src="https://user-images.githubusercontent.com/60108/191217498-59d6ef7c-8cd3-4859-9c78-bbc5213d737d.png">
but the path is configured
<img width="672" alt="Screenshot 2022-09-20 at 11 53 33" src="https://user-images.githubusercontent.com/60108/191215133-24f4cfb8-1ed8-4809-a718-9e8e7b18e64e.png">
<img width="971" alt="Screenshot 2022-09-20 at 11 53 10" src="https://user-images.githubusercontent.com/60108/191215193-bc606eb3-5290-4159-9028-73eaa7f45ba3.png">

Any thoughts?
</div>

**Comment by markshust** [comment]
I'm going to tag this as unable to replicate, but if anyone has this issue in the future, please comment on this ticket and I'll reopen it.

**Comment by r-martins** [comment]
I'm also struggling with the same issue, when debugging Setup Data Patch

**Comment by markshust** [comment]
@r-martins Is a project mapping set up from src -> /var/www/html?

<img width="1390" alt="Screenshot 2022-12-28 at 7 55 11 AM" src="https://user-images.githubusercontent.com/437029/209815628-bad89a97-9b20-44e3-8ce7-47bfeb38c142.png">

**Comment by LucScu** [comment]
it works like a charm, thx @markshust
