### ISSUE TITLE
RIP markshust docker (he has greater things to do ;)

### ISSUE THREAD

**Issue by jsjsvsvs** [markshust/docker-magento#783]
**Description**
Hopefully someone can take over this docker repo. /tears

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**

**Comment by rangerz** [comment]
Is this a delayed April Fools joke? :grin::grin::grin:

**Comment by markshust** [comment]
My last release was a few weeks ago 😂
https://github.com/markshust/docker-magento/blob/master/CHANGELOG.md#4320---2022-09-13

**Comment by jsjsvsvs** [comment]
can you tell me how I can use this? I'm in need, very badly!

**Comment by markshust** [comment]
@jsjsvsvs there's a free course at https://github.com/markshust/docker-magento#free-course

Full documentation at https://github.com/markshust/docker-magento#usage

Can't do any more for you! 😁
