### ISSUE TITLE
Xdebug Not Working With Linux - It keeps giving Incoming Connection From Xdebug Pop-up

### ISSUE THREAD

**Issue by bharmalaliasgar** [markshust/docker-magento#785]
I have setup latest Magento version 2.4.5 using the installer script. While trying to setup Xdebug as per the user manual, it keeps giving error "Incoming Connnection From Xdebug" 

I have tested multple solution but none seems to work. Below are my configuration and error encountered

Error:

![Screenshot from 2022-10-01 15-59-43](https://user-images.githubusercontent.com/33605994/193405288-023ab065-4527-4171-a964-98744d429741.png)

Xdebug Terminal:

![Screenshot from 2022-10-01 16-02-24](https://user-images.githubusercontent.com/33605994/193405423-e867c5c1-6e4a-48c3-be25-c1ec912d2634.png)

Xdebug Settings On PHPSTORM

![Screenshot from 2022-10-01 16-03-00](https://user-images.githubusercontent.com/33605994/193405438-bdf6ab45-9871-430d-8c31-8035d12c9b6b.png)
![Screenshot from 2022-10-01 16-03-12](https://user-images.githubusercontent.com/33605994/193405440-510679e2-e12e-4703-ae63-6a9c546fb668.png)
![Screenshot from 2022-10-01 16-03-26](https://user-images.githubusercontent.com/33605994/193405442-3a620643-51f2-4ac7-b19f-d1f0bed22ed1.png)
![Screenshot from 2022-10-01 16-03-40](https://user-images.githubusercontent.com/33605994/193405443-4f858f5a-4fc3-4497-a0ba-f5b2d8a33d72.png)
![Screenshot from 2022-10-01 16-04-17](https://user-images.githubusercontent.com/33605994/193405446-d4cdb88b-dda8-4b84-8da1-9f8ba56461b5.png)
![Screenshot from 2022-10-01 16-04-51](https://user-images.githubusercontent.com/33605994/193405447-2de261c1-0c40-4521-b81f-5d49aecca73c.png)

**Comment by markshust** [comment]
It doesn't look like your path mappings have been setup correctly. Please see https://courses.m.academy/courses/487758/lectures/9064478 for step by step instructions on setting up Xdebug with PhpStorm.
