### ISSUE TITLE
unknown shorthand flag: 'f' in -f See 'docker --help'.

### ISSUE THREAD

**Issue by johnverzijden** [markshust/docker-magento#786]
On the directory where to install just use the one liner:
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5
Initialized empty Git repository in /home/john/websites/chokdee/.git/
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Tried to install on ubuntu Ubuntu 20.04.4 LTS
Docker version 20.10.15, build fd82621

Just to let you know. I'll install manually.

**Comment by johnverzijden** [comment]
Hi Mark,

could it be that this is the issue? 

in the bin/download you use "docker compose -f docker-compose.yml up -d"

I think you mean "docker-compose -f docker-compose.yml up -d" (the dash between docker and compose)

With kind regards,
John

**Comment by johnverzijden** [comment]
Ah solved.

The docker compose (with a space) is a newer project to migrate compose to Go with the rest of the docker project. This is the v2 branch of the [docker/compose](https://github.com/docker/compose/tree/v2) repo. It's been first introduced to Docker Desktop users, so docker users on Linux didn't see the command. In addition to migrating to Go, it uses the compose-spec, and part of the rewrite may result in behavior differences.

For anyone having the same issue and is not a "daily docker user" :)

**Comment by johnverzijden** [comment]
btw for Linux users if the docker v2 install is not stable on your OS / version and you don't want to spent time on the new docker version right now; replacing the docker compose with docker-compose (with the dash) worked for me :)

**Comment by rangerz** [comment]
I added a pull request https://github.com/markshust/docker-magento/pull/787 for this issue. Hopping @markshust can merge it soon.
