### ISSUE TITLE
Documentation for WSL2

### ISSUE THREAD

**Issue by webguru-pt** [markshust/docker-magento#807]
I was able to successfully install docker and download magento using the manual setup instruction on WSL2.
However when I run bin/setup magento.test
I get 
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
env/db.env: line 6: $'\r': command not found

Can anyone give me any idea on why this is happening and how I could solve it?

Thanks

**Comment by markshust** [comment]
This line appears to be the main error:

```
/usr/libexec/docker/cli-plugins/docker-app: no such file or directory
```

Do you have the Docker Desktop app installed?

**Comment by avlm** [comment]
Hi! I'm also facing this issue to run on WSL2, but the error message I'm getting is slightly different, I don't have the first docker-app warning, instead I'm receiving a docker help text in the end, like when you type a wrong command.

I'm following [this](https://mpolinowski.github.io/docs/Development/Magento/2019-09-21--magento2-docker-install/2019-09-21/) tutorial. but using the defaullt that was downloaded with the template. I'm not doing the changes that the tutorial suggests to change the PHP version.

here's the full `bin/setup my.magento.test` output:
```
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
Builds, (re)creates, starts, and attaches to containers for a service.

Unless they are already running, this command also starts any linked services.

The `docker-compose up` command aggregates the output of each container. When
the command exits, all containers are stopped. Running `docker-compose up -d`
starts the containers in the background and leaves them running.

If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.

If you want to force Compose to stop and recreate all containers, use the
`--force-recreate` flag.

Usage: up [options] [--scale SERVICE=NUM...] [--] [SERVICE...]

Options:
    -d, --detach               Detached mode: Run containers in the background,
                               print new container names. Incompatible with
                               --abort-on-container-exit.
    --no-color                 Produce monochrome output.
    --quiet-pull               Pull without printing progress information
    --no-deps                  Don't start linked services.
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
    --always-recreate-deps     Recreate dependent containers.
                               Incompatible with --no-recreate.
    --no-recreate              If containers already exist, don't recreate
                               them. Incompatible with --force-recreate and -V.
    --no-build                 Don't build an image, even if it's missing.
    --no-start                 Don't start the services after creating them.
    --build                    Build images before starting containers.
    --abort-on-container-exit  Stops all containers if any container was
                               stopped. Incompatible with -d.
    --attach-dependencies      Attach to dependent containers.
    -t, --timeout TIMEOUT      Use this timeout in seconds for container
                               shutdown when attached or when containers are
                               already running. (default: 10)
    -V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving
                               data from the previous containers.
    --remove-orphans           Remove containers for services not defined
                               in the Compose file.
    --exit-code-from SERVICE   Return the exit code of the selected service
                               container. Implies --abort-on-container-exit.
    --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the
                               `scale` setting in the Compose file if present.
    --no-log-prefix            Don't print prefix in logs.
```

docker service is running. `docker version 20.10.21`
docker-compose is installed. `docker-compose version 1.29.0`

Ps: I don't have Docker Desktop installed. I can do if it's necessary, but I would prefer to run everything inside WSL2 if possible.

let me know if you need any extra info.

**Comment by markshust** [comment]
I'm going to close this as I've had no response from the creator of this ticket, however have you seen the documentation for WSL2 at https://github.com/markshust/docker-magento/discussions/372 ?

Unfortunately I can't debug either of these issues, as Windows is "not officially supported" in docker-magento, however I did get it working a long time ago with WSL2 with not many issues. Everything should be documented in that thread.

I'd like to formalize the WSL2 process soon and have it on my todo list, unless someone else can put together a good readme to do so.

**Comment by andy-sixtystores** [comment]
Not sure if this is too late, but I just face this issue.


After trying to run `bin/setup magento.test` I got the `env/db.env: line 6: $'\r': command not found` error.

Example of the console:
```
