### ISSUE TITLE
bin/download: cannot execute: required file not found

### ISSUE THREAD

**Issue by shalomfriss** [markshust/docker-magento#808]
**Description**
when I run the command I get bin/download: cannot execute: required file not found

**Steps To Reproduce**
1. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5-p1 community

**Expected Result**
magento is installed

**Actual Result**
Initialized empty Git repository in /Users/user/Sites/mage/.git/
bash: line 11: bin/download: cannot execute: required file not found

**Comment by markshust** [comment]
I'm unable to replicate this, it downloads for me.
