### ISSUE TITLE
Unable to setup magento with automatic option

### ISSUE THREAD

**Issue by malikabid** [markshust/docker-magento#812]
**Description**
Unable to setup magento with automatic option

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5-p1 community
returns error:
**Initialized empty Git repository in ~/Sites/mage245/.git/
unknown flag: --no-dev
Failed to start Docker services
unknown flag: --no-dev**

**Docker compose version : v2.12.2**

**Steps To Reproduce**
1. 
install latest docker
run the command "curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5-p1 community"

**Expected Result**
magento installs successfully

**Actual Result**
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/abid/Sites/mage245/.git/
unknown flag: --no-dev
Failed to start Docker services
unknown flag: --no-dev

**Comment by rangerz** [comment]
`bin/start` need to update, try to run `bin/update`

**Comment by kiryl-rumiacew** [comment]
Where i need to change it?

**Comment by alexJouni** [comment]
@rangerz   no didt work
you have docker-compose --no-dev  , by default  this flag  is not recognize by docker-compose
its composer flag

**Comment by rangerz** [comment]
Fixed in https://github.com/markshust/docker-magento/pull/815

**Comment by malikabid** [comment]
thank you @rangerz
