### ISSUE TITLE
Dont work bin/start --no-dev

### ISSUE THREAD

**Issue by daniloaldmdh** [markshust/docker-magento#813]
I'm using WSL and docker, even the previous version worked normally, but I think this new tutorial with the command "bin/start --no-dev"
does not work.

**Steps To Reproduce**
1. Follow the installation tutorial until the command bin/start --no-dev

**Expected Result**
Build docker

**Actual Result**
![Screenshot_1](https://user-images.githubusercontent.com/116209476/203064554-a96e9431-3042-4da9-bb5c-30429f01edd4.png)

**Comment by rangerz** [comment]
`bin/start` need to update, try to run `bin/update`

**Comment by rangerz** [comment]
Fixed in https://github.com/markshust/docker-magento/pull/815
