### ISSUE TITLE
unknown flag: --no-dev

### ISSUE THREAD

**Issue by alexJouni** [markshust/docker-magento#814]
Hello team,

I have an issue on my Mac M1 with :
 curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5-p1 community

result 👎 
![Capture d’écran 2022-11-21 à 18 05 09](https://user-images.githubusercontent.com/644515/203116494-1e2594e6-fca4-4eb0-a628-9094a50c216b.png)

**Comment by alexJouni** [comment]
Yes it's work 👍  , i am waiting the full setup to finish

**Comment by markshust** [comment]
This should be resolved
