### ISSUE TITLE
Magento 2 version 2.4.2 issue on Automated Setup not work or manual setup also do not work.

### ISSUE THREAD

**Issue by tbunitrade** [markshust/docker-magento#818]
**Description**
macOS 12.5 Monterey  I do it several times, deleted the folder Magento and try again to install packages with several different versions, but it does not get success.
nano cd/hosts 
I add 127.0.0.1 magento.test to the bottom of this file, here sample

//#Host Database
//
//# localhost is used to configure the loopback interface
//## when the system is booting.  Do not change this entry.
//#
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
//# Added by Docker Desktop
//# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
127.0.0.1 magento.test

**Steps To Reproduce**
1. mkdir magento
2. cd magento
3. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2 community
I try to setup, not a latest version 2.4.5, I need to install 2.4.2

**Expected Result**
Docker params for now is 
CPUs 12 
Memory 16GB
Swap 4 Gb
 Disk size 80Gb

yes I see all  8 containers, magento app-1, phpfpm-1 db-1 elasticsearch-1 rabbitmq-1 mailcather-1 redis-1 
If I will try to open https://magento.test/. I see 403 error Nginx

**Actual Result**

magento % curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2 community
Initialized empty Git repository in /Users/osony/Sites/magento/.git/
[+] Running 7/7
 ⠿ Container magento-app-1            Stopped                                                                       0.3s
 ⠿ Container magento-mailcatcher-1    Stopped                                                                       0.2s
 ⠿ Container magento-phpfpm-1         Stopped                                                                       0.2s
 ⠿ Container magento-elasticsearch-1  Stopped                                                                       0.8s
 ⠿ Container magento-rabbitmq-1       Stopped                                                                       6.3s
 ⠿ Container magento-redis-1          Stopped                                                                       0.2s
 ⠿ Container magento-db-1             Stopped                                                                       1.4s
[+] Running 7/7
 ⠿ Container magento-mailcatcher-1    Started                                                                       0.7s
 ⠿ Container magento-redis-1          Healthy                                                                       6.0s
 ⠿ Container magento-rabbitmq-1       Healthy                                                                       7.0s
 ⠿ Container magento-elasticsearch-1  Healthy                                                                      16.5s
 ⠿ Container magento-db-1             Healthy                                                                       6.0s
 ⠿ Container magento-phpfpm-1         Started                                                                      17.1s
 ⠿ Container magento-app-1            Started                                                                      17.6s
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.2" project at "./"

                                                     
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.  
                                                     

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

**Comment by markshust** [comment]
Everything is working properly, so unable to replicate.

Your error is leading to artifacts being left over from a preexisting install attempt. Please see [markshust/docker-magento#install-fails-because-project-directory-is-not-empty](https://github.com/markshust/docker-magento/#install-fails-because-project-directory-is-not-empty)
