### ISSUE TITLE
Created custom file 01.php in pub folder but it is not accessible from url

### ISSUE THREAD

**Issue by abdulbasitnawab** [markshust/docker-magento#819]
**

**

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**

**Comment by rangerz** [comment]
You need to setup `nginx.conf` to do this way

**Comment by markshust** [comment]
This happens because the `pub` directory is not mounted for performance reasons. You can customize the `compose.dev.yaml` file and add in the pub directory if you wish, but it'll probably slow the performance.

**Comment by abdulbasitnawab** [comment]
Hi yes after adding to ngninx.conf in the html folder it worked, but i have to do bin/start is there a way i can only restart/reload  the ngnix service

**Comment by rangerz** [comment]
```bash
# restart app (nginx contaioner)
bin/restart app

# reload nginx
bin/docker-compose exec app nginx -s reload
```

**Comment by abdulbasitnawab** [comment]
thanks for the quick reply, highy appreciated can you also support if i have an existing project on github how can i pull this project tobe used with this docker
