### ISSUE TITLE
Manual setup not worked with latest 2.4.5 version

### ISSUE THREAD

**Issue by tbunitrade** [markshust/docker-magento#820]
**Description**

**Steps To Reproduce**
1. 

**Expected Result**

**Actual Result**
osony@C02F45AFMD6P magento % curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash

Initialized empty Git repository in /Users/osony/Sites/magento/.git/
osony@C02F45AFMD6P magento % bin/download 2.4.5-p1 community
[+] Running 8/8
 ⠿ Network magento_default            Created                                                                       0.0s
 ⠿ Container magento-mailcatcher-1    Started                                                                       1.1s
 ⠿ Container magento-rabbitmq-1       Healthy                                                                       7.2s
 ⠿ Container magento-elasticsearch-1  Healthy                                                                      16.7s
 ⠿ Container magento-db-1             Healthy                                                                       6.2s
 ⠿ Container magento-redis-1          Healthy                                                                       6.2s
 ⠿ Container magento-phpfpm-1         Started                                                                      17.3s
 ⠿ Container magento-app-1            Started                                                                      17.7s
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.5-p1" project at "./"

                                                     
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.

**Comment by markshust** [comment]
Everything is working properly, so unable to replicate.

Your error is leading to artifacts being left over from a preexisting install attempt. Please see https://github.com/markshust/docker-magento/#install-fails-because-project-directory-is-not-empty
