### ISSUE TITLE
service "phpfpm" is not running container #1

### ISSUE THREAD

**Issue by llgdd** [markshust/docker-magento#821]
**Description**
Stumbling upon this error on Linux. Not sure what causes it—it occurs on using almost any of the scripts placed under bin/

**Steps To Reproduce**
```bash
$ mkdir -p ~/Sites/magento
$ cd $_
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
$ bin/download 2.4.5-p1 community

Composer authentication required (repo.magento.com public and private keys):
    Username: PUBLICKEY
    Password: PRIVATEKEY

service "phpfpm" is not running container #1
service "phpfpm" is not running container #1
Composer auth has been set up.
Fixing filesystem ownerships...
service "phpfpm" is not running container #1
Filesystem ownerships fixed.
service "phpfpm" is not running container #1
service "phpfpm" is not running container #1
```

**Expected Result**
Scripts under bin/ are expected to run and do whatever they are supposed to do normally without this error.

**Actual Result**
Scripts under bin/ error out saying `service "phpfpm" is not running container #1`

**Comment by llgdd** [comment]
Can’t replicate anymore, it’s now working properly. Pretty sure I just messed something up. ¯\_(ツ)_/¯

**Comment by theshreyas** [comment]
I am facing the same error, and have not done any customization.

**Comment by JohnnyMa** [comment]
BTW, I fixed it by allocating at least 6GB of RAM to Docker to continue. Hope it helps~
