### ISSUE TITLE
PhpStorm: Incoming Connection From Xdebug Windows WSL2 Environment Variable

### ISSUE THREAD

**Issue by salesigniter** [markshust/docker-magento#825]
### Discussed in https://github.com/markshust/docker-magento/discussions/647

<div type='discussions-op-text'>

<sup>Originally posted by **overrode** February 23, 2022</sup>
Im using PhpStorm on Linux and  everytime i refresh the page, i get a pop-up with the message "Incoming Connection From Xdebug" which has different port and no Server name:
![xdebug_incoming](https://user-images.githubusercontent.com/15195423/155284021-33e7d522-7154-4925-9b9f-6e7eb313b706.png)

And it also creates an EMPTY Server name:
![xdebug_incoming_empty](https://user-images.githubusercontent.com/15195423/155284023-81cdafba-b197-465d-ae6d-7e5618787f48.png)

I have my custom-server test.local with the port 80 and the path mapping setting and it works only if i click Run -> Debug 'test.local' and wait for the page refresh.

So, for some reason, the Xdebug does not take my custom-server name (test.local, which works) and allways creates an empty one.
If i click Accept it gives me an error:
![xdebug_incoming_error](https://user-images.githubusercontent.com/15195423/155284538-ee45303e-60fa-4d6a-96b1-60b366dc60ab.png)

Any ideea how to get the Xdebug to use my custon Server name (test.local) when i enable the Listener and refresh the page?

</div>

**Comment by salesigniter** [comment]
I am not sure how to set this in docker, or if this will fix it: 

export PHP_IDE_CONFIG="serverName=SomeName"

As suggested by the phpstorm docs. Has anyone got xdebug phpstorm wsl2 setup working?

**Comment by salesigniter** [comment]
nevermind, this was as simple as putting this in the nginx.conf.sample file:

`server_name  magento2.test;`

then bin/restart

just replace with whatever server name you want, that is all that phpstorm needs, nothing complicated though because I'm new at docker took me 3 hours of digging. 

If you do this the mapping added by phpstorm is all automatic and works fine:

![image](https://user-images.githubusercontent.com/321250/205604464-cee06c02-4ef9-472e-b1c6-4909d1f862b2.png)

**Comment by pykettk** [comment]
+1 for the above solution - worked for me too!

**Comment by markshust** [comment]
@pykettk @salesigniter is this a Linux-thing? I've never needed to do this on Mac.

**Comment by pykettk** [comment]
@markshust I've had this issue on:
- Ubuntu 20.04
- Intel Mac
- M2 Mac

I've only ever resolved it in the latter case, using the above suggestion, I gave up trying in the other cases 😅

**Comment by asannikov** [comment]
this solution helped me:
https://github.com/markshust/docker-magento/discussions/647#discussioncomment-7142106
