### ISSUE TITLE
 Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

### ISSUE THREAD

**Issue by Mounisha0811** [markshust/docker-magento#829]
While trying to install Magento via docker, facing following issue:

![image](https://user-images.githubusercontent.com/120167956/206654705-f86eb590-bf1b-4b3b-b807-423ef97bf77a.png)

Steps to reproduce:

1. Installed WSL2
2. Install docker Version 20.10.21
3. Install docker-compose version 1.25.0
4. created project directory: mkdir -p ~/Sites/magento
5. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
6. bin/download 2.4.5-p1 community
7. bin/setup magento.test

Error during the setup command

**Comment by iliasokolovneklo** [comment]
It is because currently opensearch is used by default.
@markshust it is a crazy decision to use opensearch by default. For now, 99% percent of Magento installations use elasticearch. It would better return elasticsearch by default.

**Comment by ssx** [comment]
@Mounisha0811 are you setting the hostname for opensearch anywhere?

**Comment by rangerz** [comment]
You may run the `bin/update` 
`composer.yaml` is using opensearch now, so you need to run below command to update the search engine setting
```
bin/magento config:set catalog/search/elasticsearch7_server_hostname opensearch
```

**Comment by Mounisha0811** [comment]
@ssx  : No , not setting anywhere

@rangerz  : Ran bin/update, still issue persist
But bin/magento command will work only after Magento is installed, I am stuck before installing Magento only

**Comment by Mounisha0811** [comment]
@ssx  : No , not setting anywhere

@rangerz  : Ran bin/update, still issue persist
But bin/magento command will work only after Magento is installed, I am stuck before installing Magento only

**Comment by Mounisha0811** [comment]
Issue still persist

**Comment by rangerz** [comment]
Remove all and re-install them
```
bin/removeall

bin/setup magento.test
```

**Comment by pykettk** [comment]
I'm facing this same issue. Following @rangerz suggestion of `bin/removeall` and `bin/setup magento.test` does not fix the issue for me either. Once the containers are recreated the process errors out cause the `bin/magento` executable doesn't exist - because Magento failed to initialise during the first `bin/setup` run.

I have a slightly different system setup to @Mounisha0811 - I'm running Docker version 20.10.21 (build baeda1f) and Docker Compose version v2.12.2.

**Comment by pykettk** [comment]
I found the issue. The `bin/setup` file expects you to be using Open Search. Changing the [`--elasticsearch-host` value in the `setup:install` command](https://github.com/markshust/docker-magento/blob/master/compose/bin/setup#L65) to `$ES_HOST` resolves the issue. This variable value comes from the [`env/elasticsearch.env` file](https://github.com/markshust/docker-magento/blob/master/compose/env/elasticsearch.env#L1).

I'll open a pull request to add this information to the README momentarily. Ideally `bin/setup` would detect whether you're using Open Search or Elasticsearch and use the correct host - sadly I don't have the time to look into this just now.
