### ISSUE TITLE
Missing Elasticsearch 7.17-0 Image

### ISSUE THREAD

**Issue by pykettk** [markshust/docker-magento#833]
# Description
The `7.17-0` tag for the `markoshust/magento-elasticsearch` image [does not exist in Docker Hub](https://hub.docker.com/r/markoshust/magento-elasticsearch/tags?page=1&name=7.17). [Magento System Requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) states a requirement for Elasticsearch version `7.17` for 2.4.5 and 2.4.5-p1 - the latter being the default version installed in this project.

# Steps To Reproduce
Follow the manual setup steps for a new project but switch to using Elasticsearch instead of Open Search:
1. `mkdir -p ~/Sites/magento`
2. `cd $_`
3. `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash`
4. Edit the `compose.yaml` file to comment out the lines for the `opensearch` container and uncomment the lines for the `elasticsearch` container
5. `bin/download 2.4.5-p1 community`
6. Observe the following error message:
	```bash
	[+] Running 0/1
	 ⠿ elasticsearch Error
	Error response from daemon: manifest for markoshust/magento-elasticsearch:7.17-0 not found: manifest unknown: manifest unknown
	Failed to start Docker services
	```

# Expected Result
Docker is able to download the `markoshust/magento-elasticsearch:7.17-0` image, create the `elasticsearch` container, and the `bin/download` command executes without error.

# Actual Result
Docker cannot find the `7.17-0` tag for the `markoshust/magento-elasticsearch` image and results in the following error:
```bash
[+] Running 0/1
 ⠿ elasticsearch Error
Error response from daemon: manifest for markoshust/magento-elasticsearch:7.17-0 not found: manifest unknown: manifest unknown
Failed to start Docker services
```

# System Info
- MacOS 13.0 (22A380)
- Docker version 20.10.21, build baeda1f
- Docker Compose version v2.12.2

**Comment by markshust** [comment]
Oops -- I never re-ran the GitHub action to build this!

Just ran it, so should be all set now: https://hub.docker.com/r/markoshust/magento-elasticsearch/tags

**Comment by pykettk** [comment]
Confirming as resolved, thanks for the quick response, Mark 🙂
