### ISSUE TITLE
phpmyadmin doesn't match specific platform warning

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#842]
**Description**
The warning message appears on a fresh install of docker-magento on Apple Silicon machines:

```
 ⠙ phpmyadmin The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
```

**Steps To Reproduce**
1. Install new docker-magento instance on M1 mac

**Expected Result**
`bin/start` starts phpmyadmin without any errors or warnings

**Actual Result**
 ⠙ phpmyadmin The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s

**Comment by o0mohd90o** [comment]
I have the same issue Macbook pro M1

**Comment by YanNerio** [comment]
Hello, I'm having this issue as well and nginx won't start. 
It happens in M2 pro.

bin/restart: warning + nginx not starting
bin/start: no warning, nginx up but I got 403 forbidden when opening the app.

Any thoughts?

**Comment by markshust** [comment]
This should only affect the phpmyadmin container. This doesn't seem to affect php or nginx, so @YanNerio your issue is something else. I'd attempt the install again and ignore the phpmyadmin warning for now.

I am getting this warning and have confirmed this. I'm not sure if a phpmyadmin image is available for apple silicon, but will look into this.

**Comment by markshust** [comment]
Fixed this my replacing it with a completely different Docker image (https://hub.docker.com/r/linuxserver/phpmyadmin) which seems to support both amd and x86_64 archs.

**Comment by SlimDeluxe** [comment]
The official phpmyadmin image now has arm builds also:
https://hub.docker.com/_/phpmyadmin
