### ISSUE TITLE
Magento 2.3.7 not working 

### ISSUE THREAD

**Issue by gajjardhara** [markshust/docker-magento#843]
**Description**
When I run autosetup it install 8.1 with magneto 2.3.7 and 8.1 php not compatible with Magento 2.3.7

**Steps To Reproduce**
1. Run below command 
2. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.3.7 community

**Expected Result**
it should run with php 7.4 

**Actual Result**
it is running with php 8.1

**Comment by markshust** [comment]
Yep, this is expected because Magento 2.3 has reached EOL. I'm no longer supporting dead software.
