### ISSUE TITLE
Setup with existing project that runs an older version of Magento 2.

### ISSUE THREAD

**Issue by basnetarun** [markshust/docker-magento#844]
### **Description**
I have an existing project that is running CE at version 2.4.2. I followed the guide to install an existing project and am stuck at an error that arises on running the command: 

> Import app-specific environment settings:
> `bin/magento app:config:import`

The error says: 
_Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory_

Upon Running `bin/composer install`, it would not install anything because the **composer.json** and **composer.lock** file of course come from the existing project and are locked down into older versions of php for example. What are the appropriate steps that are needed to be followed in such a case please? 

### **Steps To Reproduce**
Assuming there is an existing project+database dump with a M2 version older than the version used in here. 
1. From under ["**Existing Projects**" section in the documentation](https://github.com/markshust/docker-magento#existing-projects), follow steps up to "import existing database" (assuming all previous steps were successful till this point)
2. Run `bin/magento app:config:import`

### **Expected Result**
The expected result is some kind of confirmation saying the configuration was imported or that there was nothing to import. 

### **Actual Result**
Error message: 
> Autoload error: Vendor autoload is not found. Please run 'composer install' under application root directory.

I am assuming that I need to replace my existing **composer.json** and **composer.lock** file from the version of Magento that I want to upgrade to. Has anyone done this successfully or can guide me towards the correct direction? The following is the result after that. 

So far I 
- removed the vendor folder in the container 
- replaced my composer.json from [the latest version available in github](https://github.com/magento/magento2/blob/2.4-develop/composer.json) 
- renamed existing composer.lock to composer.lock.bkup
- ran `composer update`

And after that if I try `bin/magento app:config:import` (or any other bin/magento commands) I receive the following error: 

_Fatal error: Uncaught Error: Class "Magento\Framework\Component\ComponentRegistrar" not found in /var/www/html/app/design/frontend/magento2-test/theme-frontend/registration.php:9_

The contents of that file however is just as follows (of which the last line is pointed by the error): 

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::THEME, 'frontend/magento2-test/theme-frontend', __DIR__);
```

**Comment by nicolas-medina** [comment]
Hi @basnetarun,

You need to manually change the image versions in [compose.yaml](https://github.com/markshust/docker-magento/blob/master/compose/compose.yaml#L35) for PHP, DB, Redis and ElasticSearch.

For Magento 2.4.2 you can use:
PHPFPM: markoshust/magento-php:7.4-fpm
DB: mariadb:10.4
ElasticSearch: markoshust/magento-elasticsearch:7.9.3-1
Redis: redis:6.0-alpine

**Comment by basnetarun** [comment]
Hi @nicolas-medina, 
Thanks a lot for the help! It works now. I will see if I can update it to the latest version.
