### ISSUE TITLE
Can't make a new project

### ISSUE THREAD

**Issue by amjad16th** [markshust/docker-magento#847]
**Description**
When using the Automated Setup (New Project) 

**Steps To Reproduce**
1. **curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5-p1 community**

**Expected Result**
New project to be made

**Actual Result**
  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:

  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

**Comment by markshust** [comment]
I'm unable to replicate this, and have installed it many times on my machine with no issues (even fresh Mac installs). I'll close this out pending further info.
