### ISSUE TITLE
unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by kernmichael** [markshust/docker-magento#851]
When trying to setup Magento with the automated setup script like so

> % curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- my-mag2.test 2.4.4-p2 community

I get the following error message

> mv: rename compose/.vscode to ./.vscode: Directory not empty
> Initialized empty Git repository in /Users/michaelberner/Sites/magento/.git/
> **unknown shorthand flag: 'f' in -f**
> See 'docker --help'.
> 
> Usage:  docker [OPTIONS] COMMAND
> 
> A self-sufficient runtime for containers
> 
> Options:
>       --config string      Location of client config files (default
>                            "/Users/michaelberner/.docker")
>   -c, --context string     Name of the context to use to connect to the
>                            daemon (overrides DOCKER_HOST env var and
>                            default context set with "docker context use")
>   -D, --debug              Enable debug mode
>   -H, --host list          Daemon socket(s) to connect to
>   -l, --log-level string   Set the logging level
>                            ("debug"|"info"|"warn"|"error"|"fatal")
>                            (default "info")
>       --tls                Use TLS; implied by --tlsverify
>       --tlscacert string   Trust certs signed only by this CA (default
>                            "/Users/michaelberner/.docker/ca.pem")
>       --tlscert string     Path to TLS certificate file (default
>                            "/Users/michaelberner/.docker/cert.pem")
>       --tlskey string      Path to TLS key file (default
>                            "/Users/michaelberner/.docker/key.pem")
>       --tlsverify          Use TLS and verify the remote
>   -v, --version            Print version information and quit

I am on macOS Monterey 12.5 with an Intel Core i5
I have Docker Desktop and Visual Studio Code installed.

> % docker version
> Client:
>  Cloud integration: v1.0.29
>  Version:           20.10.22
>  API version:       1.41
>  Go version:        go1.18.9
>  Git commit:        3a2c30b
>  Built:             Thu Dec 15 22:28:41 2022
>  OS/Arch:           darwin/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Desktop 4.16.2 (95914)
>  Engine:
>   Version:          20.10.22
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.18.9
>   Git commit:       42c8b31
>   Built:            Thu Dec 15 22:26:14 2022
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.14
>   GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
>  runc:
>   Version:          1.1.4
>   GitCommit:        v1.1.4-0-g5fd4c4d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

I found similar sounding issues on the web
e.g. 
https://stackoverflow.com/questions/66682037/path-to-docker-compose-yml-as-a-parameter
https://github.com/docker/compose/issues/8986

Specifically, https://github.com/docker/compose/issues/8986#issuecomment-984139082
states, as far as I understand, that the order of options makes a difference, and when a command uses both the -f and the up -d options up -d needs to be at the end of the command after the -f instead of the other way around; so, for example, 
docker-compose up -d -f /data/....../docker-compose.yml
does not work, but
docker-compose -f /data/......./docker-compose.yml up -d
would work.

But I am not sure, if that is really it.

Weirdly
% docker --help
does not even list the -f option at all on my machine:

> Usage:  docker [OPTIONS] COMMAND
> 
> A self-sufficient runtime for containers
> 
> Options:
>       --config string      Location of client config files (default "/Users/michaelberner/.docker")
>   -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default
>                            context set with "docker context use")
>   -D, --debug              Enable debug mode
>   -H, --host list          Daemon socket(s) to connect to
>   -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
>       --tls                Use TLS; implied by --tlsverify
>       --tlscacert string   Trust certs signed only by this CA (default "/Users/michaelberner/.docker/ca.pem")
>       --tlscert string     Path to TLS certificate file (default "/Users/michaelberner/.docker/cert.pem")
>       --tlskey string      Path to TLS key file (default "/Users/michaelberner/.docker/key.pem")
>       --tlsverify          Use TLS and verify the remote
>   -v, --version            Print version information and quit

So, do I maybe have an old version of Docker installed?

But I did download Docker Desktop from the docker website mid January 2023 so that should be up to date.

**Comment by markshust** [comment]
Hi Michael,

This is odd, because the `-f` flag is appearing first in all docker compose calls:
https://github.com/markshust/docker-magento/blob/master/compose/bin/docker-compose

What version(s) of Docker are you running? The new script `docker compose` replaces `docker-compose`. If you are able to run `docker compose version` from your command line, it should use the new version that's been out for some time now.

For reference, here's my output using the most recent versions:
<img width="431" alt="Screenshot 2023-01-25 at 8 21 51 AM" src="https://user-images.githubusercontent.com/437029/214574189-28e12a3d-f366-4995-a19e-1fb52ce6150c.png">

**Comment by kernmichael** [comment]
Hi Michael,
thank you for you looking into this. The issue must somehow be on my side.
My terminal "knows" the docker command, but not docker-compose:
![2023-01-28_11-51-33](https://user-images.githubusercontent.com/88185014/215262708-dc1e40aa-1682-4ead-86b2-e9a276e26386.png)
Like I said, I have Docker Desktop for Mac installed.
Maybe this might be some path issue.
I will to try to figure it out.
Anyway, I am sorry for having taken up your time with this. Thank you again for looking into this and for sharing your project.
best wishes, kind regards
Michael
