### ISSUE TITLE
New File in PHP Storm is not added in Docker Container automatically with newest versions of PHPStorm and Docker

### ISSUE THREAD

**Issue by UlliKraus** [markshust/docker-magento#853]
We have the following problem with PHP Storm Build #PS-223.8214.64 and Docker 4.15.0 (93002). 

When a new file is added in PHPStorm e.g. file.html it used to be automatically copied to the Docker container with older Builds of PHPStorm and Docker. 
With the newest versions the problem is that first the "bin/copytocontainer file.less" command has to be executed for the file to finally be found in the Docker container. 

Does anyone else have this problem? And does anyone have a solution for it?

**Comment by JesKingDev** [comment]
What's the full path to the new file that's not being copied?

**Comment by markshust** [comment]
I'm unable to replicate this and have never experienced it -- it's definitely not typical for this to happen. The usage of PhpStorm is irrelevant here, as it would be completely dependent upon your host OS and Docker Desktop.

What are your system details and which method did you use to install M2 with docker-magento?

**Comment by UlliKraus** [comment]
Thanks for the info and counter question: 

It concerns files under the following path: 
src/app/code/Xxxxxx/Adminmenu/etc

e.g. module.xml

But also a test file directly in the src folder was not taken over automatically. 
--
M2 was installed with Docker on a MacBook Pro 2022 with M1 chip. But also on a 2020 MacBook Pro with Intel chip. The problem occurs on both.

**Comment by UlliKraus** [comment]
[https://www.veed.io/view/26b932e5-9c3a-44d6-ab4c-f741dce8a456?sharingWidget=true&panel=share](url)
Heres a simple video of the issue

**Comment by markshust** [comment]
Where are you setting up this project at? It should be a subfolder of your ~/Sites/ directory, or somewhere else in your home directory. I have a feeling it's not there. I've never had this issue in 7+ years running this setup on my mac.

**Comment by UlliKraus** [comment]
Hi, its set up in "User/Webserver/magento2_docker/src" directory

**Comment by rangerz** [comment]
Try to restart Docker Desktop or reboot your machine.

**Comment by markshust** [comment]
> ## But also a test file directly in the src folder was not taken over automatically.

I think I'm going to close this out as it works as expected for me, but not that the above reference will not sync. If you simply create a file in src/, it won't sync. This is because only specific directories are synced as listed in the volumes at https://github.com/markshust/docker-magento/blob/master/compose/compose.dev.yaml for performance reasons.
