### ISSUE TITLE
Suggestion: Isolate operations requiring root permissions

### ISSUE THREAD

**Issue by antonkril** [markshust/docker-magento#854]
**Description**
I use a non-root user for normal operations on my Mac. Whenever I need to perform operations requiring root permissions I `su` into my root user. With this setup the automated installation does not work for my normal user. But I don't want to install magento as a root.

Root permissions are only required to edit `/etc/hosts` and install certificate. These scripts could be isolated for a non-root user setup.

**Comment by EvgeniyZverev** [comment]
Hi, @antonkril 

I added a script to facilitate editing the system's host file at /etc/hosts in this [pull request](https://github.com/markshust/docker-magento/pull/1015).

**Comment by markshust** [comment]
Sorry for the delay in answering this @antonkril. I've gotten a bit behind with project issues and am trying to catch up.

`sudo` is only required to add a record to `/etc/hosts`. Magento will be installed on your local host username, not root, so there is nothing to worry about here.

I'll try to think of a solution that doesn't require sudo/root for the base install, as I know this could cause some hesitation, as it the typical install script is executed from a curl command 😬
