### ISSUE TITLE
bin/magento doesn't find /bin/bash

### ISSUE THREAD

**Issue by daef** [markshust/docker-magento#864]
On systems which don't have bash under /bin/bash the scripts are broken.

This could probably be fixed by the superior shebang `#!/usr/bin/env bash` ([more](https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html)).

**Comment by daef** [comment]
I use [nixos](https://nixos.org/), which doesn't keep binaries around in /bin because one might have different versions installed.
/usr/bin/env is POSIX

**Comment by markshust** [comment]
I really appreciate it @daef! All merged in 🤓
