### ISSUE TITLE
bin/xdebug enable doesn't work || it's disabled once the bin/restart or bin/start is executed

### ISSUE THREAD

**Issue by maritos** [markshust/docker-magento#871]
**Description**

I've faced strange error when the command `bin/xdebug enable` is executed.

Once the phpfpm container is restarted the php.ini files back in to the original version with xdebug=off.

and now the bin/xdebug status - says that xdebug is disabled - SHOULD BE ENABLED

and if I go with:
`docker-compose restart phpfpm` - it is OK

but `bin/restart phpfpm`
breaks the feature 

`bin/restart` recreates the container some reson but docker-compose restart only restarts the container

### POSSIBLE SOLUTION:
 changing "docker compose" to "docker-compose" (with a hyphen in bin/start and bin/stop) seems to solve the issue

**Steps To Reproduce**
1. bin/xdebug enable
2. bin/xdebug status

**Expected Result**

Xdebug is enabled

**Actual Result**

Xdebug is disabled

**SYSTEM INFO** 

docker --version
Docker version 23.0.1, build a5ee5b1
docker-compose --version
docker-compose version 1.29.2, build unknown

**Comment by xavierojeda** [comment]
Duplicate issue #866

**Comment by markshust** [comment]
Closing as a dupe
