### ISSUE TITLE
WSL2 Slow on first load

### ISSUE THREAD

**Issue by wolfautoparts** [markshust/docker-magento#873]
**Description**
Running on WSL2.
WSL configured for 8CPU and 16GB Ram

**Steps To Reproduce**
1.  Clean Install
2.  Goto URL

**Expected Result**
The page should load reasonably fast.

**Actual Result**
First page load is slow 7-10sec. After that other pages load <1s. If you stop using the site for a while and go back to it it is slow again for the first page load.

**Comment by artmouse** [comment]
Check https://github.com/markshust/docker-magento/issues/700

**Comment by markshust** [comment]
7-10 sec on first page load seems about right. I don't think there is any problem here, as it depends on your machine specs.
