### ISSUE TITLE
Elasticsearch container exits after starting up

### ISSUE THREAD

**Issue by ennostuurman** [markshust/docker-magento#875]
**Description**

Elasticsearch container exits after starting up on Linux (Ubuntu).

The container log shows the following error.

```
Error: Could not find or load main class "-Xms1g
Caused by: java.lang.ClassNotFoundException: "-Xms1g
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

error:
Error: Could not find or load main class "-Xms1g
Caused by: java.lang.ClassNotFoundException: "-Xms1g
	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

**Steps To Reproduce**
1. run bin/start
2. check status with bin/status

**Expected Result**
Elasticsearch container runs and shows State: "Up (healthy)

**Actual Result**
Elasticsearch container exited showing State: Exit 1

**Comment by rangerz** [comment]
It's weird issue ...
Try to remove the double qoute for `ES_JAVA_OPTS="-Xms1g -Xmx1g"` in `elasticsearch.env`

Ref: https://stackoverflow.com/questions/44926335/passing-es-java-opts-variable-with-spaces-when-using-docker-compose

**Comment by ennostuurman** [comment]
Thanks @rangerz ! 

Changing the env to `OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g` works with bin/start. Checking with bin/status gives me status okay still after a few minutes:

`magento245-p2_opensearch_1    ./opensearch-docker-entryp    Up (healthy)   0.0.0.0:9200->9200/tcp`

@markshust  this likely requires an adjustment for both Opensearch and Elasticsearch env config (at least for Linux OS)? 

Related to this issue. On Linux bin/setup fails with the original env config (with quotes) as well as without quotes.

```
bin/setup magento245-p2.test
env/opensearch.env: line 6: -Xmx1g: command not found
```

**Comment by markshust** [comment]
Sorry @ennostuurman, just heads down in other work at the moment. Maybe I can ask Maggie to fix this 😆

**Comment by markshust** [comment]
@ennostuurman I made a change to remove the quotes around this JAVA OPTS var, since it appears to help out here. I believe this solves the original issue. If there is still an issue with Linux, please open up a new issue with specific details on that one and we can take it from there :)

**Comment by markshust** [comment]
So just that quickly, I had to revert that commit as I got this error on my mac:

```
Adding Magento modules to Composer allow-plugins directive...
Running, Magento setup:install...
env/elasticsearch.env: line 5: -Xmx1g: command not found
```

So, it appears we absolutely need that line quoted out on macOS for the env file to be parsed correctly.

What are the details of your operating system and etc.? I've never had an issue with this, so at the moment I'm unable to replicate.

**Comment by ennostuurman** [comment]
hey @markshust thanks for looking into this. Looks like this is an isolated issue so in that case I don't mind changing this manually in the elastichsearch or opensearch env files. Maggie what do you advise, shall we close this ticket?
