### ISSUE TITLE
bin/start fails on fails on mac os x (Catalina 10.15.7)

### ISSUE THREAD

**Issue by three-old-coders** [markshust/docker-magento#877]
#310 

starting point:  curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.5-p1 community

after stopping the containers using "bin/stop" starting fails

magento2 % bin/stop
[+] Running 7/7 
⠿ Container magento2-mailcatcher-1  Stopped    0.2s
⠿ Container magento2-app-1          Stopped 0.2s
⠿ Container magento2-phpfpm-1       Stopped 0.1s
⠿ Container magento2-db-1           Stopped 2.0s
 ⠿ Container magento2-opensearch-1   Stopped  0.4s
 ⠿ Container magento2-redis-1        Stopped 0.4s
 ⠿ Container magento2-rabbitmq-1     Stopped
 
magento2 % bin/start
./src/app/design: No such file or directory
./src/app/etc: No such file or directory
./src/composer.json: No such file or directory
./src/composer.lock: No such file or directory
./src/grunt-config.json.sample: No such file or directory
./src/Gruntfile.js.sample: No such file or directory
./src/dev/tools/grunt/configs: No such file or directory
./src/nginx.conf.sample: No such file or directory
./src/package.json.sample: No such file or directory
Failed to start docker for missing volume files 

magento2 % docker-compose up -d
Recreating magento2-app-1         ... done
Recreating magento2-redis-1       ... done
Recreating magento2-rabbitmq-1    ... done
Recreating magento2-mailcatcher-1 ... done
Recreating magento2-opensearch-1  ... done
Recreating magento2-phpfpm-1      ... done
Recreating magento2-db-1          ... done 

is working.

documentation states "https://magento.test/" which seems to be wrong. When using "https://magento2.test/" site responds with 403 forbidden.

I found #757 #372 but the fixes concerning the yaml file are present in the current files.

Furthermore I saw this in the console log:

Composer authentication required (repo.magento.com public and private keys):
    Username: ****
    Password: ****

  [Seld\JsonLint\ParsingException]                                        
  "/var/www/.composer/auth.json" does not contain valid JSON              
  Parse error on line 1:                                                  
                                                                          
  ^                                                                       
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  
                                                                          

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [-j|--json] [-m|--merge] [--append] [--source] [--] [<setting-key>] [<setting-value>]...

Composer auth has been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.

                                                                          
  [Seld\JsonLint\ParsingException]                                        
  "/var/www/.composer/auth.json" does not contain valid JSON              
  Parse error on line 1:                                                  
                                                                          
  ^                                                                       
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  
                                                                          

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

I logged into the docker container and added a new file

docker exec -ti ****** bash
cd ..
cd .composer
edit auth.json

Now auth is working.

Nevertheless 403 remains. 

looking into the NGINX logs by 
docker-compose logs -f --tail="10" app
shows:

app_1          | 2023/03/13 16:46:37 [error] 29#29: *2 directory index of "/etc/nginx/html/" is forbidden, client: 172.18.0.1, server: , request: "GET / HTTP/2.0", host: "magento2.test"
app_1          | 172.18.0.1 - - [13/Mar/2023:16:46:37 +0000] "GET / HTTP/2.0" 403 555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "-"

Assuming the default location of nginx.conf is /etc/nginx/nginx.conf than this config entirely misses. 

Any hint how to solve this?

**Comment by markshust** [comment]
What was the specific output of running the single curl line? It sounds like the install just failed. Perhaps the contents of the `~/.composer/auth.json` file on your host machine is invalidly formatted?

I'd reattempt the install after possibly fixing that file or removing it. Before reattempting, please remove your current attempt/folders/etc with the info at https://github.com/markshust/docker-magento#misc-info

**Comment by MichaelPanW** [comment]
I'm also using a Mac M1 for development.
I tried to increase the memory of Docker to 8.5 GB.
then run: bin/setup magento.test
fix my problem
good luck

**Comment by markshust** [comment]
I am closing this out as I'm unable to replicate.
