### ISSUE TITLE
Failing unit tests on 2.4.6

### ISSUE THREAD

**Issue by MTheProgrammer** [markshust/docker-magento#890]
**Description**
Unit tests fail on MacOS, MacBookAir M2, arm64.

I wonder whether it is a problem with certain library version or Magento 2 is not compatible with arm64. 
If that's incorrect library version then docker image should be rebuild with correct dependencies.
If the issue is related to Magento itself, I'll migrate this ticket to their repository.

**Steps To Reproduce**
1. Setup docker-magento according to the instruction in README
2. run `bin/dev-test-run unit`

**Expected Result**
All tests pass

**Actual Result**
Some tests fail, notably those with rounding issues

<img width="1385" alt="Screenshot 2023-03-22 at 12 43 00 PM" src="https://user-images.githubusercontent.com/6697660/226805400-e54c38be-9449-4783-be05-bbc77b719328.png">

**Comment by piotrkwiecinski** [comment]
Late reply but there is an open issue in core: https://github.com/magento/magento2/issues/37474 with failing tests on both 2.4.6 and develop 2.4-x

**Comment by hostep** [comment]
It actually sounds more related to https://github.com/magento/magento2/issues/36167 (so downgrading `sebastian/comparator` to a version lower than 4.0.8 could maybe fix this?)

**Comment by markshust** [comment]
Closing this as it appears to be an issue with the core as @piotrkwiecinski pointed out
