### ISSUE TITLE
unable to install PHP 8.1 ioncube extension on M1

### ISSUE THREAD

**Issue by sankharay** [markshust/docker-magento#893]
**Description**

DockerFile

`FROM markoshust/magento-php:8.1-fpm-1
MAINTAINER Mark Shust <mark@shust.com>

USER root

RUN mkdir -p /etc/nginx/html /var/www/html /sock \
  && chown -R app:app /etc/nginx /var/www /usr/local/etc/php/conf.d /sock

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

RUN cd /tmp \
  && curl -O https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_aarch64.tar.gz \
  && tar zxvf ioncube_loaders_lin_x86-64.tar.gz \
  && export PHP_VERSION=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;") \
  && export PHP_EXT_DIR=$(php-config --extension-dir) \
  && cp "/tmp/ioncube/ioncube_loader_lin_8.1.so" "${PHP_EXT_DIR}/ioncube.so" \
  && docker-php-ext-enable ioncube

USER app:app
VOLUME /var/www
WORKDIR /var/www/html
`

ERROR i am getting

`
PHP -v

Warning: Failed loading Zend extension 'ioncube' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/ioncube.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.6 (cli) (built: May 13 2022 22:50:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
    with blackfire v1.78.0~linux-x64-non_zts81, https://blackfire.io, by Blackfire
`

**Comment by markshust** [comment]
I've dropped support for ioncube a while back, as I no longer believe in the mission of that project. That said, you are free to fork & pull this repo and add in support for it if you wish.
