### ISSUE TITLE
Weird error when using bin/copytocontainer --all

### ISSUE THREAD

**Issue by rayjaymor85** [markshust/docker-magento#894]
**Description**
I've been using this docker template for a while, it's fantastic so thanks heaps for it!

I'm trying to test my website on 2.4.6 using the php8.2-fpm-develop image. I did this by basically creating a fresh docker instance and then importing my files via git and copying my images into the src folder locally.

Everything has gone well, except none of my media images appear to be coming into the container and I get an error message of `Error response from daemon: Error processing tar file(exit status 1): unlinkat /var/www/html/Gruntfile.js: device or resource busy`

If I docker exec into the container there is no evidence to suggest my media files successfully copied. They just aren't there. So for whatever reason this gruntfile.js file inside the container is interrupting the copy process.

Ownership and Perms in both the local and docker file system are all clear as far as I can tell.

Anyone have any ideas what could be causing this?

**Comment by rayjaymor85** [comment]
To be clear this will definitely be something PEBKAC on my end; I successfully ran the upgrade without issue yesterday but accidentally blew away that instance. So just trying again but it's not going nearly as smoothly today.

**Comment by rayjaymor85** [comment]
and I have no idea why it didn't occur to me earlier to just copy the specific folder I was trying to copy. All running fine now.

Please ignore this error and write it off as end-user stupidity.

If someone does get the same issue I mention before bin/copytocontainer pub/media worked fine.

**Comment by talipkorkmazer** [comment]
If someone comes here in the future, the solution is:
`bin/stop`
`docker-compose -f compose.yaml up -d`
`bin/copytocontainer --all`
