### ISSUE TITLE
Gulp / NVM

### ISSUE THREAD

**Issue by niketk-hanes** [markshust/docker-magento#899]
Hello - Can someone provide any instructions on how to install gulp inside the docker enviroments?

Below are the typical steps I would follow - 

* Install nvm / node - https://tecadmin.net/install-nvm-macos-with-homebrew/ -> Install version v10.24.1
* Install Gulp - https://coder-coder.com/fix-gulp-command-not-found-error/
* npm install
* gulp --production 

When trying to install brew, running into below error

niket@Apples-MacBook-Pro champion % bin/cli apt-get install ruby-full -y
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

sudo also does not seem to work.

**Comment by artmouse** [comment]
bin/root ???

**Comment by anvanza** [comment]
Take a look at bin/setup-grunt and bin/npm.

**Comment by markshust** [comment]
Hi @niketk-hanes,

While Gulp isn't officially supported by Magento, I just realized that I have no videos on how to set up Grunt, which is the official JS compiler of Magento. So, I just uploaded them!

You can check out how to set up Grunt in docker-magento at https://courses.m.academy/courses/487758/lectures/48475483
