### ISSUE TITLE
Newest installer is failing

### ISSUE THREAD

**Issue by patadeloso** [markshust/docker-magento#903]
**Description**
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6 community

Initialized empty Git repository in /Users/XXXXX/Sites/magento/.git/
[+] Running 8/8
 ⠿ Network magento_default          Created                                                                                                                  0.0s
 ⠿ Container magento-redis-1        Healthy                                                                                                                  6.4s
 ⠿ Container magento-opensearch-1   Healthy                                                                                                                 16.9s
 ⠿ Container magento-rabbitmq-1     Healthy                                                                                                                  8.4s
 ⠿ Container magento-db-1           Healthy                                                                                                                  6.4s
 ⠿ Container magento-mailcatcher-1  Started                                                                                                                  1.0s
 ⠿ Container magento-phpfpm-1       Started                                                                                                                 17.5s
 ⠿ Container magento-app-1          Started                                                                                                                 17.8s
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.6" project at "./"

  [InvalidArgumentException]
  Project directory "/var/www/html/." is not empty.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

**Steps To Reproduce**
1. Try to run one step installer

**Expected Result**
Installer runs successfully

**Actual Result**
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.6" project at "./"

  [InvalidArgumentException]
  Project directory "/var/www/html/." is not empty.

**Comment by patadeloso** [comment]
I was able to get something installed but it looks like it is installing Magento in the container but not the project dir.

bin/restart
[+] Running 7/7
 ⠿ Container magento-mailcatcher-1  Stopped                                                                                                                  0.2s
 ⠿ Container magento-app-1          Stopped                                                                                                                  0.9s
 ⠿ Container magento-phpfpm-1       Stopped                                                                                                                  0.2s
 ⠿ Container magento-redis-1        Stopped                                                                                                                  0.4s
 ⠿ Container magento-rabbitmq-1     Stopped                                                                                                                  6.6s
 ⠿ Container magento-db-1           Stopped                                                                                                                  1.7s
 ⠿ Container magento-opensearch-1   Stopped                                                                                                                  0.6s
./src/app/design: No such file or directory
./src/app/etc: No such file or directory
./src/composer.json: No such file or directory
./src/composer.lock: No such file or directory
./src/grunt-config.json.sample: No such file or directory
./src/Gruntfile.js.sample: No such file or directory
./src/dev/tools/grunt/configs: No such file or directory
./src/nginx.conf.sample: No such file or directory
./src/package.json.sample: No such file or directory
Failed to start docker for missing volume files

~/Sites/magento  on   main ?12 ▓▒░─────────────────────────────────────────────────────────────────────────────────────────────────────░▒▓ took 9s  
❯ ls -lah
total 72
drwxr-xr-x  15 shaun  staff   480B Apr  8 21:26 .
drwxr-xr-x   3 shaun  staff    96B Apr  8 21:26 ..
drwxr-xr-x   9 shaun  staff   288B Apr  8 22:01 .git
-rw-r--r--   1 shaun  staff     5B Apr  8 21:26 .gitignore
drwxr-xr-x   3 shaun  staff    96B Apr  8 21:26 .vscode
-rw-r--r--   1 shaun  staff   5.3K Apr  8 21:26 Makefile
drwxr-xr-x  55 shaun  staff   1.7K Apr  8 21:26 bin
-rw-r--r--   1 shaun  staff   3.4K Apr  8 21:26 compose.commerce246beta.yaml
-rw-r--r--   1 shaun  staff   191B Apr  8 21:26 compose.dev-linux.yaml
-rw-r--r--   1 shaun  staff   242B Apr  8 21:26 compose.dev-ssh.yaml
-rw-r--r--   1 shaun  staff   1.2K Apr  8 21:26 compose.dev.yaml
-rw-r--r--   1 shaun  staff   1.2K Apr  8 21:26 compose.healthcheck.yaml
-rw-r--r--   1 shaun  staff   3.4K Apr  8 21:26 compose.yaml
drwxr-xr-x  10 shaun  staff   320B Apr  8 21:26 env
drwxr-xr-x   3 shaun  staff    96B Apr  8 21:26 template

**Comment by patadeloso** [comment]
I should have continue reading the README

https://github.com/markshust/docker-magento#misc-info

**Comment by Jazyac** [comment]
@patadeloso  can you advise how you fixed it?
I have read the misc-info section, and havent come accross any suggestions for it.
I am getting this error--
"./src/grunt-config.json.sample: No such file or directory"
Thanks
