### ISSUE TITLE
How upgrade from 2.4.4 to 2.4.6?

### ISSUE THREAD

**Issue by mao3li** [markshust/docker-magento#904]
How upgrade from 2.4.4 to 2.4.6?

**Comment by hans2103** [comment]
@mao3li please have a look at the documentation of Magento

https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html?lang=en

**Comment by markshust** [comment]
This isn't an issue with this specific project/repo, so closing this one out.
