### ISSUE TITLE
Some files / folders created by the one line installer is not owned by the current user

### ISSUE THREAD

**Issue by skygunner** [markshust/docker-magento#908]
**Description**
OS is Ubuntu 22.04
some files under ~/.composer and /src are owned by user opc, not the current user ran the script

**Comment by EvgeniyZverev** [comment]
Hi, @skygunner 

Here's an example of how you can change ownership recursively for the mentioned directories:

```code
sudo chown -R $(whoami):$(whoami) ~/.composer
sudo chown -R $(whoami):$(whoami) /src
```

In these commands:

- '-R' stands for recursive, which means it will apply the ownership change to all files and subdirectories within the specified directory.
- $(whoami) is a way to dynamically get the current username.

Make sure to replace /src with the actual path of the directory you want to modify.

After running these commands, the ownership of the files and directories should be changed to the current user.

**Comment by markshust** [comment]
The `~/.composer` and `src` directories should always be owned by your local user, on mac or linux. I'd suggest to correct your pers using the suggested method above, which should correct your issue. Sounds like something funky has been going on on your local machine in regards to ownerships, as this isn't typical.
