### ISSUE TITLE
Problmes with permission

### ISSUE THREAD

**Issue by cctorres** [markshust/docker-magento#915]
Hello! 

I Have a custom Magento setup with the docker environment. I am trying to duplicate this docker environment in another docker container but after run 'bin/setup-domain local.test' I'm having those:
- In the terminal
OCI runtime exec failed: exec failed: unable to start container process: exec: "bin/magento": permission denied: unknown
- in the front end
We can't read some files that are required to run the Magento application. This usually means file permissions are set incorrectly.

If I ran the another environment, I don't have any problema but I want to use other environment.

Note: I build my own nginx as the tutorial said to get multi store.

There is a solution for this or something to try?

Thanks!

**Comment by diegobonagurio** [comment]
Any solution? @cctorres

**Comment by cctorres** [comment]
> Any solution? @cctorres
For some reason when I ran composer: install src/app/etc folder it was not getting the files as it should. I made a copy and paste of another folder that I had in the project and it worked for me
