### ISSUE TITLE
Latest 2.4.6 docker not running on Linux(Ubuntu 22.10)

### ISSUE THREAD

**Issue by bbakalov** [markshust/docker-magento#919]
**Description**
Tried to install the latest Magento 2.4.6 on Linux (Ubuntu 22.10) by script, and as a result, I had an error
`error mounting /var/www/html/empty Magento/src/composer.lock`

I also tried to change **compose.dev.yml** as described (here)[https://github.com/markshust/docker-magento#linux] , unfortunately with and without these changes, had the same result. 
Screenshots:  
![default compose dev yml](https://user-images.githubusercontent.com/9625352/235871331-c8e8b79c-b9ed-4c59-81b5-48cc5173f6e1.png)

![linux compose dev yml](https://user-images.githubusercontent.com/9625352/235871309-dec3408a-59ec-453f-ab8f-59f1562408d8.png)

**Steps To Reproduce**
1. run command from 'Automated Setup (New Project)'
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6 community`
**Expected Result**
The empty Magento project is working

**Actual Result**
During installation error: `error mounting /var/www/html/empty Magento/src/composer.lock to rootfs as /var/www/html/composer.lock`

**Comment by markshust** [comment]
"empty Magento" is an odd folder to mount, no? I'm wondering if everything is ok there and that a composer.lock file exists on your host machine.
