### ISSUE TITLE
New entry in /etc/hosts doesn't get added to new line

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#921]
**Description**
Per https://courses.m.academy/courses/set-up-magento-2-development-environment-docker/lectures/8974570 there have been a couple reports of this happening:

<img width="879" alt="Screenshot 2023-05-07 at 9 47 17 AM" src="https://user-images.githubusercontent.com/437029/236681398-ee588d72-e8c7-46a3-844d-db0409cb4e3b.png">

**Steps To Reproduce**
I have yet to reproduce this on my local machine, however the code should be checked to ensure that the script properly executes on all different types of host OS's.

**Expected Result**
New entries in /etc/hosts get added to new lines

**Actual Result**
New entries in /etc/hosts get added to the last line in the file

**Comment by markshust** [comment]
Is anyone able to replicate this?

**Comment by markshust** [comment]
This was reported by a couple users but I'm unable to replicate, will be closing this out shortly.

**Comment by Hotpick** [comment]
@markshust i get similar
![image](https://github.com/markshust/docker-magento/assets/18401509/8b85d562-f731-4536-bbed-ed20fab5432e)

**Comment by markshust** [comment]
@Hotpick what is the contents of your `/etc/hosts` file on your host machine after running the above line? This ticket is solely for newlines with `/etc/hosts`, but your post relates back to not being able to connect to a database.

**Comment by markshust** [comment]
I'm unable to replicate this, so closing it out.
