### ISSUE TITLE
Setup Error - Automated & Manual - `/usr/bin/env: ‘bash\r’: No such file or directory` 

### ISSUE THREAD

**Issue by andy-sixtystores** [markshust/docker-magento#929]
**Description**
Getting the error `/usr/bin/env: ‘bash\r’: No such file or directory` when setting up a new instance.
I am on Windows 11 and am using WSL2 and Docker, my existing instances work fine without issue (these are an older version of `docker-magento`).

![Screenshot 2023-05-19 122113](https://github.com/markshust/docker-magento/assets/57661701/e705f6b9-1774-43ba-a269-aeb207979891)

**Steps To Reproduce**
1. `mkdir store`
2. `cd $_`
3. `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- store.localhost 2.4.6 community` OR `bin/download 2.4.6 community`

**Expected Result**
The installation completes without error and is ready for the next stages of setting up.

**Actual Result**
The following error is returned:
```
Initialized empty Git repository in /home/andy/websites/store/.git/
/usr/bin/env: ‘bash\r’: No such file or directory
```

Trying to run any script inside the `./bin` directory throws the `/usr/bin/env: ‘bash\r’: No such file or directory` error.

**Comment by andy-sixtystores** [comment]
I have also tried downloading Magento directly and copying the files to the `./src` directory then following the existing install method. However, I get the same error outlined above when I attempt to run `composer install`.

**Comment by andy-sixtystores** [comment]
I have got past this error by changing the `line endings` to `LF` from `CRLF` in all the bash files inside the `.\bin\` directory.

This can be done with this one-liner inside the project directory:

```bash
find ./bin -type f -exec sed -i 's/\r$//' {} +
```

**Comment by o0mohd0o** [comment]
I had the same issue on macOS

git config --global core.autocrlf input

This configuration tells Git to convert CRLF line endings to LF on commit, but not to convert LF to CRLF on checkout.

git config --global core.eol lf

This configuration ensures that Git normalizes line endings to LF when checking out files.
