### ISSUE TITLE
Magento 2.4.6

### ISSUE THREAD

**Issue by sr-expert** [markshust/docker-magento#935]
maria db 10.6
opensearch 2.5
php 8.2
not found 

[+] Running 0/3
 ⠿ phpfpm Error                                                            2.1s
 ⠿ db Error                                                                2.1s
 ⠿ opensearch Error                                                        2.1s

plz you can update to last version

**Comment by markshust** [comment]
Everything works for me using the one line setup with 2.4.6, closing out as unable to replicate.
