### ISSUE TITLE
bin/composer install command fails due to timing in setup process

### ISSUE THREAD

**Issue by schneider-vaimo** [markshust/docker-magento#941]
**Description**
The instructions for setting up an existing project appear to be somewhat confusing. The execution of `bin/composer install` seems to be misplaced in the sequence, leading to errors due to the premature execution.

**Steps To Reproduce**
1. Follow instructions for setting up existing project
2. Reach the `bin/composer install` step.

**Expected Result**
`bin/composer install` runs smoothly, without any errors.

**Actual Result**
`bin/composer install` fails, returning the following error:
`service "phpfpm" is not running container #1`

**Additional Information**
Upon running `bin/composer install` after the `bin/start --no-dev` command, the following error was encountered:
`Composer could not find a composer.json file in /var/www/html`

It seems the `bin/composer install` step should be relocated to a later position in the process, specifically after executing `bin/copytocontainer --all`. This is due to the requirement of a composer.json file for the execution of `bin/composer install`.

**Comment by simonmaass** [comment]
i am also getting this error:

<img width="439" alt="image" src="https://github.com/markshust/docker-magento/assets/32599710/ff5cc05b-e9ba-4a1e-9085-73ad80d1a260">

**Comment by schneider-vaimo** [comment]
@simonmaass I don't think that error is related to this issue.
It appears your composer.json is not valid JSON. I would suggest checking for obvious mistakes, and otherwise use a JSON validator to check for any discrepancies.
