### ISSUE TITLE
Error on Apple M2 when doing bin/start --no-dev: phpfpm The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by steven410** [markshust/docker-magento#943]
**Description**
I am following the setup for an existing project. When running bin/start --no-dev there is an error related to phpfm's platform. Several stackoverflow threads have adding --platform linux/amd64 to docker run as a solution but that doesn't seem doable here as docker run doesn't seem to be used. Because of this I am unable to continue with the setup. 

**Steps To Reproduce**
1. Follow directions as listed here: https://github.com/markshust/docker-magento#existing-projects using an M2 chip

**Expected Result**
The container is started

**Actual Result**
The container cannot be started. An error occurs: phpfpm The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by Cyapow** [comment]
In Docker hub go to Settings > Features in Development and enable "Use Rosetta for x86/amd64 emulation on Apple Silicon"
Only problem is when docker hub updates it always unchecks it but thats what I've used on other docker issues like this on the m1

**Comment by steven410** [comment]
> In Docker hub go to Settings > Features in Development and enable "Use Rosetta for x86/amd64 emulation on Apple Silicon" Only problem is when docker hub updates it always unchecks it but thats what I've used on other docker issues like this on the m1

Thanks for this. I have Rosetta installed. I have enabled this setting and the needed "Use Virtualization framework" setting under General. I still get this error.
