### ISSUE TITLE
RabbitMQ and Open search fail to start containers on M1 mac

### ISSUE THREAD

**Issue by Cyapow** [markshust/docker-magento#944]
When running the setup both Rabbit MQ and Open search fail to load. 

In docker I have "Use Rosetta for x86/amd64 emulation on Apple Silicon" enabled

![image](https://github.com/markshust/docker-magento/assets/5711362/a54cc22a-28bf-4771-81c7-e31f679814bb)

![image](https://github.com/markshust/docker-magento/assets/5711362/a7c1c248-9d8b-44e0-ad90-ea94b6d61f5f)

![image](https://github.com/markshust/docker-magento/assets/5711362/dab98c9e-c13d-4aab-9c8b-87aa71d92f83)

Has anyone experienced similar?

**Comment by pixelhed** [comment]
@Cyapow I have the same issue

**Comment by markshust** [comment]
What happens when you leave the "Use Rosetta" box unchecked?

**Comment by pixelhed** [comment]
hi @markshust i 'solved' the problem. After migrating to apple silicon i used my existing external drive which i sed to store all docker data. When i used the default docker location for the docker data, then tried again it all worked. I assume it had something to do with the build on the previous intel system. When starting with a fresh system rabbitmq & open search started.
@Cyapow maybe this helps you?

**Comment by markshust** [comment]
Ah yes, thanks for letting us know about this!
