### ISSUE TITLE
Docker Installation Issue on Magento 2.4.2 with MacBook M2 Pro Chip

### ISSUE THREAD

**Issue by madonzy** [markshust/docker-magento#946]
**Description:**
Installation issue with the solution on an existing Magento project (version 2.4.2) using tag 38.0.0 on a MacBook with M2 Pro chip.

**Steps To Reproduce:**

1. Attempt to install the solution on an existing Magento project (version 2.4.2) using tag 38.0.0 on a MacBook with M1/M2 chip
2. Run docker-compose -f docker-compose.yml up -d.

**Expected Result:**
The solution should install and run successfully.

**Actual Result:**
I encounter the error no matching manifest for linux/arm64/v8 in the manifest list entries. Installing the master version of magento-docker proceeds with fetching arm images, but the versions of the services do not match Magento 2.4.2.

**Question:**
Can anyone provide guidance on how to successfully install and run the solution on an existing Magento project (version 2.4.2) using tag 38.0.0 on a MacBook with an M2 Pro chip? Any suggestions or workarounds would be greatly appreciated.

**Comment by markshust** [comment]
2.4.2 has been deprecated for almost 2 years now without updates! https://experienceleague.adobe.com/docs/commerce-operations/release/versions.html?lang=en

Someone can always chime in here, but I don't support outdated/old versions of Magento, so closing this out as a non-issue.

**Comment by cykolln** [comment]
@madonzy We support customers all the way down to version 2.3.3 so I've had to get a little creative on using docker-magento to run m2 locally for a wide range of versions. This script works for me to automate setup for 2.4.2, the one caveat being im still on an intel mac so it may need to be tweaked.

```
#!/usr/bin/env bash

echo "Cloning docker-magento..."
git clone git@github.com:markshust/docker-magento.git 2.4.2
cd 2.4.2

# checkout specific commit
echo "taking us back in time to when docker-magento supported 2.4.2 (checking out commit 8c1084c)"
git checkout 8c1084c

echo "getting directory ready for install"
# manually does what the template does in the manual setup docs
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
mkdir -p ~/.composer ~/.ssh
touch ~/.ssh/id_rsa ~/.ssh/known_hosts

echo "downloading version 2.4.2"
bin/download 2.4.2

echo "finally setting up docker_magento"
bin/setup magento.test
```
