### ISSUE TITLE
How to install unzip in docker-magento?

### ISSUE THREAD

**Issue by AngeloZou** [markshust/docker-magento#948]
Hi,

How to install unzip in docker-magento? I can't find the Dockerfile, how can I add Dockerfile instructions.
`RUN apt-get update && apt-get install -y unzip`

![Screenshot_3](https://github.com/markshust/docker-magento/assets/81738253/e68d21c5-5bd2-4897-9b02-404b2ffafb11)

**Comment by markshust** [comment]
Info on customizing Dockerfile's is at https://courses.m.academy/courses/487758/lectures/36702861

Since this isn't an issue with this project, I'm going to close this issue out.
