### ISSUE TITLE
Issue with ed_25519 type SSH key for github

### ISSUE THREAD

**Issue by MaheshBharadwaj** [markshust/docker-magento#953]
**Description**
The compose.yaml mounts ~/.ssh/id_rsa by default. Github recommends using ed25519 key [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) and as a result the line should read ~/.ssh/id_ed25519

**Steps To Reproduce**
Use id_ed25519 in local and run the commands as is. It should fail with SSH error.

**Expected Result**

**Actual Result**

**Comment by janmyszkier** [comment]
@MaheshBharadwaj Is this really an issue? where is this key even used?

**Comment by MaheshBharadwaj** [comment]
When we attempt to pull the github image

**Comment by janmyszkier** [comment]
@MaheshBharadwaj  there is a misunderstanding here :
- `~/.ssh/id_rsa` is just a path to your key and the fact your key is named `id_rsa` doesn't make it a RSA key on it's own. You can have ED25519 key under `id_rsa` name and it will work just fine. So if you have different path, you can modify the default path. If your key is incorrect, composer will tell you that anyway if it still needs it.
- not everyone out there has the file `~/.ssh/id_ed25519` (I do not, even though I do use ed25519 key all the time, but it's under different path) 
- github still supports RSA keys, so `~/.ssh/id_rsa` keys are still valid keys if generated correctly

You can read on this here:
https://ikarus.sg/rsa-is-not-dead/

**Comment by khemmapon** [comment]
I've got the issue with `bin/cli git clone git@github.com:magento/magento2.git .`
<img width="603" alt="Screenshot 2566-07-19 at 12 44 27" src="https://github.com/markshust/docker-magento/assets/19380990/34e6f1f1-35a5-407a-824a-9e7347195ee9">

Do I have to modify compose.yaml file to use id_ed25519?

**Comment by markshust** [comment]
Closing this out as a non-issue, since I don't get any warnings, errors, etc. using the keys I've been using over the last decade 😄

**Comment by MaheshBharadwaj** [comment]
@hans2103 this is the exact error that I obtained as well but looks like this is a non issue because id_ed25519 can also be stored under id_rsa (Not sure why you would do that but ok)
