### ISSUE TITLE
Can we run docker with native home brew nginx and mysql installed in mac

### ISSUE THREAD

**Issue by kdaharwal** [markshust/docker-magento#960]
@markshust  In Mac i had setup of nginx and mysql with home brew and its working fine.

I have setup new project with docker it told me to update port which i changed from compose.yaml file and its installed successfully.

But while opening https://magento.test/ its showing 
403 Forbidden
nginx/1.18.0 

Do we need to remove native installed Nginx and Mysql with brew ?

@markshust please check above issue.

**Comment by kdaharwal** [comment]
Hi @janmyszkier 

Thank you for replying.

They solution you have written i had already tried
<img width="1423" alt="Screenshot 2023-07-18 at 10 56 48 PM" src="https://github.com/markshust/docker-magento/assets/115615371/8e3da4f5-eef5-4ece-a874-f320b3c838e8">
And i am able to installed it successfully, had changed port in compose.yaml file.

Domain not working my end  https://magento.test/
Below issue is coming 
403 Forbidden
nginx/1.18.0

I stop Nginx  services 

brew services list
 
Name               Status       User             File
docker-machine     none                          
elasticsearch-full started      root             ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch-full.plist
mysql              started      kushagradaharwal ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
**nginx              stopped      root             ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist**
php                error  19968 kushagradaharwal ~/Library/LaunchAgents/homebrew.mxcl.php.plist
php@7.4            none                          
php@8.0            none                          
php@8.1            error  19968 root             ~/Library/LaunchAgents/homebrew.mxcl.php@8.1.plist
rabbitmq           started      root             ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
sonarqube          none                          
unbound            none     

@janmyszkier  Please write a proper solution if you don't know no issue.

@markshust

**Comment by markshust** [comment]
@markshust there's no issue with this, so closing it out. As long as no services are running on the respective Docker ports, this project will work just fine 👍 There's nothing to check for me or change with this project to solve your issue. I'd recommend shutting down all services, deleting all docker-magento attempt install builds, and try again.
