### ISSUE TITLE
Existing Project Deletes .git Directory

### ISSUE THREAD

**Issue by Stoyvo** [markshust/docker-magento#966]
**Description**
I have an existing project, it has a git repository and everything. So I followed the instructions until this point:
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash`

This deletes your .git directory. All your existing branches, remotes, etc are **GONE**.

**Steps To Reproduce**
1. Have project with a git repository
2. Follow the Setup instructions for "Existing Project"

**Expected Result**
3. Observe your existing git configurations are gone.

**Actual Result**
Don't do that, or at very least warn me?

**Comment by Stoyvo** [comment]
To recover git repository, run these commands:
**NOTE:** This does not recover any local branches or stashes, it only pulls whats on your remote server.

```
git remote add origin URL_TO_REPO
git fetch --all
git branch main origin/main
git reset HEAD -- .
```

**Comment by markshust** [comment]
From the documentation at https://github.com/markshust/docker-magento#existing-projects the existing project setup is meant to be done in a new, blank folder. Even though you are setting up an existing project, this is a brand new docker-magento project. The next step in the documentation after the line you provided hints to this:

```
# Replace with existing source code of your existing Magento instance:
cp -R ~/Sites/existing src
# or: git clone git@github.com:myrepo.git src
```
