### ISSUE TITLE
Adding `strace` to image

### ISSUE THREAD

**Issue by nwcasebolt** [markshust/docker-magento#983]
**Description**
We use MageMojo's m2-ce-cron module to manage our crons. This module uses `strace` to run consumers ([see here](https://github.com/magemojo/m2-ce-cron)), evidently in order to fix problems with consumers that run out of control. We have to work around this when testing locally since the docker-magento php-fpm image does not install `strace`.

Can `strace` be added to the Docker image, or is that a negatory?

**Comment by markshust** [comment]
Merged in the PR, appreciate it. It'll be included in the next tagged release (which is coming as soon as I can get through all of the new PRs)
