### ISSUE TITLE
phpfpm depends on undefined service open search

### ISSUE THREAD

**Issue by farmaworld** [markshust/docker-magento#989]
[+] Running 11/11
 ✔ elasticsearch 10 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                   42.7s 
   ✔ fb0b3276a519 Pull complete                                                                                                  11.8s 
   ✔ 38dd47397c96 Pull complete                                                                                                   2.0s 
   ✔ a9cc04abc7e0 Pull complete                                                                                                   0.6s 
   ✔ 1b5db66d71d3 Pull complete                                                                                                  34.3s 
   ✔ e314b07b4a41 Pull complete                                                                                                   4.8s 
   ✔ c1cbe2363e68 Pull complete                                                                                                   6.8s 
   ✔ aec6881665fb Pull complete                                                                                                   7.8s 
   ✔ 20a24512c722 Pull complete                                                                                                   8.7s 
   ✔ f3d802e5d059 Pull complete                                                                                                  10.1s 
   ✔ 40f0246bfeb9 Pull complete                                                                                                  13.9s 
[+] Running 13/13
 ✔ Network farmaworld_default            Created                                                                                  0.2s 
 ✔ Volume "farmaworld_appdata"           Created                                                                                  0.0s 
 ✔ Volume "farmaworld_sockdata"          Created                                                                                  0.0s 
 ✔ Volume "farmaworld_ssldata"           Created                                                                                  0.0s 
 ✔ Volume "farmaworld_dbdata"            Created                                                                                  0.0s 
 ✔ Volume "farmaworld_rabbitmqdata"      Created                                                                                  0.0s 
 ✔ Container farmaworld-elasticsearch-1  Started                                                                                  0.9s 
 ✔ Container farmaworld-db-1             Started                                                                                  0.9s 
 ✔ Container farmaworld-rabbitmq-1       Started                                                                                  0.9s 
 ✔ Container farmaworld-mailcatcher-1    Started                                                                                  0.9s 
 ✔ Container farmaworld-phpfpm-1         Started                                                                                  0.9s 
 ✔ Container farmaworld-redis-1          Started                                                                                  0.9s 
 ✔ Container farmaworld-app-1            Started                                                                                  0.9s 
imac@iMac-di-iMac farmaworld % bin/copytocontainer --all                               
service "phpfpm" depends on undefined service opensearch: invalid compose project

i uncomment the block with elasticsearch and comment opesearch like instructions 

copy of all file

imac@iMac-di-iMac farmaworld % bin/copytocontainer --all                               
service "phpfpm" depends on undefined service opensearch: invalid compose project

**Comment by murali290987** [comment]
i am also facing same issue in my mac system. i am downloading magento 2.4.5-p1. any solution?
Issue: 
service "phpfpm" depends on undefined service "opensearch": invalid compose project
Error: The "src" directory is not empty. Please remove all contents within this directory and try again.
