### ISSUE TITLE
Automate setup doesn't finish - Copying from container takes too long

### ISSUE THREAD

**Issue by nickyichov** [markshust/docker-magento#990]
**Description**

I followed the [video](https://courses.m.academy/courses/487758/lectures/8974570) on setting up Magento 2 with docker. However, I ran into a problem where after Magento is installed it takes hours to copy from the container. It never can finish because the Docker always crashes at some point. 

![image](https://github.com/markshust/docker-magento/assets/79098081/35d4c7d9-df88-4796-bcad-ae324cd713cd)

After more than an hour, copying from container got to 169mb and docker crashed. 
I tried this several times for the past few days but the result is always the same.

The resources are set as described.
I am on Windows but I used WSL to run the command.

**Steps To Reproduce**

1. Running the command for the first time gives me the following error:
`curl: (6) Could not resolve host: raw.githubusercontent.com`
which I fixed by adding a DNS nameserver to _/etc/resolv.conf_

2. After running `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p2 community` again, everything goes smoothly until it reaches _copying from container_

3. I decided to do the rest of the commands manually.
The ones being executed were `bin/magento setup:static-content:deploy -f` and `bin/magento indexer:reindex` because that followed in the video. 

4. I added `127.0.0.1 ::1 magento.test` to _/etc/hosts_. 

However, all this was with no success.

**Comment by aepod** [comment]
I can confirm this happens. I was setting this up myself the same way. WSL Linux on windows. Everything was smooth until it hit the copy files from host, now it is hung up. I will leave it be to see if it ever finishes, but it already has been well over 1/2 hour.

**Comment by nickyichov** [comment]
I found a solution.
The problem with me was that I stored the project in C:/ directory. After changing the installation directory under the WSL home folder (home/user/) everything went smoothly. 
I can confirm that I did the same with other projects ran on Docker and Docker's time performance improved dramatically.
