### ISSUE TITLE
Existing Project: receive error when running  bin/magento app:config:import

### ISSUE THREAD

**Issue by janderson-uw** [markshust/docker-magento#997]
Existing Project: receive error when running  bin/magento app:config:import

```
$ bin/magento app:config:import

                                                                
  There are no commands defined in the "app:config" namespace.  
                                                                
  Did you mean one of these?                                    
      module:config                                             
      setup:config                                              
      setup:store-config        
```                               

I am at the point in the guide at using an existing project of running bin/magento app:config:import and it errors out with the above error.

I am on latest version of Ubuntu Linux. The project is a Magento Cloud 2.4.6-p1 project that I have cloned down from BitBucket.

**Comment by magenizr** [comment]
Hi @janderson-uw 

I ran into the same issue while setting up an existing cloud project. Here is how I fixed it.

1. Redis

Make sure the host and port is set as below:

```
'server' => 'localhost',
'port' => '6370',
```

2. Db

Simply replace the entire `db` section with the below snippet.

```
    'db' =>
        [
            'connection' =>
                [
                    'default' =>
                        [
                            'host' => 'db',
                            'dbname' => 'magento',
                            'username' => 'magento',
                            'password' => 'magento'
                        ],
                    'indexer' =>
                        [
                            'host' => 'db',
                            'dbname' => 'magento',
                            'username' => 'magento',
                            'password' => 'magento'
                        ],
                ]
        ],
```

3. Lock

Replace the `lock` section with

```
    'lock' => [
        'provider' => 'db'
    ],
```

After that, execute `bin/copytocontainer --all` and try to run `bin/magento app:config:import` again.

**Comment by markshust** [comment]
Yes, this is a non-issue with this project, and @magenizr nailed it -- this is a standard Magento error that occurs when it can't connect to the database. So, be sure to check your `app/etc/env.php` settings and try again :)
