### ISSUE TITLE
Magento 2.4.6 p2 vendor changes

### ISSUE THREAD

**Issue by Ceh9N** [markshust/docker-magento#999]
I configured magento on my machine on docker by using your instruction. Also i added my custom extension. But then 2 problems were found. 1) I tried to configure xdebug by our instructions but it doesnt seems to work, when i put breakpoint in pub/index.php file debug dont catch anything. 2) I tried to debug magento with dd(); function but when i try to add it in vendor it doesnt change vendor code, so that i tried to change some templates for example sales_order_view but it also dont change anything. After that changes i checked that i am in dev mode and runned s:up but it also dont change anything. How could i fix it. Why my changes to vendor code are not applying.

**Comment by anvanza** [comment]
Push the vendor changes back to the container using the bin/copytocontainer command. 
For ex.  `bin/copytocontainer vendor/magento`

**Comment by markshust** [comment]
The `pub` directory is not mounted to the container for performance reasons, so testing `pub/index.php` will not trigger the Xdebug breakpoint. I'd recommend testing Xdebug with some code in `app/code`, as that is bi-directionally synced. I should document this someplace! :)
